‏JJHK‏JJKJKHIJ‏HJIJJJJJJJJJ‏JJJJJHJJJHJJHJJJ‏HJIJIJJMנצJLJJJJKJ‏
JJGJJJJצסIנקרIJHKJIIJI‏JHJJJJHJףקIקס	קשJ	JJJGJIHKJ‏JHJJJGHKJKףKI	צץHצקתM
HJJIKJJIKI‏HKJIJIHףMרMMüIüתקIרKMKIJJJII‏JHJJK
‎üüרMM‎JKM‎üM
HJHH‏
JJHJJM
MJ‎MMJ‎KüJJI‏IHKJIIJHKMüMM	KK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏JJHK‏JJKJKHIJ‏HJIJJJJJJJJJ‏JJJJJף	סJJJ‏HJIJMHףסקKüüüJJKJ‏
JJGJסס
‎HJüüMMKJIIJI‏JHJJJ	נקתüIJMצMMJJJJGJIHKJ‏JHJJJGHתקקMMJMMJHJKIJףששIKJJIKI‏HKJIJIתMüMMHKJJKJH
תנ	
JJJII‏JHJJKJIIJIHLIJ	שתHüMרJHH‏
JJHJ
נף	ששüIJüüJJI‏IHצ
ש‎MüMM	KK‏HM‎MMשIJJKJH‏IKJGJJGJ‏IKJKÿ‏JJHK‏JJKJKHIJ‏HJIJJJקרJJJJ‏JJJJ
HJנסJHJJJ‏HJIJ	סJJץJנJJKJ‏
JJGJJנM´JנסMסרIIJI‏JHJJJJקצסKµ´´נ	HKנץüתIHKJ‏JHJJJGHMIרצץI·¶IץHKסKקצ‎J‎KJJIKI‏HKJIJMשMKצK÷¸K÷צ	שKMüMMJJII‏JHJJKMתüMKIK»K¸ü‎üJMMJHH‏
JJHMMMרüJM¼¼ü‎HMMJI‏IHKJIMתüMMKMJKK‏JIJIM
MMMH‏IKJGJJGJ‏IKJKÿ‏	סננ‏Kנננ‏KMHננס‏סIס‏סנס	‏
KIHMIסIMKסI‏	IKKKKסKHננKI	‏KMנKIMנסKMK	סII	‏IMHננKMסI
ננK	נ	‏MסMנKנס	MננKסIKנ		‏M	נסKHנס	
IIKנסM	I	I‏MI	IMנסננHIננ
	KנIMKMMI‏סMMK
Mננ	M	
HננKIHMM	ס
	M‏		MK	ננננסMIH	נננHKננס
IMM‏

	Iנ	נ	סH	KI
MנMK	נס	M

‏	Mס	נ		M		KK		נKKKננסMI
M‏M
M				M


MIKK	סףMנI	צIMM‏JHJMMMM			MHMIףM
MנננM
MMMMIKI‏HKMMMM
MMMMM	
KMIסMIMMMKJI‏JHMMMMM	MHMMM	IMMKII‏
JJMKLLKMMIMMMMMMKJ‏IILKKKLMMMMMMLL‏JIKJKLKKKLKI‏IKJHJJHJ‏IKJKÿ‏ססKKMף‏	סKKKסנ‏KKKס	‏IIKKנ	
‏MנKMKKIIMסKס
‏KIMKMIIM	‏נננK	ס
IסKKM‏KנMנK	נננ		IK	MMI‏	KMנסIננננס	K	K‏MIKMIMנססMKKIMM‏MMKKII	KססKMM‏נMנM
IMMII‏סנסננסנס


KIMM
	ף‏HMננ
סס	
KKKM
	‏	MKIKMIנK		KMKIKKK‏	נננKKM	IKM
HMH	KM‏	סנMKIIKKMH	
MM‏		נסנסIIננננסס		MMMJ‏JHס	ס	M
Mס	נסס	M
		
KKMMKKIKI‏	M	
MM
I
M		

	M
MMMKKKII‏JMMMMMMIM
M
MMLJKIH‏
JJMMIM	MLJKKJ‏IHLKJJKILLKLKKLK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏סננ	‏
נ‏סII‏נMIIMננ‏	MKנIKM‏	MננHHKסIM
‏			נHMMMננסIM‏
M	סM	סMKKIIנסKHKנ‏
K
I
HסMMKMHHKMנססM‏	H
H
נIIIKננס
	M‏	MHססססנMKKס

תM
‏נMMס		KסנסנIננKMIKK
‏סMIMס
K	ננס	סMנסMKKס‏		KIMK	
נסK
	סK	Mסס	KZY‏
ס
KסIKKס	
ססMנסת‏KMMYY‏
	
	MננMנK	ס	K

‏K‏MYX‏

MצססMMKKKKסIM
ת
K‏M‏
YYX‏M
K
	ננI
HססMIK
‎	KMM
YXZY‏MKMסMס	H
K	MKKMK‎M‎XYYX‏JHJKKננס	KM
רררIHM‎‎üYYYXJHJJJGMMסס	
KK	
KMHKMYYYY‏HKJIJKKM

MK	
üIMMMMMMYYZ‏JHJJM

KMK
üMMMMMMMJHH‏
JJHMMMMüMMHMMMJI‏IHK
üMüüKKK‏JIJMMMKKI‏IKJDJJHJ‏IKJKÿ‏‏II‏	I‏
	HIKנ‏KסMנIKס‏M
I
נס		
‏MH
K		
‏KM	KKM‏KHH

MMü‏
KHKס‏KMMKסס‏MMKHI‏סMMM
I‏MMKMKMü‏HMMM
KMLL‏JJJKKM
MMMMMMüü‏HJIJIKKKMס		MMMMMKKJ‏
JJGJJJJJKIKLLILKKILKJIJI‏JHJJJJHJHKIKKLJLLKKKKKGJIHKJ‏JHJJJGHKJKJHJGJKKIKKJJHJJIKJJIKI‏HKJIJIHFHJLHKJJKJHJKIKIJJJII‏JHJJKJIIJIHLIJIIJGJKHJHH‏
JJHJJJHJJIJHJJHJHJJI‏IHKJIIJHKKJKJJKK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏נMHHK‏נHKHHKIIM‏	MKMHIHMIKHIK‏	KHIHHMIIK‏	KHHנHHKIHס‏YנMIנסMKס‏	HHססHIMKKIנM‏KMIMס	HMIסMHIIMנH‏MKKIKKסKKI	סנMIIKנH‏ס
ננMMIMIMK		ססKנMIנססM‏סKKKK
MK
	סססנMסI	H‏ZZMMM		
MMIMK		ףסננI	

Mנ‏XZYYKס	MMMKIנסKH
סMנס‏ZZXZZZI
MK
	סK
IKIMMMש	‏YXZYZZ	KHMרIMרMIIת‏XYYYYY‎IMשM
KMü‏YYZXYY‎üIHüששK


KMM‏XYZYYXüüMHMMMM	ששKMMMMMM‏XYXYYXY	
MMMMMKMMM‏YXXYZXYס

סMKüHMMüM‏XYYYZYZXüMMKMüMMMMM‏YXXXYXXYMMMMMMM‏XXYXXYüüMMMMMMMMMM‏YXXMMM‏X‏MMÿ‏JJ8K‏:JKJ;HIJ‏9JI9:::::9JJ‏JJJ99;<<<;;::JJ9‏HJ99:;<====<;;::JJKJ‏
JJ9:9:;<=>MM>=<<<;::::JI‏JHJ999;<=>>M?NN>=<<<;;;:::KJ‏JHJJ::;<<<=>??NNNNM>=<;;;;:::I9I‏H8J;<<==>?NNNONNN>==<<;:JJII‏8H:;<=>>??NNN???=<;;;9HH‏
J8H:<<==>?M?>=<<:8JI‏IH9:;<=>>><;;:KK‏8IJ:;<=<;:J8‏IK;;;::J‏:<J9ÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGסFIHGHGFDFHJFIHHIHHHIGIGHHHGGססJJHFHHGHGGHGFJGHGGHDHIJHFFףסססעMףנHHFHHHIHHGHFHHFHJHHGצפףףץKMעסGFJHGGHFIIHIHHIIצצצצקקקMעסנKKIIHנHGHGHIGHHIHFרררקIץץקGפעעעצצGףGIHDHHDHצצרררקJפץףקקקץץעעIצJEMIGHHJצצקקררקGCפעעקKססצKעץץILצצקקררקרפLעעקק	J‏ססצJKעIץקקקעGפפMקרJקקצצ‏ףLMצKJעKעפקLףGפLקרLרצצ‏
נצפףFנJIעקץHקקררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFףצצצKKLJJHHFHHHIHHGHFHHFHJHHGצפשרMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקשעקעJMLKLHצצסףGIHDHHDHצצLHתקץשעףקקJקץKMMKLססKGHHJצצקקרLGרשעעצצרKKרJJנFKףסIIץרקרקרעצG	JעעצקשרננרנIHKצסנףץצצףצעצרL	MפצצרררLסKKנJKJKנץנץKצעMצר	FעILקצררקףנננJKףLנץJJעעצתרשILIJתששררצJצLKצKKנץץנKLנףשLשסKGKשששרפץנKףסJJץננJצננץקשעJIרKIרשעפפפףפKJנJKLKKננקקIMMGHתרIJעLפפץצJKJJIMLנצנפץצJKנץIשררMLIMפץפLLקקKHLצפףHסשHIףץץעIרצףפJIJץקLIףLKIKMץץJסץקשרJץעףצIקצץJJנKJץץLJJIףפץפססשקקץJףףMKקקMצסGף
קנJנץIססקץעעפGKצקKץMנKJL
ץLצצץפססשעףספרתץקMףף‏KKIIHHKLפIKנLKףKKפעשרףףJIףצצGKMץףGKIפנJסףJצףעשצפףJתצףקץLץץףףץIJEMIKפKJנHקMצצפעGCפעףצKJMץעףףסKנצנILKJKKHJעעעפץLררררקJקר‏סJKIעץפקקGעעMפרJûרקקצצ‏LMסKJKעעעפLקGףLפץLרררצצ‏
נצFףJIסעעHץץקרררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ	‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGסFIHGHGFDFHJFIHHIHHHIGIGHHHGGסססHFHHGHGGHGFJGHGGHDHIJHFFףסססעLףKKHHFHHHIHHGHFHHFHJHHGצILףץפעJGFJHGGHFIIHIHHIIצLIJקקקעעסJףפLKKHGHGHIGHHIHFרKרGKץץקעפעעעKצסJJGIHDHHDHצצרJרIץKIףקקקץץעעKסJJKLGHHJצצקIMMGHפפIJקLנסרץףנJצKJJIMLעץףצצףJKפרIררצMLIMפףצLLKHצפLץץקHעץררHIףצקקIץפצצJIJףסLILKIKMפצJרץרפףJףצקIקצJJפעKJנLJJIץץףשרפעפפעJצקMKץפMנGנפJצץפשIשרףספצצGKרףK‏ץMעKJLננLףצצפששרףףפצףצצרףMץףKKIIHHKLנIKסLKצKKקצץףעצJIקץקGץףףץףננGKIרננJפקJצצפעצעפJףצץץץץעףףסIנJEMIKרKJסשHעMפץררGCרקרקK‏ססKעעILKJKKHJפפרקרLקקצצ‏J‏ףסצצJKעIעפקקףGפץMררJצצ‏
LMצKJףKנסעעLץGקLררL‏סעFJIעקקHצצצצ‏נJFעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFצצצסKKLJJHHFHHHIHHGHFHHFHJHHGצפףףMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץפץףקקJקץKMMKLססKGHHJצצקקרLGרפפעעקקKKרJJנFKףסIIץרקרקרררGרJפעעקשסננרנIHKצסנףץצצףצקרקLצMפצצצקפLסKKנJKJKףץנץKצצMררקFץILקצףצקףנננJKףLJJעפצרררILIJרששפצצJצLKצKKננKLףףצLררKפGKרשששפץנKףסJJננJצצררJצIקKIרשףץץפףפKJנJKLKKצפקקIMMGHררIJצLפץץפצJKJJIMLנצףפץצJKצפIרררMLIMץץפצצLLפKHLצפףHצףץפHIףררצIצצףפJIJץץLILKIKMץץJקצעץרJףףףצIקצץJJצKJסLJJIףפץפצצרץרפJףףMKקקMצסGעענJנץIףשרפעפפGKצקKץMנKJLנפLצצץפשששרףספצצץקMףף‏KKIIHHKLנIKנLKףKKפששרףףJIףצצGKMKMףGKIננJסףJצףצקצץףJצצףקץLץLףףץIJEMIKנKJנHקMצצפעGCפעףצKJMJMףףסKנצנILKJKKHJקעעפץLררררקJקר‏סJKIעץץקקGעעMפרJררקקצצ‏LMסKJKעעעפLקGףLפץLרררצצ‏
נצFףJIסעעHץץקקררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFצצססKKLJJHHFHHHIHHGHFHHFHJHHGצפףףMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץפץףקקJKMMKLססKGHHJצצקקרLGרפפעעקקKKJJנFKףסIIץרקרקרררGרJףעעקשסננץנIHK	צצננסץצצףצקרקLףMפצצצקפLסKKפJKJKפצףנסKץצMררקFץILקצףצקףקצצJKLעצJJסנץרררILIJשששפצצJ		LKפKKץצצKLרסץLררKGKרשששפץצקKJJעצצJצשסףתJףIתKIרשףץץפףפףצKJJKLKKצפשרIMMGHררIJצLפץץפצJקKJJIMLענףפררJKצףIתררMLIMץץפצצLLקצKHנLצפצHצףרשHIףררצIצצףפJIJק	LILKIKMץץJקקשûרJףףףצIקצץJJצ‏KJףLJJIףפץצרששררץJףףMKקקMצסףGצסJץנץIרשûר	פפGKצקKץMסKJLנפLצצץפשרר	פספצצץקMףף‏KKIIHHKLנIKנLKףKKפרר	ףףJIףצצGKMץףסGKIננJסףJצ			צץףJצצףקץLץץףףץIJEMIKנKJנHקM		פעGCפעףצKJMץעףףסKףק	ILKJKKHJ	עפצLרתתרקJקר‏סJK	IעץץקקGץM	תJתתתתתצ‏LMסKJKעעעצLקGףLתתLתתתצצ‏
נצנFףJIצHץרתקררר‏סעJFףצץקקתצצצצ‏נףצץףףפצ‏ססססף‏סססÿ‏HIJI‏GIIHIFGH‏FHGIHHLIMHHI‏HHHIKJJIIHHHFIHH‏FIGHGHHHIKIHHJHHHMIJ‏
HI7JHHIHHHHHIDHGHFGGGHHG‏5GHHHHFHFIGHHJKHHHHHHJDHGFIH‏HFH5HEHIIIGI6EHIHFHFIKH5HGIHHGIGJסHIHGGGHDFKJJJJIIIGHJGIGHHHGGצצKJKIIIHIHGIHIFJHJHKIDHIJHFFףצצצKKLJJHHF6IHIIIMHMHMHHJHHGצפצצMפKKIMJIKKLIJFIIHIHJHIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץףףקקJקץKMMKLססKIHHJצצקקרLGקרעקקKKרJJנFKףסIIץרקרקרררG‏JרעקשסנרנIHKצסנףץצצףננננLMתקשצקפLסKKנJKJKףץנץKששMשענFפILתצףצקףננJKףLJJערשץנILIJûתשפצצJנLKצKKננKLףףרLנ	KûGKרתששפץצנKJJננJצץרנקJûIשKIתתףפץפףפץפKJJKLKKצפקשסIMMGHררIJתLףץץפצJפKJJIMLנצףפץצJKצצIרררMLIMעץפצצLL	פKHLצפףHצףץפHIףררצIץעףפJIJץץLILKIKMץץJקצע	שJנףנצIץעץJJצKJLJJIףפץפ	צרקששJףףMKעעקMצסGצףנJנררIרצרשרקנGKתתKץMנKJLצפLצצצ	שששרשנעצצתקMףף‏KKIIHHKL	IKנLKףKKפששרענJIתתצGKMץףGKI	קJסףJצףצקצנJצרףקץLץץףףץIJEMIK	KJנHקMצצפעGCפעףצKJMץעףףסKנ	קILKJKKHJקעעפץLששûûקJקר‏סJKIר	ץקקGעעMפרJתûתרצצ‏LMסKJKששעפLקGףLפצLשûשצצ‏
נצFפJIסעעHץץקתרûש‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ