‏JJHK‏JJKJKHIJ‏HJIJJJJJJJJJ‏JJJJJHJJJHJJHJJJ‏HJIJIJJףJLJJJJKJ‏
JJGJJJJףפץIJHKJIIJI‏JHJJJJHJנפצפפצקJJJGJIHKJ‏JHJJJGHKJKנףשףעףפקרHJJIKJJIKI‏HKJIJIHנץתפרקרקפפץתקJIJKIII‏JHJJKשרûץשששתץקשûרHJHH‏
JJHIHצתשתüתשר
ûJJI‏IJKJJIJKIûתשKK‏JJIJKIIJJKJH‏IKJGJJGJ‏IKJKÿ‏JJHK‏JJKJKHIJ‏HJIJJJJJJJJJ‏JJJJJנJJJ‏HJIJ	נפץרûûJJKJ‏
JJGJשש	תרû	KJIIJI‏JHJJJפקרתת
נף	JJJJGJIHKJ‏JHJJJGHקפפקשת
	JHJKIJנצצIKJJIKI‏HKJIJIקקüüüHKJJKJHקJJJII‏JHJJKJIIJIHLIJצקרר	ץJHH‏
JJHJנ	צצרשתûû	JJI‏IHףצש

ûששKK‏Jששש
צIJJKJH‏IKJGJJGJ‏IKJKÿ‏JJHK‏JJKJKHIJ‏HJIJJפפץJJJJ‏JJJJעעצJJJ‏HJIJעעJJKJ‏
JJGJJ²³ףץIIJI‏JHJJJפף´³²²פףערקIHKJ‏JHJJJGH	קץףע´µ´´עפץפףשתשKJJIKI‏HKJIJ	שצפץףµ·¶··ףצתשûJJII‏JHJJתקקרצש¹¸¶¶רשüתשJHH‏
JJHששתץרתצ¹¹רשתüûJI‏IHKJIתקר¹שתûJKK‏JIJI			H‏IKJGJJGJ‏IKJKÿ‏‏‏‏‏‏
‏	‏‏‏‏‏	‏	‏‏‏		‏
		נף		
‏JHJ			
	נ	

IKI‏HK			


	


	JII‏JH			
	נ	


JHH‏
JJJJJHJ
				

JI‏IHKJIIJ



KK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏נ‏‏ס‏‏	‏		
‏	
	‏	


‏					

‏
	
		



‏	
		

‏




‏	
	נ‏		
	‏		


	



‏
	



	


‏		
	
	
	‏		

	
J‏JH	
JJIKI‏				עסJJJII‏J		
				
		נףKHJHH‏
JJ
	
	

	
JHJJI‏IHKJIIJKKJKJJKK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏‏‏‏‏‏‏		‏	‏
		‏		
	‏	
		ק‏					
‏	
	

‏	XW‏		קתתüWW‏			תתתתWV‏	ףץקתתתתWWV‏
		שüüWVXW‏	
			
	שש	VWWV‏JHJ
			ץץץ
ש	ששü
WWWVJHJJJG						
û
ת	ûWWWW‏HKJIJ
		
ר
	תתWWX‏JHJJ			רר
	ûû
JHH‏
JJH	

	ררר
	תתJI‏IHK	
ר	רררתKK‏JIJ	
	ף		KJH‏IKJGJJGJ‏IKJKÿ‏‏‏‏‏		‏	‏			
‏
	
	
‏



ü‏
	
	‏			ü	
‏

			

	‏	


‏	
		üü‏Hנ			

תת‏JJJJJ
üüüü	‏HJIJIJJJנ			JKJ‏
JJGJJJJJJHJKJFJIJHKJIIJI‏JHJJJJHJHKIJJKHJJJJJJJGJIHKJ‏JHJJJGHKJKJHJGJJJHJKIJHJJIKJJIKI‏HKJIJIHFHJLHKJJKJHJKIKIJJJII‏JHJJKJIIJIHLIJIIJGJKHJHH‏
JJHJJJHJJIJHJJHJHJJI‏IHKJIIJHKKJKJJKK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏‏‏‏‏‏W‏	
‏‏‏			‏		


‏XX	

נ‏VXWWרע‏XXVXXX	
	

	ץ
		
צ‏WVXWXX	

				ץץץץ			ק	
‏VWWWWWש

	


צ





ר
‏WWXVWWשüü
רצצ				
‏VWXWWVûüüüüצצ		

רש‏VWVWWVW					


רתû‏WVVWXVW	
üûûJ‏VWWWXWXVûתת


üת
KJKJ‏WVVVWVVWת



KIJGHJIKI‏VVWVVWüüüüתת	
KIJIGJJJII‏WVV	üüüKIJKIJKIJIGJHJHH‏
VüüüKIJJJIJHKIGJJJJI‏IHKJIIJHKKJKJJKK‏JIJIJKIJJKJH‏IKJGJJGJ‏IKJKÿ‏JJ8K‏:JKJ;HIJ‏9JI9:::::9JJ‏JJJ99;<<<;;::JJ9‏HJ99:;<====<;;::JJKJ‏
JJ9:9:;<=>MM>=<<<;::::JI‏JHJ999;<=>>M?NN>=<<<;;;:::KJ‏JHJJ::;<<<=>??NNNNM>=<;;;;:::I9I‏H8J;<<==>?NNNONNN>==<<;:JJII‏8H:;<=>>??NNN???=<;;;9HH‏
J8H:<<==>?M?>=<<:8JI‏IH9:;<=>>><;;:KK‏8IJ:;<=<;:J8‏IK;;;::J‏:<J9ÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGסFIHGHGFDFHJFIHHIHHHIGIGHHHGGססJJHFHHGHGGHGFJGHGGHDHIJHFFףסססעMףנHHFHHHIHHGHFHHFHJHHGצפףףץKMעסGFJHGGHFIIHIHHIIצצצצקקקMעסנKKIIHנHGHGHIGHHIHFרררקIץץקGפעעעצצGףGIHDHHDHצצרררקJפץףקקקץץעעIצJEMIGHHJצצקקררקGCפעעקKססצKעץץILצצקקררקרפLעעקק	J‏ססצJKעIץקקקעGפפMקרJקקצצ‏ףLMצKJעKעפקLףGפLקרLרצצ‏
נצפףFנJIעקץHקקררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFףצצצKKLJJHHFHHHIHHGHFHHFHJHHGצפשרMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקשעקעJMLKLHצצסףGIHDHHDHצצLHתקץשעףקקJקץKMMKLססKGHHJצצקקרLGרשעעצצרKKרJJנFKףסIIץרקרקרעצG	JעעצקשרננרנIHKצסנףץצצףצעצרL	MפצצרררLסKKנJKJKנץנץKצעMצר	FעILקצררקףנננJKףLנץJJעעצתרשILIJתששררצJצLKצKKנץץנKLנףשLשסKGKשששרפץנKףסJJץננJצננץקשעJIרKIרשעפפפףפKJנJKLKKננקקIMMGHתרIJעLפפץצJKJJIMLנצנפץצJKנץIשררMLIMפץפLLקקKHLצפףHסשHIףץץעIרצףפJIJץקLIףLKIKMץץJסץקשרJץעףצIקצץJJנKJץץLJJIףפץפססשקקץJףףMKקקMצסGף
קנJנץIססקץעעפGKצקKץMנKJL
ץLצצץפססשעףספרתץקMףף‏KKIIHHKLפIKנLKףKKפעשרףףJIףצצGKMץףGKIפנJסףJצףעשצפףJתצףקץLץץףףץIJEMIKפKJנHקMצצפעGCפעףצKJMץעףףסKנצנILKJKKHJעעעפץLררררקJקר‏סJKIעץפקקGעעMפרJûרקקצצ‏LMסKJKעעעפLקGףLפץLרררצצ‏
נצFףJIסעעHץץקרררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ	‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGסFIHGHGFDFHJFIHHIHHHIGIGHHHGGסססHFHHGHGGHGFJGHGGHDHIJHFFףסססעLףKKHHFHHHIHHGHFHHFHJHHGצILףץפעJGFJHGGHFIIHIHHIIצLIJקקקעעסJףפLKKHGHGHIGHHIHFרKרGKץץקעפעעעKצסJJGIHDHHDHצצרJרIץKIףקקקץץעעKסJJKLGHHJצצקIMMGHפפIJקLנסרץףנJצKJJIMLעץףצצףJKפרIררצMLIMפףצLLKHצפLץץקHעץררHIףצקקIץפצצJIJףסLILKIKMפצJרץרפףJףצקIקצJJפעKJנLJJIץץףשרפעפפעJצקMKץפMנGנפJצץפשIשרףספצצGKרףK‏ץMעKJLננLףצצפששרףףפצףצצרףMץףKKIIHHKLנIKסLKצKKקצץףעצJIקץקGץףףץףננGKIרננJפקJצצפעצעפJףצץץץץעףףסIנJEMIKרKJסשHעMפץררGCרקרקK‏ססKעעILKJKKHJפפרקרLקקצצ‏J‏ףסצצJKעIעפקקףGפץMררJצצ‏
LMצKJףKנסעעLץGקLררL‏סעFJIעקקHצצצצ‏נJFעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFצצצסKKLJJHHFHHHIHHGHFHHFHJHHGצפףףMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץפץףקקJקץKMMKLססKGHHJצצקקרLGרפפעעקקKKרJJנFKףסIIץרקרקרררGרJפעעקשסננרנIHKצסנףץצצףצקרקLצMפצצצקפLסKKנJKJKףץנץKצצMררקFץILקצףצקףנננJKףLJJעפצרררILIJרששפצצJצLKצKKננKLףףצLררKפGKרשששפץנKףסJJננJצצררJצIקKIרשףץץפףפKJנJKLKKצפקקIMMGHררIJצLפץץפצJKJJIMLנצףפץצJKצפIרררMLIMץץפצצLLפKHLצפףHצףץפHIףררצIצצףפJIJץץLILKIKMץץJקצעץרJףףףצIקצץJJצKJסLJJIףפץפצצרץרפJףףMKקקMצסGעענJנץIףשרפעפפGKצקKץMנKJLנפLצצץפשששרףספצצץקMףף‏KKIIHHKLנIKנLKףKKפששרףףJIףצצGKMKMףGKIננJסףJצףצקצץףJצצףקץLץLףףץIJEMIKנKJנHקMצצפעGCפעףצKJMJMףףסKנצנILKJKKHJקעעפץLררררקJקר‏סJKIעץץקקGעעMפרJררקקצצ‏LMסKJKעעעפLקGףLפץLרררצצ‏
נצFףJIסעעHץץקקררר‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ‏HHFI‏HHIHIFGH‏FHGHHHHHHHHH‏HHHHHFHHHFHHFHHH‏FHGHGHHHIEHHHJHHHHIH‏
HHEHHHHHHFHIHDHGHFIHGGHG‏HFHHHHFHFIGHHIFHHHHHHHDHGFIH‏HFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGJסFIHGHGFDFHJFIHHIHHHIGIGHHHGGצצKJKHFHHGHGGHGFJGHGGHDHIJHFFצצססKKLJJHHFHHHIHHGHFHHFHJHHGצפףףMפKKIMGFJHGGHFIIHIHHIIצצצצקקקעעסKפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץפץףקקJKMMKLססKGHHJצצקקרLGרפפעעקקKKJJנFKףסIIץרקרקרררGרJףעעקשסננץנIHK	צצננסץצצףצקרקLףMפצצצקפLסKKפJKJKפצףנסKץצMררקFץILקצףצקףקצצJKLעצJJסנץרררILIJשששפצצJ		LKפKKץצצKLרסץLררKGKרשששפץצקKJJעצצJצשסףתJףIתKIרשףץץפףפףצKJJKLKKצפשרIMMGHררIJצLפץץפצJקKJJIMLענףפררJKצףIתררMLIMץץפצצLLקצKHנLצפצHצףרשHIףררצIצצףפJIJק	LILKIKMץץJקקשûרJףףףצIקצץJJצ‏KJףLJJIףפץצרששררץJףףMKקקMצסףGצסJץנץIרשûר	פפGKצקKץMסKJLנפLצצץפשרר	פספצצץקMףף‏KKIIHHKLנIKנLKףKKפרר	ףףJIףצצGKMץףסGKIננJסףJצ			צץףJצצףקץLץץףףץIJEMIKנKJנHקM		פעGCפעףצKJMץעףףסKףק	ILKJKKHJ	עפצLרתתרקJקר‏סJK	IעץץקקGץM	תJתתתתתצ‏LMסKJKעעעצLקGףLתתLתתתצצ‏
נצנFףJIצHץרתקררר‏סעJFףצץקקתצצצצ‏נףצץףףפצ‏ססססף‏סססÿ‏HIJI‏GIIHIFGH‏FHGIHHLIMHHI‏HHHIKJJIIHHHFIHH‏FIGHGHHHIKIHHJHHHMIJ‏
HI7JHHIHHHHHIDHGHFGGGHHG‏5GHHHHFHFIGHHJKHHHHHHJDHGFIH‏HFH5HEHIIIGI6EHIHFHFIKH5HGIHHGIGJסHIHGGGHDFKJJJJIIIGHJGIGHHHGGצצKJKIIIHIHGIHIFJHJHKIDHIJHFFףצצצKKLJJHHF6IHIIIMHMHMHHJHHGצפצצMפKKIMJIKKLIJFIIHIHJHIצצצצקקקעעסKףפHנHGHGHIGHHIHFJLLרקקץץקעJMLKLHצצסףGIHDHHDHצצLHרקץףףקקJקץKMMKLססKIHHJצצקקרLGקרעקקKKרJJנFKףסIIץרקרקרררG‏JרעקשסנרנIHKצסנףץצצףננננLMתקשצקפLסKKנJKJKףץנץKששMשענFפILתצףצקףננJKףLJJערשץנILIJûתשפצצJנLKצKKננKLףףרLנ	KûGKרתששפץצנKJJננJצץרנקJûIשKIתתףפץפףפץפKJJKLKKצפקשסIMMGHררIJתLףץץפצJפKJJIMLנצףפץצJKצצIרררMLIMעץפצצLL	פKHLצפףHצףץפHIףררצIץעףפJIJץץLILKIKMץץJקצע	שJנףנצIץעץJJצKJLJJIףפץפ	צרקששJףףMKעעקMצסGצףנJנררIרצרשרקנGKתתKץMנKJLצפLצצצ	שששרשנעצצתקMףף‏KKIIHHKL	IKנLKףKKפששרענJIתתצGKMץףGKI	קJסףJצףצקצנJצרףקץLץץףףץIJEMIK	KJנHקMצצפעGCפעףצKJMץעףףסKנ	קILKJKKHJקעעפץLששûûקJקר‏סJKIר	ץקקGעעMפרJתûתרצצ‏LMסKJKששעפLקGףLפצLשûשצצ‏
נצFפJIסעעHץץקתרûש‏סעJFעקקקצצצצ‏נףעפץףףפצ‏ססססף‏סססÿ