þJJHHþIIHGHHHHþHHIJJ©©FIHHHþFHHJFHH­¯EªJFJHFFþFHHIHI®‹®E¯FJGEIHDIHþ
HDIFHI®GŽGFEGFFFHFEHHGþHHEIHI¯îGFŒE‹FGFG„GEHIFHHHþHIIEFHIª®EGGŒGFGEG‹GFG„HIFHHHIGþHHFHI¨FGHŒFFEŒFFFGHGF©GHIHHGþHFFHIHIEEEJFJGEEIHIHFHDFþ
¤HIHIGHHE‹JHHGIHI¦HFþGJFHHJ‹F‹JHHFJIIþHIGJFGFJJI¥FþGHGJGHIHþHJJJÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;<====<;;::HIIHþ
HH9:9:;<=>MM>=<<<;::::HGþHFH999;<=>>M?NN>=<<<;;;:::IHþHFHH::;<<<=>??NNNNM>=<;;;;:::G9GþF8H;<<==>?NNNONNN>==<<;:HHGGþ8F:;<=>>??NNN???=<;;;9FFþ
H8H:<<==>?M?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHIJJIFHHFHHHþFHIIIJJJ99IIIJIIHHIHþ
II:<=>:;<=<;:98999IHGGHGþHIIJ989:<=>>====::;=II888FIHþHFHHHHIIJJ88<>?>>>;<<>==;:IHHGIGþFIHGHGHIIJ::;<=89:JIHIHGGþHFHHGHHIJKK=8IIHIJHFFþ
HHIIIJK<88IIIHIHHGþGIJI<89IIIHHHIIþHI=9IIGIHIHFþIIIDHHDHþGHHJÿþJJHKþJ77JKHIJþHJ7<;87JJJJJþJJ878=;8:798HJJJþHJI79;:>9;8::7JJJKJþ
JJGJ7;<=<;9;;87KJIIJIþJHJJJ7===>>
98JJGJIHKJþJHJJJGH9>>>Z
::JJIKJJIKIþHKJI9;??	


;7IJJJIIþJHJ77;887HJHHþ
JJH8;:7JHJJIþJH8;<;7JJKKþJI8998I8JKJHþIKJGJJGJþIJJKÿþJJ8Kþ:JKJ;HIJþ9JI9:::::9JJþJJJ99;<<<;;::JJ9þHJ99:;
===<;;:9JJKJþ
JJ9;9:;<>>L
J;KJI:JIþJHJ	99;<
>M
J9988IHKJþJHJJ8<<
NJ99	IKJJI9IþH8J;<<;??NN>LKJI:JJIIþ8HJ9:;<=L?
ML=
JK;<HHþ
J8H=<<=>=<H8JIþIH9:;<=>==<;;<KKþ8IJ:	
=<;:J8þIK;::Jþ:<J9ÿþþþ	þþ
þ
þþþþ
HþþHHIH\\HþþFHGHHHH]
H]þHHHHHFHHHF]HHþFHGHGHHHIEHHH^^HHIHþ
HHEHHH9::799HDH\FIHGGHGþHFHHHH8H9:<=:::<
[::HDHGFIHþHFHHHEFI89:9:;<<;<;::HGIHHGIGþFIH9999:><<=>>
===<>:HHHGGþHF9H:;<=<
==<::Fþ
H::=<=??>?>::;þ;<;=>>=?>==<;:þ;:<=>>>?<::þ;<=<<;;Hþ::<=ÿ	þþþ]þ]þþ^þþ^þþþþ
þ]þ^]þþ^^þþ^_þþ
þþþþþ
þþJJ_þJ::_IJþH::JJ^JJJJþJJJJ;=;^;::JJJþHJ:J=:;<=_<;;:::KJþ
JJG:::;<<===<;=:IJIþJ::J::;<<===^]=<<;:9HKJþIHJJ::=;<<==??>_=;;9999KKþH:::<<<<=
?>==>>><=<;9þJ:;<==???>>>>>==>>><;:þ
:;;<<==>>>===>==<<>;þ:;:;<<<<===>=<<;þJ:;<<<<<:;:HþIKJ;;JGJþIKJJÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþ FHþHGþIþFGHþFþHFHGþHþHFþFþIþGHHIIIþGHþFHþHGJKFMMJHGþFþHGþHIMGHIMFHMJGHIþHFþFþLGHIIHMMHGLIIHMIþGHþFHJIHGKMHIKJNLGHNIKJHGþ	HGLIILHIIMLLNIHGKLHHLKGHIþLJLGHJKIJMFLMMLMHIIJLIIHLJMJþLJLIHGJMMMMJMFHNJKIMNFLNLIKJLIMKþJMLKLKJLMMHGLLIOLHFMKLLLLLKIþLJLLMLKKLMGHMINMGHLMJLJJþ
LLJLLLIHGMLJHGJLJLLKþKJMLKKLJMMLGHIMMþLKLKLMKLLMLJþKMLILLILþKMLMÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKUSGJGHKJGEþFþGJIKQ	
UUSRJJIGJGþFþFJEJJGU		WUSRSKIIIIGþJHGJGJQS
	WYWUKJKHIJþJHJJIGIKS	
	W

TIIJKIKIþHKKIKIIT	
	

VJKJIIþJHJJKJKIU	

	XSTV		ZJHHþ
JJHJJJGJJIJ[T	VKJIþIHKJIIJHKK	WKþJIKIJKIJJU
XþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGSUTUJIþFþFþJIJKJGJãKJGEþFþGJIKIJEIT

UJIGJGþFþFJEJJGJJGR	

UKIIIIGþJHGJGJFIFKT	
	WUKJKHIJþJHJJIGIKGKGHRã
TUJIIJKIKIþHKKIKIIFIJSSU	

VWIJKJIIþJHJJKJKIFU		IK		ZYZJHHþ
JJHJJJGJJIJHKTHKJIþIHKJIIJHKK	WKþJIKIJKIJJ

XþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJITSSIþGþGHI		
USJIþFþFþJIS		

KJGEþFþGJãUU		
	äSIGJGþFþFJETUVä		


UUTSIIIGþJHGJWXWXXY	
TS	
VUVKHIJþJHJJIGXWXYZ[ZYSãTUVY	
XXWY[JKIKIþHKKIKIIFIJLSTUUXXVZYZYZ[\JIIþJHJJKJKIFäUäXZZZJGJIHJHHþ
JJHJJJGJZY[\\\HJã]JIþIHKJIIJHKKJKJçé]þJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGSUGJTTSJGEþFþGJIKIJVTIGJGþFþFJEJJGJ	
	

TKIIIIGþJHGJGJFIT
	UKJKHIJþJHJJIGIKGKX

	
	
	UJIIJKIKIþHKKIKIIF\ZX		
VIJKJIIþJHJJKJKIF\ZZXWUVWHJHHþ
JJHJJJGJJI\ZXXWVUKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþHGHIHHHIGHHHHHHEF¤þHHJHHHHGHFHGHIEHFH¢¢þ
IHFHGHFIFGGHHEFHHIG¢¡¤þHHIGHFHHGHHFDFGHGGHF£¢£¤þGHFHGHGHHEHFEHGHEGHHG¡¡¤¢¤þFGFHGHHFIEFHIGGFHGIIHI¢£¤¢¡£þHHHGEFGEFGHGGHFEHGHIGHH¤¢¡£¢¤¢IEFGEFHIHFHHEHFGHGGIHFHH£¢£¢¤£¢¤þGGGJHFGHGIIHIHHIHHGHH¡¢¡¤¡¢¤þHHGHHHIGHHGHGHGGHF£¢£¤¢£þ
HGIHFHFHHHHGHHG£¢¡£¡þGGHHHGHGIIHI¢¤¢¤þHGHGHIGHH££¡þGIHJHH¢¡þGHH£ÿþHGHIHHHIGHHHHHHH£¤þHHJHHHHGHFHGHIGH¡¢¢¢þ
IHFHGHGIHGGHHIHH¡££¢¡¤þHHIGHHHHHHHFGHGH¤¢¤¢£¢£¤þGHGHHHGHIGHGHHHI¡£¡¢£¢¡¤¢¤þFGHJGIHHIHHHIGGG£¢¤£¢£¢£¤¢¡£þHFHGGHGGHGHGGHFG¤¢¡¤¡¢£¤¢¡£¢¤¢IHHGHHHIHHIHGHHG¤¢£¤¢£¢££¢£¢¤£¢¤þ¡¢ ¡¢ ¡¡ ¢ ¢¡¢¢¤¢£¡¢¤£¢¡¤¡¢¤þ¡¢¢ ¢ ¢¡¢¡ ¡£¡¢¤£¢£¢£¤¢£þ
¢¢ ¡¡¢¢¡ ¡¤¢¤¡¢£¢¡£¡þ¡¢¡ ¡ ¡¢¤£¢£¢¤¢¤þ¢ ¢¢¡¢¤¡¢££¡þ¡¡ ¡¢¢¢¡þ¢¡¤£ÿþHHFHþHGHGHHILþIHIHGIHIGJJLþHHGGHHHHHHJKIKJKþGGGHHHGHIGHIJIKILJLJþ
FGHJGIHHIHHJIJJKJKKKKKILþHFHGGHGGIGHGGHHIKLKJLLLJLKLJþIHHGHHHIHHHHGHHGJJIKLLKLKLJLKLJIþ¡¢ ¡¢ ¡¡ ¢ ¢¡¢£¤£¤¢£¤££¢£¢¤£þ¡¢¢ ¢ ¢¡¢¡ ¡£¤££¡¢¤£¢£¤¡þ
¢¢ ¡¡¢¢¡ ¡¤£¢¤£¢£¢£¤þ¡¢¡ ¡ ¡¢£¢¤¡¢¤¢£þ¢ ¢¢¡¢¤£¢£¢¤þ¡¡ ¡£¡££þ¢¡££ÿ¡¡LJLKKLJJKKLKKJKLþ ¡¡ JJLKJKLLKLLLLJKLþ   ¢¡ JLILLJJLKKLKKKLLþ
¡  ¡ ¡¡¡LLKJLLLJLLLLJLJKþ ¡¢  ¢ ¢¡ KLIKKLKKLJLLLKJLþ ¢¡¡¡ ¡¡¢ ¡ LLKLLLLKLLKJKJLJþ¡¡ ¢ ¢¡ ¡¢ ¡¡¡LJLKKLKKJJLKKLKJþ¡¢¡¡ ¡ ¡ ¡¡ ¡ ¡¡JLLJLKLLKLLLJJLJþ ¡ ¡¡ ¡ ¡ ¡¡¢¡£¢£¤¢£¢££¢£¢¤£þ¡ ¢¡ ¡¢ ¢ ¡¡¢¤¢£¡¢¤£¢¡¤¡þ
 ¢¡¡ ¡¡¡¢ ¢¡¢¤£¢£¢£¤þ¢ ¢¡ ¢¡ ¤¢¤¡¢£¢¡þ¡ ¡  ¡¢£¢£¢¤þ¢¡  ¢¡¢£þ  ¢¢ÿ¡LLMLKKLJJKKLKKJKLþ  KJMJMKJKLLKLLLLJKLþ  ¡LKLJLMMLJJLKMLKKKLLþ
¡  ¡LJMKLLKLMLLLLLLLJJIKþ ¡¢ ¡LLLJLMLKKMLMKLJLLLIJLþ ¢¡¡¡ KLHKILMLKLLLMMLLKJKJJJþ¡¡ ¢ ¢¡LJLLLJLLJMKKLKMMJMKMLKJþ¡¢¡¡ ¡ ¡LLLLLLLLJLMJLKLLKLMLMLMHþ ¡ ¡¡ ¡KKKJLLKLKLKKJLKNLKJKJþ¡ ¢¡ ¡LLLJLKKJLLKKLKLKLLþ
 ¢¡¡ LLHKIKLLLLHLKKLþ¢ ¢ LJLLJLKKLLKKþ¡ ¡LKLKLKLKLþ¢ KLHLKKþ¡LLKÿþHGþIKIIþHGIJKKþHGHJJKILþHHFIKIJKJLþHHHGIIIKKHLLþIGIHIHKGKJJLLLþHHHHHIIJIKKLIKKKþHGHHHGHHIHIHKLLLLLþGHFIGHHHJKIKJIJLLLJLþHHHGHIHFKGHGIJKLLIKKLKþ	HGIGHHIGGHIHHJKKILKLJLLLþHIHGHGHHHGHIGIJILILKLLKKJLþGGFGHJGIHHIHJGIHKIJLLLILJLKLþHHFHGGHGGJGHGGJHIIKKLLKJKLJKJKþIHHGHHHIHHHHGHGHGJKILKKJLLKKLKLLþGGGJHGGHGIIHJHGHILJLKLLKLLLJþHHGHGHIGHHGFJIKJKKJLKKLKþ
HGIHFHHHHIHJJILKKJKJþGGHHHGJHIILJILKLþHGIGHHLJHKKKþGFGIHIKJþJHJIÿþHGHþIHIGGHþHGHHHHGHHþHGHHHGHHGHIGþHHFIGHHHHHHHHHHþHHHGHIHFHGHGIHGGGHþIGIGHHIGHHHHHHHFJHHHHþ
HHHHHHHHHGHIGHGHHGHGIHGGþHGHHHGHHGHIHHHIGHHHHHHHF¤þGHFIGHHHJHHHHGHFHGHIGHGH¢¢þHHHGHIHFHGHGIHGGHHIHHHIG¢¡¤þHGIGHHIGHHHHHHHFGHGHGGHF£¢£¤þHIHGHGHHHGHIGHGHHHHHGHHG¡¡¤¢¤þGGFGHJGIHHIHHHIGGGHGIIHI¢£¤¢¡£þHHHHGGHGHHGHGGHFGHGHIGHH¤¢¡£¢¤¢IHHGHHHIHHHHGHHGHGGIHFHH£¢£¢¤£¢¤þGGGJHGGHGIIHIHHIHHGHH¡¢¡¤¡¢¤þHHGHHHIGHHGHGHGGHF£¢£¤¢£þ
HGIHFHHHHHHGHHG£¢¡£¡þGGHHHGHGIIHI¢¤¢¤þHGHGHIGHH££¡þGIHJHH¢¡þGHH£ÿþKLLþKKLJLKþLKLKLKLKLþKKLLKKLJLLJLþLKKLILLLLKIKHLLþLLKLKLKKLLJKKLJLLLþJKJKLKKLJKKLKLKLLJKKKþ	LLLJLLLKLLKLJLLJLLLLLLLLþ¡LLHLKKLJJKKLKKLJLLJLLLJLþ  KJHJLKJKLLKLLLLKLLLIKHLKþ  ¡LKLJLILLLJLKKLKKHLKLJLLLþ¡  ¡LJKKLLKJLLLLLLLLJKLLKKJLþ ¡¢ ¡LLLJLKLHKKLKKLJLLLILJLKLþ ¢¡¡¡ KLHKILLLKLLLLKLLKJKLJHJKþ¡¡ ¢ ¢¡LJLLLJLLJLKKLKKJJLKKLHLLþ¡¢¡¡ ¡ ¡LLLLLLLLJLLJLKLLKLLLJLLLþ ¡ ¡¡ ¡KKKJLLKLKLKKJLKKLKJKJþ¡ ¢¡ ¡LLLJLKKJLLKKLKLKLLþ
 ¢¡¡ LLHKIKLLLLHLKKLþ¢ ¢ LJLLJLKKLLKKþ¡ ¡LKLKLKLKLþ¢ KLHLKKþ¡LLKÿþDþFþEþDþEþEþGþGþGþFþFþHFþEþFþFEFþFþGFþEþGGþFþGFþGGFFHIHþEGþGþGFþHFþFHþFHHIIGIHIþFGHþFFFþEþGþGGIGGIIIHFIIFHIHIEEGJFþEþGEþEIIHJJIIJIGJEJEIHIGHHJþEþHHþHFIIEJEFJJGJJJJIIJFHHJþFþHþHGHFIEIFGFIJFFJIJHIKIEIJJFGþJGþIHHEIHIHFJJFHJHIJHKKFFIJHGJGHEHIHIEIEFIJJJFHEJIKHKKHFIKJGJJHEJ¡¡GGHIIEHJEJIJFIKFGKIHFJHHFJGH£¤ ¡¡ IFGKJFHJJFEKIGIKHFHKJFGH¡¢¢¢   ¢¡ FJJGJHJFKKGIKHEHIKFH¡££¢¡¤¡  ¡ ¡¡¡HJHJGFKHIJKHHEKJ¤¢¤¢£¢£¤ ¡¢  ¢ ¢¡ HJFKHIJJKIGI¡£¡¢£¢¡¤¢¤ ¢¡¡¡ ¡¡¢ ¡ EHGJFFJE£¢¤£¢£¢£¤¢¡£¡¡ ¢ ¢¡ ¡¢ ¡¡¡HJIF¤¢¡¤¡¢£¤¢¡£¢¤¢¡¢¡¡ ¡ ¡ ¡¡ ¡ ¡¡¤¢£¤¢£¢££¢£¢¤£¢¤þ ¡ ¡¡ ¡ ¡ ¡¡¢¡¢¤¢£¡¢¤£¢¡¤¡¢¤þ¡ ¢¡ ¡¢ ¢ ¡¡£¡¢¤£¢£¢£¤¢£þ
 ¢¡¡ ¡¡¡¢ ¤¢¤¡¢£¢¡£¡þ¢ ¢¡ ¢¡ ¤£¢£¢¤¢¤þ¡ ¡  ¡¤¡¢££¡þ¢¡  ¢¢¢¡þ  ¤£ÿþHGHþIHIGGHþHGHHHHGHHþHGHHHGHHGHIGþHHFIGHHHHHHHHHHþHHHGHIHFHGHGIHGGGHþIGIGHHIGHHHHHHHFJHHHHþ
HHHHHHHHHGHIGHGHHGHGIJGGþHGHHHGHHGHIHHHIGHHHHJHH£¤þGHFIGHHHJHHHHGHFHGJIJH¡¢¢¢þHHHGHIHFHGHGJHJGJHIHH¡££¢¡¤þHGIGHHIGHHJHJHJFGHGH¤¢¤¢£¢£¤þHIHGHJHHHJHIGHGHHHI¡£¡¢£¢¡¤¢¤þGGFGHJGJHJIHHHIGGG£¢¤£¢£¢£¤¢¡£þHJFJIGHGGHGHGGHFG¤¢¡¤¡¢£¤¢¡£¢¤¢IJHGHHHIHHIHGHHG¤¢£¤¢£¢££¢£¢¤£¢¤þ¡¢ ¡¢ ¡¡ ¢ ¢¡¢¢¤¢£¡¢¤£¢¡¤¡¢¤þ¡¢¢ ¢ ¢¡¢¡ ¡£¡¢¤£¢£¢£¤¢£þ
¢¢ ¡¡¢¢¡ ¡¤¢¤¡¢£¢¡£¡þ¡¢¡ ¡ ¡¢¤£¢£¢¤¢¤þ¢ ¢¢¡¢¤¡¢££¡þ¡¡ ¡¢¢¢¡þ¢¡¤£ÿþKLLþKKLJLKþLKLKLKLKLþKKLLKKLJLLJLþLKKLILLLLKIKHLLþLLKLKLKKLLJKKLJLLLþJKJKLKKLJKKLKLKLLJKKKþ	LLNJLLLKLLKLJLLJLLLLLLLLþ¡¡LHLNKNJJKKLKKLJLLJLLLJLþ ¡¡ JJLKJMLLKLLLLKLLLIKHLKþ   ¢¡ JLILLNJLNKLKKHLKLJLLLþ¡  ¡ ¡¡¡LLKJLLLLLNLLJKLLKKJLþ ¡¢  ¢ ¢¡ KLIKKLKKLJNLNILJLKLþ ¢¡¡¡ ¡¡¢ ¡ LLKLLLLKLLKMKNJHJKþ¡¡ ¢ ¢¡ ¡¢ ¡¡¡LJLKKLKKJJLKKLNLLþ¡¢¡¡ ¡ ¡ ¡¡ ¡ ¡¡JLLJLKLLKLLLJJNJþ ¡ ¡¡ ¡ ¡ ¡¡¢¡£¢£¤¢£¢££¢£¢¤£þ¡ ¢¡ ¡¢ ¢ ¡¡¢¤¢£¡¢¤£¢¡¤¡þ
 ¢¡¡ ¡¡¡¢ ¢¡¢¤£¢£¢£¤þ¢ ¢¡ ¢¡ ¤¢¤¡¢£¢¡þ¡ ¡  ¡¢£¢£¢¤þ¢¡  ¢¡¢£þ  ¢¢ÿþKLIHþKKLJIKGHþLKLKLIJHIGHHþKKLLKKIJKGHHGHIGþLKKLILLLLKIHJHHHHHHHþ
LLKLKLKKLLJIHFHGHGIHGGGHþJKJKLKKLJKKLKLGKHHHHHHFJHHHHþLLLJLLLKLLKLJLLJKIHIGHGHHGHGIHGG¡LLHLKKLJJKKLIKLHIHHHIGHHHHHHHF¤  KJHJLKJKLLKLLJIKJGHFHGHIGHGH¢¢  ¡LKLJLILLLJLKJKIHGGHHIHHHIG¢¡¤¡  ¡LJKKLLKJLLLIJHHFGHGHGGHF£¢£¤ ¡¢ ¡LLLJLKLHKKLHKHHIHHGHHG¡¡¤¢¤ ¢¡¡¡ KLHKILLLKLIGHGHGIIHI¢£¤¢¡£¡¡ ¢ ¢¡LJLLLJLLJKGHHHIGHH¤¢¡£¢¤¢¡¢¡¡ ¡ ¡LLLLLLILJHGIHFHH£¢£¢¤£¢¤þ ¡ ¡¡ ¡KKKJLLKHIHHGHH¡¢¡¤¡¢¤þ¡ ¢¡ ¡LLLJIJKHJGHF£¢£¤¢£þ
 ¢¡¡ LLHKIHGHHG£¢¡£¡þ¢ ¢ LJLJKIHI¢¤¢¤þ¡ ¡LKLHHH££¡þ¢ KJIH¢¡þ¡LH£ÿ¡¡LJLKKLJJKKLKKJKIHHHIGHHHHHHH£¤ ¡¡ JJLKJKLLKLIJHHHGHFHGHIGH¡¢¢¢   ¢¡ JLILLJJLKHKIHGGHHIHH¡££¢¡¤¡  ¡ ¡¡¡LLKJLJLJJHHFGHGH¤¢¤¢£¢£¤ ¡¢  ¢ ¢¡ KLIKHLHGHHHI¡£¡¢£¢¡¤¢¤ ¢¡¡¡ ¡¡¢ ¡ LLILIJGG£¢¤£¢£¢£¤¢¡£¡¡ ¢ ¢¡ ¡¢ ¡¡¡LJFG¤¢¡¤¡¢£¤¢¡£¢¤¢¡¢¡¡ ¡ ¡ ¡¡ ¡ ¡¡¤¢£¤¢£¢££¢£¢¤£¢¤þ ¡ ¡¡ ¡ ¡ ¡¡¢¡¢¤¢£¡¢¤£¢¡¤¡¢¤þ¡ ¢¡ ¡¢ ¢ ¡¡£¡¢¤£¢£¢£¤¢£þ
 ¢¡¡ ¡¡¡¢ ¤¢¤¡¢£¢¡£¡þ¢ ¢¡ ¢¡ ¤£¢£¢¤¢¤þ¡ ¡  ¡¤¡¢££¡þ¢¡  ¢¢¢¡þ  ¤£ÿþJKGKþJIKEIHIIþHIIKJGKFJEJIþJIJKJGJIJGJGHKJGþGJIKIJEIKFJIEIEJJIGJþ
FJEJJGJJGKJGJKGKGHKKIIIIþJHGJGJFIFKIJJIEJIEIJJJKJKHIJþJHJJIGIKGKGHKGJKGHFGKJHFJIIJKIKIþHKKIKIIFIJLHKJIKGIJKIGIJKJIIþJHJJKJKIFIHLKJIKJGJIHJHHþ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJJJJJJIEIEJJIGJGþFþFJEJJGJJ©¨§§¨KGJJJJKIIIIGþJHGJGJFIH¨ª©¨¨©HIE§HKJKJKHIJþJHJJIGJKJJ¨ª«ª©©ªHF§KJHFJIIJKIKIþHKKJHI§¨ªª¨¨KJIK¨¨JKIGIJKJIIþJHJJKJKIFK¨LKJJJJGJIHJHHþ
JJHJJJGJK©¨JKKHJHKJIþIHKJIIJH©§JKJJKKþJIKIJKI§JKJHþIKJGJJJJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKJJJJKFJIEIEJJIGJGþFþFJJKH©ª©¨§JGJKGKGHKKIIIIGþJHGJGJF««¬©¨JJJJJEIJJJKJKHIJþJHJJIGIKGKGHK©Jª©©ª¨KKKJJIIJKIKIþHKKIKIIFIJLHK¬«««ªªªIGIJKJIIþJHJJKJKKKK¬¬¬¬¬«¬ª¨¨©JKJþ
JJKJ§¨©ª«IJHKKHJHKJIþIHKJJJJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKKJHJIþFþFþJIJKJJJIKKH§¨§JGEþFþGJIKIJHHK§J¨¨©©¨©IGJGþFþFJEJJGJKG§©ª¨KHKGHKKIIIIGþJHGJGJKKH§ªª«ª¨JJKKKJJKJKHIJþJHJJIGIKJ§©¬¬©§KKHFGJHHFJIIJKIKIþHKKIKIIJKJLHHKIKJKHJ¨JIJKJIIþJHJJKJJJKHJJJHI¨ª«§KHJHHþ
JJHJJJJH¨©©©©©ª§KKJIþIHKK©©©©KKHKJJKKþJIHIJHKKJJJHþIJKHHKJJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJJJKFJIEIEJJIGJGþFþFJEJJGJJKKKGJKGKGHKKIIIIGþJHGJGJFIFKHJHJJJIEIJJJKJKHIJþJHJJIGIKJKKHKGJJKHFGKJHFKIIJKIKIþHKKIKIJH§§LKK§¨§GIJKKJKKKJIIþJHJJKJH§F§§¨¨JIKKHJH§JHHþ
JJHJKJJKHIJHKKJH§¨¨IþIHKJIIJKHJJKJKHKþJIKIJJJJJKJHþIKJGJJGJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJKKFJEJIþFþFþJIJKJGJIKKJJHKJGEþFþGJIKJJEIKFJKKIJJJIGJGþFþFJEJJGJJGKJGKHJKHKJKIIIIGþJHGJGJFIFKIJJKHKH§IJJJKJKHIJþJHJJIGIKKKGHH§§HJHF¨¨JKKJIIJKIKIþHKKIHIHH§ªªª§JHKH§©¨§GIHKJIIþJHH¨¨©««ª©¨§HJ¨©¨ª©«ª©HHþ
JJKJJ§©©¨©ª««««¨§KHIþIHJJH§§¨¨§§§§KJKþJIJJH§§HJJJHþIKJKKKKJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEJKJJIEIEJJIGJGþFþFJEJJGJJKJJGKJGKGHKKJIIIGþJHGJGJFIJKIJJKEJKEIJJJKJJHIJþJHJJIGIKGJKHKJK§¨¨FGKJKF§IHJKIKIþHKKIKIIHI§§H§¨©ª§HKHI¨¨©ªKIIþJHJJKK¨©ª¨©ªªKH§¨GHHKKHHþ
JJJKHHGª««JH¨©©§KKJIþIHKJKKHH©©ª«JHKKþJIKIJKIHHKJHþIKJGJJGJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIJJEJJIGJGþFþFJEJJGJJHKJGJKJKGJKKIIIIGþJHGJHJFIJK§¨JIHJIEJJKJHKKHIJþJHJJKKJJKH§¨¨©©KJHHHKJHKJHKJKIKIþHK§§¨I¨ªªª¨§§JJKG©¨¨¨§§¨KKIIþJHJKHJ¨¨¨§HLKJJHJGJIHJHHþ
JJKHHJ§§JIJHKKHJHKJIþIHKJIIJJJHJKJJKKþJIKIJK§¨JKJHþIKKHJJGJþIKKKÿþFþGþFþIFþEþEþGJJHKþGþFþFþGJJKJKHIJþGþGH©IJJ§JJJJJJþFþFþJJ§¨JH§¨JHJJHJJJEþFþHJ§¨¨¨J§¨¨JJJLJJJJKJGþFþJJGJJ§¨JJ¨¨KJFJ¨J¨¨§IIJIGþJHJ©§§¨©HKIJJKH¨§©¨¨§J¨JIHKJþJHJJJGªª§KJH¨GJJJ©©K¨JHJJIKJJIKIþHKJIJIH§HJ¨§KJ§KJHJKI¨IJJJIIþJHJJKJ¨¨¨¨§L§¨¨IJ§¨©HJHHþ
JJH¨©©H§¨I©¨§J¨¨§JJIþ¨¨©JI¨JHK©¨§JJKKþJIJI¨§¨JJKJHþIKJ¨§¨GJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJGJKGKGHKKIIIIGþJHGJGJFIFKIJJIEJIEIKJJKJKHIJþJHJJIGIKGKGHKGJJKHFGKJHFJIIJKJKIþHKKIKIIFIJLHKJKJGIJKIGIJJJJHþJHJJKJKIFIHJHJIKJGJIHJJJþ
JJHJJJGJJI§§JJHJHKJJþIHKJIIJHKKKKJKJJþJIKIJKIJJHJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþJKIKIJEIKFJIEIEJJIGJGþFþFJEJJJJJGKJGJKGKGHKKIIIIGþJJJJGJF§FHHHJIEJIEIJJJKJKHIJþJJ§JKJJKGKGHKG¨¨HHJGKJHFJIIJKIKIþHJ§§JJIFIJJJJJIKJIJKIGIJKJIIþK©JJKJKIFIHKªJKKKKJIHJHHþ
ªJHJJJGKJHª§KKJJJKJIþIHKK¨IH§ª¨JHHKKKþHH¨¨¨©ªJHHJHþ©ª©GHHKJþHHKKÿþFþGþFþIFþEþEþGJJG§þGþFþFþGJJJE§HJKþGþGKIJJJH©JJKKIþFþFþJIJHJGJJJ¨JJHKJGEþFþKK§K¨JEIKJH¨§IH§¨IªKGþFþKHEH§§©K¨§JHJªGJGHK¨«H¨IGþJHGJGJ§§ªH©¨JH¨¬§¨¨J§©¬§©¨ªªþJHJJIGIJKHH¨ª©J§©¬§©¨¨¨«¬©ª§HHKIþHKKIKIIJKKHH§¨©ª¨ª«©©GIHKHKKþJHJJKJKJJHHLKJIKJGJIHKKKþ
JJHJJJGJKKKKHHKKKKJIþIHKJIIJHJJJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJGJKGKGHKKIIIIGþJHGJGJFIFKJJJJJJIEIJJJKJKHIJþJHJJIGIKJJJJJKKKKJJGKJHFJIIJKIKIþHKKIJJJJKKKKKKKKKJJKIGIJKJIIþJJJKKKKKKKKKKKKKKKJIHJHHþ
KKKKKKKKJJJJJJJKKJJIþKKKKJJJJJJJKJJJKþJJJJJKIJJKJHþJKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJJJKþFþFþJIJKJGJIJGJJKKKKEþFþGJIKIJEIKFJJJKKKHKKJGþFþFJEJJGJJGKJGJJKKKKKJJJJJGþJHGJGJFIFKIJJJJKKKKJJJJKKHIJþJHJJIGIKGKGHKGJKJKKJJJJFJIIJKIKIþHKKIKIIFIJLHKJIJKJJJIGIJKJIIþJHJJKJKIFIHLKJJKJGJIHJHHþ
JJHJJJGJJIJHKJKJHKJIþIHKJIIJHKKJKJKJJþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJJHKþGþFþFþGJ¨¨JKHIJþGþGHJI¨©§JJJJJJþFþFþJJJJJH©©JHJ§©JJJEþFþHJIJIJJJKGJ©§¨ªJJJKJGþFþJJ¨JJJJJJ©JKJF©©JHKJII©IGþJHJJ©¨§JHKI©©KHJJJJJJJG§¨HKJþJHJJJGH¨¨¨JHJª©¨JHJKIJHJ¨©©JJIKIþHKJIJI¨¨HJ©Hª¨¨KJHJK§©©©JJIIþJHJJKJI§¨IHLIJIIJGJKHJHHþ
JJHJ§¨©J©¨JHJJHJHJJIþI¨¨©II¨©§¨¨KJJKKþJIJIJK¨§JKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJJKIJEIKFJIEIEJJIGJGþFþFJEJJJJJJJJGJKGKGHKKIIIIGþJHGJGJFIFKIJJIEJIEIJJJKJKHIJþJHJJIGIKGKGHKGJKGHFGKJHFJIIJKIKIþHKKIKIIFIJLHKJIKGIJKIGIJKJIIþJHJJKJKIFIHLKJIKJGJIHJHHþ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJJJJGJJGKJGJKGKGHKKIIIIGþJHGJHJFIFKIJJIEJIEIJJJKJKHIJþJHJJIG§©ªKGHKGJ©¨§¨§ªJHFJIIJKIKIþHKKIKI«KIJ§§¨ª©¨©¨©H¨¨§§K§IIþJHJJ«§§I¨¨©«ª©ª©¨G©©¨¨§¨þ
HH«¨¨§ª¨©IJHHHH¨ªªª©þªª©¨IHKKJJJJJKKKþKKKJJJIJJKJJþJKJGJJJJþJJJJÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJJþFþFþJIJKJGJIJGJGHKJGEþFþGJIKI©JIKFJIEKEH§§GHGþFþFJEJJGJJ©ªJGJ§GH§H©¨IKJJGþJHGJGJK§FJIJ©¨§¨§E©¨JHKJJHIJþJHJJIGIKGKG¬«ª©¨¨©ª©KHKKJIIJKJJJþHKKIKIIFIJLHKK©ªGHKKJJIJKJJJþJHJJKJKIFIHLK§IHKJJIHJHJþ
JJHJJJGJJIJH§KHJHKJKþIHKJIIJHKKJ§JKJJþJIKIJKIJJK§HþIKJJKHG¨þIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGH§¨JIHIIþGþG¨©§¨ªHJFJEJIþFþFþKKKH¨©ª§J§JGHKJGEþFþJJIKIJJKK¨§¨HIEJJIGJGþFþJJEJJGJJGKJK¨©G§§HKKIIIIGþJKKH¨§§§FKIJJIEKHE¨§HJKJKHIJþJKJ©¨©§KJK§KJGJJ§§FGKJHHKJIJKIKIþ©©KJJKIFIJLHJHIKGIJKIGIJKJIIþ©HJJJJKIFIKHKJIKJG§JHJHHþ
JJHJJJHHJ¨ª«¨¨HHHKJIþ§HJJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJH©©þGþFþFþGJK¨¨ª«ª«þGþGKHª¨©KKKKKJ©þFþFþH¨©©ªKKIJJJGHK§¨EþFþH§¨ªJJKIKFJIEIEJJKHJGþFþ©¨HKJGJJGKJGJKGKJJHKIIIIGþJHª©§JHKJKIJJIEJJJKJJJKJKHIJþJHJJIGIKGKGHKKKJKKHGKJHFJIIJKIKIþHKKIKIIFIJLHKHIKGIJKIGIJKJIIþJHJJKJKIFI©LKJIKJGJIHJHHþ
JJHJJJGJJ©JHKKHJHKJIþIHKJIIJ§KKJKJJKKþJIKIJ©IJJKJHþIKJG©JGJþIHJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIHKJGKFJEJIþFþFþJIJKJ¨JIJGJGHKJGEþFþGJIKIJEI©FJIEIEJJIGJGþFþFJEJJGJJGK¨«JKGKGHKKIIIIGþJHGJGJFIFKIJ©«ªJIEIJJJKJKHIJþJHJJIGIKGKGHK§ª«ªJFGKJHFJIIJKIKIþHKKIKIIFIJLH«¬«KGIJKIGIJKJIIþJHJJKJKIH§¬¬¬HIKJGJIHJHHþ
JJHJJJG©­­­HKKHJHKJIþIHKJ§ª­®®§JKJJKKþ§¨§¯®¯®©KJJHþ©¯¯¯®ªHKþ¯¯¯«ÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJKJKGKGHJJ©©¨©GþJHGJGJFIFKIJJI§¨©EIH¨©«ª©ª¬¯þJHJJIGIKGKGHKGJKGHF©§¨ª¬­«««¬©¯¯þHKKIKIIFIJLHKJIKGI©ª«­­¬¬¬­¬þJHJJKJKIFIHLKJIKJGJIH­­­þ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJGJKGKGHKKIIIIGþJHKJGKHKFKIJJIEJIEIJJJKJKHIJþ¯¬¨JH¨§HGKGHKGJKGHFGKJHFJIIJKIKIþª¨§¨¨I¨HKJLHKJIKGIJKIGIJKJIIþHHJJK§HJFIHLKJIKJGJIHJHHþ
JJJJJKGJJIJHKKHJHKJIþIHKHHIJHKKJKJJKKþJKHIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþG®¯®­þGþFþFþG®®¯¯¯­«¨þGþGHII®¯¯¯­­HJIþFþFþJIJKJGJ¯¯­HGHKJJEþFþGJIKI©ª«¬¯¯§EIHKJIGJGþFþFJEJ¨¨©ª«¬«­JKGKGH§KHHIKGþJHGJH§§IFKIJJ­EJIEIJJJKJKHIJþJHJJIGIKGKGHKGJJ«HFGKJHFJIIJKIKIþHKKIKIIFIJLHKJH«GIJKIGIJKJIIþJHJJKJKIFIHLKH¨KJGJIHJHHþ
JJHJJJGJJIJHK©HJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGJJGJKGKGHKKIIIIGþJHGJGJFIFKIJ§¨EJIEIJJJKJKHIJþJHJJIGIKGKGHKGJH§KFGKJHFJIIJKIKIþHKKIKIIFIJLHKJ¨©§JJKIGIJKJIIþJHJJKJKIFIHLKH§KHGJIHJHHþ
JJHJJJGJJIJH§HHJHKJIþIHKJIIJHK¨ªKJJKKþJIKIJK§©«¨§HþIKJJ©ª¬ªþK©ª«ÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJGJKGKGHKKIIIIGþJHGJGJFIFKIJJIEJIEIJJJKJKHIJþJHJJIGIKGKGHKGJKGHFGKJHFJIIJKJ©«þHKKIKIIFIJLHKJIKGIJKIGIJKJJ©þJHJJKJKIFIHLKJIKJGJIHJHHþ
JJHJJJGJJJKHK§¨JHKJIþIHKJIIJHKJJK«©KKþJIKIJKIJJKJ«þIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGEþFþGJIKIJEIKFJIEIEJJIGJGþFþ¨HJJJGJJGKJGJKGKGHKKIIIIGþ­«©JHHJIFKIJJIEJIEIJJJKJKHIJþ¬¬®¬ª§IKKKGHKGJ«©§FKJJHFJIIJKIKIþ¯®«¨§§HH§¨ª«¬­¨KKJJKIGIJKJIIþ¬ª§¨K¨©©«KHLKJIKJGJIHJHHþ
¨JHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþG«¬­­þGþFþFþGJ¬¬­­®¯¯þGþGHJ«­¬®®¯¯¯®ªþFþFþJIJ«¬®­¯¯¯¯¯JKJGEþFþ¬«ª¬¬¬®¯JFJIEIEJJIGJGþFþFJJJJ­­®JKJGJKGKGHKKIIIIGþJHGJGJF®®KIJJIEJIEIJJJKJKHIJþJHJJIGIK©­JHKGJKGHFGKJHFJIIJKIKIþHKKIKI¨FIJLHKJIKGIJKIGIJKJIIþJHJJ©ªKIFIHLKJIKJGJIHJHHþ
JJH©©JGJJIJHKKHJHKJIþIH¨JHJJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿ&þLKKKLþJJJGÿþFþ EþFG…þE‰FKJIþEþFJKJIGHþEˆJKJIþHIHÿþFþNŽEþJMOGFþHHGLMFŽEþHLMJFþEþNJþEÿþFJGHþKJGJJHEJþFFIJHGJGHEŽþIKIEIJJFGîJGŽŒþJJIIJFHHJJFEHEŒŒ‹þ
IGJJEIHIGHHJFEEŒ‹DŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‰Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIINFGHŽFFFFEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHFŽEGFG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þNFDFGGFŠG‹EFŠŠŠ‹Œ‹ŠŠŠŠþ
ŽFGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþF‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ‡EHGJGHJIFFþŠŠˆ†GJJGFJJIEIKIþ‹Œ‹‹ŠEH†EFJJHHFJIIJJþ
‹‹‹‹Œ‰D‹ŠEEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠŠ‹‹‹EEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF†HGFIIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠGFGE…FHHEFFGþŒŠŠŠ‹‰‹Š‰ŠFEŠGŠFG‹GFˆDFJþ
Œ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰F‡þ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHHIHþHIHIEEGJþGEGFGHEFFFGEþˆˆFEGEEGEG‹GFEþ‹Œ‹JŠFFŠ‹GFD‹GŒFE‹Œ‹þ
‹‹‹‹ŒE‰G‰GŠŒGŠGŠŠGGŒ‹ŠŠŠþ‹‹‹‹ŠŠŠG‹‹‹GŠG‹ŠF‰ŠHEŒŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰Š‹G‹‹Š‰‹‹ŠŠŠ‹ŠŠ‹Šˆˆˆ‹Š‹þŠ‰‰Š‹ŠŠ‹ŠŠŠGH‹Š‹ŒŒŒŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰ŠŠŠŠŠŠ‹Œ‹ŠŠŠŠþ
Œ‰‰‰‰‹‹‹‹ŠŒ‹Š‹ŒŒŒŒŒŒþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFFIJHGJGHE‹þIKIEIJJFGLJGŒ‹‹þJJIIJFHHJGFŒHEŠ‹ŒŒ‹þ
IGJJEIHIGHHJMEŽŒDŠŠŠŠŠŠþIIHFIFHIHIEEGJF‹EŠ‹‹Š‹ŒŒŒŒ‹‹þHIHIIGIIGFGHGFFFŽEŒ‹ŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHKLEGMGMGF‹Š‰‹ŒŠŠ‹Š‰‰Š‰þKFDOFŠ‹GFG‰‹E‹ŠŠŠ‹Œ‹ŠŠŠŠþ
DFŒGŒG‰G‰‹FŠ‹ŒŒŒŒŒŒþFŒ‹‹‹ŠŠ‰‰ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþŠŠ‰ˆGJGGFJJIEIKIþ‹Š‹ŠŠEH„EFJJHHFJIIJJþ
‹‹‹‹Œ‹DŠ‰EEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠ‹‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠ‹‹‹‹‹‹ŒŠEFFFFJHGFGIIGIIHIHþ‹Š‹ŒŒŒ‹‹‹ŠŠŠ‰FGKGFGELFHHEFFGþŠŠŠŠ‹Š‹Š‹‹FE‰GˆFG‡GF‡DFKþ
‹ŠŠŠŠ‹‹‹F‹‹G‰GŠŠG‹F‹þ‹‹‹‹Œ‹Š‰ŠŠŠŠ‹‹ŒFþ‹‹‹‹Š‹‹‹Œ‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹Š‰þ‹Œ‹ŠŠŠŠ‹ŒŒŒŒ‹‹‹ŒŒŒŒ‹þ
‹‹‹‹Œ‰‰Œ‰‰Š‹‹‹ŠŠŠŠŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠŠ‹‹‹‹ŠŠ‹Š‰‰Š‹Š‹ŒŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰Š‹‹‹‹Š‰‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠŒ‹Š‹ŒŒŒŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠŠŠŠŠ‹Œ‹ŠŠŠŠþ
Œ‰‰‰‰‹‹‹‹ŠŒ‹Š‹ŒŒŒŒŒŒþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþFFEHGJGHJIFFþIKIEGJJGFJJIEIKIþJJIIJEHHJFFJHHFJIIJJþ
IGJJEIDIGHEJJHHGIHIEJJGIþIIHFIFHIHIEEGFJGEEIHIHFIFHIIþHIHIIGIIKFGHGFEFFFFïHGFOIIGIIHIHþGFFEHHNŒEGGFGGFGEîFHHEFFGþMFDFŽŽGFGFEEGŠFG‹GF‰DFMþ
DFGŒŒG‹FŠŒGŠGŒŒGŒFŒþF‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFþFFIJHGJGHEŒþDIKIEIJJFGŽJG‰ŠŠ‰þEEþJJIIJFHHJJFFŽHEŒŒŒŒ‹þFFIGJJEIHIGHHJEEE‰ˆDŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‹Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIIHFGHKFFFFEŒŒŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHHIEGEGGGFŒEŒŒŒŠ‹‹Š‰‰Š‰þIFDJFIHGFHHJEEŠŒ‹DŒ‹ŠŠŠŠþ
JFIGJFGHGFFHEŒŒŒŒŒþIKIEIJJFGŒJG‹ŠŠ‹þFFIJHGJGHE‰ŠþKJGJJHEJþFJGHÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþFþ‹‹Š‰GJ†GFJJIEIKIDþ‹Œ‹Š‰EH‹FFJJHHFJIIJJþEEþ‹‹‹‹Œ‰DŠŒEEEJHHGIHIEJJGIFFþ‹‹‹‹ŠŠŠŠ‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF…HGFHIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹‹ŠEEFGGGEGEIHHHEFFGþŒŠŠŠ‹HD‹‰EEEJHHFGHIFJDFIþ
Œ‰‰ŒŠEH‡FFJGHGFJGIFJþ‹Œ‹‹GJ†GFJJIEIKIþ‰ˆEHGJGHJIFFþJEHJJGJKþHGJFÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþFþ‹‹‹ŠŠŠŠ‰‰Š‹‹þFþD‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹ŠFDþ
EEþEŒ‹GŠŠG‹GŒŒF‹G‹ŒGŒDEþEEþFFŽFEŒF‰‰GF‰FEEGŠFGŠGF‹EFNFFþEGFFFHHŒEGGGGFŠGFGEŠFHHFFFGþHIHIIGIIŽFGH‹FFFFEFHGF‹IIGIIHIHþIIHFIFHIHIEEGJFGEEIHIHFIFHIIþIGJJEIHIGHHJJEHGIDIEJJGIþ
JJIIJFHHJFFJHHEJIIJJþIKIEIJJFGJJGEIKIþFFIJHGJGHEFFþKJGJJHEJþFJGHÿþŠŠŠŠþ‹Š‰‰Š‹ŠŠþ‹‹GIIGu‹‹‹‹‹þŠ‹‹GHHHHGŠŠ‹ŠŒ‹Šþ‹Š‹ŠGIHIHGGG‹‹‹‹ŠŠŠ‹þ
‹‹‹‹Œ‹GGIHHIGGGŠŠ‹Š‹Š‹‹‹þ‹‹‹‹ŠŠŠ‹GGGGHIGGHt‹‹‹Š‹ŠŠŠŠ‹þ‹‹‹ŠŠŠ‹‰ˆˆGJGGIIGGHIGwŠ‹Œ‹‹‹‰‹Š‹þ‹Š‹ŒŒŠŠŠŠˆGIHIHGGGKH‹Š‹‹‹‹‹ŠþŠŠŠŠ‹Š‹Š‡JJJKGHJLIŠ‹ŠŠŠŠþ
‹ŠŠŠŠ‹‹‰‡KMKJMM‹ŠŒ‹‹þ‹‹H‹Œ‹Š‰ŒŒŒŒ‹Š‹‹þ‹‹‹‹Š‹‹‹‹‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ˆˆŠIJH‹Š‰þ‹Œ‹ŠGGGIŒŒŒHGGILŒŒŒ‹þ
‹‹‹‹ŒGJJJIJ‹ˆKILˆˆŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠHJGHIKŠ‹Š‰‰Š‹Š‹ŠGŠŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGHJKN‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆ‹Š‹þŠ‰‰Šˆˆ‰HHM‰ˆHŒˆˆ‹HHHŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠHIGGHI‹ŠŠŠŠþ
Œ‰‰‰‰‹JGJŠGGIJKLŒŒŒŒþ‹‹‹‹JJJGˆLJJˆˆ‰Šþ‹‹‰ˆ‰‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠGGG‰Š‹‹þ‹‹Š‰GIIHHIIIG‹Š‰þ‹Œ‹ŠGIHHHHHHHIIGŒŒŒ‹þ
‹‹‹‹GIGHHHHHHIGGHHHG‹ŠŠŠþ‹‹‹‹ŠŠGGIHHHHHGGGGIGHIGŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGIIIIIIGGGHGGJIHˆˆˆ‹Š‹þŠ‰‰Š‹ˆJGGGGGGGGGGGGKJLKJ‡‰Š‰þŒŠŠŠˆHHIGGJGIIJIJMKJOˆŠŠþ
Œ‰‰JJKGIKGIJIJKOMLŒŒþ‹Ù‹‹HKOHIJJKLŠŠ‹þ‹‹‹‡‡ˆˆˆˆ‡‡Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þFþ‹‹‹‹Š‰‰ŠŠ‰‰ŠþDŒ‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þEEþEŽGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþFFNFEFGFŠ‹‹EŠŠŠŠ‹Œ‹ŠŠŠŠþGFFFHHŽŽEGGG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þHIHIIGIINFGHŽFFFŒEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þIIHFIFHIHIEEGJF‹E‰Š‹Š‹ŒŒŒŒ‹‹þIGJJEIHIGHHJŽEŒ‹DŠŒ‹ŠŠŠþ
JJIIJFHHJîFHEŒŒ‹þIKIEIJJFGîJGŽŒþFFIJHGJGHEŽþKJGJJHEJþFJGHÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þ‹‹‹‹Š‰‰ŠŠ‰‰ŠþFþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹DþŒ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰ˆEþEEþŒŠŠŠ‹‰‹Š‰Š‹EŠŠGFG‹‹FˆEFJFFþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠG‰GE…„HHFFFGþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEŠFFFGHGFIIIGIIHIHþ‹‹‹‹ŠŠŠŠ‹‹‹EŠFJGEEIHIHFIFHIIþ‹‹‹‹Œ‰D‹Š‰E†JHHGIHIEJJGIþ
‹Œ‹‹ŠEH†…FIJHHFJIIJJþŠŠˆ†GJJGFJJIEIKIþˆ‡EHGJGHJIFFþJEHJJGJKþHGJFÿþFJGHþKJGJJHEJþFFIJHGJGHEŽþIKIEIJJFGîJGŽŒþJJIIJFHHJJFEHEŒŒ‹þ
IGJJEIHIGHHJFEEŒ‹DŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‰Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIINFGHŽFFFFEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHFŽEGFG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þNFDFGGFŠG‹EFŠŠŠ‹Œ‹ŠŠŠŠþ
ŽFGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþF‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ‡EHGJGHJIFFþŠŠˆ†GJJGFJJIEIKIþ‹Œ‹‹ŠEH†EFJJHHFJIIJJþ
‹‹‹‹Œ‰D‹ŠEEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠŠ‹‹‹EEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF†HGFIIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠGFGE…FHHEFFGþŒŠŠŠ‹‰‹Š‰ŠFEŠGŠFG‹GFˆDFJþ
Œ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰F‡þ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHHIHþHIHIEEGJþGEGFGHEFFFGEþˆˆFEGEEGEG‹GFE‹þ‹ŠŒJŠFFŠ‹GFDGŒFE‹Œ‹þ
‹‹‹‹‹EŠGŠGŠŒGŠG‰‰GGŠŒ‹Š‹þ‹‹‹‹Š‰‰G‹G‹GŠG‹ŠFŠŠŒHE‹ŠŠŠ‹‹þ‹‹‹Š‰‰ŠŠŠ‹‹‹ŠŠGH‹‹‹‹Š‰Š‹Š‰‰ˆ‹Š‹þŠŠŠŠ‹‰‹‹‹Š‰‰ŠŠŠŠ‹ŠŠ‹‹ŠŠŠ‹‰þŒŠ‹ŒŒŒ‹ŠŠŠ‹Œ‹‹‹‹‹‹ŠŒ‹Š‹Œþ
Š‰‰‰‰‹‹‹‹Š‹ŠŠŠŠ‹Š‹ŠŠþ‹‹‹‹‹ŠŠ‰Œ‹‹‹‹‰Š‹þ‹‹‹‹ŠŠŠ‹ŠŠŠŠþŒ‹Š‹ŒŒŒ‹þŠŠ‹‹ÿþFJGHþKJGJJHEJþFFIJHGJGHE‹þIKIEIJJFGLJGŒ‹‹þJJIIJFHHJGFŒHEŠ‹ŒŒ‹þ
IGJJEIHIGHHJMEŽŒDŠŠŠŠŠŠþIIHFIFHIHIEEGJF‹EŠ‹‹Š‹ŒŒŒŒ‹‹þHIHIIGIIGFGHGFFFŽEŒ‹ŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHKLEGMGMGF‹Š‰‹ŒŠŠ‹Š‰‰Š‰þKFDOFŠ‹GFG‰‹E‹ŠŠŠ‹Œ‹ŠŠŠŠþ
DFŒGŒG‰G‰‹FŠ‹ŒŒŒŒŒŒþFŒ‹‹‹ŠŠ‰‰ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþŠŠ‰ˆGJGGFJJIEIKIþ‹Š‹ŠŠEH„EFJJHHFJIIJJþ
‹‹‹‹Œ‹DŠ‰EEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠ‹‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠ‹‹‹‹‹‹ŒŠEFFFFJHGFGIIGIIHIHþ‹Š‹ŒŒŒ‹‹‹ŠŠŠ‰FGKGFGELFHHEFFGþŠŠŠŠ‹Š‹Š‹‹FE‰GˆFG‡GF‡DFKþ
‹ŠŠŠŠ‹‹‹F‹‹G‰GŠŠG‹F‹þ‹‹‹‹Œ‹Š‰ŠŠŠŠ‹‹ŒFþ‹‹‹‹Š‹‹‹Œ‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþ‹‹‹‹þ‹ŠŠŠŠ‹ŠŠþ‹‹Œ‹‹‹ŠŠŠ‹‹‹þ‹‹ŠŠŠŠŒ‹Š‹ŒŒŒ‹ŠŠþ‹ŠŒ‹Š‹ŒŒ‹ŠŠŠ‹‹‹ŒŒŒŒ‹þ
‹‹‹‹‹ŠŠŠŠŠŠ‹‹‹Š‰‰Š‰ŠŒ‹Š‹þ‹‹‹‹Š‰‰Š‹‹‹‹Š‰‹ŠŠŠŠ‹Š‹‹ŠŠŠ‹‹þ‹‹‹Š‰‰ŠŠŠ‹‹‹‹ŠŠŠ‹‹‹‹‹Š‰Š‹Š‰‰ˆ‹Š‹þŠŠŠŠ‹‰‹‹‹Š‰‰Š‹ŠŠŠŠ‹ŠŠ‹‹ŠŠŠ‹‰þŒŠ‹ŒŒŒ‹ŠŠŠ‹Œ‹‹‹‹‹‹ŠŒ‹Š‹Œþ
Š‰‰‰‰‹‹‹‹Š‹ŠŠŠŠ‹Š‹ŠŠþ‹‹‹‹‹ŠŠ‰Œ‹‹‹‹‰Š‹þ‹‹‹‹ŠŠŠ‹ŠŠŠŠþŒ‹Š‹ŒŒŒ‹þŠŠ‹‹ÿþHGJFþJEHJJGJKþFFEHGJGHJIFFþIKIEGJJGFJJIEIKIþJJIIJEHHJFFJHHFJIIJJþ
IGJJEIDIGHEJJHHGIHIEJJGIþIIHFIFHIHIEEGFJGEEIHIHFIFHIIþHIHIIGIIKFGHGFEFFFFïHGFOIIGIIHIHþGFFEHHNŒEGGFGGFGEîFHHEFFGþMFDFŽŽGFGFEEGŠFG‹GF‰DFMþ
DFGŒŒG‹FŠŒGŠGŒŒGŒFŒþF‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFþFFIJHGJGHEŒþDIKIEIJJFGŽJG‰ŠŠ‰þEEþJJIIJFHHJJFFŽHEŒŒŒŒ‹þFFIGJJEIHIGHHJEEE‰ˆDŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‹Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIIHFGHKFFFFEŒŒŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHHIEGEGGGFŒEŒŒŒŠ‹‹Š‰‰Š‰þIFDJFIHGFHHJEEŠŒ‹DŒ‹ŠŠŠŠþ
JFIGJFGHGFFHEŒŒŒŒŒþIKIEIJJFGŒJG‹ŠŠ‹þFFIJHGJGHE‰ŠþKJGJJHEJþFJGHÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþFþ‹‹Š‰GJ†GFJJIEIKIDþ‹Œ‹Š‰EH‹FFJJHHFJIIJJþEEþ‹‹‹‹Œ‰DŠŒEEEJHHGIHIEJJGIFFþ‹‹‹‹ŠŠŠŠ‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF…HGFHIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹‹ŠEEFGGGEGEIHHHEFFGþŒŠŠŠ‹HD‹‰EEEJHHFGHIFJDFIþ
Œ‰‰ŒŠEH‡FFJGHGFJGIFJþ‹Œ‹‹GJ†GFJJIEIKIþ‰ˆEHGJGHJIFFþJEHJJGJKþHGJFÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþFþ‹‹‹ŠŠŠŠ‰‰Š‹‹þFþFþD‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹ŠFDþ
EEþEŒ‹GŠŠG‹GŒŒF‹G‹ŒGŒDEþEEþFFŽFEŒF‰‰GF‰FEEGŠFGŠGF‹EFNFFþEGFFFHHŒEGGGGFŠGFGEŠFHHFFFGþHIHIIGIIŽFGH‹FFFFEFHGF‹IIGIIHIHþIIHFIFHIHIEEGJFGEEIHIHFIFHIIþIGJJEIHIGHHJJEHGIDIEJJGIþ
JJIIJFHHJFFJHHEJIIJJþIKIEIJJFGJJGEIKIþFFIJHGJGHEFFþKJGJJHEJþFJGHÿþŠŠŠŠþ‹Š‰‰Š‹ŠŠþ‹‹GIIGu‹‹‹‹‹þŠ‹‹GHHHHGŠŠ‹ŠŒ‹Šþ‹Š‹ŠGIHIHGGG‹‹‹‹ŠŠŠ‹þ
‹‹‹‹Œ‹GGIHHIGGGŠŠ‹Š‹Š‹‹‹þ‹‹‹‹ŠŠŠ‹GGGGHIGGHt‹‹‹Š‹ŠŠŠŠ‹þ‹‹‹ŠŠŠ‹‰ˆˆGJGGIIGGHIGwŠ‹Œ‹‹‹‰‹Š‹þ‹Š‹ŒŒŠŠŠŠˆGIHIHGGGKH‹Š‹‹‹‹‹ŠþŠŠŠŠ‹Š‹Š‡JJJKGHJLIŠ‹ŠŠŠŠþ
‹ŠŠŠŠ‹‹‰‡KMKJMM‹ŠŒ‹‹þ‹‹H‹Œ‹Š‰ŒŒŒŒ‹Š‹‹þ‹‹‹‹Š‹‹‹‹‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ˆˆŠIJH‹Š‰þ‹Œ‹ŠGGGIŒŒŒHGGILŒŒŒ‹þ
‹‹‹‹ŒGJJJIJ‹ˆKILˆˆŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠHJGHIKŠ‹Š‰‰Š‹Š‹ŠGŠŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGHJKN‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆ‹Š‹þŠ‰‰Šˆˆ‰HHM‰ˆHŒˆˆ‹HHHŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠHIGGHI‹ŠŠŠŠþ
Œ‰‰‰‰‹JGJŠGGIJKLŒŒŒŒþ‹‹‹‹JJJGˆLJJˆˆ‰Šþ‹‹‰ˆ‰‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹ŒþŒŒ‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠGGG‰Š‹‹þ‹‹Š‰GIIHHIIIG‹Š‰þ‹Œ‹ŠGIHHHHHHHIIGŒŒŒ‹þ
‹‹‹‹GIGHHHHHHIGGHHHG‹ŠŠŠþ‹‹‹‹ŠŠGGIHHHHHGGGGIGHIGŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGIIIIIIGGGHGGJIHˆˆˆ‹Š‹þŠ‰‰Š‹ˆJGGGGGGGGGGGGKJLKJ‡‰Š‰þŒŠŠŠˆHHIGGJGIIJIJMKJOˆŠŠþ
Œ‰‰JJKGIKGIJIJKOMLŒŒþ‹Ù‹‹HKOHIJJKLŠŠ‹þ‹‹‹‡‡ˆˆˆˆ‡‡Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þFþ‹‹‹‹Š‰‰ŠŠ‰‰ŠþDŒ‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þEEþEŽGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþFFNFEFGFŠ‹‹EŠŠŠŠ‹Œ‹ŠŠŠŠþGFFFHHŽŽEGGG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þHIHIIGIINFGHŽFFFŒEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þIIHFIFHIHIEEGJF‹E‰Š‹Š‹ŒŒŒŒ‹‹þIGJJEIHIGHHJŽEŒ‹DŠŒ‹ŠŠŠþ
JJIIJFHHJîFHEŒŒ‹þIKIEIJJFGîJGŽŒþFFIJHGJGHEŽþKJGJJHEJþFJGHÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þ‹‹‹‹Š‰‰ŠŠ‰‰ŠþFþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹DþŒ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰ˆEþEEþŒŠŠŠ‹‰‹Š‰Š‹EŠŠGFG‹‹FˆEFJFFþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠG‰GE…„HHFFFGþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEŠFFFGHGFIIIGIIHIHþ‹‹‹‹ŠŠŠŠ‹‹‹EŠFJGEEIHIHFIFHIIþ‹‹‹‹Œ‰D‹Š‰E†JHHGIHIEJJGIþ
‹Œ‹‹ŠEH†…FIJHHFJIIJJþŠŠˆ†GJJGFJJIEIKIþˆ‡EHGJGHJIFFþJEHJJGJKþHGJFÿþFJGHþKJGJJHEJþFFIJHGJGHEŽþIKIEIJJFGîJGŽŒþJJIIJFHHJJFEHEŒŒ‹þ
IGJJEIHIGHHJFEEŒ‹DŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‰Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIINFGHŽFFFFEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHFŽEGFG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þNFDFGGFŠG‹EFŠŠŠ‹Œ‹ŠŠŠŠþ
ŽFGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþF‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ‡EHGJGHJIFFþŠŠˆ†GJJGFJJIEIKIþ‹Œ‹‹ŠEH†EFJJHHFJIIJJþ
‹‹‹‹Œ‰D‹ŠEEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠŠ‹‹‹EEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF†HGFIIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠGFGE…FHHEFFGþŒŠŠŠ‹‰‹Š‰ŠFEŠGŠFG‹GFˆDFJþ
Œ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰F‡þ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHHIHþHIHIEEGJþGEGFGHEFFFGEþˆˆFEGEEGEG‹GFEþ‹Œ‹JŠFFŠ‹GFD‹GŒFE‹Œ‹þ
‹‹‹‹ŒE‰G‰GŠŒGŠGŠŠGGŒ‹ŠŠŠþ‹‹‹‹ŠŠŠG‹‹‹GŠG‹ŠF‰ŠHEŒŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰Š‹G‹‹Š‰‹‹ŠŠŠ‹ŠŠ‹Šˆˆˆ‹Š‹þŠ‰‰Š‹ŠŠ‹ŠŠŠGH‹Š‹ŒŒŒŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰ŠŠŠŠŠŠ‹Œ‹ŠŠŠŠþ
Œ‰‰‰‰‹‹‹‹ŠŒ‹Š‹ŒŒŒŒŒŒþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFFIJHGJGHE‹þIKIEIJJFGLJGŒ‹‹þJJIIJFHHJGFŒHEŠ‹ŒŒ‹þ
IGJJEIHIGHHJMEŽŒDŠŠŠŠŠŠþIIHFIFHIHIEEGJF‹EŠ‹‹Š‹ŒŒŒŒ‹‹þHIHIIGIIGFGHGFFFŽEŒ‹ŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHKLEGMGMGF‹Š‰‹ŒŠŠ‹Š‰‰Š‰þKFDOFŠ‹GFG‰‹E‹ŠŠŠ‹Œ‹ŠŠŠŠþ
DFŒGŒG‰G‰‹FŠ‹ŒŒŒŒŒŒþFŒ‹‹‹ŠŠ‰‰ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþŠŠ‰ˆGJGGFJJIEIKIþ‹Š‹ŠŠEH„EFJJHHFJIIJJþ
‹‹‹‹Œ‹DŠ‰EEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠ‹‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠ‹‹‹‹‹‹ŒŠEFFFFJHGFGIIGIIHIHþ‹Š‹ŒŒŒ‹‹‹ŠŠŠ‰FGKGFGELFHHEFFGþŠŠŠŠ‹Š‹Š‹‹FE‰GˆFG‡GF‡DFKþ
‹ŠŠŠŠ‹‹‹F‹‹G‰GŠŠG‹F‹þ‹‹‹‹Œ‹Š‰ŠŠŠŠ‹‹ŒFþ‹‹‹‹Š‹‹‹Œ‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹Š‰þ‹Œ‹ŠŠŠŠ‹ŒŒŒŒ‹‹‹ŒŒŒŒ‹þ
‹‹‹‹Œ‰‰Œ‰‰Š‹‹‹ŠŠŠŠŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠŠ‹‹‹‹ŠŠ‹Š‰‰Š‹Š‹ŒŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰Š‹‹‹‹Š‰‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠŒ‹Š‹ŒŒŒŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠŠŠŠŠ‹Œ‹ŠŠŠŠþ
Œ‰‰‰‰‹‹‹‹ŠŒ‹Š‹ŒŒŒŒŒŒþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþFFEHGJGHJIFFþIKIEGJJGFJJIEIKIþJJIIJEHHJFFJHHFJIIJJþ
IGJJEIDIGHEJJHHGIHIEJJGIþIIHFIFHIHIEEGFJGEEIHIHFIFHIIþHIHIIGIIKFGHGFEFFFFïHGFOIIGIIHIHþGFFEHHNŒEGGFGGFGEîFHHEFFGþMFDFŽŽGFGFEEGŠFG‹GF‰DFMþ
DFGŒŒG‹FŠŒGŠGŒŒGŒFŒþF‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFþFFIJHGJGHEŒþDIKIEIJJFGŽJG‰ŠŠ‰þEEþJJIIJFHHJJFFŽHEŒŒŒŒ‹þFFIGJJEIHIGHHJEEE‰ˆDŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‹Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIIHFGHKFFFFEŒŒŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHHIEGEGGGFŒEŒŒŒŠ‹‹Š‰‰Š‰þIFDJFIHGFHHJEEŠŒ‹DŒ‹ŠŠŠŠþ
JFIGJFGHGFFHEŒŒŒŒŒþIKIEIJJFGŒJG‹ŠŠ‹þFFIJHGJGHE‰ŠþKJGJJHEJþFJGHÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþFþ‹‹Š‰GJ†GFJJIEIKIDþ‹Œ‹Š‰EH‹FFJJHHFJIIJJþEEþ‹‹‹‹Œ‰DŠŒEEEJHHGIHIEJJGIFFþ‹‹‹‹ŠŠŠŠ‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF…HGFHIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹‹ŠEEFGGGEGEIHHHEFFGþŒŠŠŠ‹HD‹‰EEEJHHFGHIFJDFIþ
Œ‰‰ŒŠEH‡FFJGHGFJGIFJþ‹Œ‹‹GJ†GFJJIEIKIþ‰ˆEHGJGHJIFFþJEHJJGJKþHGJFÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþFþ‹‹‹ŠŠŠŠ‰‰Š‹‹þFþFþD‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹ŠFDþ
EEþEŒ‹GŠŠG‹GŒŒF‹G‹ŒGŒDEþEEþFFŽFEŒF‰‰GF‰FEEGŠFGŠGF‹EFNFFþEGFFFHHŒEGGGGFŠGFGEŠFHHFFFGþHIHIIGIIŽFGH‹FFFFEFHGF‹IIGIIHIHþIIHFIFHIHIEEGJFGEEIHIHFIFHIIþIGJJEIHIGHHJJEHGIDIEJJGIþ
JJIIJFHHJFFJHHEJIIJJþIKIEIJJFGJJGEIKIþFFIJHGJGHEFFþKJGJJHEJþFJGHÿþŠŠŠŠþ‹Š‰‰Š‹ŠŠþ‹‹GIIGu‹‹‹‹‹þŠ‹‹GHHHHGŠŠ‹ŠŒ‹Šþ‹Š‹ŠGIHIHGGG‹‹‹‹ŠŠŠ‹þ
‹‹‹‹Œ‹GGIHHIGGGŠŠ‹Š‹Š‹‹‹þ‹‹‹‹ŠŠŠ‹GGGGHIGGHt‹‹‹Š‹ŠŠŠŠ‹þ‹‹‹ŠŠŠ‹‰ˆˆGJGGIIGGHIGwŠ‹Œ‹‹‹‰‹Š‹þ‹Š‹ŒŒŠŠŠŠˆGIHIHGGGKH‹Š‹‹‹‹‹ŠþŠŠŠŠ‹Š‹Š‡JJJKGHJLIŠ‹ŠŠŠŠþ
‹ŠŠŠŠ‹‹‰‡KMKJMM‹ŠŒ‹‹þ‹‹H‹Œ‹Š‰ŒŒŒŒ‹Š‹‹þ‹‹‹‹Š‹‹‹‹‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ˆˆŠIJH‹Š‰þ‹Œ‹ŠGGGIŒŒŒHGGILŒŒŒ‹þ
‹‹‹‹ŒGJJJIJ‹ˆKILˆˆŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠHJGHIKŠ‹Š‰‰Š‹Š‹ŠGŠŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGHJKN‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆ‹Š‹þŠ‰‰Šˆˆ‰HHM‰ˆHŒˆˆ‹HHHŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠHIGGHI‹ŠŠŠŠþ
Œ‰‰‰‰‹JGJŠGGIJKLŒŒŒŒþ‹‹‹‹JJJGˆLJJˆˆ‰Šþ‹‹‰ˆ‰‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠGGG‰Š‹‹þ‹‹Š‰GIIHHIIIG‹Š‰þ‹Œ‹ŠGIHHHHHHHIIGŒŒŒ‹þ
‹‹‹‹GIGHHHHHHIGGHHHG‹ŠŠŠþ‹‹‹‹ŠŠGGIHHHHHGGGGIGHIGŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGIIIIIIGGGHGGJIHˆˆˆ‹Š‹þŠ‰‰Š‹ˆJGGGGGGGGGGGGKJLKJ‡‰Š‰þŒŠŠŠˆHHIGGJGIIJIJMKJOˆŠŠþ
Œ‰‰JJKGIKGIJIJKOMLŒŒþ‹Ù‹‹HKOHIJJKLŠŠ‹þ‹‹‹‡‡ˆˆˆˆ‡‡Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þFþ‹‹‹‹Š‰‰ŠŠ‰‰ŠþFDŒ‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þEEDEŽGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþFFNFEFGFŠ‹‹EŠŠŠŠ‹Œ‹ŠŠŠŠþGFFFHHŽŽEGGG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þHIHIIGIINFGHŽFFFŒEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þIIHFIFHIHIEEGJF‹E‰Š‹Š‹ŒŒŒŒ‹‹þIGJJEIHIGHHJŽEŒ‹DŠŒ‹ŠŠŠþ
JJIIJFHHJîFHEŒŒ‹þIKIEIJJFGîJGŽŒþFFIJHGJGHEŽþKJGJJHEJþFJGHÿþŒŒ‹‹þ‹ŠŠŠŠ‹‰‹þ‹‹‹‹Š‰‰ŠŠ‰‰ŠþFþ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹DþŒ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰ˆEþEEþŒŠŠŠ‹‰‹Š‰Š‹EŠŠGFG‹‹FˆEFJFFþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠG‰GE…„HHFFFGþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEŠFFFGHGFIIIGIIHIHþ‹‹‹‹ŠŠŠŠ‹‹‹EŠFJGEEIHIHFIFHIIþ‹‹‹‹Œ‰D‹Š‰E†JHHGIHIEJJGIþ
‹Œ‹‹ŠEH†…FIJHHFJIIJJþŠŠˆ†GJJGFJJIEIKIþˆ‡EHGJGHJIFFþJEHJJGJKþHGJFÿþFJGHþKJGJJHEJþFFIJHGJGHEŽþIKIEIJJFGîJGŽŒþJJIIJFHHJJFEHEŒŒ‹þ
IGJJEIHIGHHJFEEŒ‹DŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‰Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIINFGHŽFFFFEŠŠ‹ŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHFŽEGFG‹GFŠ‹ŒŒŒŠ‹‹Š‰‰Š‰þNFDFGGFŠG‹EFŠŠŠ‹Œ‹ŠŠŠŠþ
ŽFGŒ‹G‹GŠŒFŠ‹ŒŒŒŒŒŒþFF‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ‡EHGJGHJIFFþŠŠˆ†GJJGFJJIEIKIþ‹Œ‹‹ŠEH†EFJJHHFJIIJJþ
‹‹‹‹Œ‰D‹ŠEEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠŠ‹‹‹EEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF†HGFIIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹ŠŠŠŠFGŠGFGE…FHHEFFGþŒŠŠŠ‹‰‹Š‰ŠFEŠGŠFG‹GFˆDFJþ
Œ‰‰‰‰‹‹‹FŠŒGŠGŒ‹G‰F‡þ‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHHIHþHIHIEEGJþGEGFGHEFFFGEþˆˆFEGEEGEG‹GFE‹þ‹ŠŒJŠFFŠ‹GFDGŒFE‹Œ‹þ
‹‹‹‹‹EŠGŠGŠŒGŠG‰‰GGŠŒ‹Š‹þ‹‹‹‹Š‰‰G‹G‹GŠG‹ŠFŠŠŒHE‹ŠŠŠ‹‹þ‹‹‹Š‰‰ŠŠŠ‹‹‹ŠŠGH‹‹‹‹Š‰Š‹Š‰‰ˆ‹Š‹þŠŠŠŠ‹‰‹‹‹Š‰‰ŠŠŠŠ‹ŠŠ‹‹ŠŠŠ‹‰þŒŠ‹ŒŒŒ‹ŠŠŠ‹Œ‹‹‹‹‹‹ŠŒ‹Š‹Œþ
Š‰‰‰‰‹‹‹‹Š‹ŠŠŠŠ‹Š‹ŠŠþ‹‹‹‹‹ŠŠ‰Œ‹‹‹‹‰Š‹þ‹‹‹‹ŠŠŠ‹ŠŠŠŠþŒ‹Š‹ŒŒŒ‹þŠŠ‹‹ÿþFJGHþKJGJJHEJþFFIJHGJGHE‹þIKIEIJJFGLJGŒ‹‹þJJIIJFHHJGFŒHEŠ‹ŒŒ‹þ
IGJJEIHIGHHJMEŽŒDŠŠŠŠŠŠþIIHFIFHIHIEEGJF‹EŠ‹‹Š‹ŒŒŒŒ‹‹þHIHIIGIIGFGHGFFFŽEŒ‹ŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHKLEGMGMGF‹Š‰‹ŒŠŠ‹Š‰‰Š‰þKFDOFŠ‹GFG‰‹E‹ŠŠŠ‹Œ‹ŠŠŠŠþ
DFŒGŒG‰G‰‹FŠ‹ŒŒŒŒŒŒþFŒ‹‹‹ŠŠ‰‰ŠŠŠ‹ŠŠ‹þ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþŠŠ‰ˆGJGGFJJIEIKIþ‹Š‹ŠŠEH„EFJJHHFJIIJJþ
‹‹‹‹Œ‹DŠ‰EEFJHHGIHIEJJGIþ‹‹‹‹ŠŠŠ‹‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠ‹‹‹‹‹‹ŒŠEFFFFJHGFGIIGIIHIHþ‹Š‹ŒŒŒ‹‹‹ŠŠŠ‰FGKGFGELFHHEFFGþŠŠŠŠ‹Š‹Š‹‹FE‰GˆFG‡GF‡DFKþ
‹ŠŠŠŠ‹‹‹F‹‹G‰GŠŠG‹F‹þ‹‹‹‹Œ‹Š‰ŠŠŠŠ‹‹ŒFþ‹‹‹‹Š‹‹‹Œ‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþ‹‹‹‹þ‹ŠŠŠŠ‹ŠŠþ‹‹Œ‹‹‹ŠŠŠ‹‹‹þ‹‹ŠŠŠŠŒ‹Š‹ŒŒŒ‹ŠŠþ‹ŠŒ‹Š‹ŒŒ‹ŠŠŠ‹‹‹ŒŒŒŒ‹þ
‹‹‹‹‹ŠŠŠŠŠŠ‹‹‹Š‰‰Š‰ŠŒ‹Š‹þ‹‹‹‹Š‰‰Š‹‹‹‹Š‰‹ŠŠŠŠ‹Š‹‹ŠŠŠ‹‹þ‹‹‹Š‰‰ŠŠŠ‹‹‹‹ŠŠŠ‹‹‹‹‹Š‰Š‹Š‰‰ˆ‹Š‹þŠŠŠŠ‹‰‹‹‹Š‰‰Š‹ŠŠŠŠ‹ŠŠ‹‹ŠŠŠ‹‰þŒŠ‹ŒŒŒ‹ŠŠŠ‹Œ‹‹‹‹‹‹ŠŒ‹Š‹Œþ
Š‰‰‰‰‹‹‹‹Š‹ŠŠŠŠ‹Š‹ŠŠþ‹‹‹‹‹ŠŠ‰Œ‹‹‹‹‰Š‹þ‹‹‹‹ŠŠŠ‹ŠŠŠŠþŒ‹Š‹ŒŒŒ‹þŠŠ‹‹ÿþHGJFþJEHJJGJKþFFEHGJGHJIFFþIKIEGJJGFJJIEIKIþJJIIJEHHJFFJHHFJIIJJþ
IGJJEIDIGHEJJHHGIHIEJJGIþIIHFIFHIHIEEGFJGEEIHIHFIFHIIþHIHIIGIIKFGHGFEFFFFïHGFOIIGIIHIHþGFFEHHNŒEGGFGGFGEîFHHEFFGþMFDFŽŽGFGFEEGŠFG‹GF‰DFMþ
DFGŒŒG‹FŠŒGŠGŒŒGŒFŒþF‹‹‹‹‹ŠŠ‰‹ŠŠŠ‹ŠŠFþ‹‹‹‹Š‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþFJGHþKJGJJHEJþFþFFIJHGJGHEŒþDIKIEIJJFGŽJG‰ŠŠ‰þEEþJJIIJFHHJJFFŽHEŒŒŒŒ‹þFFIGJJEIHIGHHJEEE‰ˆDŠŒ‹ŠŠŠþIIHFIFHIHIEEGJFEE‹Š‹Š‹ŒŒŒŒ‹‹þHIHIIGIIHFGHKFFFFEŒŒŒŠŠŠ‹Šˆˆˆ‹Š‹þGFFEHHHIEGEGGGFŒEŒŒŒŠ‹‹Š‰‰Š‰þIFDJFIHGFHHJEEŠŒ‹DŒ‹ŠŠŠŠþ
JFIGJFGHGFFHEŒŒŒŒŒþFIKIEIJJFGŒJG‹ŠŠ‹þFFIJHGJGHE‰ŠþKJGJJHEJþFJGHÿþHGJFþJEHJJGJKþˆ†EHGJGHJIFFþFþ‹‹Š‰GJ†GFJJIEIKIDþ‹Œ‹Š‰EH‹FFJJHHFJIIJJþEEþ‹‹‹‹Œ‰DŠŒEEEJHHGIHIEJJGIFFþ‹‹‹‹ŠŠŠŠ‹‹ŠEEFJGEEIHIHFIFHIIþ‹‹‹ŠŠŠŠ‰Š‹‹‹‹ŠEFFFF…HGFHIIGIIHIHþŠ‰‰Š‹ŠŠ‹‹‹ŠEEFGGGEGEIHHHEFFGþŒŠŠŠ‹HD‹‰EEEJHHFGHIFJDFIþ
Œ‰‰ŒŠEH‡FFJGHGFJGIFJþ‹Œ‹‹GJ†GFJJIEIKIþ‰ˆEHGJGHJIFFþJEHJJGJKþHGJFÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþFþ‹‹‹ŠŠŠŠ‰‰Š‹‹þFþFþD‹‹Š‰‰Œ‹ŠŠŠŠ‹‹‹ŠFDþ
EEþEŒ‹GŠŠG‹GŒŒF‹G‹ŒGŒDEþEEþFFŽFEŒF‰‰GF‰FEEGŠFGŠGF‹EFNFFþEGFFFHHŒEGGGGFŠGFGEŠFHHFFFGþHIHIIGIIŽFGH‹FFFFEFHGF‹IIGIIHIHþIIHFIFHIHIEEGJFGEEIHIHFIFHIIþIGJJEIHIGHHJJEHGIDIEJJGIþ
JJIIJFHHJFFJHHEJIIJJþIKIEIJJFGJJGEIKIþFFIJHGJGHEFFþKJGJJHEJþFJGHÿþŠŠŠŠþ‹Š‰‰Š‹ŠŠþ‹‹GIIGu‹‹‹‹‹þŠ‹‹GHHHHGŠŠ‹ŠŒ‹Šþ‹Š‹ŠGIHIHGGG‹‹‹‹ŠŠŠ‹þ
‹‹‹‹Œ‹GGIHHIGGGŠŠ‹Š‹Š‹‹‹þ‹‹‹‹ŠŠŠ‹GGGGHIGGHt‹‹‹Š‹ŠŠŠŠ‹þ‹‹‹ŠŠŠ‹‰ˆˆGJGGIIGGHIGwŠ‹Œ‹‹‹‰‹Š‹þ‹Š‹ŒŒŠŠŠŠˆGIHIHGGGKH‹Š‹‹‹‹‹ŠþŠŠŠŠ‹Š‹Š‡JJJKGHJLIŠ‹ŠŠŠŠþ
‹ŠŠŠŠ‹‹‰‡KMKJMM‹ŠŒ‹‹þ‹‹H‹Œ‹Š‰ŒŒŒŒ‹Š‹‹þ‹‹‹‹Š‹‹‹‹‹‹‹þ‹Š‹ŠŠŠŠ‹þŒ‹‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠŠŠ‰‰Š‹‹þ‹‹Š‰‰Œ‹ˆˆŠIJH‹Š‰þ‹Œ‹ŠGGGIŒŒŒHGGILŒŒŒ‹þ
‹‹‹‹ŒGJJJIJ‹ˆKILˆˆŠŒ‹ŠŠŠþ‹‹‹‹ŠŠŠHJGHIKŠ‹Š‰‰Š‹Š‹ŠGŠŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGHJKN‹‹ŠŠŠ‹ŠŠŠ‹Šˆˆ‹Š‹þŠ‰‰Šˆˆ‰HHM‰ˆHŒˆˆ‹HHHŠ‹‹Š‰‰Š‰þŒŠŠŠ‹‰‹Š‰Š‹‹ŠHIGGHI‹ŠŠŠŠþ
Œ‰‰‰‰‹JGJŠGGIJKLŒŒŒŒþ‹‹‹‹JJJGˆLJJˆˆ‰Šþ‹‹‰ˆ‰‰‰ŠŠ‰‰Šþ‹ŠŠŠŠ‹‰‹ŒþŒŒ‹‹ÿþŠŠŠ‹þŒ‹Š‹ŒŒŒŠþ‹‹‹ŠŠGGG‰Š‹‹þ‹‹Š‰GIIHHIIIG‹Š‰þ‹Œ‹ŠGIHHHHHHHIIGŒŒŒ‹þ
‹‹‹‹GIGHHHHHHIGGHHHG‹ŠŠŠþ‹‹‹‹ŠŠGGIHHHHHGGGGIGHIGŒŒŒ‹‹þ‹‹‹ŠŠŠŠ‰HGGIIIIIIGGGHGGJIHˆˆˆ‹Š‹þŠ‰‰Š‹ˆJGGGGGGGGGGGGKJLKJ‡‰Š‰þŒŠŠŠˆHHIGGJGIIJIJMKJOˆŠŠþ
Œ‰‰JJKGIKGIJIJKOMLŒŒþ‹Ù‹‹HKOHIJJKLŠŠ‹þ‹‹‹‡‡ˆˆˆˆ‡‡Šþ‹ŠŠŠŠ‹‰‹þŒŒ‹‹ÿþŠŠ‹‹þŒ‹Š‹ŒŒŒ‹þFþ‹‹‹‹ŠŠŠ‹ŠŠŠŠþDŒ‹‹‹‹ŠŠ‰Œ‹‹‹‹‰Š‹þEEþEŽG‹ŠG‹GŠ‹FŠŠŠ‹Š‹ŠŠþFFNFEF‹ŠGFG‹ŒE‹‹‹‹‹ŠŒ‹Š‹ŒþGFFFHHŽEGGŒGFŠŠŠ‹ŠŠ‹‹ŠŠŠ‹‰þHIHIIGIINFGHGFFF‹E‹‹‹Š‰Š‹Š‰‰ˆ‹Š‹þIIHFIFHIHIEEGJF‹EŠŠ‹Š‹‹ŠŠŠ‹‹þIGJJEIHIGHHJŽEŒ‹D‰ŠŒ‹Š‹þ
JJIIJFHHJîFŒHE‹ŒŒŒ‹þIKIEIJJFGîJGŽŒþFFIJHGJGHEŽþKJGJJHEJþFJGHÿþŠŠ‹‹þŒ‹Š‹ŒŒŒ‹þ‹‹‹‹ŠŠŠ‹ŠŠŠŠþFþ‹‹‹‹‹ŠŠ‰Œ‹‹‹‹‰ŠFDþŠ‰‰‰‰‹‹‹FŠ‹GŠGŠ‹G‰DEþEEþŒŠ‹ŒŒŒ‹ŠŠŠFE‹G‹FG‰GF…EFJFFþŠŠŠŠ‹‰‹‹‹Š‰‰ŠFGŠGFGE‡FHHFFFGþ‹‹‹Š‰‰ŠŠŠ‹‹‹‹ŠEFFFF†HGFIIIGIIHIHþ‹‹‹‹Š‰‰Š‹‹‹EEFJGEEIHIHFIFHIIþ‹‹‹‹‹ŠD‹ŠEEFJHHGIHIEJJGIþ
‹ŠŒ‹ŠEH†EFJJHHFJIIJJþŠŠˆ†GJJGFJJIEIKIþˆ‡EHGJGHJIFFþJEHJJGJKþHGJFÿ