þHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHHIEHHHJHHHHIHþ
HHEHHHHHHFHIHDHGHFIHGGHGþHFHHHHFHFIGHHIFHHHHHHHDHGFIHþHFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGþFIHGHGFDFHJFIHHIHHHIGIGHHHGGþHFHHGHGGHGFJGHGGHDHIJHFFþ
HHFHHHIHHGHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþHþFþHþGþFþGþGþIþIþIþHþHþJHþGþHþHGHþHþIHþGþIIþHþIHþIIHHJKJþGIþIþIHþJHþHJþHJJKKIKJKþHIJþHHHþGþIþIKIIKKKJHKKHJKJKGGILHþGþIGþGKKJLLKKLKILGLGKJKIJJLþGþJJþJHKKGLGHLLILLLLKKLHJJLþHþJþJIJHKGKHIHKLHHLKLJKMKGKLLHIþLIþKJJGKJKJHLLHJLJKLJMMHHKLJILIJGJKJKGKGHKLLLHJGLKMJMMJHKMLILLJGLþIIJKKGJLGLKLHKMHIMKJHLJJHLIJþKHIMLHJLLHGMKIKMJHJMLHIJþ
HLLILJLHMMIKMJGJKMHJþJLJLIHMJKLMJJGMLþJLHMJKLLMKIKþGJILHHLGþJLKHÿþ=8;:8þ48::88=þ4888;:;9::K;N;þ898899;9;<M;;;;Lþ:::;9:=K==;K:=Mþ69=;K©::<LKL=LOMMþ8L;;;<©§===;=ONL<þ;9=9K;MN:=NNOMMþL=<MMMNNFNONLþOLMM¦©OOOO¨þ¥«H¨«þ¨«þ©«Lÿþ997þ579þ9799’þ9999999þ568þ97:;;9999:9þ9þ88:8<þ==;:9;9<þ<;9þ
9þ98::7:8<????===<<<þ;þ;þ7þ=<;:==?••?þ??=<<<<þ==;þ787788þ??==þ9þ<••þ<MMþN=>>þ878888þ?—?=::þ•þ?=?=?MN===þ788988—>=;:::99==<=;>M?þ>?þ7þ9þ998::•>><:;<99;==?MMM??<þOþ9;9<;:988:<<;;;;:===?MNNOM??<þ9;=þ?þ=;;;:;;;;==?:==?MONMþMMþ>>þ?=<;;<<==?O?ø>MNONþ7776þM>>>>>=?=;;?MMOOþ778987þ=NONNM??:;>>>>MOþOOþ799::;8=NN>=??>–<9>>;=MOþOOMþ;<<<<::89<<<===><>=?MMONNOOOþ==>>=þ=<=>??ü>M>MM?M—>>üNþ>O<þ>??>þ??>??>›þMN;>š=<>›NN??Oþ???MM>?›þ<<<=?>—<<<MNN>þ==þN?þM›þ™=™=;=;?>>MN>>þNM=þ
›™›þš;=>=>>>>MOþO;ONþ—›J•??=??=?>?M=NþNNþ6:::=þJ——:?NNMNN???=<NþMþ:;::;;=JI—›–MNON™NN??>=?þ	<<<=;<J—™›”JHJN›JJ?M???>=>þ8;?=M›?I—™JK–J?<>›šMNNN?>ONOþ:N==??JJ—JHJ;<<=>N›OOONNNOOOþJH=???????I;;<<>??NNOOOOOOKOþJHJJJN??????JG<›>MNNNNOOJIKJJIKOþHKJIO???—šJHK™—NNOOOOKIJJJIIþJHJJIJIšJIH˜›JLOOLJKKJHHþ
JJHJJ—šJ–˜™MMLKKKJJIþIHJJ—š—šMMMLLKKKþJIJ—™›MLLLJHþIKMMMMKJþIKKJÿþ
==þ<MMþNþ;=?=:=þ=?=?MNþ9þ;>=;þ==þ=;>M?þ>þ998:þ”þ><=þ<=9þ=þMMM??<þOþ;9<;:988:<<;;==:===?MNNOM??<þ;=þ?þ=;;;:;;;==>>>==?M997þ579þ>>þ?=<;;<=>??O?9799‘N99999þ77þ7þM>>>>>568;97:;;:999:9þ778987þ=NONNM5588:8;>==<;9þ9þ7799::;8=NN;=98::7:<<????===<þ9:;<<<<::87<<<=<;:==?þ”?O??=<<þ:<==>>=<797788ü??==M9þ<þN<MM<þ>??>þM;9:888”?–?=::=<”þN?=?=þ???M?>?9;:988–>=;:::99==<=;þ<<=›?–=<;;:;;;;==?:==?MOþ>>þ><;;<<==?O?ø>MNOþ777þ?=>>>>=?=;;?MMOOþ5::::87þ=NONNM??:;>>>>MOþ::;;:<<:;8=NN<<=?>•<9>>;=Mþ78::;;;;<<M=O=:89:;>>>>><>=?MMþ;<;:;<=;=>O????N<=>??ü??>MM?Mþ=<<==>?M???M??O??>?þ”þ?N;þ??=Mš=MMN?NNN?8=<:˜•þ<<?8=þN===>š?OO??O8:?:=<:˜”;=:;<<::?þ=>?>???O678:=::<<;;::::<==;<<M=þN??OOO<=;:::=<=;<=<;:<==;=>O==þONOO<>==;:;;=;=>O=<<<=>?M??=þJHJJ=??=<<=;>?M;??=Mš<MMNMNNþJHJJJG==??=Mš<MMN:N===>š˜OO??OKIþHKJIJ;N===>š˜OO?=;?;M=OO?OIIþJHJJ=<?;M=OO?OON?>OOOOOHþ
JJHN?>OOOOOOOOONOONIþIHONOO—šOOOO™MLKþJILLJ–œN™œLLþIKšœ™MLJþIšœLÿþOOOþOþOOOþOþOOOOþOOþOOþLOMþOOLOOONþLMNNONþHKLþJLþLLONLMLþOMOOOþIKMNIKLKMNOOMNMþOONOOþ	JLMþOJLMMþOMþOONMLKOOOþOþKþOOJKLþNþKLOþNNþNMLþOOOOLOOOKLMNOOLKþMNMKþ
OOOOOOþOKLMNJLNMLJONMLKþOþIKMKLMMOOJLNONJMLþNMLKOOþJLNKKMLMO™KMOOOLNMOOONOOþOþOILMHLONNNMOLONOOMNNOOþOOþOOOJOHLþMOKNOKMNOONþNOONMKþOþOOOOOOMLMMþIMMOOMNNþLMþNLKþJKMOKLLNLMOJNOO˜MNNKMLOþMLþJKMNLOLMOMOOLOOKMN˜NLNOOOONLþILMþOOOOOOOOLOONOO˜—ONNNOOOþNþKþOOOOKLNOKNONLK—OONMKþOOþOOOþIKMNKMLOLMLOKMONLKþOþOþKKMOOLNOJMONKMKOOMLKþ	OþKþOOMOOONOOMNMOOONKþOOOOOO˜OšOMNOOOOþNþJOOJJOO–˜šOOOOOOþHJIOIJJO”˜™JJOOJJJOJþ
JJGJJJJJ”™˜™JKJIOHKJIIJIþJHJJJKLL•˜šJ˜š™—JJJJJJKJIHKJþJHJJJGHKKLLLJ˜šLN™–LKKJJJIKJJIKIþHKJIJIJKKLLššKLLLLKKKKIJJJIIþJHJJIKIKLLMLKKKKKKJKJJHHþ
JJHJJJKLLMLKJJJKKJJIþIHJJIKKLLKKKJJKKþJIJIJJIJJKJHþIKJJJJJJþIJJJÿþMþLNþLMþNLþKMNNKMLþMLþLMNMMLNMþONLMLþKKLNNLONNNNNþLMNNLJþKLMNOKMLOONLNKML™™MLþKLLMþKLNMKOONLLN™˜þONLþ
MMþOLNONMOONJNN™þNþOOOMONOOOOOMLš˜OþOþOOOOOKLN˜LMONLšOOOþKLNþ	OOOOOKMNNKMLOOMLOOOKMNNþ	OOþKLMOOLNMšO˜NLþKLMOþ	OþMOOOONNN™šš™NOMOOOOOþ
OOOOOOOONMML™OOOMMLLOOOþOOOOOKLNOOOONLJNLMMNMMLOOþOþOOKMNNKOOKMMLKMLLþMNLþJLMOJLMMOMONLNMMþOOMLþKLNþLMONLNNNMNMMLONNþNNþKMNNJMOOLNOOLOONMMLOOOþ	KLMþLNOKMOOKMLLONNLOOOOþMþOONOKLNOKLONMMONMLþOOþ
OOOOOMOOKMOOONLOONNþOþOOOMMLOOKLNOOONMOOONLþ
OþLMþNMOOMþOOšOONOKLNNLMþ	JMLþMLOOOOOšOOOOMNNKOOOþLNMOþONOOOOOOšOHLOOOLNOOOþMNNþOOONNMLOO™OMOJOONNOOOþNKOOOLMOONL™OJOOOHJONþOOþKMOOJMMOOOMš™JOOOJJJJKJOþKLOOGONOOJONšKJJOOOHKOIIJIþMHOOJNOOHK˜™˜KHJJJOJJJJJIHKJþJHJJOOHKONJH—™šLJHJKIOHJJIKJJIKIþHOOIJOHJHJ˜˜™šLKJJJKIKIJJJIIþJHJJIKLL–˜˜™˜LKKKKJJJJHHþ
JJKLM˜šMMM˜šš™LLKJJIþI™šMLKLLMM˜MMLLKþJIJKLLLKJKJHþIKJKKKJJþIJJJÿþMMLþKLNþLMþNLLþNNOONþKMNNKMLþMLþOþOOOOKLMþLNMþONLþOOMMLLþNNNþNþKLNNLMONLLLþNþKMNNKMLLOMLNNLþNOþKLMMþLNMMOOOONLLOONþ
NNOMMþNNNNKMLOOMLOOONþNOOOOOþNOLNNOLNMOOONLþONþOOOþOOOOOOMMLONNNOOOONMMLþOþKLNOLMþNLL\NKLNOLMþNLLþ	KMNOOMLþMLOKMNNKMLþMLþKLMþLOO^þOOLLM__LNMOOþNLþMþMMNLNOOO_^OO]^OONOOOONONþNONOLMONOMLOOOO\]^_OONOONOOOOONþNONKMOOOOONLOOO]__ONOOOOOOOþNOOþOLOOOOOOOOOMM__OOOOOOMMLNOþMLþNOOOOOOKLNOLMONLLKLNOLMONLLNþONþOOLOMOMNNKMOOOMKMNNKMLOOMLOOOþNNOLMLMLNOOONLMOOLOM^OONOOOþKOONKMLOOMLMOO__OO\^OOOOOMMþKOOþLNOOIOOOMO_ML__KLNOLMONLþMþNOOOOJLOOLM_NLLJMNNKMLOOMþNOOOOJMNNGOL__MJLMOOLNMOOOþJJOOOJJLMHJLNM^_OMLOOONNNþOþJHJNOJHJMKIJNOON^__ONOONINKJþJHJJJGHKJKJHJNOOO^^_IJHOOONJJIKIþHKJIJIHJHJKOOOJ\]^JKIKIOONIIþJHJJIJIIJJJJ[]^MJJJKJJHNþ
JJHJJKKKLLZ^_LMJKJJIþIHJJLLLY\]_^^MKKþJIJIY[^LL]_]þIKJKKJJJþIJJJÿþJþJHJþJJþJIJþKIJþJJJþKJIJKþJIJþKIJKþKKJJþJHKþKIJKLþKþKJJIIKþKJKLJJKþLLþJHIKþKKLJKLþJI…HIIJþJHKþKLKKLJIGHIJJKJKþJKLKL‰MIHHJKKþKJþJLL‰‰LIKþKþ	LK…JKKþJMM‹MLþLKKLLKJIJ‰KMLKKþLLLþ‰‹LJ‰LKþLþK‹MM‰‹LKþKKMLMK‹MKJJþKJLLMKKKLLKJKþJLLLKþLLKJþKKLLþJLKJþLLLþ
LLJþJJJþJLÿþJJKþIJLKKþHJKLKJKGþGKKJKLKJJIHGþKLKLIIKKKLLKLIHHHHJKþ
IJJJJKLHHŠ‡Š‰ŠKIIJJKKKþKLLKKLLL†Šš•œ›ŒMKLLLLLKþLKKKL‡‹LL‡ŒŠš›ŽŽŠMJJGGHKKKþHHJLKJJJKKM†‡ˆ‰ˆMLLKKKJLLHHGþHJMLLLLLLJKKJKMLMMLIHGþIJLLKLIHKLMMMMLLKIIIIIIIþ
HHGHGKKKKLJJJKLIHIGHþFHHHLJ‡KKLLIHGHþHHGJJLJLLJHHþHGLMLLJIþHGHHÿþLLLþKLMMMLþJLMLþMþMMLþJKMLþ
NLþLLMMLþJþJKLþ
NNMLKJJLNLþJHLKþLLLLLþLLKKLMNMþJIJKKþKKLKMLLþLLKLLMNMþIJKLþLLLMMþMLMþ	MMLMNþJþJLþMMMLMþNMLþMLKKKþLMMNþLLJLþMLLMMþMþKLLMNMLKKþKLMNLLLLMNMMNþKNNNMMMMMLKMyzMNLLLLMMMþ
NMþNMMxu|zMLzxzKLMMLþMN{~~~Nv|~|zNMþNMNMLMþNNM{}OOx~u~xNMLJIJJKLþLMLMLMNMMMNNMMOz|~|zLKJKKMLKLLþMMþJþJMMLNNzxzMMOzxzLKKLMMNLMMMþMþKLNMw|~|zNOMNMLLMMþLþ
Nx~u~xNMMzzLMLMKLþLLNz|~|zNNxuzzMMþMþMþ	LLLLMNNzxzNMOOy~~NNMþ
LKKLMMMNþMMNOO~NMLþ
KLLMMNþLLLNMNONNLKKKLþLLMMLþKJLIMNOONNOMLLJKKLþMLþLLJLILNONLLMNOONMKJKLþ	HJIJLILNNMMMLJJLLMNüKJMLþJJGJJJJLMNNMMLKIJHKJJLNKLMLþJHJJJJHLLLNNMLKKJJJJJJJJJMNLMLJHJJJGHKJMMMNMLLKIJKIJHJJIKJLMMMþHKJIJIHKIMKJKKJKJJJKIKIJJJIKþJHJJIJIIJIHJIJIIJJJKJJHHþ
JJHJJJKJJIJHJJHJKJJIþIHJJIIJHKKJKJJKKþJIJIJKIJJKJHþIKJJJJKJþIJJJÿþ645:=þ459þ??þ5245þ649<þ?4678þ=>=þ75þ47<Iþ???579;þ
<>þ::HH7<IFG=>?þ477þ
?þ:<:H9=HH<>?H59þ4þ:>?=<H;<>:;=??þ:???H:>9=þI?þ2346=?3457þ365:??K?5479þ4478??????7679þ748:?þ???K?;69<þ?9<þLK?<?þLLLÿþ643568þ:;:8689þ	4þ=;;969;þ89þ=;969<þ84<þ=;969>þ849;þ?=96<þ843<;þ?<8;þ8459;<þ:8644þ	4688þ??;;8643<;=þ==>8755þ45789:;??=<845:;<==>>>>986þ48<????>:?>7644<<=????>þ9þ?>;?9559==>???þ?>=:64>==???þ??;79>=>?>45þ?<8<>>?9<<<;;:þ>=:?>>9====<=;;þ>=>?>:<þ<þK??=;<þKH387JþKKKJKÿþ325þ23444þ34588þ2þ569þ23þ4:9<þ2þ357:8<þ23þ5;;<<þ234þ;þ345:=<<þ459;:9þ59;:9þ6;;:9þ;;:9þ54þ666544þ<;:þ;6þ766þ66888644þ;:þ;6:þ9<==><;:9:;73þ;þ;89;>==;<;:þ=;6þ;9:<>>?=<þ	=>þ;:<><;þ=þ
;=>>=þHHFIþ>???þHHIHIFGHþ>=<;::87677779:;<=>Hþ??>><<<=<<=;:::<<=F<<Hþ
?????>;<;:H:9E9:;<H<<=IHþ
HHEH9::9H97I899:H9:<=GHGþHFHHIIIIIIIIIIIIHHHHHHFHGFIHþJJJJJJJJJJJIIIIIIHHHGHFHHGIHHGIGþFJJJJJIIIIHHIHHIHHHIGIGHHHGGþHFHHGHGGHGFGGHGGHFHIFHFFþ
HHFHHHIHHGHFHHFHFHHGþGFGHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGHHFHþGHHGÿþ<??þ9;>?>?þ:;;<>;þ:8<=>=>þ::;<>;þ88<<=;<þHH87:;=>=þ78:;<:þHHIHI89><<>=þ679:;FHGHHHHH9H<;<>?þ56899HHHFHHHFHH:9;==þ45688GHHHIIIHHH98H;=?þ
HH457HHHIIIJJIHGH7I:<=HGþHFHH446HHIIJJJHIJIIHH8:=?FIHþHFHHHEF3HIIJJJJHHHIJIIF79<=HHGIGþFIHGHGHIJIJIIHHIHIIIGI8;=HGGþHFHHIIIIIHIIHHGGIJJI7:FFþ
HHIIIHIHHGHFHHFHIHH9þGFHHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHHHHHHþGHHIÿþHHFIþHHIHI6789;>>?þFHGHHH69:;9<=?=þHHHHHFHHHF;=9:<=9>??þ
FHGHGHHHI48:8G79?:;???þHHEHHHHHHF58<74GHF:9>???þHFHHHHFHFIG6:6F5HHHHHIJJGFIHþHFHHHEFIHIHFH:65HFHIGIJJIGIHHGIGþFIHGHGFHFH6;5HHIHIJJIIGHHHGGþHFHHGHGG65FGGHJJIIHIHHFFþ
HHFHHH8HHIJJIHFHHHHGþGFHHGIIIIIHIHHIIþHGHGIIGHHIHFþGIHHHHHHþGHHHÿþ3þ364þ44þ
35977þ7654þ46:95þ27764þ37;;8þ45887þ356<<;þ79:;8þ5þ456<96þ;þ8þ3457þ4568:9þ4þ235;??þ457;:þ8þ4469=<þ468:þ95þ679==þ2þ466:;8þ345=<<I3þ467<:þ345==<34Hþ7;7H34=<?45HHHþ589::H35;4?5:HFHHHþF589<<56<56:<HHHHHIHþ
HHEH489<77<6:=<GHFIHGGHGþHFHHHHF;8;<9=:=;:HHHHHHHGFIHþHFHH9<;<=I=<==>=;:HIGHFHHGIHHGIGþFIHG=>>?FH==?=<IHHHIGIGHHHGGþHFHIJ>9???>>IJJIIHHIHHFFþ
HHF:????>???JJJJIHHGþGFIH?G==??JJIHIIþHG?G<<=?JIIFþGI;;<HIHþGHHIÿþMJ65þLþMJIHJJI5þKKNþONONONMNþHIJLJGþHKNOþ5F5þNLþMþMNONNNþIKMLþNNþ5GHJL6þNMþ7þKþKNþMMMNNþLMMLOOGHIKLK=;þMLþLþ7NMNNNþLKMOKGKLM?þ;þML7þ
7LMNNMJKMIMMLKL<þMIþ	MJMLLMLOONMNNNNM?>=þMþMMKKIþOOOOOOþ?>þMLL7þ;LMNNOONMþ	MLI7þ	:MMMMONOMþ	KJþ;LMNK;^KLLMþJJþ>IMNLHIONMNMþMLþ6MM];MMMNONNþ>HML[KMJNKJMMþ6MN;[[þ7J7NNþHNMZ[\þNML7þLMþ\YNMMMJMþ;þMNKKþKþNL7YþJKHINNVV[þHJJJJJJJZXZþJJJJJJJHJJHZYJþHJIJIJKGJJJKJUV[KJþJJGJJJJJJKKJLMM\YJIIJIþJHJJJJHJHKLKLMMMMLLKLLKKKþJHJJJGHKJKJHKKKLMLMMMMKKKJJþHKJIJIHKHJKKKKKKLLLLLJJJIþ	JHJJIJIIJJJJKKKKJKKJHHþJJHJJJJIJHJJKKKJJIþIHJJJHKKJKJJKKþJIJKIJJKJHþIKJJJJJJþIJJJÿ
þMJ55F5þNMþJþNMNOþMKþKLJHG5þNNMþMKIKþNNONMMMþNþLþLKþHGþOLþML<NNMMJþNJMKþMþKGKOMKL<NNNJN9þMMIMKJMNNMJ9þNMNOOLMLLMJMMþOOOOOOMþKKMMþMNOMNNML;þ9LLMþMLLKMLþ^MMM:þ	9KþMLLKJþ^_NML;þMLKJþ___þLI>þMNLJJþ___þMJþMNþKþ	^]_þMLJþ
MNMþ\\]þMLþ
Nþ\[ZþLþJJ\[XþJJKJKXX[þHJIJJJJZWXJJþJJJJJHJJJHZY[JJJþHJIJIJJJKGJJUWZJJJKJþ
JJGJJJJJJHJKJJXWX[KJIIJIþJHJJJJHJHKIJJKHJJZYZJJJJIHKJþJHJJJGHKJKJHJGJJJHJZVX[JJIKJJIKIþHKJIJIJKKKKJKJLLLLXXZKIJJJIIþJHJJIJIILLLLMMMML[\[KJHHþ
JJHJJKKLLLMMMMML[[JIþIHKJIIJKKKLLMMMKþJIJIJKIJJKJHþIKJKJJKJþIJJKÿþ234þ223445þ5þ==>==?C679:þ>???C55788::þ><>>þ9::;þ?;?þD57:;<=þ?þ:;<<=>þ===>>þ=>>>?þ?????þHHFIþ?????þHHIHIFGHþ??????þFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHIIIHHHHHHHHHIHþ
HHEHHHIIJJJIIIHGHFIHGGHGþHFHHHHIIIJJJJJJIIHHHHHIHGFIHþHFHHHEFIHHHHIIJJJJJIGHFHHGIHHGIGþFIHGHGFHFHHHIIIIJIHIGIGHHHGGþHFHHGHGGHGFHGHIJIHH<IHFFþ
HHFHHHIHHGHFHIIHIHHGþGFHHGGHFIIHHHHHIþHGHGHIGHHHHFþGIHHHHJHþGHHIÿþ2246557==þ332379>þ2467544?=??þ3544449:;þE75????????9??5447789:þ247966=?????;???>>>>:679;þ467:87??????<?????7766779<þ5469:9<??>???=????þ466>59<þ447:8<þ>>??????7þ;>679;þ458þ>>???:G:9þ:9:9;þ47þFH:;;H;HH::Hþ;9;þHHHHHF:;=;=;:7HHþ;þFHGHGHHHIE::;;;HHHIHþ
HHEHHHHIIJIIHIH::IIHGGHGþHFHHHHFHIJJIHIFHHHIJJIIHGFIHþHFHHHEFIHIJJIIHHHFHIHIJJJIIHHGIGþFIHGHGFJJJJIIHHIHHHIIIIIHHGGþHFHHGIIIIIHGGHGGHHHIIHFFþ
HHFHHHIHHGHFHHFHHHHGþGFGHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGHHHHþGHHHÿþ	?4568;;;þ???446E:788þ?????77þ::642þ?????þ8þ:896þ;þ>>>??þ:þ96Eþ==<>>þ=þ8653þ<<<>>þ	7545þ<<>>þ4579=þ74þ>>þ89:=????þ>>þ:<;=þ???þ;<>þ?þHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHIJIIHEHHHGHHHHIHþ
HHEHHIIIIJIIHGHGHFIHGGHGþHFHHHIIIIIJJJJIHHHHHHHGHGFIHþHFHHHEFIHIHHIIJJJIHIGHFHHGIHHGIGþFIHGHGFGFHHHIIIJIHHIGIGHHHGGþHFHHGHGGHGHHIHHHHHHIGHFFþ
HHFHHHIHHGHFHHFHHHHGþGFHHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGGHGHþGHHGÿþ4224449=þ434455????þ434Eþ?>?þ5699þ??þ445689?þ434569?þ44668?þ945:69FIþ87888?IFGHþF7:;:HHHHHHHþH<<>;>HHHFHHFHHHþFHG<<<=96EHHHIHHHHIHþ
HHEHH?=<<<<IHI<<pFIHGGHGþHFHHHHFH===;<IFH<<tHHHIHGFIHþHFHHHEFIHIH===<HH<;>>t9sHGIHHGIGþFIHGHGIIIH==<HH=<>=9:=>HHHGGþHFHHIIIIJ=<I>>==?<<>IHFFþ
HHFHHHIH<?>;HHFHIHHGþGFIHGGH?>IHIHHIIþHGHGHIGHHIHFþGIHIHHIHþGHHHÿþ¡þHHFJIKKNþ£þHHIMMNNNNMNNþ¤þFHGHHHJK‡NNNM,,þ¥¦HHHHHFHJKL‡‹KJL(!*,þF§¨HGHHHIELLLþKKLL(%'eþHHEHH¨¦HHFHIHJJJKLLM(#'(-þHFHHHHFH¨¥GHHIFHKLLLM©%!,-þHFHHHIIIHIH¨¥¥HH£¤¦§¨©©««,($JIGþFIHGIJJJJJJ¨¦¨©KHNNNLNKNJJIGþHFHHGHIIIIJJKNNNNLKJKJFFþ
HHFHHHIHHGKLMMMJJHHGþGFIHGGHKLMNNKHIIþHGHGHMMLMNKFþGIHNMMNNþGNNLÿþHHFIþHHIHIFGHþ
¤þFHGHHHHHHHHHþ	¦þHHHHHFHHHFHHKLMHþ§þF¡GHGHHJIEHHKLLMMIIHþ¥¦þHHE¢HHJKKLMIKLMMNNNJGGHGþ¤§þHFHHH£FKLLLMMLLMMNNHJMJHGFI¦þHFHHHEF¤HKLMNNOKMMNIKLJJHG§¨¨GIGþFIHGHG¤LMNNNLMOONJKLM¤¥¦§HGGþHFHH¦NG+((—((+)¦§?LKHFFþ
HHFH,)—%%%—),,)?MHHGþGFIc(–”—)c,#"JIIþHG—*JHFþGhj-LHþ-ÿþ(((#(þNþ%)*(&&þKNNMMN¦¤NNLLþLLNKHGMH¦£NMJLKþ=MþMKKLJJNON¤¢LKJHHþJJKGLKJHHMNN¥¤ILJHHIHþ
KMLM¢JHHHFLMMN£LHFIHGGHGþNNFHKLM¥HFIGHK?MN£NLHHHHHGFIHþNNHHHEFI¦IHFHEJLMN£N?LIHHGIHHGIGþFIHGHG§I¤¥¥¥IKLM£MMMJIGHHHGGþHFHH¨¤§GH¦¤IGK¦LMLNJIHFFþ
HHF§HHIJ§¥¦¦§KLMMHHGþGFIHGIJJJJJJJJIIþHGHGHIJJJIHFþGIHIHHIHþGHHHÿþHHFIþJKMHHIHIFGHþLKKLLLNHHHHHHHHþ)MLLLLLLMNHHFHHFHHHþ%(,MMMLMMMMNNHHHHHHHHIHþ)%()£¤MMMKJNNOHHHGHFIHGGHGþ,(%¨§¦£HIIGHHNFHHHHHHHHHGFIHþHF%NNN¨¦£JKKJJIHFHIGHFHHGIHHGIGþNNNMMN¨¦£HHFIHHIHH IGIGHHHGGþ?LKMNN¨¦HGFHGHGG§HHIHHFFþ
?KLMN¨¨HHGHFHH§HIHHGþGFIKªª¨¨¦¦¦¦ªIIIþHGIJKKKKKJHFþGIHIHHHHþGHHHÿþJLþKJþHLKLþKKLþLLLHIKKLLKKLþLLKLHKK(—(-NLKKþHHKKKL(#,(”)*"NMLLKþFHGHGJJL'%'-hj"(£NMLþ
HHEHHHHHJM/($(#/NMMGHGþHFHHHHFHIJLLNNNNNNM?LKIIGFIHþHFHHHEFIHIKLLMMNMNNMLMMJHGIHHGIGþFIHGHGFIKLLKKLKKMKJLLLGHHHGGþHFHHGJKJJKLJIHKKKJLLJHFFþ
HHFHHHIHHGHFIKKKJLHGþGFHHGGHFIIHJKKLLþHGHGHIGHHIHFþGIHHHHHHþGHHHÿþHHFIþHHIHIFGHþFHGHHHKKLMLLþHHHHHFLLKMKKKMLNþFHGHGHILKLL€ˆLLLMNMŽþ
HHEHHHHILMMM‰†‹MMMMN†ŠþHFFIFEFHGKLLIJLJLNLLMN‡ŒŠþHFHHHEHJHIKLJHHJKKLMJJKMŠ‰þFIHGHGFHILLJJJIIJKKLLMN†‡þHFHHHHJJLKLKMKLLNKKLLHFFþ
HHFHHIJJJLNNNNNMKHHGþGFHHHIIJKKJJHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþHHFIþHHIHIFGHþJKKLIHHHHHHHþKKJKLLKLIFHHFHHHþFLLKLLLKKKKKKJHHHHIHþ
‹ŒNLLMMMMMMMMLJHFIHGGHGþŽŽŽŠNLKHHIIJKLLLMKHHHDHGFIHþŽŒ‹ŠNMLJJJKKLLLMKJHFHHGIHHGIGþˆNNNMLLLLLKMMJHHIGIGHHHGGþHFHNMMMMMLMMKHGGHDHIJHFFþ
HHNNNNNMJJHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHHKKKJHHHHHHIHþ
HHEHHHHHJKMJLLLJHFIHGGHGþHFHHHHFHFJKLMIKLLLJHHHDHGFIHþHFHHHEFIHIJLLLMGJJKLLJIHHGIHHGIGþFIHGHGFLLKKLMIJIIKLLJIGHHHGGþHFHHGMLLLLMJKKKLLMJIJHFFþ
MHFHLLLLMMMLLMMKJHJJþGFJLŠ‡ˆŠ‰ŠŠJJIJþˆ‹‰Š˜—•ˆ‰‹Žþš•šœ™›þ™š›‹ÿþ‡ˆ‰‰þþFMMNNMNNNNNJþHHLMLLMMKLMMMMJHþFHGLLLLLMMKJKJJLMJIHþ
HHEHHKLLLIƒML€…KJLMJHGHGþHFHHHHFKMMKKMMK‰‰LKMJHHHGFIHþHFHHHEFIHIJMKKKMJJKLMJIHHGIHHGIGþFIHGHGFDFJMML†LLLLJIGIGHHHGGþHFHHGHGGIJMNMMJIHHHIJHFFþ
HHFHHHIHHNMJIIIHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþWWUUUWþWTTSSTTWþ[WUUUUW^þYXYZ[\]]^þXXYZ[\]\^þYVVWXYZ[]þVVWXYZ[]^þUWXYZ[\]^^þUVXYZ[[[]þWVVWXYZ[\^þUWXYZ[\]^þVVVXYZZ[\þVVWXYZ\]^þWWXYZ[\]^þXWVXYZ[\^^þXWVWXYZ[\^þXXWXYZ[\]^þXVUVXYZ[\]^þXWWWXYZ\]^_þXWWXYZ[\]^_þXWWWYZ[\]^_JHþXWVWXZ[[\^_HIHHHþXXWVWXYZ\]^_IIHHHHIHþ
HXXYYXYZ\]]^^IHIHGIHGGHGþHXYYZZZY[]^^^_^[HJHHHHDHGFIHþHZZZ[Z[[Z\]]^^^_^]Z[IIIIHGIHHGIGþFIKK\\Z[\]]^___]\[ZZ[IGHHHGGþHJJ\[[\\]^___^^][[YXJHFFþ
HHJ\[\\^^MM^^^]]L[ZGþGF\[\]^^LLLLKKIIþHJ\]]]^KKIHHþGKLLKJHHþJJJJÿþWTTTTTUYþWTTTTTUYþTTUUUUTZþXVVUUUV]]þUUVXYZ\]þYXYZ[\]^þYXXYYXYZþYUUVWZ\]þZWXYXXYZþZUVWXZ\]þYYYZ[\]^þYWXZ[\]^þXWXYZYZ[þXVWXZ\]^þXXYZ[\]]þXYZ[\]^]þVWXYYXY[þUVWX[\]]þYZZ[\]^^þVYZZ[\]^ZþVYZ[\]^^]þVWXYZYZ]ZþUVWXY[]]]þXYZ[\]^^^þXYZ[\[\^^þYYZ[\^ÿ
þ=þ>=?þ><?Mþ>=>MMþL<=?MMMþ>>==>MNþLMþ>þ>KMNMþLþ<þ=;KLLMKKLþKJIH<LLMMþMKKþKJIHJJJKLLMLþLþ9JKLLLJKLMLþKJþHIKKKþLJLMLþKJI9IKþJKKþLKLLþJþHIKLþJKLþJLLþKþI9JJKKþJKLþKþKJJHJþIJKþJKLþLþJþHHJLþJJKþJLþJHHIJJJLþIJKLþJLþKþIJIJ?LþKJJLþLþJHIJKIK?KþLILþJJIHþK=J=?KþJLþ>III<<=þ=K?þKþK9I<<=?þ??þ>=I;þ=<>?þ?þ;H;þ>=Lþ=<;þ=Lþ>=>Lþ?ÿ	þIþ9;þ;þ>J;K>Lþ>I=þ>LKKLLþ>Mþ	;=??>KKKLKLþKM>LþL9>=?>KþLJJJKLþM?K?þLLLL>þ>KKKþLLKLþ
M?MþLL==>?>KþKKLLþLLþ
LM?LþM>=>??>LþKJKKþJN?M>KM>J>????LLþLLLLþ
J?LLLML?>MMNNN??KIHLLþLKKNLNLK?M?>NNM?LLLLJHIþ	MMLMMMLNMMKMN?LMILLþKKJJþNLKLMMKLM?MM?LLLþMLLKKþLKMMMLLKL??NM??KLMMLKKILþKKLMMMLKKL??MMM?K?KLJIMþ	=??M«M??=K???þLL?JIKKLþ
?MM«­MMM?=>?JKLKK??JJKKþ	?LM«­NMKKK=>L?KþI9þ
>?M?MMKLLM?=>MþLM©§MKLLMMM?=þMKLL©LMKMLLMþLMLLªLªþLMMþLLL«ªª«KLMþLþ««LKþKþLþLÿþLKLJKþMMLKJJþJKKþ>LMMJJJKKKJK9þM=<LKKþKJHJJIKJþNM>=KM>JHKJþJKK9þMNMK>KL>ILþHIKþJþMKKMLLK;=LMþHIKKþKKMþMKLL<HILKIHJKþKLþKKLLKJJJHILLIJþIþLþKJLKJLþKJ9JLLKþLþJKLJLþKKKIHJLLþJJLþKKJþKI9JMþLLJþMLKJþLKIHþJKþLKJþKKJJ9þKþLKJþKJIþLJþKJJþLJþKJIþLþLJJþLIþLJþKþÿÿ
þHKLKþKLIJKLþHIJJþIIKLþKIJKþIGIIþLKJJLþIGGGLþLLLLKþJJGGIþIþKLMMKJþGIþJHJJLþLþLþJIþJJHHþLþLþJJJJIHHKþKKJIJIþLþJ?KIKJIHJKþKIJ=KþHIJJþJKIþIK<III>þKKþK=III9KþKþ?IIIþ;I=>þ=Iþ;H;þJþ;<=þ>;<>þ><þÿÿþKK<<=KLKKKKþKJKþKHJJKLLKþKþKKLþ<JJKJ;KLKKLKþKLKKIKJLKKJJKMLþKþLKþIKKLþMJLKJKMLKIþKþIKLLþ<KLþKJLMLKJKþIJKLþ<JLþLKHLMLKKþJKLþJLLKILMKLþKLþJKLLKþJKL>þLþJLLþKþ??þKLþIIþMþIþ K?ÿþKJJIJþIJJJKJKKLJKþIJJJþJKLþKJKþHJJþJJJLþJLþJKLþJI99;HþJKKþKLþKþ:;þKIJKþJKLþKI:JI;þKKIJKKþJIKJJLKþJKLLþ<LMþKJþIKKKþLþ9þIKMMK?LþIKKþK<LMLKK?þLLþ?JKMMKþKLþLLLþ??MþMKþLLKMþMKJþLLþMþMKKþMÿþ
9KKKJJ;þ9HIJKLKKKJKKK;þIHþJIJKKJKKKMMþJKKKKKþKKKMMMMMLL;þKLþJKKþKþ???MMLLJþKþJLKKþ?MMþLþJLþ?Mþ?MþLþJþ
MMMLþMMLMM?þ?LþL?þMLþ?þM???þ>?þKþLLþL?LLþ?>þ?þ?L>þ????þ>?>þ>ÿþ	HIþKJJIHþLLKIJþLLLKKIJJþLLLKIHþKJIþLKKIJþLþLJJJJþJKKLJþLLKKJIþJIþIKKLLKKJIþKKKHK;þKKLKJIþKKH:þKIþKKLIþ>JIJþKLKIþKKLþ>=KJþLLG;JIþKIþ>><þKKJ;þIIþIKKþ=þ=JJIþKIIþJ;þKJ:<;þ>þJK;þJþ=;þ>=Jþ<þ>=>=þ>þL<þKIþJÿþJJKKLJKKþJLþLLLKKJJIIII:KþI<JKKK>L>KKJJII:þKLþIJKþJKKLþLLKLKKJJIKþJþ
IJþJKLKþNLJLK<KLJJILþ
IþIKKþLKMþKLMLKJIþKþKþJJKþKLMMþKLMþLKJJJKþJKþKKþJKLMþKLMþJLKK>JLJþ??þKþKKLMþKLLMþL?þKKIL?MþMþ	=LMþK=LMþKJMþL>IKþMþK=LMþKJLMþ>>>J=LþLMLMþL>?Lþ?KILþLKKþM?þM>IþIJJKKK=>?KLLMKþIHIIH;=>LLLL?MMMKLLþ
IHJIJ=>???>>LLMþ>MMMMþIHJJKKþLJI?L?þM>>MMþ>MMMþIJJKKKLLMþLJ=>?þ>>Mþ>«M?þIJLLþLIKKLMMþLJ=>LþK>M¬>?LþIKKLLKþKIJKLMþLI=>LþMMM¬??KþIKHþKLLKþKIJKLMþLIKLþ¬M©«?>=JKþJIKKþKIJKLMþJKLþªª?L>=?KþJIKLþKIJKMþLKKMþL>L><?MþIKþIKKþJLMþ>þL>=>MMþIþJKLþKþ
MMMþ;KþLMþLÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHGHEHGHHHHHHIHþ
HHEHHFHGFFHGHHFGHFIHGGHGþHFHHFFFHFFGEFFFFHHIJHIHHGFIHþHFHHHEFGFEEEFFGGHGIGHIIKIJIHHGIGþFGFFEEFEEFGFGFFIFHFHJKJJHIHGþFEFFFFFGFEFFGFIGGHJJKJKIþ
EFEEFFHFGGHFHGFHIKJKþFGFGHIHIGIGJIJKKþHFIGHJGGKJKJþHFJHIKJHþGIFIÿþHHFIþHHIHGFGEþFHGHHFEEFFGFþHHHHHFGEFDFEFEFEþFHGHGHHDEFFEFEEFEGFFþ
HHEHHHHHHFFEDDEFFEFEGHGIþHFHHHHFHFIFEFDFEFEEFEGFGFHHJþHFHHHEFIHIHFHEDFFDFFEGFFEGIIGHIIþFIHGHGFGFHGHHFDGEFEHEGFFIHIFþHFHHGHGGHFFEGEGHFHHFGHFFþ
HHFHHHIHHGHEGHEGGGFFþGFJHGGHFIGFFHGHHþHGHGHIGHHEHHþGIHGHHHHþGHHJÿþHHFIþIHGGIFGHþKJHHJGJHIHHHþJKJJHIHJHJIIJHHHþJKKKJHGHJIJJHIIIHHIHþ
IIJJKKJHIHJJKKHIGIJJGGHGþHJKJKJJIGGJHJIJJIIGJIJJHGFIHþJIIJHJIIHHHIHIJKKIHHIIJKIJIHHGIGþJHIGHIHIIHKHKIJHHGIKKJJIHHGGþIFIHIHIKJIJJIIHIJKJIJHFFþ
JJHJIHIKJIGHIKJIKHHGþJKJKJHHIHIKJKIIIþKJIIIHJKJIHFþJJHKIHDHþIIHJÿþJJJGþJIIFJJFJþGHGHGFHIJFHIþHFHGHHGHIFHJJJHIþHFHHGHHJHJJJJJHJJKJIþ
HHEHHFHGIHHJHIJJJJJIJKHHþHFHHHHFHFHHFHIHIIJHIHHIHHIIJþHFHHHEFIHIHFHHHHHGJHJHHIHHJIHIIGþFIHGHGFDFIGFIHHIIHHIGIGHHHGGþHFHHDHGGHFFJGIGIHDHIJHFFþ
HHFHHHIHHIIFHHIHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþV2V2Y\]þ2323VþXWXWVWþVHV2WZþ>W>WWXZþ	ZZZZ[YVY:IIWXYIH>=>>XYZ[þ[[[[þW9WY9:X[::9;<>XYXYZþ\þ\þHHG]ZY<Z];;:<>I37þXþFH99:;\\][_<9:<89;>>þ
HH9:9:;<=[\\>=8<7;::::>GþHFH999;<=>W124;>1235;;;:::IHþHFHH::;<<<=V438>?8=3257;;;:::G9GþF8H;<<==V256=>???=5457;:HHGGþ8F:;<=WW68=N>???=947:9FFþ
H8H:ZY:=>?M?>=<<=:=GþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþKH43þJKKKLþKHGFHHþ3þIILþþGHJHEþFILMþ3W3XYþXþ[MLLLG	IKJþLLG3EFHJIHWKXþ[þKþKLLGJKKJMNEFGIJþJþJþþKLLLGJIKMIEIJKþJKLLKHIKGKKJIJKþKKHKJJKJMMLKLLLLKþIZþKMMMMMþZþ9JþLLMMLKþ8KKKKML_KIJJKþ9JKLþ9[MLþJKþ<KLJþ[KþþKþ[ZYþ<^\þ\VVþ^\þZXZþ[]þZYþZ\þUV[þYþ\Y\þVY[þWY[þWVXþ\Y\[þVY[þ
LLþHHWY[þ
LJþHHIHWVXHþ
KLþ
FHGHHHHY\[HHþ	KþHHHHHFHHHWY[FHHHþKþFHGHGHHHIEHXV\HHHHIHþ
HHEHHHHHHHIHY\\HFIHGGHGþHFHHHHFHFIGIFX[\HHHH[JKFIHþHFHHHEFIHIHFH[[]GHFH\[KKHGIGþFIHGHGFDFHJFXZ[HIGIG\\KKGþHFHHGHGGHG^^WWYX[HIJHFKþ
HHFHKJI<===^^ZYXYYZGþKJJIG89:;===\[þHGHGH::;<=K=þGIHDHH8:þGHHJÿþKþLþHKþKþLKþKLþMLþKKþLKþKJLþLþKKLKþKKLLIþJJJJKþHKKKLLGHþJJJJJKþK8ILKLL:IþIIKþKKþZþFHKK9LKL:JKKLIKKþ[þZ\\\LKKKMKJKLKLKKKþ=\[\\KKMKKLLILIHþ
:;<==<_]]LLLMLMHGþH89:]======MLLKLLKLIHþHFHHH89:;]\[;<<==<;;;;;;JLLLLKIGþFIHGHG999999:::;;;::GIGHLLLJþHFHHGHGGH:::::::HDHIJHFFþ
HHFHHHIHHGHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIH:þGIHDHHDHþGHHJÿþ421346þTþ421346467þ	2þ	]þ8986467[[þ27þ;99Z\[[\Zþ67\þ;Z]]\Z\<þX[\^þ;]^^\<:þX[^^þ>[\Z:9þX[_^þ86422þ	2466>:699XY\^_^\þ8642233þ224668>=99XY]__^\;;;<65334þ2356789>=;:YY]HI^;;<<<<764þ26:=>>><8=<X\]Z^^^====<þ7þH><9=Z\<^[[<===9þFH99=<;\Z^_;;===HIIHþ
HH9:9:;>=YZ\<;<=<2343:HGEþHFH999;<=>=:[:<<=7:::9984EIHþHFHH::;<<<=><;8=<<7;;;;:;9963G9GþF8H;<<==>?<;<><8:>==<<;5:HGGþ8F:;<=>>?==;9:??=<;;;9FFþ
H8H:<<==165?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþVVU227;þVVU227þZXVV3þ=<þ\ZXþ=<=þ
UUUþX\þ=þ>>>XWZYYþUUUVþ^[\þ>>>XWZYYþUVVWWXYþ][þ>>>>\þ\þ^þ^_WWXYYYþ^\Zþ===>þ^þXVVWXYY][þ^\Zþ;;==þ]^][þ]þ\^[YXþ;;:þ235;þY^^]]^\[ZYXZþ::þ6235;>>þ]^^\^\ZZZZþ::þ678;=>>>þ	]_\]]\[Z[þ:þ:9;þ>>þ\\]=];[\þ:;þ;7:<þ>þ[[\?][\8I;9;78<<þVV4335;]><91015<[þ[YWVVV==]]<122YY[þX[X?>>>==]7=3XY\9þ\þ
XH9[X;>>>=9??<<Z]IIH\ZYþHH\:9]W=>>>>:??=?Z]:][ZY9þHFH9WY][Y>><>>???5<<;[ZX79IHþHFHH::;WYZ=>??<>=>887<;87879:G9GþF8H;<<W:>?NN99I9I88=<<979HGGþ8F:;<;>>??N89;9985;;;9FFþ
H8H:<<==>?M8899<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;<====<;;::HIIHþ
HH9:9:;<=>MM>=<<<;::::HGþHFH999;<=>>M?NN>=<<<;;;:::IHþHFHH::;<<<=>??NNNNM>=<;;;;:::G9GþF8H;<<==>?NNNONNN>==<<;:HHGGþ8F:;<=>>??NNN???=<;;;9FFþ
H8H:<<==>?M?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHIJJIFHHFHHHþFHIIIJJJ99IIIJIIHHIHþ
II:<=>:;<=<;:98999IHGGHGþHIIJ989:<=>>====::;=II888FIHþHFHHHHIIJJ88<>?>>>;<<>==;:IHHGIGþFIHGHGHIIJ::;<=89:JIHIHGGþHFHHGHHIJKK=8IIHIJHFFþ
HHIIIJK<88IIIHIHHGþGIJI<89IIIHHHIIþHI=9IIGIHIHFþIIIDHHDHþGHHJÿþHHFIþHHI77FGHþFHGH7<;87HHHþHHHH878=;8:798HHþFHGHG79;:>9;8::7HIHþ
HHEHHH7;<=<;9;;87GGHGþHFHHHHF7===>>
98DHGFIHþHFHHHEFIH9>>>Z
::GIHHGIGþFIHGHG9;??	


;7HHGGþHFHHG77;887FFþ
HHFHH8;:7GGHþGFJH8;<;7IIþHGHG8998H8HFþGIHDHHDHþGHHJÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;
===<;;:9HIIHþ
HH9;9:;<>>L
I;HHG:HGþHFH	99;<
>M
I9988GFIHþHFHH8<<
NJ99	GIHHG9GþF8H;<<;??NN>LKJI:HHGGþ8FH9:;<=L?
ML=
JI;<FFþ
H8H=<<=>=<I8HGþGF9:;<=>==<;;<IIþ8GH:	
=<;:H8þGI;::Hþ:<H9ÿþþþ	þþ
þ
þþþþ
HþþHHIH\\HþþFHGHHHH]
H]þHHHHHFHHHF]HHþFHGHGHHHIEHHH^^HHIHþ
HHEHHH9::799HDH\FIHGGHGþHFHHHH8H9:<=:::<
[::HDHGFIHþHFHHHEFI89:9:;<<;<;::HGIHHGIGþFIH9999:><<=>>
===<>:HHHGGþHF9H:;<=<
==<::Fþ
H::=<=??>?>::;þ;<;=>>=?>==<;:þ;:<=>>>?<::þ;<=<<;;Hþ::<=ÿ	þþþ]þ]þþ^þþ^þþþþ
þ]þ^]þþ^^þþ^_þþ
þþþþþ
þþHH_þH::_GHþF::HH^HHHHþHHHH;=;^;::HHHþFH:H=:;<=_<;;:::IHþ
HHE:::;<<===<;=:GHGþH::H::;<<===^]=<<;:9FIHþHFHH::=;<<==??>_=;;9999IGþF:::<<<<=
?>==>>><=<;9þH:;<==???>>>>>==>>><;:þ
:;;<<==>>>===>==<<>;þ:;:;<<<<===>=<<;þH:;<<<<<:;:FþGIH;;HDHþGHHJÿ
þ
GKIHþJKLKLMMMMLþKJJMNMMMKþJJLJMNNNMJ9þJþMIKþ^LKK8þKJþKKþ^_MKþ9þJJMþIKþ___þJLMþIþ___þLþJMþJKKþ^]_þLKþKJMþHþKþ\\LKþLþKþLþ\[
LKMþJJþJLþ\[	L9MþLKMþLKþXX
KMþLþLKþZWKKþLþZKþKþHUWZþHHIXWX[HþFHGHHHZYZHHHþHHHHHFHHZVX[FHHHþFHGHGHHHIEHXXZHHHHIHþ
HHEHHHHHHFHIHD[\[FIHGGHGþHFHHHHFHFIGHHIFH[[[<HHDHGFIHþHFHHHEFIHIHFH:::::<<=:9;HGIHHGGGþFIHGHGFDF::;<;;<<<:;GIGHHHGGþHFHHGH::;<<;<<<<HDHIJHFFþ
HHFH9::;;;;;::9HJHHGþGFJH9:::::9IHHIIþHG9999GHHIHFþGIHDHHDHþGHHJÿþZþZþZYZ\þUþYZþ[XY\þ
WþVþ[[]Yþ[VWX\þ
WWþ\\]]ZþUWY]þ\ZYþ\\\]þY]\\þ\[ZZþ[\\]\[þW\\\\þ\[ZXþ[]\[\þ]þW\\\þ\^^þY[]þVþWZ]\þ]]ZYþ[X[YVþUXZ[þ[YZ]\]þ[Y:XþUXZZþ]ZYYY7þUYUþW[Z]]YXX7þXWWWþ
ZYYXþW[Y]]ZYXþXþZ[[[Y[Yþ[ZY::W[X^[YXþYY\[]]\[[[[þ	ZYY7]W;YþYXY]\\þX::;Z;:;X;YXþYXZ\]]þXXX<=^[;[Z:þY;<<;þXWZYY[]\7[]]<]^>>>þZ\\[[7[]]\]\^]>^\[Z]]\^\\\\\[þZ\[[þXY]]][[[Z]?>?^^^^þ\\^þ^\þ[]\þ[^^[[YZY[]\þ^þ[þ[^Y]\<=[\]]\þY\^^][=>M]_\]\þ\^^<^>>M?]^_[\]þ\<^\=>þNN\N_[\]þ\^\\Z?þONN^]Z\þ[\\\>þ]^]Z\þZZþ	>__^\]þVþ_þ]ÿ
þLLLþLLLþLMþLLþLLLþLLLþLKKKKþMþKLMLLLLþKK¨§MþLMªLþMKKLLþ©¨¨Mþ©©MLLLþMLKLLþ©ªLþ¨©LLþMMLþMLKLþLLLLþ¨ªMþMLLLMþLLþMLLLLLLLþMMMLLLþMLLLMþMþMMþLLL§LLMMMLMMM©LMþMLL§©MMNMþLLMþMLL¨L©MMMLMLþLLLMLþMLLLNMLLLMþMLLLLLþLLMMMKKLLþMMNMMMMNLJJKKLLLþLLMMþMMLLLLLþMNNNþMMLKLMLþMLþLMþMþLMLLLþLNLþMMNLKþMþLLLLLLMMMNMKLLKKþLJKLLMMMKLNLLLLMMMþLLKLMMMþ]LMMMLLLLLþ
LLKþMMþLLLMMMMLKKKLþLLLLþLLLMþMMLLKKLþMMLþ	LKMMþMLLLKLþMþLLMNNNMþMLLKLþLMNONNNþMMLþM]]NNNþMÿþ<\<þ]]þM<<þ^]MþM<;þM]]MMþ<;;þM^]Mþ<<]<þM<<þM^<]Mþ<MMMM<þM<MM<<MþMMþMM^Mþ<MMMMMþMM<;;;]þM^MMM>_M^<<<[MM]<;;þ__>>>_MM]]M]\þ<<þM>>>>MMMM]þ<þ	M<<<<<MM_>>_MþMMM]]]^MMMMM>MþM>>þ;<MMM^^M<Mþ<M><^MMMMMþM>><^]M>MMMþ<M><\<MNNM><þM><N<<MNNN>MþM><<MNþ??þ<<MMÿþHH8Iþ:IIHY[\\þ9IG9::]]^^^]þHHG99;	]^_\^^]þFH99:;<===]^_;_]^
þ
HH9:9:;<=>MM>\__][^^

þHFH999;<=>>M?NN>\<_\]^




þHFHH::;<<<=>??NNNNM[\\]©	
§§§þF8H;<<==>?NNNON£¤¦§©©««
þ8F©§§§¨©©©NNN?^^^\[Y]]^^þ
©8H:<<==>?M[]]]\[^^\þGF9:;<=>Z_<^;]^Iþ8GH:;<\^__^^þGI;;]]\]þ:<^]ÿþ©©©©þ:IIH;HIHþ[]G9:::::9HHþH[\\\^^<<;;::HI9þ]\\\\\\]^=<;;::HIIHþ

]]]]]]]]^=<<<;::::HGþ

£¤]]>>]^O>=<<<;;;:::IHþ§
	¨§¦£=>??NNNM>=<;;;;:::G9Gþ	__^¨¦>?NNNONNN>==<<;:HHGGþ\F\[]^¨¦??NNN???=<;;;9FFþ
]8[\^¨¨=>?M?>=<<:8HGþG[]];^¨¦>><;;:IIþ8GH:;¨©©©:H8þGI;;;:©©þ:<H9ÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;<====<;;:[\]IHþ
HH9:9:;<=YZM>=[\\\]]::HGþHFH999;<=Z[[\N[\]]]^^^;:::IHþHFHH::;£<Z[\\[\[[\\^^^XY\;:::G9GþF8H;<¤=[[\]^^Z^^^^XZ[\;:§§§§þ][^]¥\]^^


^\[[\_;9FFþ
^^¦¦_<		




¦§8[Zþ	
		——



I\þ	¤	££
£	
þ¤¦¦¦¦—
þ¤£¨ÿþ

	þ__^¤^^[_þ^[G9^¦£^\Z\^þ]^]\__^^¥£^\:^^9þ_H_\\]]\\O^¤¢\^^[^^Hþ
^^__]]]]]>M^^¥¤<\\YW::HGþ]^^^]];^^^>M?\^^£¥[<;;;:::IHþ^^^^:]^^<<=>??NN\^£¨^\;;;;:::G9Gþ^^8H;<<==>?NNN^\^£¨^=\<;:HHGGþ8F:;<=>>??NNNZ¥§[\[^;9FFþ
H8H:<<==>?M?¥ZZ[\\HGþGF9:;<=>>><¥;\\þ8GH:;<=<;¥©8þGI;;;::Hþ:<H9ÿþ9þ;8:þ8þ:::9þLþKKþ:þ8LLLK:K6KþM:LþKK:::Kþ6þLþLLþ6L9LMMM:M799798þ	KþM:::99KMK:9989:88OOþ8þKKLM:98:88::88L898KKKOþ98::KK89988988LML<L9LLKKOJþK988:M8L786N:88LLLN:LLKKOþKKK99:88:9887MLKNLL:MKK:MþLKKNK89::8799KMLMNNMML:KLþKKNNMJ:K8989MLLLLNN9INMLKNþKKNKI9NNJ:KLKLLMMNNNIKNMM9KþNKMLLN:::NMKN:LKNKLLIL:NNNKM:þM:LKNLIL:NNNKM::NLNN:::NMKN:KþMNKLLNNNIKNMM9K:LLKKI9NNJ::NKþNNNNLLNN9INMLKNNLLLNNMJ:JKKKNþKOMNNNLMNNMML:KLN:JLNKNMI::JLLþKKMMNNNKNLL:MKK:MKKKKNKI9:LLLNNKNKNKMLLN8LN:LLKKOK::NK9ILM:::KNKM:M:LKNNN9ILLKKOJ:KN:K8KLLLKMLMNMNMNKLLKKKI9:KKKOKNKM:NLKK:MMMNMNNNNNNLLKKNMI::OONMM9KMMMKKNMNNMOMOMNNNNNNMJ:JKKKNMLKNNNMMMMJNMNMMMMMNNKKI9NNJ::NKL:KLMMNNNKIKNOKMKMLNLNN:::NMKN:KKK:MKMKKK:9KNM:L:LKNKLLIL:NNNKM:LKKOKKOKJLNKNKLKLKLLMMNNNIKNMM9KKKOJKOOOKNKMM:LKMLMLLLLNN9INMLKNKKKOKKOJLKNKNLKLMLKMKMLMNNMML:KL:LOOLOJLLNNNMþMLLKMKNKNLL:MKK:MKKNNKNNNKKMþKMLKNLNLN:LLKKOLLLNNN:NNþ
KNLLNLLLLKKOJMNNNN:KþLN:LLKKKKKOKLNLLþLLKKKOOOOLNMþKKKOOMNNþOOMNÿþ9þLþK:þMþNLK::8þLL;K:Lþ::LLþKþM;;::9þKKþ88:K7KMMþ;;8;8LþKþKLKKNKKK9MKMMLMKL898LLKNKKLþLþKKKNNMLKKNK87M<<:::LNK:JMNNLNLþKLKKI9NNNMJ:K8:89L:J:JNN9IKMOLLþKKNN:::KI9NNJ:KL:J:NKMN:::NMMLLKNNKLIL:N:::NMKN:K:MKNNN:LILMKLLKMMNNNNILIL:NNNKM:K9MMNKINNNL:LK:MMLLNN9NNNIKNMM9KNKLMNI9NNLKLK:8NNNLMNNLNN9INMLKNLK:LMMNNMLMMM8NOOLKNLLLMNNMML:KLM:KKM:LLNKNMNNNMMLMNLNKNLL:MKK:MOKKLL:NLLLLNMNMKKKNLL:LLLN:LLKKOJOKKLLI::JLNNMN::LKLN:LLKKLLKKOJOKKKMJ:JKKKNMNNLLKLLMLLKKOOOKKKOOOKI9NNJ::NKKNM:LMMLLLLKKKONOOOOLNN:::NMKN:K:MMNKLLKKMLMNOOM:LKNKLLIL:NNNKM:NMNNNNLLKKKNLL:MLKLLMMNNNIKNMM9KNNOMNNNNNNMLLN:LLKMLLLLNN9INMLKNMOMMMNNKKI9NNLLLKKOJKMLMNNMML:KLMMKMLNLNN:::NMKKKKKONKKNLL:MKK:MMK:LKNKLLIL:NNNKMOOOKNNNLN:LLKKOL:LKLLMMNNNIKNMM9KK9MMNKINLLKKOJKLþMLLLLNN9INMLKNNKLMNI9NNLKKKOþKMLMNNMML:KLLK:LMMNNMLMKOOþKNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKþOOOOÿþKþ8KKKþKþ998:8K:KKK9:þ78877:ML7KþKþ9þ79997:77:79Mþ9þ9þM88MNM97K9:898KKþ9þ7::NNNNN888L7ML9989þ7þ	MN8779MNN9N98:L8MMNM:896þMMNN97N797NM;<877NMLLLK7þMLNLNM887K8;;<LM<699KL98:þLKNKLNLL899:977M<7M76K89LLþKLLMNNNN:K99K8M<<6:898LLLKLþNMLLLLNNN:NN88<K7:97LLNKKLLLþ:JKKKNNKNNNKKM8887LN:JMNNLLNKþKKK:LLLLOJLLNNNML::JNN9IKNMO:þKNLL:LLKKOJLKNK::NKMN:::NMMM8þKLLLLL9KOOOKN:N:MKNNN:LILLMKNþ:KKKKLIKKOKJ:MKK9MMNKINNNKL:Nþ8MMMMK:KMKKKK9MNKLMNI9NNLLKLMþNNMNNKLMMNNNNKLLK:LMMNNMLMMMNþNMNNNLNNNMMMLK:M:KKM:LLNKLMKNþMNMKLLMMMMKKM:KOKKLL:NLNNKL:MþNMMMNNNNLKK:OKKJOKKLLKKKLLKNMþNKMLLN88KLLLJOKOKKKMNKKLLNNNNLþM:LKNNN9ILM:OKKOOJ:JMNNKNNNMOLLþMNKLLKKKI9:LOON::JNNNKKLNNKMNLLLNNNNLLKKNMI::K:NKM:JMNNNKKNMOLLNOMNNNNNNMJ:JK:MK:JNN9IKKNNMMMNMOMMMNNKKI9NNJ:K:NKMN:::NNLNLMKMMMKMLNLNN:::NMK:MKNNN:LILLKNKL:LMK:LKNKLLIL:NNNK9MMNKINNNMMLLKLKL:LKLLMMNNNIKNMNKLMNI9NNLLLLMKLLKLþMLLLLNN9INMLK:LMMNNMLMKLMLLMþKMLMNNMMLM:KKM:LLNKMKLMKþ
KNLL:MKOKKLL:NLNKLNKþLN:LLJOKKLLNL:NLþLLKOKKKLLKLLþKOOKKKKKþOOOOOÿþ:8;7þKN:98<88þMLNNN9<LMLK7þ9<M<NMM<8:MMM8MMþM<M<<LNNLK:99::M<MM9þ
NK9<N97K9NNM<L:9LNK7MMK8þ7::N7779779:MMMM:L<<KMLMLKK7þNL8799NN99:NMLNNMM9:<MLL77MK77OOMNNN97999::<N<MM:<;:KNL:K7K7KKKONMMNKM887<MNNNMMLK:M9:88:9LLKKOJNNNMKKNN898:LMNNMMM:6:89LN:LLKKONKNNMKLNN:99K8=<=::898KNLL:MKK:MMLJKNKK::KLL88;LLL97KMLMNNMML:KLNNMKOOOKKKKNLL88LLMLLLLNN9INMLKNMMKLMMK::KKKMLLLLKLLMMNNNIKNMM9K:NNNKMMKKKNL:LMM:LKNKLLIL:NNNKM::NMKN:KNKKLLKLO:KMLNLNN:::NMKN:KMLLLLNKNNLNLNO:KMMMNNKKI9NNJ::NKLLMKNNNNKNNNNNKKOMNNNNNNMJ:JKKKNKNKLJLLNNN:LLLKNNNNNLLKKNMI::JLLLNLNLNNLN:LLN_:KMNKLLKKKI9:LLLNNMNNK:KNLL::KK:MMM:LKNNN9ILM:::KNNNNNMLMMMMML:KLNNKMLLN88KLLLKMLMNNLLKMNMMKNNLKNNNMMMNNNNLKK:MMMNKLKKKNNNINNNNMNNMNMKLLMMMMKKNMNNLKNNJNMMMNNNLLNNNMNNNLNNNMMMMJNMMLNKIKNMMNKKMMKKNNMNNKLMMNNNKIKNMMNNNKNNNMKKNNLL8MMMMK:KMKKK:9KNMKLLMMNKNNMKLNNN:KKKKLIKKOKJLNKNNNNLNNMLJKNKK:::KLLLLL9KOOOKNKMMMNNKLMNNMKKOOO:KKNLL:LLKKOJLKNKNMMKNNNMMKLLMKK:KKKK:LLLLOJLLNNNMþKKKKKKKLL99NMJ:JKKKNNKNNNKKMþKKKKKKKNNNNNNMLLLLNNN:NNþ
KKKK:M:KMNKLLMNNNN:KþKNL:LMM:LKNKLNLLþLKLO:KMLNLNMþO:KMMMNNþKOMNÿþ9K9þ89þKK899þ::9K9K:KKþ98þKJ:KKþ99KM7698LþJþJKþ:þ9LM97L8M69þIþKJ:::LLK8MM:NNKK88þKþKþKJKþ:L8:MKKNNKK:77Kþ99KþKKKKLKMKNLKK:99NNþKþII9KþLKNMKK::9NMKNþJIþJKKKLþ9:LMLL8NNNNONþJ:I:ONNJ7LLLNN7L7NLLKMNMMþ:J:8JN8JN99KMM8KKLNMKKNNOþ:þMM88NNLL9LM::LKNOLKNLLþKþKJM888LK8NNKN:KMNKL:Mþ:þJK:J8::MLLLMLN:LMM:LKLMþNN9LLLKLK:J:JNNNN:KLKMKMLLLþ:JKLMML88LMM::KNNLLKKMMMMNNþ9J:LKOO88K:N:JJJ:LNMKKKNMNNMþ9þKKMLOI9IK:JK:JL:KKNLKMMKNMNþMM9NO8K9þLL:I:L:L::NNNMKKNNþ::NKJ:MþMMNL:LKL::KNNLKNNþIIN9JMMþNNNMNK:MLLMLNNNMKNþ9L9JþNNNNNN::KKMMMONNNMMþIþ9KNNI9:NIJKKKKKK:KMNKNMþK9J:M:N9L:NN:KL:LKN:LMM:LKLþ9LL:9IKJ::MMKN:MLLKKK:KMKKL:þ9Kþ8LKKM9KMMKKMMNNþ::LMM:LKLþ:L:þMMKNM99þNNNþKKLNNKMLLþIKþK8M8LKþLLþIþLLLKKMMMMMþ:L:þ8LLNþL:KK::þKKþNNþJL:þ:þLL::þL:LþL9þ99þMMþL::þNN:MMKKþ::LKLLLKþLJLNLJ:MLMMKþLLKþMLNKþNN:KNL:NMLKLNNLþNKþLNNJLNLILNLKNþNLþOþMþKLLLþNNLþLþMNNLNLLNNLþNOOKþMLLþLþNMÿþM6þM96D697Mþ7MNKK77MMMM9þ9LLMNNMK96DMMM69þ99L9:KNKKL9999MMM68þ9LLLL:KLKK9L997LMNNLL667þLLLL7KL:LLKKK:9LMMN:9LLLLK9þLKKLþLLN799K9K:9NMªKL:68::K9KþL:INN99KK9LK89MKL:K69L:L88:K8ONNN::N::N9:K:89MM9K9K699:NO9:O:NNNMINNNNKKK::99N99K:KK9KLþNKMKNNNþ::IKKMM:88Mþ9K:K8KN:8OþNNMLLLLNþKKK:MþIþNMþ9KKþK:M:KMNKLLMþNNþ99MMMIL:NNNKMþKKNL:LMM:LKNKLþNKKNM:::NMKN:KNKKLLKLO:KMLNLNþ999þNNI9NNJ::NKNNLNLNO:KMMMNNKþKKLL99NMJ:JKKKNNKNNNNNKKOMNNNNþKKNNNNMI::JLLNNN:LLLKNNNNNLLKþKKMNI9:LLLNNLN:LLN_:KMNKLþKKþNNMM9ILM:::KNLL:þKK:MMM:LKNNþKKLN88KLLLKMLMþMML:KLNNKMLþJ:KNM89LKK:MMMNMþNNLKNNNMMMNNNþ::LK9LNþMKKNMNNþNNMNNMNMKLþMMþMM::KKMMMMMJNMþNNþLLNNNMNNNLNNþL99KþMNNNKIKNMMNKþMMKKNNMNNKLMþI:KKþMKKK:9KNNNMKKNNLþMMMþ	IKKOþJLNþNKNNMKLNNþKKKþ99KOOOKNþMMLJKNKK:þLLLLþL9KKþOJLþNþNNMKþOOþKKNLL:LþLLKþOJþNNNMMKLþMKþ:KKKþLLLþLþK9LþKNNLLLLNNMMKOþMKKþ:Lþ:9LLJLNL:LþMOMNNNNNNNNþ:LþILLþL:OL:þLLNMþLMOLNþMþ	:þKKLLNL:NMNMKKþLLNþKKLNNLMNNNOLKMNþLNþKLLNNNNNLMOLKþNMNNLMLLLþLKþMMMLþMÿþK9þ:K9LLMþM9LLKKþLþMMM6M6K:KKþKKKþM77M769999K:L9:þ8M7MM677LL7:KKLMLLKKþ
MM8MMM69LLLLK9:97:LM9þKþ	NNNK779K97LMLM:7K:KLM8Kþ	MMNKLN8799MLL:LKLLKK9K::KþLLKLK:::97M::LLLL7:M:9þKþMMKKKLMM:L9::LLLKKK:KKNþKþOOLKKLN:KMMKKKKKK:::KMMNþOONMKL:LMM:LKKN:NNNMKKNNKþNNKLL:KLLNKMLLNNLKNNLKNNKMKLþ::MMNLLKLNMMMM:LMLNNNMKNMKMLLþMMNNNNNKMNKMMNKMMMONNNMLLKKLLKþNNNLNNNNNNLLKNMMMKKMNKLNMLLKKþMMMM:KMNKLKMKK:M:KMM:LKLLKKLþNNM:LMNNLKLLLKL:LMMMKKLLKKKKKþMM:KLNKKNNMNNNKK:KMKKþKKKKMNKþMMLKNLLMMMNNMLM:LMM:LþKKMNKþKþMMLKLNMNMNNNNN:KLNNKMLNNþKKNNKþMM:LNMNLKNNONNLLKKNMMMNNKKMþKKþNNKNNNNN:KMMKLNMKKKþKK:þNNNNNNN:LMM:LKKþMMþMþKKþNN:NKL:KLLLKMLLNNNþ:þMKKþLLþMMMMMNLLKLNMMMM:Lþ:MKKKLLþLLþMMMNNNNNKMNKMMNKM:þ:MMKKLLþNNNNLNNNNNNLLKNþM::KKMMMþLþMMMMþNNKLKMKKþMKLKMMþMMMMþNNþLMMKKþMMMLLL:MþKþMMþMMþLKNLþLKKþML:þMMþMþLLNþNLLMKMþLLLLþMMKLþLNNLLþLKþL:þMKþMMNLLþLKþLLLþKKþNþLLþLLþKNMNNMLLþMMNMÿþ9þ999M7þ::69KK7968M6þ978879K7:8888867þ997:77:9K77796M68789þM867K¨¨K7MM8:8988M78776þK876798¦:7:KNM:89MMM779778þKKKLK978M¨LM:MNMM8NKL9989:86OOþKþL989978MLM:LNNN«N9L8L898KKKOþKþK98989:MLLLKNLMLMLKL9LLKKOJþKLKKNKK988:MML756NNNMLLLN:LLKKOþKLNNMJ:KK99:88:9887MLKNLL:MKK:MþKKKI9NNJ:KK89::8799KMLMNNMML:KLþNKN:::NMKN::K8989MLLLLNN9INMLKNKM:LIL:NNNKM:LLKLKLLMMNNNIKNMM9KKMNNNNIKNMM9KLLL:LKNKLLIL:NNNKM:KNNLNN9INMLKN:JLNMLNLNN:::NMKN:K:OMLMNNMML:KLKKKNMMNNKKI9NNJ::NK8MMKNLL:MKK:M::NKMNNNNNNMJ:JKKKNNKMKNLN:LLKKOKN:KNNNLLKKNMI::JLLN:LKNLNLLKKOJNKM:NKLLKKKI9:LLLNNMLKLLMMLLKKKOMM9K:LKNNN9ILM:::KNNMMMLLLLNKKOOMLKNKMLLN88KLLLKMLMNKMLLKMLMNNOOL:KLMMMNNNNLKK:MMMNM:LKNNNKNLL:MKK:MNMKLLMMMMKKNMNNMNKLLKKKILN:LLKKOMNNNLNNNMMMMJNMNNNNLLKKNMILLKKOJNMNNKLMMNNNKIKNOMNNNNNNMJ:JKKKKOMMMMK:KMKKK:9KNMMMNNKKI9NNJ::NOOKKKKLIKKOKJLNKNKMLNLNN:::NMKN:KKLLLLL9KOOOKNKMM:LKNKLLIL:NNNKM:KNLL:LLKKOJLKNKNLKLLMMNNNIKNMM9KKKK:LLLLOJLLNNNMþMLLLLNN9INMLKN:JKKKNNKNNNKKMþKMLMNNMML:KLNMLLLLNNN:NNþ
KNLL:MKK:MKLLMNNNN:KþLN:LLKKOLKNKLNLLþLLKKOJMLNLNMþKKKOMMNNþOOMNÿþ©þ¨þ9þ¨þ¨6:þ8þ:9þ©þ¨87M8þ96897777§¨M788898K7Mþ
K877K6L=<=¨<==ML889:9LþKKKKK8888LLN©<LM86898LLKLþKKKNNN8K97K8N<<7:§9¨LNKKLLLþLþNKMLLN88ILM:7787:::L:JMNNLLLKLþM:LKNNN9ILM:LL:89L:JNN9IKNKKLKLþMNKLLKKKI9:LLLLL:NKMN:::JMNKKLLKNNNNLLKKNMI::JL:MKNNN:JN:JMNNLLKOMNNNNNNMNNN8KKK9MM:NK:JNN9IKLK:MMMNNNKMLLN88ILNKL:M:NKMN:::NK:8KMLNLM:LKNNN9ILLK:K:MKNNN:LILM8N:LKNKMNKLLKKKI9M:KNK9MMNKINNNNNNLKLLMNNNNLLKKNMOKKLNKLMNI9NNLMNMNMMLLOMNNNNNNMJJOKMLK:LMMNNMLNMNMMMNKMMMNNKKI9NOKKOM:KKM:LLNKMNNKMLLNKMLNLNN:::OOKJOKKLL:NLLMKNM:LKNN:LKNKLLIL:NNNOJOKKLLNNKL:MMNKLLKLKLLMMNNNIKNMOOKKKKKKLLKNMNNNNLLKKMLLLLNN9INMLOOMNKKLLNNNNOMNNNNNNMJKMLMNNMML:KLJMNNNNNNMOMMMNNKKI9NNJKNLL:MKK:MN9IKKNNMMMKMLNLNN:::NMKNLN:LLKKO:::NNLNLMK:LKNKLLIL:NNNKM:LLKKOJ:LILLKNKL:LKLLMMNNNIKNMM9KK9KKKOINNNMMLLKLþMLLLLNN9INMLKNNKLMOO9NNLLLLMþKMLMNNMML:KLLK:LMMNNMLMKþ
KNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKÿþ87866KKþ99878M7M7K78þ788777MMMMM86þ79997MMMM7:M8697þM88MNMMMNMM888876897þ
7::NNNNNNMM7MM77897:7þ	MN8779MNNNNNNNM87M89M886þ7þMMNN97N797NN79MMMM777:97K7:þMLNLNM887K87788M666M9788:9LþLKNKLNLL898777879MM76K89LLKLLKþKLLMNNNN:K99K88K96:898LNKKNKKLþNMLLLLNNN:NN88KK7:97L:JM:JMNNLLþ:JKKKNNKNNNKKM8887L:JN:JNN9IKLLþKKK:LLLLOJLLNNNML:NK:NKMN:::NLKþKNLL:LLKKOJLKNKN:MK:MKNNN:LNKKLLKLLLLL9KOOOKNKMMK9MK9MMNK:JMNNLK:KKKKLIKKOKJLNKMNKLNKLM:JNN9IKK:8MMMMK:KMKKK:M:LLK:LK:NKMN:::NM8NNMNNKLMMNNNKMNKM:KM:MKNNN:LILNNNMNNNLNNNMMMMNNNOKKOK9MMNKINNNMNMNMKLLMMMMKKNOMNJOKJNKLMNI9NNLNMNMMMNNNNLKK:MMMMOKKOLK:LMMNNMLMNNKMLLN88KLLLKKMLOONOM:KKM:LLNKKNM:LKNNN9ILM:::LKNKLLOKKLL:NL:L:MMNKLLKKKI9:LLLKLLMMNJOKKLLM9KKNMNNNNLLKKNMI::JLMLLLLOKKKNMLKNNNNOMNNNNNNMJ:JKKKNNKMLOONMML:KLNMOMMMNNKKI9NNJ::NKKN:KNLL:MKK:MMMMKMLNLNN:::NMKN:KK:NKMLN:LLKKOLMK:LKNKLLIL:NNNKM::MKNNN:LLKKOJKL:LKLLMMNNNIKNMM9KK9MMNKINNKKKOLKLþMLLLLNN9INMLKNNKLMNI9NNLLOOMþKMLMNNMML:KLLK:LMMNNMLMKþ
KNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKþOOOOÿþ<7<7þK8:68K:7þ¤ªªML¦££¥<K8þM¨¤ªMM¥£¨§¤¤<<MMþMMM§§ªMM©¥££§©<<<997þMMNN¨¨«N«§¨ª¬¬ª<<M¨£¤98þ7::NNNNN©©ª«§©ª¬¬M<:©¤¤¦LKK7þNL8779NNNN¨¨«ª¨§«¬¬NML¨©©¨MK77OOMNNN977KKNN¨¨©©¨«¬¬NNM©§©L:7KKKONMMNKM887KNNªªª©«¬¬NMª¨©8:LLKKOJNNNMKKNN898N©©«ª«¬¬7Nª8KLN:LLKKONKNNMKLNN:99K88©ª6:898KNLL:MKK:MMLJKNKK::KLL88K¨7:97KMLMNNMML:KLNNMKOOOKKKKNLL8887MLLLLNN9INMLKNMMKLMMK::KKKMLLLLKLLMMNNNIKNMM9K:NNNKMMKKKNL:LMM:LKNKLLIL:NNNKM::NMKN:KNKKLLKLO:KMLNLNN:::NMKN:KMLLLLNKNNLNLNO:KMMMNNKKI9NNJ::NKLLMKNNNNKNNNNNKKOMNNNNNNMJ:JKKKNKNKLJLLNNN:LLLKNNNNNLLKKNMI::JLLLNLNLNNLN:LLN_:KMNKLLKKKI9:LLLNNMNNK:KNLL::KK:MMM:LKNNN9ILM:::KNNNNNMLMMMMML:KLNNKMLLN88KLLLKMLMNNLLKMNMMKNNLKNNNMMMNNNNLKK:MMMNKLKKKNNNINNNNMNNMNMKLLMMMMKKNMNNLKNNJNMMMNNNLLNNNMNNNLNNNMMMMJNMMLNKIKNMMNKKMMKKNNMNNKLMMNNNKIKNMMNNNKNNNMKKNNLL8MMMMK:KMKKK:9KNMKLLMMNKNNMKLNNN:KKKKLIKKOKJLNKNNNNLNNMLJKNKK:::KLLLLL9KOOOKNKMMMNNKLMNNMKKOOO:KKNLL:LLKKOJLKNKNMMKNNNMMKLLMKK:KKKK:LLLLOJLLNNNMþKKKKKKKLL99NMJ:JKKKNNKNNNKKMþKKKKKKKNNNNNNMLLLLNNN:NNþ
KKKK:M:KMNKLLMNNNN:KþKNL:LMM:LKNKLNLLþLKLO:KMLNLNMþO:KMMMNNþKOMNÿþ9þ:Lþ788MMMMMþ68M8NMMMM797þ69M99NMLMM76987þ9þ999KK7M:MK7MMM69þ8767757:668999LMNNKK88þ	877KKLK599668©MMMNNKK:77KþL8KK8L:LM7668þKLªNNLKK:99NNþLLK:::LMMMK665þ7LMKK::9NMKNþ8KKK9NNNK9:KKLþ868MLL8NNNNONþII8:NKI9KKNNL7LLLNN757NLLKMNMMþLLNþ8I8:98LN99KMM8KKLNMKKNNOþ::þK8KLLMM8KNNLL9LM::LKNOLKNLLKKLþ9K9KKLþ9KK888LK8NNKN:KMNKL:Mþ:K::N:JM::8JJMLLLMLN:LMM:LKLMþ:KKKNN9LLLJ9KJ:KKNNNN:KLKMKMLLLKK:K:::KLNMJLLLMMKKKNNLLKKMMMMNNLLþ9LLLLKOO88K:N:KKK:LKMKKKNMNNMþ9LþKKMLLLJ9KL:K::L:KKNLKMMKNMNþMM9NOLK9KLL:LKL:LK:NNNMKKNNþJ:NKKLMþMMNL:LKL::KNNLKNNþJJNKKMMþNNNMNK:MLLMLNNNMKNþLLK9þNNNNNN::KKMMMONNNMMþLLþKKKNN:KMNK:KJJKKK:KMNKNMþ:KM:N:LMNN:KK:LKN:LMM:LKLþLK9LKK:KKLKN:MLLKKK:KMKKL:þ9LKKM:KKLKKMMNNþ::LMM:LKþLþMMKNK:LLþNNNNþKKLNNKMLþ
KMLLKKþLLLKKMMMMþLLNNþKKKþÿÿþ7M§MþM9§M©97Mþ7MNM§MªMMMMMþMMKMNNM§©MNMMM69þ766667NMNMM¨NNMMM686þ
57776KK96NNNMM¨NMNN66667þL7777KKKKM566NNN¨NNN56777K9KþLKKKþLLNN:57577NNMªKL5K:K:K9KKLJJNN99KK9L9K59876N6ªL:LLKKK8ONNN::N::N9:K:9K8K875665ª:NO88O:NNNMJNNNNKKK:KKLNNL8K5L::LþNNMKNNNþ:KKLKMM:KK9MK7LMLLN:8OþNNMLLLLNþKKK:MKK:Nþ:LKLLNK:M:KMNKLLMþNNþ99MMMKK:NNNKMKK:KNL:LMM:LKNKLþNKKNM::LKMKN:KNLMLLKLO:KMLNLNþKKKþNNKKNNKK:NNNNLNLNO:KMMMNNKþKKLL9JNMK:K:MKNNKNNNNNKKOMNNNNþKKNNNNMK:M:LLNNN:LLLKNNNNNLLKþKKMJ9J:MNMNNLN:LLN_:KMNKLþKKþNNMMKNNN::JKNLL:þKK:MMM:LKNNþKKLNIMLNLNMMLMþMML:KLNNKMLþ::KI8LLLKM:JMMNMþNNLKNNNMMMNNNþ:LL8J8NþNKNMNNþNNMNNMNMKLþMMþMMJ:KþMMK9NMþNNþLLNNNMNNNLNNþLK9þNNK9KNMMNKþMMKKNNMNNKLMþ::þ:K9KNNNMKKNNLþMMMþLLNþNNNNMKLNNþKKKþLLNþMMLLKNKK:þLLþNNMKþNNþMMKLþLLþÿÿþ:9:8þ797999N:þ88::7K969:9þ:7::788K999:9:9þ99:77K9778979LMLþK9þ88:97N78K88M7LKKNL:Kþ
88:696NN998KK77:L9MNþKþMM868:658MLL9LM7LLLJ:LLþ	NNNK779997L8LK57KLL:LNMKKNþMMNKLN875979885K:KLLKLLLKKþLLKLK:NM7777957LLKKMLþLLLKþMMKKKLMM:L769LKL7:J:MþKKMþOOLKKLN:KMMK78LKKKJKKNþMMKþOONMKL:LMM:LKKN:J:JKMMNþ	NNKLL:KLLNKMLLNNNNMKKNNKþ::MMNLLKLNMMMM:LKNNLKNNKMKLþMMNNNNNKMNKMMNKMLNNNMKNMKMLLþNNNLNNNNNNLLKNMMMONNNMLLKJLLKþMMMM:KMNKLKMKK:M:KMNKLNMLLKþNNM:LMNNLKLLLKL:LMM:LKLLKJLþMM:KLNKKNNMNNNKK:KJJKþKKJKKþMMLKNLLMMMNNMLM:LMJ:LþKKMNKþMMLKLNMNMNNNNN:KLNNKMLNNþKKNNKþMM:LNMNLKNNONNLLKKNMMMNNKKMþKJJþNNKNNNNN:KMMKLNMKKKþKJ:þNNNNNNN:LMM:LKKþMMþJKþNN:NKL:KLLLKMLLNNNþLLþMMMMMNLLKLNMMMM:LþNJJþJLþMMMNNNNNKMNKMMNKMþNNNNLNNNNNNLLKNþMMMMþNNKLKMKKþMMþNNþMMKKÿþ	¥ ¢¢¢¢¥þ£¤¤£þ¢¢¢¤¤¤¤£¢þª©©«þ¤¤ ¤¦§¦§¤£§þ©©ªªþ¤¤¤£¥§¥¤¤£¡¬þ¨¨ª¬þª£¢££££££¤ª¬þ¨¨¨¬þ©©§¦¥¥¥§¨¨©«¬þ§ª§«þ©¦¦¥¦¦¦§¨ª««¬©«¨«þ©§¦¤¥¤¦¨¨¨ª¬¬ª¬ª¬þ¨¥£«¥¨«§©©¬¬«¬«¬þ©¥£©¦§¬§©ª«¬¬¬¬¬þ©¥¤¨¨§¬¬§ª«¬«¬¬þ©¥¤§¨®®®¨ª«¬­¯«þ¨¦¥¦¨®¬¥¨ª«¬­¯¬þ©§¥¦©®¬¬¨ª«¬­¯þNNNNþª§¥§¨©®¬¤©«¬¬¯þMþNNNNNNN§¥§§¨¬¥¨©ª«¬­NNNNþMþNNJKNNKL©¥¦¦§­¦¨¨ª«JKNNNNþJJKNJKL©§¤¦§ª§¨¨ªJLNNLKþMKJþJJLNNJLK©§¦¥¥©§¨¨JKL¬NKLJMMLJþJKLþNNML©§¦¤¥¨§¨©L««¬NLNNþLKJþLþNNLKNMKJ¥¥¦§¨ª««©¬NNNNNþLþJMLKLJMMLJ¥¦¨¨©««¨ªNNNNNNþMþKMMMLNNªªLKJ¦¦¨©ª­LK­NKJNNþMJKMKJNNN©©ªªL¨¤¥¨ª­KLJNNLJþMþJLMLMLJN©©¨©©ª©¨¤¥¨­LMªGGLKJþJKLMHHLKJ©¨©ª©¨¨¨¤¤¦«¬M«ªJGFLHþHFHHHEF¨L§¨©ªª©©§¥¥¤§«¬ª«ªJJHGIGþFIHG©©¨©©««MLL¨§§¦¤¥¨«®«¬JJGþH©¨©©««MLKKKLL¨¨¦¤¤§KLJIþ
KKKLKKJJKIJMM«ª©§¤¤IþGFJHJJJJIJKKLLLKþHGHGHJJJJIHFþGIHDHHDHþGHHJÿþ£¢¡¡¡¡¢¤¥þ£¢£¤¥¥¤¥£¤¥þ¤¢£¥¦¤¥¥¤¥¥þ©¤¢¢¢¢¢¤¥§©þ©©¨¤¤¥§§¨©ªþ©ª§¤£¤¦¨§ª¬þ©ª§¤£¤¦¨§ª¬þKLMþ¤§¨¤§ª§¤§©ª«ªþKLMþ¦¨©¤©®«¥¨¨«ª§ªþMþKLþNþ¨©¨¦¨«¨¥¨ªª¬§þLþLLNMLLþNN©©§¦£¤¥©©ªª¬§¬þLNNKLJNMLLþNN§¦£¦§¨§¦ªª¬©þNNNLMKNNNKLNN¨¤¢£¤¦¨ª©©¬ªNNþLNþNNMNLLNNLN¨¥££¤¤¦©©¨©¬«NNNþKJLMNKLNMKNNN§¥¢¤¥§§¦§§¨ªþNNNþKJLLLKLKLNLKNN¦££¤¥§¦§§§ªªþNþKLþMKLNNLNMþ¦¥¤£¤¥¥¦§¨ªª¬MKJþLMNMNNNNN§¤¤¤¤¤¤§§¨©ª©¬NMLJþKMMLNMKJNN¥£¥¤¥£¥©¨©ª¬«þNNþKþLNþMNNNMLJ¥£¤¥¦¥¤§¨§«JKMþKLNþLþNþMNNNNNKJ¥¤¦¦¤¥©¨¨JLM¬JLKþNþLNNNNNªªL¥§§¤¤¦©¨JKª«¬KMLMKþLMNþN§¥¨ªªª¨¤¤¦¨¨©L«ª©«¬MNNMLþLþNþ¥¤¦¦¨©­¨¦¦¨©ªªªªª¨©«¬NNNþH¥¥§©¬ª««¥¦§ª«¬¬«ª©§¨©«¬þNNþHH¥¦¦§¬ªML¥¦¨©«¬MLL««©©¨©¬NHþHHHH¨¨©¬LMK¥¨©¬«LKJJKLªªªª¨ª©¬JGþHIHIIJKK§¨§«¬LKJJIIJJKL¬ª¨©HþHHHHG§©«©«LJIIHGHIIJKLLJþ
HHF§§©¬LKKIHHHFHIIIGþGHIIILJFIIHIHHIIþHGHGHIGHHIHHþGIHDHHDHþHHHHÿþIJJJJþJøJJJJùJJþJùJøúJúùJúJúøþJøJJJJJJJùJJJJJJúþJJúJJøúJøJJJJJJIøJJøúþ	JùJùJJJJøJJJJJJùøøJJJJúJøþJJJùJJJJJJJJøJJøúJJøJIøøJJJJJþKJKùJJùJKùJJJJøJJøJJøJJ÷øJJJJJùJJLKKJJùJùKúJJJJJJJJJJJJøJJJJJJøJOJLOJJJKKùKJúJJJJJøJJJJJøJúJJLJOOHLOOOKJKúJJJJøJJJJJøJJúJJùOOLHOLJJLOOJLKKJJJJJJJIJJøJJúJJOOLJJLOOK:OJLOOLJJJJøJJJúJKJJOOLJOL:KOOONMLLMOOLOOJJúJJJJKúOLOOOMLLMNOOOLOMNMOKNLOKOKùùJJOKLJNKOMNMOLOOOOKNNNINNLNMOOOOOOOMNONNINNNKOOJNNJNJOMNNNLLOOLLOOOLLNNNMJLNJNNLNHLKNJMNKKMOLLOOLLOLMKKNMLNKHJNþNNJKNNNMKONLOOOOOOLJNOKMNNNKLNNþLMONKLNMKOJLOOOOLJOOKMNOKNþMLþLNþLJKNKK::LOOLL::KKNKJLþNLþKþKOOOOOJLLJOLOOOOKþKþ	LLLOOOHJJHOOOLþLLþLþOOOJJOOOþLþOLLOÿþIJJJJþJøJJJJùJJþJùJøúJúùJúJúøþJøJJJJJJJùJJJJJJúþJJúJJøúJøJJJJJJIøJJøúþ	JùJùJJJJøJJJJJJùøøJJJJúJøþJJJùJJJJJJJJøJJøúJJøJIøøJJJJJþJKùJJùJKùJJJJøJJøJJøJJ÷øJJJJJùJþJKKJJùJùKúJJJJJJJJJJJJøJJJJJJøMJOJMJJJKKùKJúJJJJJøJJJJJøJúJJOMJOOHMOOKJKúJJJJøJJJJJøJJúJJùOOOMHOK:JMOOJKKJJJJJJJIJJøJJúJMJOOMJ:KNMLMMJMOOJJJJøJJJúJKJJMOOMJMMLMNLOMNMMKNOMKJJúJJJJKúOKMONKMMNMOLOKNNNINNONMOOKùùJJOOOMNONNINNNKONJNJMMNNNLLOOOOOOOOOOLLNNNMMJNJNJOKNMMNKKMJMOOOMMOOOMJMKK:KMNKOJNJKNNNMKONOMOMMOOMMOMOMOL:KNNKJNLMMNKONMKOOJMOOOKOONKOMNLMNKNMMLLK:MLJKNKK::JMOOKNMNKIMNMKLLMJNLKNMLMMKOOOOJJMMOMNNNNINNNKN:KOOKHLOMNMLKNOMKMOJMLLNNNMONMJLMNOMHOJKNNNINNONMOOHJJMKKNNKNMNMNLOJONNJNHK:NNNLLOOOJJNMNMNNINNNKOMOONOJKNNMLKMMOOOO::KLLNNNMOMNJNNOONNMKNLNMNMNKNOO::KKMKKNMJNKOHNJHþLMMNKKNNNINNONMOOONKKMNNNKJNNþLNþNNJNNKMNNNLLMMOLKMNOKNMMLþKþNþOKNOMNKKMOO::KKNKJLOþNLþNNþKNNNMKJNOOMOOOJKOþKþLMLNKGNMKJMMJOOMLLþLNþLJKNKK::OOOþLþKþKþOOOOOÿþIJJJJþJøJJJJùJJþJùJøúJúùJúJúøþJøJJJJJJJùJJJJJJúþJJúJJøúJøJJJJJJIøJJøúþ	JùJùJJJJøJJJJJJùøøJJJJúJøþJJJùJJJJJJJJøJJøúJJøJIøøJJJJJþJKùJJùJKùJJJJøJJøJJøJJ÷øJJJJJùJOJKKJJùJùKúJJJJJJJJJJJJøJJJJJJøLJOJLJJJKKùKJúJJJJJøJJJJJøJúJJOLJOOHLOOKJKúJJJJøJJJJJøJJúJJùOOOLHOLJJLOOJKKJJJJJJJIJJøJJúJLJOOLNJMOOHLOJLOOJJJJøJJJúJKJJLLOLOLLNONLOMJLLOOOLOJJúJJJJKúOOLNO:OOJOOOMNMOKN:OKJLOOKùùJJOOOLMMMOOONKOONNNINNMNMMLOOOOOKOONKLMNNLLONNOLNOOMNNNLLMJKNOOKMNONNINNOKLNOOOLKNHMNKKMNNINNLNMLLNNNMNNNLNOKLOLKNNNMKJNHOMNNNLLOMKKNM;;LLOLKMNOONKLNMKKNJMNKKMOONLKMNNOOONLLJNOLOLJKNKK::NMKLNOOLKMNJKNNMMMJNNLHLOOKLOOOKLNMKJ::KKNKJLNONLMMLLHOJOOLLNOOLJKNKK:OOO:KKNKJLKJNLJOOOLOLK:OOOLKOOOOJOOLLOOKOOLHOKOOOOJOONMLOMLLLOOLLOOOLLLLOLHOOJOOK:LHOLLMNMJKNOOKOOOM<JLLJLJOHLJHNMLLMLKNNNINNONMOOOOONOOLOLJLOLLLOMNMNKNOOKNNNLLLLONJOOOOMOLOMOLOKNNNINNNNMNKKMOOOLLMOOOKOOOOOOONJNONMNNNLLMKJNOOLOOLOOOO:KONNOOOOKNOMNKKMGNMKJLLJOOLMMOLMNMOOOONOKNNNMKONJKNKK:KOONKMMNMOLLOOOOLMONKKNMKOJKOOOOMNONNINNNKOMLOþLNþLJKNKK::LLJOLLNNNMONNJNNM<<þKþKLOOOLOOLJJMKKNMONKMþNOOþLLOJLOOOJLLNOKMNNNKNNNþ
LþOOOOGLLGKMNOKNþMLþOOO::KKNKJLþNLþJOOOþKþKÿþHþFþHþGþFþGþGþIþIþIþHþHþJHþGþHþHGHþHþIHþGþIIþHþIHþIIHHJKJþGIþIþIHþJHþHJþHJJKKIKJKJHIJþHHHþGþIþIKIIKKKJHKKHJKJKGGILHþGþIGþGKKJLLKKLKILGLGKJKIJJLþGþJJþJHKKGLGHLLILLLLKKLHJJLþHþJþJIJHKGKHIHKLHHLKLJKMKGKLLHIþLIþKJJGKJKJHLLHJLJKLJMMHHKLJILIJGJKJKGKGHKLLLHJGLKMJMMJHKMLILLJGLJLIIJKKGJLGLKLHKMHIMKJHLJJHLIJøJOJLOKHIMLHJLLHGMKIKMJHJMLHIJJLJOOHLOOOHLLILJLHMMIKMJGJKMHJùOOLHOLJJLOOJLJLJLIHMJKLMJJGMLJJOOLJJLOOK:OJLOOLJLHMJKLLMKIKJOOLJOL:KOOONMLLMOOLOOGJILHHLGúOLOOOMLLMNOOOLOMNMOKNLOKOJLKHJOKLJNKOMNMOLOOOOKNNNINNLNMOOOOOOOMNONNINNNKOOJNNJNJOMNNNLLOOLLOOOLLNNNMJLNJNNLNHLKNJMNKKMOLLOOLLOLMKKNMLNKHJNþNNJKNNNMKONLOOOOOOLJNOKMNNNKLNNþLMONKLNMKOJLOOOOLJOOKMNOKNþMLþLNþLJKNKK::LOOLL::KKNKJLþNLþKþKOOOOOJLLJOLOOOOKþKþ	LLLOOOHJJHOOOLþLLþLþOOOJJOOOþLþOLLOÿþHþFþHþGþFþGþGþIþIþIþHþHþJHþGþHþHGHþHþIHþGþIIþHþIHþIIHHJKJþGIþIþIHþJHþHJþHJJKKIKJKþHIJþHHHþGþIþIKIIKKKJHKKHJKJKGGILHþGþIGþGKKJLLKKLKILGLGKJKIJJLþGþJJþJHKKGLGHLLILLLLKKLHJJLþHþJþJIJHKGKHIHKLHHLKLJKMKGKLLHIþLIþJKJJGKJKJHLLHJLJKLJMMHHKLJILIJGJKJKGKGHKLLLHJGLKMJMMJHKMLILLJGLJKIIJKKGJLGLKLHKMHIMKJHLJJHLIJMJOJMJKHIMLHJLLHGMKIKMJHJMLHIJOMJOOHMOOKHLLILJLHMMIKMJGJKMHJOOOMHOK:JMOOJKJLJLIHMJKLMJJGMLMJOOMJ:KNMLMMJMOOJJLHMJKLLMKIKMOOMJMMLMNLOMNMMKNOMKJGJILHHLGOKMONKMMNMOLOKNNNINNONMOOKJLKHOOOMNONNINNNKONJNJMMNNNLLOOOOOOOOOOLLNNNMMJNJNJOKNMMNKKMJMOOOMMOOOMJMKK:KMNKOJNJKNNNMKONOMOMMOOMMOMOMOL:KNNKJNLMMNKONMKOOJMOOOKOONKOMNLMNKNMMLLK:MLJKNKK::JMOOKNMNKIMNMKLLMJNLKNMLMMKOOOOJJMMOMNNNNINNNKN:KOOKHLOMNMLKNOMKMOJMLLNNNMONMJLMNOMHOJKNNNINNONMOOHJJMKKNNKNMNMNLOJONNJNHK:NNNLLOOOJJNMNMNNINNNKOMOONOJKNNMLKMMOOOO::KLLNNNMOMNJNNOONNMKNLNMNMNKNOO::KKMKKNMJNKOHNJHþLMMNKKNNNINNONMOOONKKMNNNKJNNþLNþNNJNNKMNNNLLMMOLKMNOKNMMLþKþNþOKNOMNKKMOO::KKNKJLOþNLþNNþKNNNMKJNOOMOOOJKOþKþLMLNKGNMKJMMJOOMLLþLNþLJKNKK::OOOþLþKþKþOOOOOÿ þGþHGHþIHþIIHHJKJþGþHJþHJJKKIKJKþHIJþHþ
IþIKIIKKKJHKKHJKJKGGIþHþGþIGþGKKJLLKKLKILGLGKJKIJJLþGþJJþJHKKGLGHLLILLLLKKLHJJLþHþJþJIJHKGKHIHKLHHLKLJKMKGKLLHIþLIþJKJJGKJKJHLLHJLJKLJMMHHKLJILIJGJKJKGKGHKLLLHJGLKMJMMJHKMLILLJGLJKIIJKKGJLGLKLHKMHIMKJHLJJHLIJLJOJLJKHIMLHJLLHGMKIKMJHJMLHIJOLJOOHLOOKHLLILJLHMMIKMJGJKMHJOOOLHOLJJLOOJKJLJLIHMJKLMJJGMLLJOOLNJMOOHLOJLOOJJLHMJKLLMKIKLLOLOLLNONLOMJLLOOOLOJGJILHHLGOOLNO:OOJOOOMNMOKN:OKJLOOKJLKHOOOLMMMOOONKOONNNINNMNMMLOOOOOKOONKLMNNLLONNOLNOOMNNNLLMJKNOOKMNONNINNOKLNOOOLKNHMNKKMNNINNLNMLLNNNMNNNLNOKLOLKNNNMKJNHOMNNNLLOMKKNM;;LLOLKMNOONKLNMKKNJMNKKMOONLKMNNOOONLLJNOLOLJKNKK::NMKLNOOLKMNJKNNMMMJNNLHLOOKLOOOKLNMKJ::KKNKJLNONLMMLLHOJOOLLNOOLJKNKK:OOO:KKNKJLKJNLJOOOLOLK:OOOLKOOOOJOOLLOOKOOLHOKOOOOJOONMLOMLLLOOLLOOOLLLLOLHOOJOOK:LHOLLMNMJKNOOKOOOM<JLLJLJOHLJHNMLLMLKNNNINNONMOOOOONOOLOLJLOLLLOMNMNKNOOKNNNLLLLONJOOOOMOLOMOLOKNNNINNNNMNKKMOOOLLMOOOKOOOOOOONJNONMNNNLLMKJNOOLOOLOOOO:KONNOOOOKNOMNKKMGNMKJLLJOOLMMOLMNMOOOONOKNNNMKONJKNKK:KOONKMMNMOLLOOOOLMONKKNMKOJKOOOOMNONNINNNKOMLOþLNþLJKNKK::LLJOLLNNNMONNJNNM<<þKþKLOOOLOOLJJMKKNMONKMþNOOþLLOJLOOOJLLNOKMNNNKNNNþ
LþOOOOGLLGKMNOKNþMLþOOO::KKNKJLþNLþJOOOþKþKÿ ÿ ÿ ÿ ÿ