þHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHHIEHHHJHHHHIHþ
HHEHHHHHHFHIHDHGHFIHGGHGþHFHHHHFHFIGHHIFHHHHHHHDHGFIHþHFHHHEFIHIHFHEHHHFHIGHFHHGIHHGIGþFIHGHGFDFHJFIHHIHHHIGIGHHHGGþHFHHGHGGHGFJGHGGHDHIJHFFþ
HHFHHHIHHGHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþFþDþFþEþDþEþEþGþGþGþFþFþHFþEþFþFEFþFþGFþEþGGþFþGFþGGFFHIHþEGþGþGFþHFþFHþFHHIIGIHIþFGHþFFFþEþGþGIGGIIIHFIIFHIHIEEGJFþEþGEþEIIHJJIIJIGJEJEIHIGHHJþEþHHþHFIIEJEFJJGJJJJIIJFHHJþFþHþHGHFIEIFGFIJFFJIJHIKIEIJJFGþJGþIHHEIHIHFJJFHJHIJHKKFFIJHGJGHEHIHIEIEFIJJJFHEJIKHKKHFIKJGJJHEJþGGHIIEHJEJIJFIKFGKIHFJHHFJGHþIFGKJFHJJFEKIGIKHFHKJFGHþ
FJJGJHJFKKGIKHEHIKFHþHJHJGFKHIJKHHEKJþHJFKHIJJKIGIþEHGJFFJEþHJIFÿþ=8;:8þ48::88=þ4888;:;9::K;N;þ898899;9;<M;;;;Lþ:::;9:=K==;K:=Mþ69=;K©::<LKL=LOMMHþ8L;;;<©§===;=ONL<HIHþ
HHE;9=9K;MN:=NNOMMIHGGHGþHFHHHHL=<MMMNNFNONLHHHHHGFIHþHFHHHEFIHOLMM¦©OOOO¨IHFHHGIHHGIGþFIHGHGFGFHII¥«H¨«JJIGIGHHHGGþHFHHGHGGHJJ¨«JJIHHHHHHFFþ
HHFHHHIK©«LKJIIIHHHGþGFGHJJKLLLKJHHIIþHGHGHJJIIIHFþGIHGHHHHþGHHHÿþ775þ357þ7577 þ7777777þ346þ75899777787þ7þ6686:þ;;98797:þ:97þ
7þ7688586:====;;;:::þ9þ9þ5þ;:98;;=££=þ==;::::þ;;9þ565566þ==;;þ7þ:££þ:KKþL;<<þ656666þ=¥=;88þ£þ=;=;=KL;;;þ566766¥<;988877;;:;9<K=þ<=þ5þ7þ77688£<<:89:779;;=KKK==:þNþ797:987668::99998;;;=KLLMK==:þ79;þ=þ;99989999;;=8;;=KMLKþKKþ<<þ=;:99::;;=M=ø<KLMLþ5554þK<<<<<;=;99=KKMMþ556765þ;LMLLK==89<<<<KMþMMþ5778896;LL<;==<¤:7<<9;KMþMMKþ9::::8867:::;;;<:<;=KKMLLMMNþ;;<<;þ;:;<==ü<K<KK=K¥<<üLþ<N:þ<==<þ==<==<©þKL9<¨;:<©LL==Mþ===KK<=©þ:::;=<¥:::KLL<þ;;þL=þK©þ§;§;9;9=<<KL<<þLK;þ
©§©þ¨9;<;<<<<KMþM9MLþ¥©H£==;==;=<=K;LþLLþ4888;þH¥¥8=LLKLL===;:LþKþ898899;HG¥©¤KLML§LL==<;=þ	:::;9:H¥§©¢HFHL©HH=K===<;<þ69=;K©>G¥§HI¤H=:<©¨KLLL=<MLMþ8L;;>>HH¥HFH9::;<L©MMMLLLMNMþHF;>=>???>G99::<==LLMMMNMNINþHFHHHL=>?>>>HE:©<KLLLLMMHGIHHGINþFIHGO???¥¨HFI§¥LLMMMMIGHHHGGþHFHHGHG¨HGF¦©HJMMJHIIHFFþ
HHFHH¥¨H¤¦§KKJIIIHHGþGFHH¥¨¥¨KKKJJIIIþHGH¥§©KJJJHFþGIKKKKIHþGIIHÿþ
;;þ:KKþLþ9;=;8;þ;=;=KLþ7þ9<;9þ;;þ;9<K=þ<þ7768þ£þ<:;þ:;7þ;þKKK==:þNþ97:987668::99;;8;;;=KLLMK==:þ9;þ=þ;9998999;;<<<;;=K775þ357þ<<þ=;:99:;<==M=7577 L77777þ55þ5þK<<<<<346975899877787þ556765þ;LMLLK3366869<;;:97þ7þ55778896;LL9;768858::====;;;:þ789::::8865:::;:98;;=þ£=M==;::þ8:;;<<;:575566ü==;;K7þ:þL:KK:þ<==<þK978666£=¥=;88;:£þL=;=;þ===K><=798766¥<;988877;;:;9þ::;œ=¥;:9989999;;=8;;=KMþ<<þ<:99::;;=M=ø<KLMþ555þ=;<<<<;=;99=KKMMþ3888865þ;LMLLK==89<<<<KMþ88998::896;LL::;=<¤:7<<9;Kþ56889999::K;N;86789<<<<<:<;=KKþ9:989:;9;<M====L:;<==ü>=<KK=Kþ;::;;<=K===K==M==<>þ£þ>L9þ==;K©;KKL=LLL=6;:8§¤þ::=6;þL;;;<©>NN=>N68=8;:8§£9;89::88=þ;<=<=>>N4568;88::998888:;;9::K;þL=>MMM:;9888;:;9:;:98:;;9;<M;;þOLMM:<;;9899;9;<M;:::;<=K==;þHFHH;==;::;9<=K9==;K©:KKLKLLþHFHHHE;;==;K©:KKL8L;;;<©§NN==NIGþFIHGH9L;;;<©§NN=;9=9K;MN=MGGþHFHH;:=9K;MN=MNL=<MMMNNFþ
HHFL=<MMMNNNNOOLMMLGþGFOLMM¦©OOOO¨KJIþHGJJH¥«L¨«JJþGI©«¨KJHþG©«JÿþMMMþMþMMMþMþMMMMþMMþMMþJMKþMMJMMMLþJKLLMLþFIJþHJþJJMLJKJþMKMMMþGIKLGIJIKLMMKLKþMMLMMþ	HJKþMHJKKþMKþMMLKJIMMMþMþIþMMHIJþLþIJMþLLþLKJþMMMMJMMMIJKLMMJIþKLKIþ
MMMMMMþMIJKLHJLKJHMLKJIþMþGIKIJKKMMHJLMLHKJþLKJIMMþHJLIIKJKM^IKMMMJLKMMMLMMþMþMGJKFJMLLLKMJMLMMKLLMMþMMþMMMHMFJþKMILMIKLMMLþLMMLKIþMþMMMMMMKJKKþGKKMMKLLþJKþLJIþHIKMIJJLJKMHLMM]KLLIKJMþKJþHIKLJMJKMKMMJMMIKL]LJLMMMMLJþGJKþMMMMMMMMJMMLMM]\MLLLMMMþLþIþMMMMIJLMILMLJI\MMLKIþMMþMMMþGIKLIKJMJKJMIKMLJIþMþMþIIKMMJLMHKMLIKIMMKJIþ	MþIþMMKMMMLMMKLKMMMLIþMMMMMM]M_MKLMMMMþLþHMMHHMM[]_MMMMMMþFHGMGHHMY]^HHMMHHHMHþ
HHEHHHHHY^]^HIHGMFIHGGHGþHFHHHIJJZ]_H]_^\HHHHHHIHGFIHþHFHHHEFIIJJJH]_JL^[JIIHHHGIHHGIGþFIHGHGHIIJJ__IJJJJIIIIGHHHGGþHFHHGIGIJJKJIIIIIIHIHHFFþ
HHFHHHIJJKJIHHHIIHHGþGFHHGIIJJIIIHHIIþHGHGHHGHHIHFþGIHHHHHHþGHHHÿþKþJLþJKþLJþIKLLIKJþKJþJKLKKJLKþMLJKJþIIJLLJMLLLLLþJKLLJHþIJKLMIKJMMLJLIKJ^^KJþIJJKþIJLKIMMLJJL^]þMLJþ
KKþMJLMLKMMLHLL^þLþMMMKMLMMMMMKJ_]MþMþMMMMMIJL]JKMLJ_MMMþIJLþ	MMMMMIKLLIKJMMKJMMMIKLLþ	MMþIJKMMJLK_M]LJþIJKMþ	MþKMMMMLLL^__^LMKMMMMMþ
MMMMMMMMLKKJ^MMMKKJJMMMþMMMMMIJLMMMMLJHLJKKLKKJMMþMþMMIKLLIMMIKKJIKJJþKLJþHJKMHJKKMKMLJLKKþMMKJþIJLþJKMLJLLLKLKKJMLLþLLþIKLLHKMMJLMMJMMLKKJMMMþ	IJKþJLMIKMMIKJJMLLJMMMMþKþMMLMIJLMIJMLKKMLKJþMMþ
MMMMMKMMIKMMMLJMMLLþMþMMMKKJMMIJLMMMLKMMMLJþ
MþJKþLKMMKþMM_MMLMIJLLJKþ	HKJþKJMMMMM_MMMMKLLIMMMþJLKMþMLMMMMMM_MFJMMMJLMMMþKLLþMMMLLKJMM^MKMHMMLLMMMþLIMMMJKMMLJ^MHMMMFHMLþMMþIKMMHKKMMMK_^HMMMHHHHIHMþIJMMEMLMMHML_IHHMMMFIMGGHGþKFMMHLMMFI]^]IFHHHMHHHHHGFIHþHFHHMMFIMLHF\^_JHFHIGMFHHGIHHGIGþFMMGHMFHFH]]^_JIHHHIGIGHHHGGþHFHHGIJJ[]]^]JIIIIHHHHFFþ
HHIJK]_KKK]__^JJIHHGþG^_KJIJJKK]KKJJIþHGHIJJJIHIHFþGIHIIIHHþGHHHÿþKKJþIJLþJKþLJJþLLMMLþIKLLIKJþKJþMþMMMMIJKþJLKþMLJþMMKKJJþLLLþLþIJLLJKMLJJJþLþIKLLIKJJMKJLLJþLMþIJKKþJLKKMMMMLJJMMLþ
LLMKKþLLLLIKJMMKJMMMLþLMMMMMþLMJLLMJLKMMMLJþMLþMMMþMMMMMMKKJMLLLNMMMLKKJþMþIJLMJKþLJJ\LIJLMJKþLJJþ	IKLMMKJþKJMIKLLIKJþKJþIJKþJMM^þMMJJK__JLKMMþLJþKþKKLJLMNN_^MM]^MMLMMMMLMLþLMLMJKMLMKJMMNN\]^_MMLMMLMMMMMLþLMLIKMMMMMLJMNN]__MLMMMMMMMþLMMþMJMMMMMNMMNKK__MMMMMMKKJLNþKJþLMMMMMMIJLMJKMLJJIJLMJKMLJJLþMLþMMJMKMKLLIKMMMKIKLLIKJMNKJMNMþLLMJKJKJLMMMLJKMMJMK^MMLMMMþIMMLIKJMMKJKMM__MM\^MMMMMKKþIMMþJLMMGMMMKM_KJ__IJLMJKMLJþKþLMMMMHJMMJK_LJJHKLLIKJMMKþLMMMMHKLLEMJ__KHJKMMJLKMMMþHHMMMHHJKFHJLK^_MKJMMMLLLþMþHFHLMHFHKIGHLMML^__MLMMLGLIHþHFHHHEFIHIHFHLMMM^^_GHFMMMLHHGIGþFIHGHGFHFHIMMMH\]^HIGIGMMLGGþHFHHGHGGHHHH[]^KHHHIHHFLþ
HHFHHIIIJJZ^_JKHIHHGþGFHHJJJY\]_^^KIIþHGHGY[^JJ]_]þGIHIIHHHþGHHHÿþJþJHJþJJþJIJþKIJþJJJþKJIJKþJIJþKIJKþKKJJþJHKþKIJKLþKþKJJIIKþKJKLJJKþLLþJHIKþKKLJKLþJI…HIIJþJHKþKLKKLJIGHIJJKJKþJKLKL‰MIHHJKKþKJþJLL‰‰LIKþKþ	LK…JKKþJMM‹MLþLKKLLKJIJ‰KMLKKþLLLþHH‰‹LJ‰LKþLþFHGHK‹MM‰‹LKþHHHHHKKMLMK‹MKJJþFHGHGHKJLLMKKKLLKJKHþ
HHEHHHHIJLLLKJJJJLLKJGHGþHFHHHHFHFKKLLJJKKJJIJLKJGFIHþHFHHHEFIHIHLLLJIJJJJIJIJLLJHHGIGþFIHGHGFGFJJJHHIJJJJJIIGJLHGGþHFHHGHGGHGFHIIIIIIHIGHFFþ
HHFHHHIHHGHFHHFHGHHGþGFGHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGHHGHþGHHGÿþJJKþIJLKKþHJKLKJKGþGKKJKLKJJIHGþKLKLIIKKKLLKLIHHHHJKþ
IJJJJKLHHŠ‡Š‰ŠKIIJJKKKþKLLKKLLL†Šš•œ›ŒMKLLLLLKþLKKKL‡‹LL‡ŒŠš›ŽŽŠMJJGGHKKKþHHJLKJJJKKM†‡ˆ‰ˆMLLKKKJLLHHGþHJMLLLLLLJKKJKMLMMLIHGþIJLLKLIHKLMMMMLLKIIIIIIIþ
HHGHGKKKKLJJJKLIHIGHþFHHHLJ‡KKLLIHGHþHHGJJLJLLJHHþHGLMLLJIþHGHHÿþJJJþIJKKKJþHJKJþKþKKJþHIKJþ
LJþJJKKJþHþHIJþ
LLKJIHHJLJþHFJIþJJJJJþJJIIJKLKþHGHIIþIIJIKJJþJJIJJKLKþGHIJþJJJKKþKJKþ	KKJKLþHþHJþKKKJKþLKJþKJIIIþJKKLþJJHJþKJJKKþKþIJJKLKJIIþIJKLJJJJKLKKLþILLLKKKKKJIKŠ‹KLJJJJKKKþ
LKþLKK‰†‹KJ‹‰‹IJKKJþKLŒL‡‹LKþLKLKJKþLLKŒŽMM‰†‰LKJHGHHIJþJKJKJKLKKKLLKKM‹‹JIHIIKJIJJþKKþHþHKKJLL‹‰‹KKM‹‰‹JIIJKKLJKKKþKþIJLKˆ‹LMKLKJJKKþJþ
L‰†‰LKK‹‹JKJKIJþJJL‹‹LL‰†‹‹KKþKþKþ	JJJJKLL‹‰‹LKMMŠLLKþ
JIIJKKKLþKKLMMLKJþ
IJJKKLþJJJLKLMLLJIIIJþJJKKJþIHJGKLMMLLMKJJHIIJþKJþJJHJGJLMLJJKLMMLKIHIJþ	FHGHJGJLLKKKJHHJJKLüIHKJþHHEHHHHJKLLKKJIGHFIHHJLIJKJþHFHHHHFJJJLLKJIIHHHHHHHHHKLJKJHFHHHEFIHKKKLKJJIGHIGHFHHGIHJKKKþFIHGHGFI…KIHIIHIHHHIGIGHHHGIþHFHHGHGGHGFHGHGGHHHIHHFFþ
HHFHHHIHHGHFHHFHIHHGþGFHHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHHHHIHþGHHHÿþ4238;þ237þ>=þ3023þ427:þ>2456þ;<;þ53þ25:Iþ=>>3579þ
:<þ88HH5:IFG;<>þ255þ
>þ8:8H7;HH:<>H37þ2þHHH8<=;:H9:<89;>>þFHGHGH8>==H8<7;HHHI>þ
HHEHHHH0124;>1235FIHGGHGþHFHHHHFH1438>?K=3257HHFHGFIHþHFHHHEFIH2256=>???=5457HHGIHHGIGþFIHGHGF5268=L>??K=947:GHHHGGþHFHHG>7:JKLJJKLLK=:=GHFFþ
HHFHJKLKJGHFJJLLLJHGþGFJKKJHFIIHIHHIIþHGHGHIGHHIHFþGIGGHHFHþGHHFÿþ421346þ8986467þ	2þ;997479þ67þ;9747:þ62:þ;9747<þ6279þ>;74:þ621:9þ>:69þ62379:þ86422þ	2466þ>=996421:9;þ;;<6533þ2356789>=;:62389:;;<<<<764þ26:=>>><8=<5422::;====<þ7þ><9=7337;;<===þHHH=<;842<;;===HþFHGHGH>=957<;<=<2343þ
HHEHHHHHH=:6:<<=7:::9984EþHFHHHHFHFIG<;8=<<7;;;;:;9963þHFHHHEFIHIIIJ<;<><8:GHFHHG5:HGIGþFIHGHHIJJKKK==;9:JJJHHGHHHGGþHFHHGHIJKKH165JKKJIIIHFFþ
HHFHHJKKKKKJKKKJIHHGþGFFHGIKKKIIIHHIIþHGHGHIIHHIHFþGIHFHHGHþGHHFÿþ103þ01222þ12366þ0þ347þ01þ287:þ0þ13586:þ01þ399::þ012þ9þ1238;::þ237987þ37987þ49987þ9987þ32þ444322þ:98þ94þ544þ44666422þ98þ948þ7:;;<:9878951þ9þ9679<;;9:98þ;94þ978:<<=;:þ	;<þ98:<:9þ;þ
9;<<;þHHFIþ<>>>þHHIHIFGHþ<;:9886545555789:;<Hþ?><<:::;::;9888::;F::Hþ
=?>?><9:98H87E789:H::;IHþ
HHEH7887H75I6778H78:;GHGþHFHHIIIIIIIIIIIIHHHHHHFHGFIHþJJJJJJJJJJJIIIIIIHHHGHFHHGIHHGIGþFJJJJJIIIIHHIHHIHHHIGIGHHHGGþHFHHGHGGHGFGGHGGHFHIFHFFþ
HHFHHHIHHGHFHHFHFHHGþGFGHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGHHFHþGHHGÿþ:==þ79<=<=þ899:<9þ86:;<;<þ889:<9þ66::;9:þHH6589;<;þ5689:8þHHIHI67<::<;þ45789FHGHHHHH7H:9:<=þ34677HHHFHHHFHH879;;þ23466GHHHIIIHHH76H9;=þ
HH235HHHIIIJJIHGH5I8:;HGþHFHH224HHIIJJJHIJIIHH68;=FIHþHFHHHEF1HIIJJJJHHHIJIIF57:;HHGIGþFIHGHGHIJIJIIHHIHIIIGI69;HGGþHFHHIIIIIHIIHHGGIJJI58FFþ
HHIIIHIHHGHFHHFHIHH7þGFHHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHHHHHHþGHHIÿþHHFIþHHIHI45679<<=þFHGHHH47897:;=;þHHHHHFHHHF9;78:;7<?>þ
FHGHGHHHI2686G57=89?>=þHHEHHHHHHF36:52GHF87<>=>þHFHHHHFHFIG484F3HHHHHIJJGFIHþHFHHHEFIHIHFH843HFHIGIJJIGIHHGIGþFIHGHGFHFH493HHIHIJJIIGHHHGGþHFHHGHGG43FGGHJJIIHIHHFFþ
HHFHHH6HHIJJIHFHHHHGþGFHHGIIIIIHIHHIIþHGHGIIGHHIHFþGIHHHHHHþGHHHÿþ1þ142þ22þ
13755þ5432þ24873þ05542þ15996þ23665þ134::9þ57896þ3þ234:74þ9þ6þ1235þ234687þ2þ0139==þ23598þ6þ2247;:þ2468þ73þ457;;þ0þ244896þ123;::I1þ245:8þ123;;:12Hþ595H12;:=23HHHþ36788H1392=38HFHHHþF367::34:348:HHHHHIHþ
HHEH267:55:48;:GHFIHGGHGþHFHHHHF969:7;8;98HHHHHHHGFIHþHFHH7:9:;I;:;;<;98HIGHFHHGIHHGIGþFIHG;<<=FH;;=;:IHHHIGIGHHHGGþHFHIJ<7=>><<IJJIIHHIHHFFþ
HHF8=??=<===JJJJIHHGþGFIH?G;;==JJIHIIþHG>G::;=JIIFþGI99:HIHþGHHIÿþKH43þJþKHGFHHG3þIILþMLMLMLKLþFGHJHEþFILMþ3D3þLJþKþKLMLLLþGIKJþLLþ3EFHJ6þLKþ7þIþILþKKKLLþJKKJMNEFGIJI;9þKJþJþ7LKLLLþJIKMIEIJK>þ9þKJ7þ
7JKLLKHIKGKKJIJ:þKGþ	KHKJJKJMMLKLLLLK=<;þKþKKIIGþMMMMMMþ=<þKJJ7þ9JKLLMMLKþ	KJG7þ	8KKKKMLMKþ	IHþ9JKLI9^IJJKþHHþ<GKLJFGMLKLKþKJþ4KK]9KKKLMLLþ<FKJ[IKHLIHKKþ4KL9[[þ7H7LLþFLKZ[\þLKJ7þJKþ\YLKKKHKþ9þKLIIþIþLJ7YþHIFGLLVV[þFHHHHHHHZXZþHHHHHHHFHHFZYHþFHGHGHIEHHHIHUV[IHþHHEHHHHHHIIHJKK\YHGGHGþHFHHHHFHFIJIJKKKKJJIJJIIIþHFHHHEFIHIHFIIIJKJKKKKIIIHHþFIHGHGFIFHIIIIIIJJJJJHHHGþ	HFHHGHGGHHHHIIIIHIIHFFþHHFHHHHGHFHHIIIHHGþGFHHHFIIHIHHIIþHGHIGHHIHFþGIHHHHHHþGHHHÿ
þKH33D3þLKþHþLKLMþKIþIJHFE3þLLKþKIGIþLLMLKKKþLþJþJIþFEþMJþKJ:LLKKHþLHKIþKþIEIMKIJ:LLLHL7þKKGKIHKLLKH7þLKLMMJKJJKHKKþMMMMMMKþIIKKþKLMKLLKJ9þ7JJKþKJJIKJþ^KKK8þ	7IþKJJIHþ^_LKJ9þKJIHþ___þJG<þKLJHHþ___þKHþKLþIþ	^]_þKJHþ
KLKþ\\]þKJþ
Lþ\[ZþJþHH\[XþHHIHIXX[þFHGHHHHZWXHHþHHHHHFHHHFZY[HHHþFHGHGHHHIEHHUWZHHHIHþ
HHEHHHHHHFHIHHXWX[IHGGHGþHFHHHHFHFIGHHIFHHZYZHHHHGFIHþHFHHHEFIHIHFHEHHHFHZVX[HHGIHHGIGþFIHGHGHIIIIHIHJJJJXXZIGHHHGGþHFHHGHGGJJJJKKKKJ[\[IHFFþ
HHFHHIIJJJKKKKKJ[[HGþGFIHGGHIIIJJKKKIþHGHGHIGHHIHFþGIHIHHIHþGHHIÿþ012þ001223þ3þ;;<;;=C4578þ<===C3356688þ<:<<þ7889þ>9>þD3589:;þ>þ89::;<þ;;;<<þ;<<<=þ=====þHHFIþ>>>?=þHHIHIFGHþ>????>þFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHIIIHHHHHHHHHIHþ
HHEHHHIIJJJIIIHGHFIHGGHGþHFHHHHIIIJJJJJJIIHHHHHIHGFIHþHFHHHEFIHHHHIIJJJJJIGHFHHGIHHGIGþFIHGHGFHFHHHIIIIJIHIGIGHHHGGþHFHHGHGGHGFHGHIJIHH:IHFFþ
HHFHHHIHHGHFHIIHIHHGþGFHHGGHFIIHHHHHIþHGHGHIGHHHHFþGIHHHHJHþGHHIÿþ0024335;;þ110157<þ0245322=;==þ132222789þE53?>>>>==>7=?32255678þ025744;>>>>=9???<<<<84579þ245865=>>>>>:???=?5544557:þ324787:=><>>=;???>þ244<37:þ22586:þ<<>>????5þ9<4579þ236þ<<>=>8G87þ87879þ25þFH899H9HH88Hþ979þHHHHHF89;9;985HHþ9þFHGHGHHHIE88999HHHIHþ
HHEHHHHIIJIIHIH88IIHGGHGþHFHHHHFHIJJIHIFHHHIJJIIHGFIHþHFHHHEFIHIJJIIHHHFHIHIJJJIIHHGIGþFIHGHGFJJJJIIHHIHHHIIIIIHHGGþHFHHGIIIIIHGGHGGHHHIIHFFþ
HHFHHHIHHGHFHHFHHHHGþGFGHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGHHHHþGHHHÿþ	>2346999þ>>>224E8566þ=>>>>55þ88420þ====>þ6þ8674þ9þ<<<==þ8þ74Eþ;;:<<þ;þ6431þ:::<<þ	5323þ::<<þ2357;þ52þ<<þ678;=>>>þ<<þ8:9;þ>>>þ9:<þ>þHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHIJIIHEHHHGHHHHIHþ
HHEHHIIIIJIIHGHGHFIHGGHGþHFHHHIIIIIJJJJIHHHHHHHGHGFIHþHFHHHEFIHIHHIIJJJIHIGHFHHGIHHGIGþFIHGHGFGFHHHIIIJIHHIGIGHHHGGþHFHHGHGGHGHHIHHHHHHIGHFFþ
HHFHHHIHHGHFHHFHHHHGþGFHHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHGGHGHþGHHGÿþ2002227;þ212233>>=>þ212Eþ=<=þ3477þ==þ223467=þ212347=þ22446=þ723847FIþ65666=IFGHþF5898HHHHHHHþH::<9<HHHFHHFHHHþFHG:::;74EHHHIHHHHIHþ
HHEHH>;::::IHI::pFIHGGHGþHFHHHHFH;;;9:IFH::tHHHIHGFIHþHFHHHEFIHIH;;;:HH:9<<t7sHGIHHGIGþFIHGHGIIIH;;:HH;:<;78;<HHHGGþHFHHIIIIJ;:I<<;;=::<IHFFþ
HHFHHHIH:><9HHFHIHHGþGFIHGGH><IHIHHIIþHGHGHIGHHIHFþGIHIHHIHþGHHHÿþ¡þHHFJIKKNþ£þHHIMMNNNNMNNþ¤þFHGHHHJK‡NNNM,,þ¥¦HHHHHFHJKL‡‹KJL(!*,þF§¨HGHHHIELLLþKKLL(%'eþHHEHH¨¦HHFHIHJJJKLLM(#'(-þHFHHHHFH¨¥GHHIFHKLLLM©%!,-þHFHHHIIIHIH¨¥¥HH£¤¦§¨©©««,($JIGþFIHGIJJJJJJ¨¦¨©KHNNNLNKNJJIGþHFHHGHIIIIJJKNNNNLKJKJFFþ
HHFHHHIHHGKLMMMJJHHGþGFIHGGHKLMNNKHIIþHGHGHMMLMNKFþGIHNMMNNþGNNLÿþHHFIþHHIHIFGHþ
¤þFHGHHHHHHHHHþ	¦þHHHHHFHHHFHHKLMHþ§þF¡GHGHHJIEHHKLLMMIIHþ¥¦þHHE¢HHJKKLMIKLMMNNNJGGHGþ¤§þHFHHH£FKLLLMMLLMMNNHJMJHGFI¦þHFHHHEF¤HKLMNNOKMMNIKLJJHG§¨¨GIGþFIHGHG¤LMNNNLMOONJKLM¤¥¦§HGGþHFHH¦NG+((—((+)¦§?LKHFFþ
HHFH,)—%%%—),,)?MHHGþGFIc(–”—)c,#"JIIþHG—*JHFþGhj-LHþ-ÿþ(((#(þNþ%)*(&&þKNNMMN¦¤NNLLþLLNKHGMH¦£NMJLKþ=MþMKKLJJNON¤¢LKJHHþJJKGLKJHHMNN¥¤ILJHHIHþ
KMLM¢JHHHFLMMN£LHFIHGGHGþNNFHKLM¥HFIGHK?MN£NLHHHHHGFIHþNNHHHEFI¦IHFHEJLMN£N?LIHHGIHHGIGþFIHGHG§I¤¥¥¥IKLM£MMMJIGHHHGGþHFHH¨¤§GH¦¤IGK¦LMLNJIHFFþ
HHF§HHIJ§¥¦¦§KLMMHHGþGFIHGIJJJJJJJJIIþHGHGHIJJJIHFþGIHIHHIHþGHHHÿþHHFIþJKMHHIHIFGHþLKKLLLNHHHHHHHHþ)MLLLLLLMNHHFHHFHHHþ%(,MMMLMMMMNNHHHHHHHHIHþ)%()£¤MMMKJNNOHHHGHFIHGGHGþ,(%¨§¦£HIIGHHNFHHHHHHHHHGFIHþHF%NNN¨¦£JKKJJIHFHIGHFHHGIHHGIGþNNNMMN¨¦£HHFIHHIHH IGIGHHHGGþ?LKMNN¨¦HGFHGHGG§HHIHHFFþ
?KLMN¨¨HHGHFHH§HIHHGþGFIKªª¨¨¦¦¦¦ªIIIþHGIJKKKKKJHFþGIHIHHHHþGHHHÿþJLþKJþHLKLþKKLþLLLHIKKLLKKLþLLKLHKK(—(-NLKKþHHKKKL(#,(”)*"NMLLKþFHGHGJJL'%'-hj"(£NMLþ
HHEHHHHHJM/($(#/NMMGHGþHFHHHHFHIJLLNNNNNNM?LKIIGFIHþHFHHHEFIHIKLLMMNMNNMLMMJHGIHHGIGþFIHGHGFIKLLKKLKKMKJLLLGHHHGGþHFHHGJKJJKLJIHKKKJLLJHFFþ
HHFHHHIHHGHFIKKKJLHGþGFHHGGHFIIHJKKLLþHGHGHIGHHIHFþGIHHHHHHþGHHHÿþHHFIþHHIHIFGHþFHGHHHKKLMLLþHHHHHFLLKMKKKMLNþFHGHGHILKLL€ˆLLLMNMŽþ
HHEHHHHILMMM‰†‹MMMMN†ŠþHFFIFEFHGKLLIJLJLNLLMN‡ŒŠþHFHHHEHJHIKLJHHJKKLMJJKMŠ‰þFIHGHGFHILLJJJIIJKKLLMN†‡þHFHHHHJJLKLKMKLLNKKLLHFFþ
HHFHHIJJJLNNNNNMKHHGþGFHHHIIJKKJJHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþHHFIþHHIHIFGHþJKKLIHHHHHHHþKKJKLLKLIFHHFHHHþFLLKLLLKKKKKKJHHHHIHþ
‹ŒNLLMMMMMMMMLJHFIHGGHGþŽŽŽŠNLKHHIIJKLLLMKHHHDHGFIHþŽŒ‹ŠNMLJJJKKLLLMKJHFHHGIHHGIGþˆNNNMLLLLLKMMJHHIGIGHHHGGþHFHNMMMMMLMMKHGGHDHIJHFFþ
HHNNNNNMJJHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHHKKKJHHHHHHIHþ
HHEHHHHHJKMJLLLJHFIHGGHGþHFHHHHFHFJKLMIKLLLJHHHDHGFIHþHFHHHEFIHIJLLLMGJJKLLJIHHGIHHGIGþFIHGHGFLLKKLMIJIIKLLJIGHHHGGþHFHHGMLLLLMJKKKLLMJIJHFFþ
MHFHLLLLMMMLLMMKJHJJþGFJLŠ‡ˆŠ‰ŠŠJJIJþˆ‹‰Š˜—•ˆ‰‹Žþš•šœ™›þ™š›‹ÿþ‡ˆ‰‰þþFMMNNMNNNNNJþHHLMLLMMKLMMMMJHþFHGLLLLLMMKJKJJLMJIHþ
HHEHHKLLLIƒML€…KJLMJHGHGþHFHHHHFKMMKKMMK‰‰LKMJHHHGFIHþHFHHHEFIHIJMKKKMJJKLMJIHHGIHHGIGþFIHGHGFDFJMML†LLLLJIGIGHHHGGþHFHHGHGGIJMNMMJIHHHIJHFFþ
HHFHHHIHHNMJIIIHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþWWUUUWþWTTSSTTWþ[WUUUUW^þYXYZ[\]]^þXXYZ[\]\^þYVVWXYZ[]þVVWXYZ[]^þUWXYZ[\]^^þUVXYZ[[[]þWVVWXYZ[\^þUWXYZ[\]^þVVVXYZZ[\þVVWXYZ\]^þWWXYZ[\]^þXWVXYZ[\^^þXWVWXYZ[\^þXXWXYZ[\]^þXVUVXYZ[\]^þXWWWXYZ\]^_þXWWXYZ[\]^_þXWWWYZ[\]^_JHþXWVWXZ[[\^_HIHHHþXXWVWXYZ\]^_IIHHHHIHþ
HXXYYXYZ\]]^^IHIHGIHGGHGþHXYYZZZY[]^^^_^[HJHHHHDHGFIHþHZZZ[Z[[Z\]]^^^_^]Z[IIIIHGIHHGIGþFIKK\\Z[\]]^___]\[ZZ[IGHHHGGþHJJ\[[\\]^___^^][[YXJHFFþ
HHJ\[\\^^MM^^^]]L[ZGþGF\[\]^^LLLLKKIIþHJ\]]]^KKIHHþGKLLKJHHþJJJJÿþWTTTTTUYþWTTTTTUYþTTUUUUTZþXVVUUUV]]þUUVXYZ\]þYXYZ[\]^þYXXYYXYZþYUUVWZ\]þZWXYXXYZþZUVWXZ\]þYYYZ[\]^þYWXZ[\]^þXWXYZYZ[þXVWXZ\]^þXXYZ[\]]þXYZ[\]^]þVWXYYXY[þUVWX[\]]þYZZ[\]^^þVYZZ[\]^ZþVYZ[\]^^]þVWXYZYZ]ZþUVWXY[]]]þXYZ[\]^^^þXYZ[\[\^^þYYZ[\^ÿ
þ=þ>=?þ><?Mþ>=>MMþL<=?MMMþ>>==>MNþLMþ>þ>KMNMþLþ<þ=;KLLMKKLþKJIH<LLMMþMKKþKJIHJJJKLLMLþLþ9JKLLLJKLMLþKJþHIKKKþLJLMLþKJI9IKþJKKþLKLLþJþHIKLþJKLþJLLþKþI9JJKKþJKLþKþKJJHJþIJKþJKLþLþJþHHJLþJJKþJLþJHHIJJJLþIJKLþJLþKþIJIJ?LþKJJLþLþJHIJKIK?KþLILþJJIHþK=J=?KþJLþ>III<<=þ=K?þKþK9I<<=?þ??þ>=I;þ=<>?þ?þ;H;þ>=Lþ=<;þ=Lþ>=>Lþ?ÿ	þIþ9;þ;þ>J;K>Lþ>I=þ>LKKLLþ>Mþ	;=??>KKKLKLþKM>LþL9>=?>KþLJJJKLþM?K?þLLLL>þ>KKKþLLKLþ
M?MþLL==>?>KþKKLLþLLþ
LM?LþM>=>??>LþKJKKþJN?M>KM>J>????LLþLLLLþ
J?LLLML?>MMNNN??KIHLLþLKKNLNLK?M?>NNM?LLLLJHIþ	MMLMMMLNMMKMN?LMILLþKKJJþNLKLMMKLM?MM?LLLþMLLKKþLKMMMLLKL??NM??KLMMLKKILþKKLMMMLKKL??MMM?K?KLJIMþ	=??M«M??=K???þLL?JIKKLþ
?MM«­MMM?=>?JKLKK??JJKKþ	?LM«­NMKKK=>L?KþI9þ
>?M?MMKLLM?=>MþLM©§MKLLMMM?=þMKLL©LMKMLLMþLMLLªLªþLMMþLLL«ªª«KLMþLþ««LKþKþLþLÿþLKLJKþMMLKJJþJKKþ>LMMJJJKKKJK9þM=<LKKþKJHJJIKJþNM>=KM>JHKJþJKK9þMNMK>KL>ILþHIKþJþMKKMLLK;=LMþHIKKþKKMþMKLL<HILKIHJKþKLþKKLLKJJJHILLIJþIþLþKJLKJLþKJ9JLLKþLþJKLJLþKKKIHJLLþJJLþKKJþKI9JMþLLJþMLKJþLKIHþJKþLKJþKKJJ9þKþLKJþKJIþLJþKJJþLJþKJIþLþLJJþLIþLJþKþÿÿ
þHKLKþKLIJKLþHIJJþIIKLþKIJKþIGIIþLKJJLþIGGGLþLLLLKþJJGGIþIþKLMMKJþGIþJHJJLþLþLþJIþJJHHþLþLþJJJJIHHKþKKJIJIþLþJ?KIKJIHJKþKIJ=KþHIJJþJKIþIK<III>þKKþK=III9KþKþ?IIIþ;I=>þ=Iþ;H;þJþ;<=þ>;<>þ><þÿÿþKK<<=KLKKKKþKJKþKHJJKLLKþKþKKLþ<JJKJ;KLKKLKþKLKKIKJLKKJJKMLþKþLKþIKKLþMJLKJKMLKIþKþIKLLþ<KLþKJLMLKJKþIJKLþ<JLþLKHLMLKKþJKLþJLLKILMKLþKLþJKLLKþJKL>þLþJLLþKþ??þKLþIIþMþIþ K?ÿþKJJIJþIJJJKJKKLJKþIJJJþJKLþKJKþHJJþJJJLþJLþJKLþJI99;HþJKKþKLþKþ:;þKIJKþJKLþKI:JI;þKKIJKKþJIKJJLKþJKLLþ<LMþKJþIKKKþLþ9þIKMMK?LþIKKþK<LMLKK?þLLþ?JKMMKþKLþLLLþ??MþMKþLLKMþMKJþLLþMþMKKþMÿþ
9KKKJJ;þ9HIJKLKKKJKKK;þIHþJIJKKJKKKMMþJKKKKKþKKKMMMMMLL;þKLþJKKþKþ???MMLLJþKþJLKKþ?MMþLþJLþ?Mþ?MþLþJþ
MMMLþMMLMM?þ?LþL?þMLþ?þM???þ>?þKþLLþL?LLþ?>þ?þ?L>þ????þ>?>þ>ÿþ	HIþKJJIHþLLKIJþLLLKKIJJþLLLKIHþKJIþLKKIJþLþLJJJJþJKKLJþLLKKJIþJIþIKKLLKKJIþKKKHK;þKKLKJIþKKH:þKIþKKLIþ>JIJþKLKIþKKLþ>=KJþLLG;JIþKIþ>><þKKJ;þIIþIKKþ=þ=JJIþKIIþJ;þKJ:<;þ>þJK;þJþ=;þ>=Jþ<þ>=>=þ>þL<þKIþJÿþJJKKLJKKþJLþLLLKKJJIIII:KþI<JKKK>L>KKJJII:þKLþIJKþJKKLþLLKLKKJJIKþJþ
IJþJKLKþNLJLK<KLJJILþ
IþIKKþLKMþKLMLKJIþKþKþJJKþKLMMþKLMþLKJJJKþJKþKKþJKLMþKLMþJLKK>JLJþ??þKþKKLMþKLLMþL?þKKIL?MþMþ	=LMþK=LMþKJMþL>IKþMþK=LMþKJLMþ>>>J=LþLMLMþL>?Lþ?KILþLKKþM?þM>IþIJJKKK=>?KLLMKþIHIIH;=>LLLL?MMMKLLþ
IHJIJ=>???>>LLMþ>MMMMþIHJJKKþLJI?L?þM>>MMþ>MMMþIJJKKKLLMþLJ=>?þ>>Mþ>«M?þIJLLþLIKKLMMþLJ=>LþK>M¬>?LþIKKLLKþKIJKLMþLI=>LþMMM¬??KþIKHþKLLKþKIJKLMþLIKLþ¬M©«?>=JKþJIKKþKIJKLMþJKLþªª?L>=?KþJIKLþKIJKMþLKKMþL>L><?MþIKþIKKþJLMþ>þL>=>MMþIþJKLþKþ
MMMþ;KþLMþLÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHFHHHFHHFHHHþFHGHGHHGHEHGHHHHHHIHþ
HHEHHFHGFFHGHHFGHFIHGGHGþHFHHFFFHFFGEFFFFHHIJHIHHGFIHþHFHHHEFGFEEEFFGGHGIGHIIKIJIHHGIGþFGFFEEFEEFGFGFFIFHFHJKJJHIHGþFEFFFFFGFEFFGFIGGHJJKJKIþ
EFEEFFHFGGHFHGFHIKJKþFGFGHIHIGIGJIJKKþHFIGHJGGKJKJþHFJHIKJHþGIFIÿþHHFIþHHIHGFGEþFHGHHFEEFFGFþHHHHHFGEFDFEFEFEþFHGHGHHDEFFEFEEFEGFFþ
HHEHHHHHHFFEDDEFFEFEGHGIþHFHHHHFHFIFEFDFEFEEFEGFGFHHJþHFHHHEFIHIHFHEDFFDFFEGFFEGIIGHIIþFIHGHGFGFHGHHFDGEFEHEGFFIHIFþHFHHGHGGHFFEGEGHFHHFGHFFþ
HHFHHHIHHGHEGHEGGGFFþGFJHGGHFIGFFHGHHþHGHGHIGHHEHHþGIHGHHHHþGHHJÿþHHFIþIHGGIFGHþKJHHJGJHIHHHþJKJJHIHJHJIIJHHHþJKKKJHGHJIJJHIIIHHIHþ
IIJJKKJHIHJJKKHIGIJJGGHGþHJKJKJJIGGJHJIJJIIGJIJJHGFIHþJIIJHJIIHHHIHIJKKIHHIIJKIJIHHGIGþJHIGHIHIIHKHKIJHHGIKKJJIHHGGþIFIHIHIKJIJJIIHIJKJIJHFFþ
JJHJIHIKJIGHIKJIKHHGþJKJKJHHIHIKJKIIIþKJIIIHJKJIHFþJJHKIHDHþIIHJÿþJJJGþJIIFJJFJþGHGHGFHIJFHIþHFHGHHGHIFHJJJHIþHFHHGHHJHJJJJJHJJKJIþ
HHEHHFHGIHHJHIJJJJJIJKHHþHFHHHHFHFHHFHIHIIJHIHHIHHIIJþHFHHHEFIHIHFHHHHHGJHJHHIHHJIHIIGþFIHGHGFDFIGFIHHIIHHIGIGHHHGGþHFHHDHGGHFFJGIGIHDHIJHFFþ
HHFHHHIHHIIFHHIHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIHFþGIHDHHDHþGHHJÿþV2V2Y\]þ2323VþXWXWVWþVHV2WZþ>W>WWXZþ	ZZZZ[YVY:IIWXYIH>=>>XYZ[þ[[[[þW9WY9:X[::9;<>XYXYZþ\þ\þHHG]ZY<Z];;:<>I37þXþFH99:;\\][_<9:<89;>>þ
HH9:9:;<=[\\>=8<7;::::>GþHFH999;<=>W124;>1235;;;:::IHþHFHH::;<<<=V438>?8=3257;;;:::G9GþF8H;<<==V256=>???=5457;:HHGGþ8F:;<=WW68=N>???=947:9FFþ
H8H:ZY:=>?M?>=<<=:=GþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþKH43þJKKKLþKHGFHHþ3þIILþþGHJHEþFILMþ3W3XYþXþ[MLLLG	IKJþLLG3EFHJIHWKXþ[þKþKLLGJKKJMNEFGIJþJþJþþKLLLGJIKMIEIJKþJKLLKHIKGKKJIJKþKKHKJJKJMMLKLLLLKþIZþKMMMMMþZþ9JþLLMMLKþ8KKKKML_KIJJKþ9JKLþ9[MLþJKþ<KLJþ[KþþKþ[ZYþ<^\þ\VVþ^\þZXZþ[]þZYþZ\þUV[þYþ\Y\þVY[þWY[þWVXþ\Y\[þVY[þ
LLþHHWY[þ
LJþHHIHWVXHþ
KLþ
FHGHHHHY\[HHþ	KþHHHHHFHHHWY[FHHHþKþFHGHGHHHIEHXV\HHHHIHþ
HHEHHHHHHHIHY\\HFIHGGHGþHFHHHHFHFIGIFX[\HHHH[JKFIHþHFHHHEFIHIHFH[[]GHFH\[KKHGIGþFIHGHGFDFHJFXZ[HIGIG\\KKGþHFHHGHGGHG^^WWYX[HIJHFKþ
HHFHKJI<===^^ZYXYYZGþKJJIG89:;===\[þHGHGH::;<=K=þGIHDHH8:þGHHJÿþKþLþHKþKþLKþKLþMLþKKþLKþKJLþLþKKLKþKKLLIþJJJJKþHKKKLLGHþJJJJJKþK8ILKLL:IþIIKþKKþZþFHKK9LKL:JKKLIKKþ[þZ\\\LKKKMKJKLKLKKKþ=\[\\KKMKKLLILIHþ
:;<==<_]]LLLMLMHGþH89:]======MLLKLLKLIHþHFHHH89:;]\[;<<==<;;;;;;JLLLLKIGþFIHGHG999999:::;;;::GIGHLLLJþHFHHGHGGH:::::::HDHIJHFFþ
HHFHHHIHHGHFHHFHJHHGþGFJHGGHFIIHIHHIIþHGHGHIGHHIH:þGIHDHHDHþGHHJÿþ421346þTþ421346467þ	2þ	]þ8986467[[þ27þ;99Z\[[\Zþ67\þ;Z]]\Z\<þX[\^þ;]^^\<:þX[^^þ>[\Z:9þX[_^þ86422þ	2466>:699XY\^_^\þ8642233þ224668>=99XY]__^\;;;<65334þ2356789>=;:YY]HI^;;<<<<764þ26:=>>><8=<X\]Z^^^====<þ7þH><9=Z\<^[[<===9þFH99=<;\Z^_;;===HIIHþ
HH9:9:;>=YZ\<;<=<2343:HGEþHFH999;<=>=:[:<<=7:::9984EIHþHFHH::;<<<=><;8=<<7;;;;:;9963G9GþF8H;<<==>?<;<><8:>==<<;5:HGGþ8F:;<=>>?==;9:??=<;;;9FFþ
H8H:<<==165?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþVVU227;þVVU227þZXVV3þ=<þ\ZXþ=<=þ
UUUþX\þ=þ>>>XWZYYþUUUVþ^[\þ>>>XWZYYþUVVWWXYþ][þ>>>>\þ\þ^þ^_WWXYYYþ^\Zþ===>þ^þXVVWXYY][þ^\Zþ;;==þ]^][þ]þ\^[YXþ;;:þ235;þY^^]]^\[ZYXZþ::þ6235;>>þ]^^\^\ZZZZþ::þ678;=>>>þ	]_\]]\[Z[þ:þ:9;þ>>þ\\]=];[\þ:;þ;7:<þ>þ[[\?][\8I;9;78<<þVV4335;]><91015<[þ[YWVVV==]]<122YY[þX[X?>>>==]7=3XY\9þ\þ
XH9[X;>>>=9??<<Z]IIH\ZYþHH\:9]W=>>>>:??=?Z]:][ZY9þHFH9WY][Y>><>>???5<<;[ZX79IHþHFHH::;WYZ=>??<>=>887<;87879:G9GþF8H;<<W:>?NN99I9I88=<<979HGGþ8F:;<;>>??N89;9985;;;9FFþ
H8H:<<==>?M8899<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;<====<;;::HIIHþ
HH9:9:;<=>MM>=<<<;::::HGþHFH999;<=>>M?NN>=<<<;;;:::IHþHFHH::;<<<=>??NNNNM>=<;;;;:::G9GþF8H;<<==>?NNNONNN>==<<;:HHGGþ8F:;<=>>??NNN???=<;;;9FFþ
H8H:<<==>?M?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHHFIþHHIHIFGHþFHGHHHHHHHHHþHHHHHIJJIFHHFHHHþFHIIIJJJ99IIIJIIHHIHþ
II:<=>:;<=<;:98999IHGGHGþHIIJ989:<=>>====::;=II888FIHþHFHHHHIIJJ88<>?>>>;<<>==;:IHHGIGþFIHGHGHIIJ::;<=89:JIHIHGGþHFHHGHHIJKK=8IIHIJHFFþ
HHIIIJK<88IIIHIHHGþGIJI<89IIIHHHIIþHI=9IIGIHIHFþIIIDHHDHþGHHJÿþHHFIþHHI77FGHþFHGH7<;87HHHþHHHH878=;8:798HHþFHGHG79;:>9;8::7HIHþ
HHEHHH7;<=<;9;;87GGHGþHFHHHHF7===>>
98DHGFIHþHFHHHEFIH9>>>Z
::GIHHGIGþFIHGHG9;??	


;7HHGGþHFHHG77;887FFþ
HHFHH8;:7GGHþGFJH8;<;7IIþHGHG8998H8HFþGIHDHHDHþGHHJÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;
===<;;:9HIIHþ
HH9;9:;<>>L
I;HHG:HGþHFH	99;<
>M
I9988GFIHþHFHH8<<
NJ99	GIHHG9GþF8H;<<;??NN>LKJI:HHGGþ8FH9:;<=L?
ML=
JI;<FFþ
H8H=<<=>=<I8HGþGF9:;<=>==<;;<IIþ8GH:	
=<;:H8þGI;::Hþ:<H9ÿþþþ	þþ
þ
þþþþ
HþþHHIH\\HþþFHGHHHH]
H]þHHHHHFHHHF]HHþFHGHGHHHIEHHH^^HHIHþ
HHEHHH9::799HDH\FIHGGHGþHFHHHH8H9:<=:::<
[::HDHGFIHþHFHHHEFI89:9:;<<;<;::HGIHHGIGþFIH9999:><<=>>
===<>:HHHGGþHF9H:;<=<
==<::Fþ
H::=<=??>?>::;þ;<;=>>=?>==<;:þ;:<=>>>?<::þ;<=<<;;Hþ::<=ÿ	þþþ]þ]þþ^þþ^þþþþ
þ]þ^]þþ^^þþ^_þþ
þþþþþ
þþHH_þH::_GHþF::HH^HHHHþHHHH;=;^;::HHHþFH:H=:;<=_<;;:::IHþ
HHE:::;<<===<;=:GHGþH::H::;<<===^]=<<;:9FIHþHFHH::=;<<==??>_=;;9999IGþF:::<<<<=
?>==>>><=<;9þH:;<==???>>>>>==>>><;:þ
:;;<<==>>>===>==<<>;þ:;:;<<<<===>=<<;þH:;<<<<<:;:FþGIH;;HDHþGHHJÿ
þ
GKIHþJKLKLMMMMLþKJJMNMMMKþJJLJMNNNMJ9þJþMIKþ^LKK8þKJþKKþ^_MKþ9þJJMþIKþ___þJLMþIþ___þLþJMþJKKþ^]_þLKþKJMþHþKþ\\LKþLþKþLþ\[
LKMþJJþJLþ\[	L9MþLKMþLKþXX
KMþLþLKþZWKKþLþZKþKþHUWZþHHIXWX[HþFHGHHHZYZHHHþHHHHHFHHZVX[FHHHþFHGHGHHHIEHXXZHHHHIHþ
HHEHHHHHHFHIHD[\[FIHGGHGþHFHHHHFHFIGHHIFH[[[<HHDHGFIHþHFHHHEFIHIHFH:::::<<=:9;HGIHHGGGþFIHGHGFDF::;<;;<<<:;GIGHHHGGþHFHHGH::;<<;<<<<HDHIJHFFþ
HHFH9::;;;;;::9HJHHGþGFJH9:::::9IHHIIþHG9999GHHIHFþGIHDHHDHþGHHJÿþZþZþZYZ\þUþYZþ[XY\þ
WþVþ[[]Yþ[VWX\þ
WWþ\þ]]ZþUWY]þ\ZYþ
]þY]]þ\[ZZþ[þ]\[þWþ
\[ZXþ[]\[\þ]þW]þ\^^þY[]þ6þWZ]\þ]]ZYþ[X[96þUXZ[þ[YZ]þ]þ[Y:8þUXZZþ]ZYYY7þ595þW[Z]]YX87þXWWWþ
ZYY8þW[Y]]Z98þXþZ[[[Y[Yþ[ZY::W[X^[98þ9Yþ[]]þ[[[[þ	ZY97]W;9þ9XY]þX::;Z;:;X;98þ9XZ\]]þXXX<=^[;[Z:þ9;<<;þXWZY9[]\7[]]<]^>>>þZ\\[[7[]]\]\^]>^\[Z]]\^þ^\\\[þZ\[[þXY]]][[[Z]?>?^^^^þ^þ^\þ[]\þ[^^[[9ZY[]\;::HI9þ^þ[þF[^9]\<=[\]]\;::HIIHþ
HHY\^^][=>M]_\]\<;::::HGþHFH9\^^<^>>M?]^_[\]<;;;:::IHþHFHH::\<^\=>??NN\N_[\];;;;:::G9GþF8H;\^\\Z?NNNONN^]Z\<<;:HHGGþ8F[\\\>>??NNN?]^]Z\;;9FFþ
HZZ:<<==>?M?>__^\]HGþVGF9:;<=>>><;_:I]þ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿ
þþþþþþþþþþþ¨§þªþþ©¨¨þ©©þþ©ªþ¨©þþþþ¨ªþþþþþþþþ§©þ§©þþ¨©þþþþþ

þþþþþþþþHþþþþ
:þ9;<<þ
F9:;<==þ9:9:;<=><<<:þH999;<=>>>=<<<;HþFHH::;<<<=>NNNM>=<;;;9GþF8H;<<==>?NONNN>==<<;:Hþ8F:;<=>??NNN???=<;;;9FFþ
H8H:<<==>?M?>=<<:8HGþGF9:;<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþ\þ]]þþ^]þþ]]þþ^]þ]þþ^]þþþþ^þþ]þ^_^[]þ___]]]\þþ:I]þþ	__Hþ]]]^HI9þ9:;<==^^HIIHþ
H9:9:;<=>^:::HGþHFH999;<=>>^]>=;:::IHþHFHH::;<<<=>\NNM>;:::G9GþF8H;<<==>NNNN>=:HHGGþ8F:;<=>NNN???=<FFþ
H8H:<>?M?>=<<:þGF9:<=>>><;;:IIþ8GH:;<=<;:H8þGI;;;::Hþ:<H9ÿþHH8Iþ:IIHY[\\þ9IG9::]]^^^]þHHG99;	]^_\^^]þFH99:;<===]^_;_]^
þ
HH9:9:;<=>MM>\__][^^

þHFH999;<=>>M?NN>\<_\]^




þHFHH::;<<<=>??NNNNM[\\]©	
§§§þF8H;<<==>?NNNON£¤¦§©©««
þ8F©§§§¨©©©NNN?^^^\[Y]]^^þ
©8H:<<==>?M[]]]\[^^\þGF9:;<=>Z_<^;]^Iþ8GH:;<\^__^^þGI;;]]\]þ:<^]ÿþ©©©©þ:IIH;HIHþ[]G9:::::9HHþH[\\\^^<<;;::HI9þ]\\\\\\]^=<;;::HIIHþ

]]]]]]]]^=<<<;::::HGþ

£¤]]>>]^O>=<<<;;;:::IHþ§
	¨§¦£=>??NNNM>=<;;;;:::G9Gþ	__^¨¦>?NNNONNN>==<<;:HHGGþ\F\[]^¨¦??NNN???=<;;;9FFþ
]8[\^¨¨=>?M?>=<<:8HGþG[]];^¨¦>><;;:IIþ8GH:;¨©©©:H8þGI;;;:©©þ:<H9ÿþHH8Iþ:IIH;HIHþ9IG9:::::9HHþHHG99;<<<;;::HI9þFH99:;<====<;;:[\]IHþ
HH9:9:;<=YZM>=[\\\]]::HGþHFH999;<=Z[[\N[\]]]^^^;:::IHþHFHH::;£<Z[\\[\[[\\^^^XY\;:::G9GþF8H;<¤=[[\]^^Z^^^^XZ[\;:§§§§þ][^]¥\]^^


^\[[\_;9FFþ
^^¦¦_<		




¦§8[Zþ	
		——



I\þ	¤	££
£	
þ¤¦¦¦¦—
þ¤£¨ÿþ

	þ__^¤^^[_þ^[G9^¦£^\Z\^þ]^]\__^^¥£^\:^^9þ_H_\\]]\\O^¤¢\^^[^^Hþ
^^__]]]]]>M^^¥¤<\\YW::HGþ]^^^]];^^^>M?\^^£¥[<;;;:::IHþ^^^^:]^^<<=>??NN\^£¨^\;;;;:::G9Gþ^^8H;<<==>?NNN^\^£¨^=\<;:HHGGþ8F:;<=>>??NNNZ¥§[\[^;9FFþ
H8H:<<==>?M?¥ZZ[\\HGþGF9:;<=>>><¥;\\þ8GH:;<=<;¥©8þGI;;;::Hþ:<H9ÿþ9þ;8:þ8þ:::9þLþKKþ:þ8LLLK:K6KþM:LþKK:::Kþ6þLþLLþ6L9LMMM:M799798þ	KþM:::99KMK:9989:88OOþ8þKKLM:98:88::88L898KKKOþ98::KK89988988LML<L9LLKKOJþK988:M8L786N:88LLLN:LLKKOþKKK99:88:9887MLKNLL:MKK:MþLKKNK89::8799KMLMNNMML:KLþKKNNMJ:K8989MLLLLNN9INMLKNþKKNKI9NNJ:KLKLLMMNNNIKNMM9KþNKMLLN:::NMKN:LKNKLLIL:NNNKM:þM:LKNLIL:NNNKM::NLNN:::NMKN:KþMNKLLNNNIKNMM9K:LLKKI9NNJ::NKþNNNNLLNN9INMLKNNLLLNNMJ:JKKKNþKOMNNNLMNNMML:KLN:JLNKNMI::JLLþKKMMNNNKNLL:MKK:MKKKKNKI9:LLLNNKNKNKMLLN8LN:LLKKOK::NK9ILM:::KNKM:M:LKNNN9ILLKKOJ:KN:K8KLLLKMLMNMNMNKLLKKKI9:KKKOKNKM:NLKK:MMMNMNNNNNNLLKKNMI::OONMM9KMMMKKNMNNMOMOMNNNNNNMJ:JKKKNMLKNNNMMMMJNMNMMMMMNNKKI9NNJ::NKL:KLMMNNNKIKNOKMKMLNLNN:::NMKN:KKK:MKMKKK:9KNM:L:LKNKLLIL:NNNKM:LKKOKKOKJLNKNKLKLKLLMMNNNIKNMM9KKKOJKOOOKNKMM:LKMLMLLLLNN9INMLKNKKKOKKOJLKNKNLKLMLKMKMLMNNMML:KL:LOOLOJLLNNNMþMLLKMKNKNLL:MKK:MKKNNKNNNKKMþKMLKNLNLN:LLKKOLLLNNN:NNþ
KNLLNLLLLKKOJMNNNN:KþLN:LLKKKKKOKLNLLþLLKKKOOOOLNMþKKKOOMNNþOOMNÿþ9þLþK:þMþNLK::8þLL;K:Lþ::LLþKþM;;::9þKKþ88:K7KMMþ;;8;8LþKþKLKKNKKK9MKMMLMKL898LLKNKKLþLþKKKNNMLKKNK87M<<:::LNK:JMNNLNLþKLKKI9NNNMJ:K8:89L:J:JNN9IKMOLLþKKNN:::KI9NNJ:KL:J:NKMN:::NMMLLKNNKLIL:N:::NMKN:K:MKNNN:LILMKLLKMMNNNNILIL:NNNKM:K9MMNKINNNL:LK:MMLLNN9NNNIKNMM9KNKLMNI9NNLKLK:8NNNLMNNLNN9INMLKNLK:LMMNNMLMMM8NOOLKNLLLMNNMML:KLM:KKM:LLNKNMNNNMMLMNLNKNLL:MKK:MOKKLL:NLLLLNMNMKKKNLL:LLLN:LLKKOJOKKLLI::JLNNMN::LKLN:LLKKLLKKOJOKKKMJ:JKKKNMNNLLKLLMLLKKOOOKKKOOOKI9NNJ::NKKNM:LMMLLLLKKKONOOOOLNN:::NMKN:K:MMNKLLKKMLMNOOM:LKNKLLIL:NNNKM:NMNNNNLLKKKNLL:MLKLLMMNNNIKNMM9KNNOMNNNNNNMLLN:LLKMLLLLNN9INMLKNMOMMMNNKKI9NNLLLKKOJKMLMNNMML:KLMMKMLNLNN:::NMKKKKKONKKNLL:MKK:MMK:LKNKLLIL:NNNKMOOOKNNNLN:LLKKOL:LKLLMMNNNIKNMM9KK9MMNKINLLKKOJKLþMLLLLNN9INMLKNNKLMNI9NNLKKKOþKMLMNNMML:KLLK:LMMNNMLMKOOþKNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKþOOOOÿþKþ8KKKþKþ998:8K:KKK9:þ78877:ML7KþKþ9þ79997:77:79Mþ9þ9þM88MNM97K9:898KKþ9þ7::NNNNN888L7ML9989þ7þ	MN8779MNN9N98:L8MMNM:896þMMNN97N797NM;<877NMLLLK7þMLNLNM887K8;;<LM<699KL98:þLKNKLNLL899:977M<7M76K89LLþKLLMNNNN:K99K8M<<6:898LLLKLþNMLLLLNNN:NN88<K7:97LLNKKLLLþ:JKKKNNKNNNKKM8887LN:JMNNLLNKþKKK:LLLLOJLLNNNML::JNN9IKNMO:þKNLL:LLKKOJLKNK::NKMN:::NMMM8þKLLLLL9KOOOKN:N:MKNNN:LILLMKNþ:KKKKLIKKOKJ:MKK9MMNKINNNKL:Nþ8MMMMK:KMKKKK9MNKLMNI9NNLLKLMþNNMNNKLMMNNNNKLLK:LMMNNMLMMMNþNMNNNLNNNMMMLK:M:KKM:LLNKLMKNþMNMKLLMMMMKKM:KOKKLL:NLNNKL:MþNMMMNNNNLKK:OKKJOKKLLKKKLLKNMþNKMLLN88KLLLJOKOKKKMNKKLLNNNNLþM:LKNNN9ILM:OKKOOJ:JMNNKNNNMOLLþMNKLLKKKI9:LOON::JNNNKKLNNKMNLLLNNNNLLKKNMI::K:NKM:JMNNNKKNMOLLNOMNNNNNNMJ:JK:MK:JNN9IKKNNMMMNMOMMMNNKKI9NNJ:K:NKMN:::NNLNLMKMMMKMLNLNN:::NMK:MKNNN:LILLKNKL:LMK:LKNKLLIL:NNNK9MMNKINNNMMLLKLKL:LKLLMMNNNIKNMNKLMNI9NNLLLLMKLLKLþMLLLLNN9INMLK:LMMNNMLMKLMLLMþKMLMNNMMLM:KKM:LLNKMKLMKþ
KNLL:MKOKKLL:NLNKLNKþLN:LLJOKKLLNL:NLþLLKOKKKLLKLLþKOOKKKKKþOOOOOÿþ:8;7þKN:98<88þMLNNN9<LMLK7þ9<M<NMM<8:MMM8MMþM<M<<LNNLK:99::M<MM9þ
NK9<N97K9NNM<L:9LNK7MMK8þ7::N7779779:MMMM:L<<KMLMLKK7þNL8799NN99:NMLNNMM9:<MLL77MK77OOMNNN97999::<N<MM:<;:KNL:K7K7KKKONMMNKM887<MNNNMMLK:M9:88:9LLKKOJNNNMKKNN898:LMNNMMM:6:89LN:LLKKONKNNMKLNN:99K8=<=::898KNLL:MKK:MMLJKNKK::KLL88;LLL97KMLMNNMML:KLNNMKOOOKKKKNLL88LLMLLLLNN9INMLKNMMKLMMK::KKKMLLLLKLLMMNNNIKNMM9K:NNNKMMKKKNL:LMM:LKNKLLIL:NNNKM::NMKN:KNKKLLKLO:KMLNLNN:::NMKN:KMLLLLNKNNLNLNO:KMMMNNKKI9NNJ::NKLLMKNNNNKNNNNNKKOMNNNNNNMJ:JKKKNKNKLJLLNNN:LLLKNNNNNLLKKNMI::JLLLNLNLNNLN:LLN_:KMNKLLKKKI9:LLLNNMNNK:KNLL::KK:MMM:LKNNN9ILM:::KNNNNNMLMMMMML:KLNNKMLLN88KLLLKMLMNNLLKMNMMKNNLKNNNMMMNNNNLKK:MMMNKLKKKNNNINNNNMNNMNMKLLMMMMKKNMNNLKNNJNMMMNNNLLNNNMNNNLNNNMMMMJNMMLNKIKNMMNKKMMKKNNMNNKLMMNNNKIKNMMNNNKNNNMKKNNLL8MMMMK:KMKKK:9KNMKLLMMNKNNMKLNNN:KKKKLIKKOKJLNKNNNNLNNMLJKNKK:::KLLLLL9KOOOKNKMMMNNKLMNNMKKOOO:KKNLL:LLKKOJLKNKNMMKNNNMMKLLMKK:KKKK:LLLLOJLLNNNMþKKKKKKKLL99NMJ:JKKKNNKNNNKKMþKKKKKKKNNNNNNMLLLLNNN:NNþ
KKKK:M:KMNKLLMNNNN:KþKNL:LMM:LKNKLNLLþLKLO:KMLNLNMþO:KMMMNNþKOMNÿþ9K9þ89þKK899þ::9K9K:KKþ98þKJ:KKþ99KM7698LþJþJKþ:þ9LM97L8M69þIþKJ:::LLK8MM:NNKK88þKþKþKJKþ:L8:MKKNNKK:77Kþ99KþKKKKLKMKNLKK:99NNþKþII9KþLKNMKK::9NMKNþJIþJKKKLþ9:LMLL8NNNNONþJ:I:ONNJ7LLLNN7L7NLLKMNMMþ:J:8JN8JN99KMM8KKLNMKKNNOþ:þMM88NNLL9LM::LKNOLKNLLþKþKJM888LK8NNKN:KMNKL:Mþ:þJK:J8::MLLLMLN:LMM:LKLMþNN9LLLKLK:J:JNNNN:KLKMKMLLLþ:JKLMML88LMM::KNNLLKKMMMMNNþ9J:LKOO88K:N:JJJ:LNMKKKNMNNMþ9þKKMLOI9IK:JK:JL:KKNLKMMKNMNþMM9NO8K9þLL:I:L:L::NNNMKKNNþ::NKJ:MþMMNL:LKL::KNNLKNNþIIN9JMMþNNNMNK:MLLMLNNNMKNþ9L9JþNNNNNN::KKMMMONNNMMþIþ9KNNI9:NIJKKKKKK:KMNKNMþK9J:M:N9L:NN:KL:LKN:LMM:LKLþ9LL:9IKJ::MMKN:MLLKKK:KMKKL:þ9Kþ8LKKM9KMMKKMMNNþ::LMM:LKLþ:L:þMMKNM99þNNNþKKLNNKMLLþIKþK8M8LKþLLþIþLLLKKMMMMMþ:L:þ8LLNþL:KK::þKKþNNþJL:þ:þLL::þL:LþL9þ99þMMþL::þNN:MMKKþ::LKLLLKþLJLNLJ:MLMMKþLLKþMLNKþNN:KNL:NMLKLNNLþNKþLNNJLNLILNLKNþNLþOþMþKLLLþNNLþLþMNNLNLLNNLþNOOKþMLLþLþNMÿþM6þM96D697Mþ7MNKK77MMMM9þ9LLMNNMK96DMMM69þ99L9:KNKKL9999MMM68þ9LLLL:KLKK9L997LMNNLL667þLLLL7KL:LLKKK:9LMMN:9LLLLK9þLKKLþLLN799K9K:9NMªKL:68::K9KþL:INN99KK9LK89MKL:K69L:L88:K8ONNN::N::N9:K:89MM9K9K699:NO9:O:NNNMINNNNKKK::99N99K:KK9KLþNKMKNNNþ::IKKMM:88Mþ9K:K8KN:8OþNNMLLLLNþKKK:MþIþNMþ9KKþK:M:KMNKLLMþNNþ99MMMIL:NNNKMþKKNL:LMM:LKNKLþNKKNM:::NMKN:KNKKLLKLO:KMLNLNþ999þNNI9NNJ::NKNNLNLNO:KMMMNNKþKKLL99NMJ:JKKKNNKNNNNNKKOMNNNNþKKNNNNMI::JLLNNN:LLLKNNNNNLLKþKKMNI9:LLLNNLN:LLN_:KMNKLþKKþNNMM9ILM:::KNLL:þKK:MMM:LKNNþKKLN88KLLLKMLMþMML:KLNNKMLþJ:KNM89LKK:MMMNMþNNLKNNNMMMNNNþ::LK9LNþMKKNMNNþNNMNNMNMKLþMMþMM::KKMMMMMJNMþNNþLLNNNMNNNLNNþL99KþMNNNKIKNMMNKþMMKKNNMNNKLMþI:KKþMKKK:9KNNNMKKNNLþMMMþ	IKKOþJLNþNKNNMKLNNþKKKþ99KOOOKNþMMLJKNKK:þLLLLþL9KKþOJLþNþNNMKþOOþKKNLL:LþLLKþOJþNNNMMKLþMKþ:KKKþLLLþLþK9LþKNNLLLLNNMMKOþMKKþ:Lþ:9LLJLNL:LþMOMNNNNNNNNþ:LþILLþL:OL:þLLNMþLMOLNþMþ	:þKKLLNL:NMNMKKþLLNþKKLNNLMNNNOLKMNþLNþKLLNNNNNLMOLKþNMNNLMLLLþLKþMMMLþMÿþK9þ:K9LLMþM9LLKKþLþMMM6M6K:KKþKKKþM77M769999K:L9:þ8M7MM677LL7:KKLMLLKKþ
MM8MMM69LLLLK9:97:LM9þKþ	NNNK779K97LMLM:7K:KLM8Kþ	MMNKLN8799MLL:LKLLKK9K::KþLLKLK:::97M::LLLL7:M:9þKþMMKKKLMM:L9::LLLKKK:KKNþKþOOLKKLN:KMMKKKKKK:::KMMNþOONMKL:LMM:LKKN:NNNMKKNNKþNNKLL:KLLNKMLLNNLKNNLKNNKMKLþ::MMNLLKLNMMMM:LMLNNNMKNMKMLLþMMNNNNNKMNKMMNKMMMONNNMLLKKLLKþNNNLNNNNNNLLKNMMMKKMNKLNMLLKKþMMMM:KMNKLKMKK:M:KMM:LKLLKKLþNNM:LMNNLKLLLKL:LMMMKKLLKKKKKþMM:KLNKKNNMNNNKK:KMKKþKKKKMNKþMMLKNLLMMMNNMLM:LMM:LþKKMNKþKþMMLKLNMNMNNNNN:KLNNKMLNNþKKNNKþMM:LNMNLKNNONNLLKKNMMMNNKKMþKKþNNKNNNNN:KMMKLNMKKKþKK:þNNNNNNN:LMM:LKKþMMþMþKKþNN:NKL:KLLLKMLLNNNþ:þMKKþLLþMMMMMNLLKLNMMMM:Lþ:MKKKLLþLLþMMMNNNNNKMNKMMNKM:þ:MMKKLLþNNNNLNNNNNNLLKNþM::KKMMMþLþMMMMþNNKLKMKKþMKLKMMþMMMMþNNþLMMKKþMMMLLL:MþKþMMþMMþLKNLþLKKþML:þMMþMþLLNþNLLMKMþLLLLþMMKLþLNNLLþLKþL:þMKþMMNLLþLKþLLLþKKþNþLLþLLþKNMNNMLLþMMNMÿþ9þ999M7þ::69KK7968M6þ978879K7:8888867þ997:77:9K77796M68789þM867K¨¨K7MM8:8988M78776þK876798¦:7:KNM:89MMM779778þKKKLK978M¨LM:MNMM8NKL9989:86OOþKþL989978MLM:LNNN«N9L8L898KKKOþKþK98989:MLLLKNLMLMLKL9LLKKOJþKLKKNKK988:MML756NNNMLLLN:LLKKOþKLNNMJ:KK99:88:9887MLKNLL:MKK:MþKKKI9NNJ:KK89::8799KMLMNNMML:KLþNKN:::NMKN::K8989MLLLLNN9INMLKNKM:LIL:NNNKM:LLKLKLLMMNNNIKNMM9KKMNNNNIKNMM9KLLL:LKNKLLIL:NNNKM:KNNLNN9INMLKN:JLNMLNLNN:::NMKN:K:OMLMNNMML:KLKKKNMMNNKKI9NNJ::NK8MMKNLL:MKK:M::NKMNNNNNNMJ:JKKKNNKMKNLN:LLKKOKN:KNNNLLKKNMI::JLLN:LKNLNLLKKOJNKM:NKLLKKKI9:LLLNNMLKLLMMLLKKKOMM9K:LKNNN9ILM:::KNNMMMLLLLNKKOOMLKNKMLLN88KLLLKMLMNKMLLKMLMNNOOL:KLMMMNNNNLKK:MMMNM:LKNNNKNLL:MKK:MNMKLLMMMMKKNMNNMNKLLKKKILN:LLKKOMNNNLNNNMMMMJNMNNNNLLKKNMILLKKOJNMNNKLMMNNNKIKNOMNNNNNNMJ:JKKKKOMMMMK:KMKKK:9KNMMMNNKKI9NNJ::NOOKKKKLIKKOKJLNKNKMLNLNN:::NMKN:KKLLLLL9KOOOKNKMM:LKNKLLIL:NNNKM:KNLL:LLKKOJLKNKNLKLLMMNNNIKNMM9KKKK:LLLLOJLLNNNMþMLLLLNN9INMLKN:JKKKNNKNNNKKMþKMLMNNMML:KLNMLLLLNNN:NNþ
KNLL:MKK:MKLLMNNNN:KþLN:LLKKOLKNKLNLLþLLKKOJMLNLNMþKKKOMMNNþOOMNÿþ©þ¨þ9þ¨þ¨6:þ8þ:9þ©þ¨87M8þ96897777§¨M788898K7Mþ
K877K6L=<=¨<==ML889:9LþKKKKK8888LLN©<LM86898LLKLþKKKNNN8K97K8N<<7:§9¨LNKKLLLþLþNKMLLN88ILM:7787:::L:JMNNLLLKLþM:LKNNN9ILM:LL:89L:JNN9IKNKKLKLþMNKLLKKKI9:LLLLL:NKMN:::JMNKKLLKNNNNLLKKNMI::JL:MKNNN:JN:JMNNLLKOMNNNNNNMNNN8KKK9MM:NK:JNN9IKLK:MMMNNNKMLLN88ILNKL:M:NKMN:::NK:8KMLNLM:LKNNN9ILLK:K:MKNNN:LILM8N:LKNKMNKLLKKKI9M:KNK9MMNKINNNNNNLKLLMNNNNLLKKNMOKKLNKLMNI9NNLMNMNMMLLOMNNNNNNMJJOKMLK:LMMNNMLNMNMMMNKMMMNNKKI9NOKKOM:KKM:LLNKMNNKMLLNKMLNLNN:::OOKJOKKLL:NLLMKNM:LKNN:LKNKLLIL:NNNOJOKKLLNNKL:MMNKLLKLKLLMMNNNIKNMOOKKKKKKLLKNMNNNNLLKKMLLLLNN9INMLOOMNKKLLNNNNOMNNNNNNMJKMLMNNMML:KLJMNNNNNNMOMMMNNKKI9NNJKNLL:MKK:MN9IKKNNMMMKMLNLNN:::NMKNLN:LLKKO:::NNLNLMK:LKNKLLIL:NNNKM:LLKKOJ:LILLKNKL:LKLLMMNNNIKNMM9KK9KKKOINNNMMLLKLþMLLLLNN9INMLKNNKLMOO9NNLLLLMþKMLMNNMML:KLLK:LMMNNMLMKþ
KNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKÿþ87866KKþ99878M7M7K78þ788777MMMMM86þ79997MMMM7:M8697þM88MNMMMNMM888876897þ
7::NNNNNNMM7MM77897:7þ	MN8779MNNNNNNNM87M89M886þ7þMMNN97N797NN79MMMM777:97K7:þMLNLNM887K87788M666M9788:9LþLKNKLNLL898777879MM76K89LLKLLKþKLLMNNNN:K99K88K96:898LNKKNKKLþNMLLLLNNN:NN88KK7:97L:JM:JMNNLLþ:JKKKNNKNNNKKM8887L:JN:JNN9IKLLþKKK:LLLLOJLLNNNML:NK:NKMN:::NLKþKNLL:LLKKOJLKNKN:MK:MKNNN:LNKKLLKLLLLL9KOOOKNKMMK9MK9MMNK:JMNNLK:KKKKLIKKOKJLNKMNKLNKLM:JNN9IKK:8MMMMK:KMKKK:M:LLK:LK:NKMN:::NM8NNMNNKLMMNNNKMNKM:KM:MKNNN:LILNNNMNNNLNNNMMMMNNNOKKOK9MMNKINNNMNMNMKLLMMMMKKNOMNJOKJNKLMNI9NNLNMNMMMNNNNLKK:MMMMOKKOLK:LMMNNMLMNNKMLLN88KLLLKKMLOONOM:KKM:LLNKKNM:LKNNN9ILM:::LKNKLLOKKLL:NL:L:MMNKLLKKKI9:LLLKLLMMNJOKKLLM9KKNMNNNNLLKKNMI::JLMLLLLOKKKNMLKNNNNOMNNNNNNMJ:JKKKNNKMLOONMML:KLNMOMMMNNKKI9NNJ::NKKN:KNLL:MKK:MMMMKMLNLNN:::NMKN:KK:NKMLN:LLKKOLMK:LKNKLLIL:NNNKM::MKNNN:LLKKOJKL:LKLLMMNNNIKNMM9KK9MMNKINNKKKOLKLþMLLLLNN9INMLKNNKLMNI9NNLLOOMþKMLMNNMML:KLLK:LMMNNMLMKþ
KNLL:MKK:MM:KKM:LLNKþLN:LLKKOOKKLL:NLþLLKKOJJOKKLLþKKKOOKKKþOOOOÿþ<7<7þK8:68K:7þ¤ªªML¦££¥<K8þM¨¤ªMM¥£¨§¤¤<<MMþMMM§§ªMM©¥££§©<<<997þMMNN¨¨«N«§¨ª¬¬ª<<M¨£¤98þ7::NNNNN©©ª«§©ª¬¬M<:©¤¤¦LKK7þNL8779NNNN¨¨«ª¨§«¬¬NML¨©©¨MK77OOMNNN977KKNN¨¨©©¨«¬¬NNM©§©L:7KKKONMMNKM887KNNªªª©«¬¬NMª¨©8:LLKKOJNNNMKKNN898N©©«ª«¬¬7Nª8KLN:LLKKONKNNMKLNN:99K88©ª6:898KNLL:MKK:MMLJKNKK::KLL88K¨7:97KMLMNNMML:KLNNMKOOOKKKKNLL8887MLLLLNN9INMLKNMMKLMMK::KKKMLLLLKLLMMNNNIKNMM9K:NNNKMMKKKNL:LMM:LKNKLLIL:NNNKM::NMKN:KNKKLLKLO:KMLNLNN:::NMKN:KMLLLLNKNNLNLNO:KMMMNNKKI9NNJ::NKLLMKNNNNKNNNNNKKOMNNNNNNMJ:JKKKNKNKLJLLNNN:LLLKNNNNNLLKKNMI::JLLLNLNLNNLN:LLN_:KMNKLLKKKI9:LLLNNMNNK:KNLL::KK:MMM:LKNNN9ILM:::KNNNNNMLMMMMML:KLNNKMLLN88KLLLKMLMNNLLKMNMMKNNLKNNNMMMNNNNLKK:MMMNKLKKKNNNINNNNMNNMNMKLLMMMMKKNMNNLKNNJNMMMNNNLLNNNMNNNLNNNMMMMJNMMLNKIKNMMNKKMMKKNNMNNKLMMNNNKIKNMMNNNKNNNMKKNNLL8MMMMK:KMKKK:9KNMKLLMMNKNNMKLNNN:KKKKLIKKOKJLNKNNNNLNNMLJKNKK:::KLLLLL9KOOOKNKMMMNNKLMNNMKKOOO:KKNLL:LLKKOJLKNKNMMKNNNMMKLLMKK:KKKK:LLLLOJLLNNNMþKKKKKKKLL99NMJ:JKKKNNKNNNKKMþKKKKKKKNNNNNNMLLLLNNN:NNþ
KKKK:M:KMNKLLMNNNN:KþKNL:LMM:LKNKLNLLþLKLO:KMLNLNMþO:KMMMNNþKOMNÿþ9þ:Lþ788MMMMMþ68M8NMMMM797þ69M99NMLMM76987þ9þ999KK7M:MK7MMM69þ8767757:668999LMNNKK88þ	877KKLK599668©MMMNNKK:77KþL8KK8L:LM7668þKLªNNLKK:99NNþLLK:::LMMMK665þ7LMKK::9NMKNþ8KKK9NNNK9:KKLþ868MLL8NNNNONþII8:NKI9KKNNL7LLLNN757NLLKMNMMþLLNþ8I8:98LN99KMM8KKLNMKKNNOþ::þK8KLLMM8KNNLL9LM::LKNOLKNLLKKLþ9K9KKLþ9KK888LK8NNKN:KMNKL:Mþ:K::N:JM::8JJMLLLMLN:LMM:LKLMþ:KKKNN9LLLJ9KJ:KKNNNN:KLKMKMLLLKK:K:::KLNMJLLLMMKKKNNLLKKMMMMNNLLþ9LLLLKOO88K:N:KKK:LKMKKKNMNNMþ9LþKKMLLLJ9KL:K::L:KKNLKMMKNMNþMM9NOLK9KLL:LKL:LK:NNNMKKNNþJ:NKKLMþMMNL:LKL::KNNLKNNþJJNKKMMþNNNMNK:MLLMLNNNMKNþLLK9þNNNNNN::KKMMMONNNMMþLLþKKKNN:KMNK:KJJKKK:KMNKNMþ:KM:N:LMNN:KK:LKN:LMM:LKLþLK9LKK:KKLKN:MLLKKK:KMKKL:þ9LKKM:KKLKKMMNNþ::LMM:LKþLþMMKNK:LLþNNNNþKKLNNKMLþ
KMLLKKþLLLKKMMMMþLLNNþKKKþÿÿþ7M§MþM9§M©97Mþ7MNM§MªMMMMMþMMKMNNM§©MNMMM69þ766667NMNMM¨NNMMM686þ
57776KK96NNNMM¨NMNN66667þL7777KKKKM566NNN¨NNN56777K9KþLKKKþLLNN:57577NNMªKL5K:K:K9KKLJJNN99KK9L9K59876N6ªL:LLKKK8ONNN::N::N9:K:9K8K875665ª:NO88O:NNNMJNNNNKKK:KKLNNL8K5L::LþNNMKNNNþ:KKLKMM:KK9MK7LMLLN:8OþNNMLLLLNþKKK:MKK:Nþ:LKLLNK:M:KMNKLLMþNNþ99MMMKK:NNNKMKK:KNL:LMM:LKNKLþNKKNM::LKMKN:KNLMLLKLO:KMLNLNþKKKþNNKKNNKK:NNNNLNLNO:KMMMNNKþKKLL9JNMK:K:MKNNKNNNNNKKOMNNNNþKKNNNNMK:M:LLNNN:LLLKNNNNNLLKþKKMJ9J:MNMNNLN:LLN_:KMNKLþKKþNNMMKNNN::JKNLL:þKK:MMM:LKNNþKKLNIMLNLNMMLMþMML:KLNNKMLþ::KI8LLLKM:JMMNMþNNLKNNNMMMNNNþ:LL8J8NþNKNMNNþNNMNNMNMKLþMMþMMJ:KþMMK9NMþNNþLLNNNMNNNLNNþLK9þNNK9KNMMNKþMMKKNNMNNKLMþ::þ:K9KNNNMKKNNLþMMMþLLNþNNNNMKLNNþKKKþLLNþMMLLKNKK:þLLþNNMKþNNþMMKLþLLþÿÿþ:9:8þ797999N:þ88::7K969:9þ:7::788K999:9:9þ99:77K9778979LMLþK9þ88:97N78K88M7LKKNL:Kþ
88:696NN998KK77:L9MNþKþMM868:658MLL9LM7LLLJ:LLþ	NNNK779997L8LK57KLL:LNMKKNþMMNKLN875979885K:KLLKLLLKKþLLKLK:NM7777957LLKKMLþLLLKþMMKKKLMM:L769LKL7:J:MþKKMþOOLKKLN:KMMK78LKKKJKKNþMMKþOONMKL:LMM:LKKN:J:JKMMNþ	NNKLL:KLLNKMLLNNNNMKKNNKþ::MMNLLKLNMMMM:LKNNLKNNKMKLþMMNNNNNKMNKMMNKMLNNNMKNMKMLLþNNNLNNNNNNLLKNMMMONNNMLLKJLLKþMMMM:KMNKLKMKK:M:KMNKLNMLLKþNNM:LMNNLKLLLKL:LMM:LKLLKJLþMM:KLNKKNNMNNNKK:KJJKþKKJKKþMMLKNLLMMMNNMLM:LMJ:LþKKMNKþMMLKLNMNMNNNNN:KLNNKMLNNþKKNNKþMM:LNMNLKNNONNLLKKNMMMNNKKMþKJJþNNKNNNNN:KMMKLNMKKKþKJ:þNNNNNNN:LMM:LKKþMMþJKþNN:NKL:KLLLKMLLNNNþLLþMMMMMNLLKLNMMMM:LþNJJþJLþMMMNNNNNKMNKMMNKMþNNNNLNNNNNNLLKNþMMMMþNNKLKMKKþMMþNNþMMKKÿþ	¥ ¢¢¢¢¥þ£¤¤£þ¢¢¢¤¤¤¤£¢þª©©«þ¤¤ ¤¦§¦§¤£§þ©©ªªþ¤¤¤£¥§¥¤¤£¡¬þ¨¨ª¬þª£¢££££££¤ª¬þ¨¨¨¬þ©©§¦¥¥¥§¨¨©«¬þ§ª§«þ©¦¦¥¦¦¦§¨ª««¬©«¨«þ©§¦¤¥¤¦¨¨¨ª¬¬ª¬ª¬þ¨¥£«¥¨«§©©¬¬«¬«¬þ©¥£©¦§¬§©ª«¬¬¬¬¬þ©¥¤¨¨§¬¬§ª«¬«¬¬þ©¥¤§¨®®®¨ª«¬­¯«þ¨¦¥¦¨®¬¥¨ª«¬­¯¬þ©§¥¦©®¬¬¨ª«¬­¯þNNNNþª§¥§¨©®¬¤©«¬¬¯þMþNNNNNNN§¥§§¨¬¥¨©ª«¬­NNNNþMþNNJKNNKL©¥¦¦§­¦¨¨ª«JKNNNNþJJKNJKL©§¤¦§ª§¨¨ªJLNNLKþMKJþJJLNNJLK©§¦¥¥©§¨¨JKL¬NKLJMMLJþJKLþNNML©§¦¤¥¨§¨©L««¬NLNNþLKJþLþNNLKNMKJ¥¥¦§¨ª««©¬NNNNNþLþJMLKLJMMLJ¥¦¨¨©««¨ªNNNNNNþMþKMMMLNNªªLKJ¦¦¨©ª­LK­NKJNNþMJKMKJNNN©©ªªL¨¤¥¨ª­KLJNNLJþMþJLMLMLJN©©¨©©ª©¨¤¥¨­LMªGGLKJþJKLMHHLKJ©¨©ª©¨¨¨¤¤¦«¬M«ªJGFLHþHFHHHEF¨L§¨©ªª©©§¥¥¤§«¬ª«ªJJHGIGþFIHG©©¨©©««MLL¨§§¦¤¥¨«®«¬JJGþH©¨©©««MLKKKLL¨¨¦¤¤§KLJIþ
KKKLKKJJKIJMM«ª©§¤¤IþGFJHJJJJIJKKLLLKþHGHGHJJJJIHFþGIHDHHDHþGHHJÿþ£¢¡¡¡¡¢¤¥þ£¢£¤¥¥¤¥£¤¥þ¤¢£¥¦¤¥¥¤¥¥þ©¤¢¢¢¢¢¤¥§©þ©©¨¤¤¥§§¨©ªþ©ª§¤£¤¦¨§ª¬þ©ª§¤£¤¦¨§ª¬þKLMþ¤§¨¤§ª§¤§©ª«ªþKLMþ¦¨©¤©®«¥¨¨«ª§ªþMþKLþNþ¨©¨¦¨«¨¥¨ªª¬§þLþLLNMLLþNN©©§¦£¤¥©©ªª¬§¬þLNNKLJNMLLþNN§¦£¦§¨§¦ªª¬©þNNNLMKNNNKLNN¨¤¢£¤¦¨ª©©¬ªNNþLNþNNMNLLNNLN¨¥££¤¤¦©©¨©¬«NNNþKJLMNKLNMKNNN§¥¢¤¥§§¦§§¨ªþNNNþKJLLLKLKLNLKNN¦££¤¥§¦§§§ªªþNþKLþMKLNNLNMþ¦¥¤£¤¥¥¦§¨ªª¬MKJþLMNMNNNNN§¤¤¤¤¤¤§§¨©ª©¬NMLJþKMMLNMKJNN¥£¥¤¥£¥©¨©ª¬«þNNþKþLNþMNNNMLJ¥£¤¥¦¥¤§¨§«JKMþKLNþLþNþMNNNNNKJ¥¤¦¦¤¥©¨¨JLM¬JLKþNþLNNNNNªªL¥§§¤¤¦©¨JKª«¬KMLMKþLMNþN§¥¨ªªª¨¤¤¦¨¨©L«ª©«¬MNNMLþLþNþ¥¤¦¦¨©­¨¦¦¨©ªªªªª¨©«¬NNNþH¥¥§©¬ª««¥¦§ª«¬¬«ª©§¨©«¬þNNþHH¥¦¦§¬ªML¥¦¨©«¬MLL««©©¨©¬NHþHHHH¨¨©¬LMK¥¨©¬«LKJJKLªªªª¨ª©¬JGþHIHIIJKK§¨§«¬LKJJIIJJKL¬ª¨©HþHHHHG§©«©«LJIIHGHIIJKLLJþ
HHF§§©¬LKKIHHHFHIIIGþGHIIILJFIIHIHHIIþHGHGHIGHHIHHþGIHDHHDHþHHHHÿ