þMþJLMøþIIIGMYþ@HIEFIK	þA@BFDGIIK	þCA@BCECHGJ
þB@@@B@BCGFCKYþ@@@@@D@@@GEBI	
þJFILI@@@B@DDAGJX
þLJHLLIIK@BDC@@HKXY	þ
LJIGJJIKLLLLI@CHVTTUY
þLLIIJLLIKLLJGGJKWSTTTT•þJKIIJJLKIKJIIIG	WYYUST•þSUWXYLLLKJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGE@EDJKGKYþ@EEE@E@@@GKEK	
þFCEHI@@@E@EKEGJX
þBCBDEBCD@EKJGGJKXY	þ
F@@ADCAEGGIIGGJKVTTUY
þKLI@BBB@EHHHGGJKWSTTTT•þJJIJJ@@@@EHIIIG	WYYUST•þSUWXYJJCDFG		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGGBGDJKGKYþBDDEBGD@BGKEK	
þJFIJKB@BGBGKEGJX
þFJHJJHGGBGKJGGJKXY	þ
@@@GJJGIJKKIGGJKVTTUY
þKJF@FLLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGIEIDJKGKYþFDDEEKEADGKEK	
þJFIJKEAEIEKKEGJX
þGJHJJHGGEIKJGGJKXY	þ
B@BGJJGIJKKIGGJKVTTUY
þKJGBGLLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGIGIDJKGKYþFDDEGKGDDGKEK	
þJFIJKGDGIGKKEGJX
þIJHJJHGGGIKJGGJKXY	þ
EAEGJJGIJKKIGGJKVTTUY
þKJIEILLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGIHIDJKGKYþFDDEHKHHDGKEK	
þJFIJKJGGIHKKEGJX
þKJHJJHGGIIKJGGJKXY	þ
GDGGJJGIJKKIGGJKVTTUY
þKJIGJLLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþMþMLMøþLKKGMYþFKJGGIK	þHDIIFJLLK	þJHDIJHJLKK
þIGFGIJIDJKGKYþFDDEHKHIDGKEK	
þJFIJKJIGIJKKEGJX
þKJHJJHGGIIKJGGJKXY	þ
IGIGJJGIJKKIGGJKVTTUY
þKJIGJLLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþKþFEJøþEDD@IYþ@DC@@BD	þJIHF@CEED	þKKHLLJLLKK
þJIHHIJIGJLIKYþGFFGHKHHGILHK	
þJFIJKJIGIJKKHIJX
þKJHJJHGGIIKJGGJKXY	þ
KIIGJJGIJKKIGGJKVTTUY
þKJIGJLLGIKKJGGJKWSTTTT•þJIGGJJKGIKJIIIG	WYYUST•þSUWXYJJJJJK		YYY	
	YWVWVUþWWWVUTTTTUUVWXY
	XWWUSUYXWWTBRUVW




YWXTBVUþWVBTX	YWY
	


	


YWYTUþTøø	W		


ø
		YVU	þ
øXY	Yø
	ø


øþ8XUV

ø

øøþ778:
7469IHþ765448þÿþ

	YWWXWWUUWWþ
YWXVUUUUVUWþ
YWVTUUUUWYVþWVTUUUU	YYþ			Xþ
				þ				þ	þ>
þY
þY

þ	Y
þJJ	þKK
Y
þJKKYY

þKK	YY


M	Yþ	KXW	

	


ML	XXþYWVW		Y			
LL	VVXþ
VVVXXYXXYY	
MLL	VTTUY
þUVWWWWWWWXYMMKKLWSTTTTWXþRSTUUVVWWWY
LLLLLYYUSTTTVTþSUWXYTUWY	
LLLKKLLL	YWVRTTVSþWWWVUTTTVVVVWøø
øKKL	XWWWRTWTYXWWTBRUVWYYY	
LKKø

YYWWXTQYXþWVBTX	YWYYY
LL
YYWWYTUþX		W		

	øø
VUY	þ
ø		YY
ø
UUUþø	YYYø
ø	Wþøø7:K

þøP79:þ¥¦9ÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þJLMø

XTBBBQSWV				
þ
IIIGMYYURBBQRUWW				
þ@HIEFIK	XWTBBBQSWVY		
	
þA@BFDGIIK	VVTBBQQUWVY		


þCA@BCECHGJ
SUUBBQRWVW			

þB@@@B@BCGFCKYVRTSBRUWUX		


@@@@@D@@@GEBI	
XVRQSUWVUY	



þI@@@B@DDAGJX
YXVTQRSTVWWYYYþ@BDC@@HKXY	YWUW4VUSSRRTþ
I@CHVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYY†URBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGE@EDJKGKYVRTSBRUWUX		


@EEE@E@@@GKEK	
XVRQSUWVUY	



þI@@@E@EKEGJX
YXVTQRSTVWWYYYþ@EKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYYURBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGGBGDJKGKYVRTSBRUWUX		


BDDEBGD@BGKEK	
XVRQSUWVUY	



þKB@BGBGKEGJX
YXVTQRSTVWWYYYþBGKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYYURBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGIEIDJKGKYVRTSBRUWUX		


FDDEEKEADGKEK	
XVRQSUWVUY	



þKEAEIEKKEGJX
YXVTQRSTVWWYYYþEIKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYYURBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGIGIDJKGKYVRTSBRUWUX		


FDDEGKGDDGKEK	
XVRQSUWVUY	



þKGDGIGKKEGJX
YXVTQRSTVWWYYYþGIKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYYURBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGIHIDJKGKYVRTSBRUWUX		


FDDEHKHHDGKEK	
XVRQSUWVUY	



þKJGGIHKKEGJX
YXVTQRSTVWWYYYþIIKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þMøþXRBBQQTWY		
þMLMø

XTBBBQSWV				
þ
LKKGMYYURBBQRUWW				
þFKJGGIK	XWTBBBQSWVY		
	
þHDIIFJLLK	VVTBBQQUWVY		


þJHDIJHJLKK
SUUBBQRWVW			

þIGFGIJIDJKGKYVRTSBRUWUX		


FDDEHKHIDGKEK	
XVRQSUWVUY	



þKJIGIJKKEGJX
YXVTQRSTVWWYYYþIIKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿþXSUW	
þþWQBQTWX	


þKøþXRBBQQTWY		
þFEJø

XTBBBQSWV				
þ
EDD@IYYURBBQRUWW				
þ@DC@@BD	XWTBBBQSWVY		
	
þJIHF@CEED	VVTBBQQUWVY		


þKKHLLJLLKK
SUUBBQRWVW			

þJIHHIJIGJLIKYVRTSBRUWUX		


GFFGHKHHGILHK	
XVRQSUWVUY	



þKJIGIJKKHIJX
YXVTQRSTVWWYYYþIIKJGGJKXY	YWUW4VUSSRRTþ
GGJKVTTUY
YVUWÐ6FWUWþWSTTTT•XWVXÐ6@WþST•WWXÐ8þWVUT•W6þSUVUÿ

	YWWXWWUUWWþ
YWXVUUUUVUWþ
YWVTUUUUWYVþWVTUUUU	YYVþ			XWþ
				Yþ					þ	
þ

		þþ	Y	

þ
þ
X
þY
àþ		X
þ
Y

ø
Pþ	
W	þ	Y
ø
à

W	þJJ	P
ø
W	þKK
Y
ø	
à
XþJKKYY

WYøX
KK	YY


M	YXW
Y	
þ	

	


ML	XXVU
	YWWWYYYþ		
LL	VVXWRW

WSRRTþ
MLL	VTTUY
XVRWX
	VWWþWSTTTTWXYXVTV8	WþSTTTVTYWUWX6þTTVSTXWXþWTX	ÿþ
øgþPPPààþ
þ
øøøøøøþ
à
ø

ø¥§þ

P
øPøø
Pøgþ


à
à
ø
þ
PPP
øøøP
øP
PPþøPPàø
P
ø
PPPþøPPà
P
øàø
Pþ
øPPPø
àPPþøPPà
PPþøPPPPPþøPPPPþøPPÿþ	YþUW	XþXXUWWTþUUWXYUWTþøøø
þ

6DDþ689:øø7D0Dþ
ø876D20027øRBþ
à
øøøø
õþø
Høø¦ø

9<þ
¦ø
9H¦:9<Hþ¥
øøø66•–I¦IHþ




ø:6:H•	þ
P
øPøø
P
<889<LPPþ


à
à
ø
Pø
PPP
øøøP
øP
PPþøPPàø
P
ø
PPPþøPPà
P
øàø
Pþ
øPPPø
àPPþøPPà
PPþøPPPPPþøPPPPþøPPÿþQRTTþUWUQTTTTþXUWWURTTTTUþHIKWUWXURTTTUU
þ::II:WUUTURBBRø
þ
ø8678:
RBBB†þ


657BQQBBQRQ†¨§¦þ

ø<BQRRQ§¦¦ø
þø
ø

Qøø
þø


øõRõø
þ
øøøø


ø¦õøøþ††¨¨¨¦¥gõøøþ¦¥gõþ§

þøÿþ

		þþ	Y	

þ
X
þ		X
þ	
W	þ

W	þW	þ
Xþ
þ>XWþUWY
þWY	

þWWWWXY
þYWXVWWWW	þ8CYXWVUSUWY
þXY5F	XWVSV	

	þY
	5EH	XXTW
þ	Y		58CI
XXV	IKþUW	XTTY
EH
	YV
JHIJ†þ
XXUWWTTTWYWDIøI•–þUUWXYUWTTW7WVVFG
øIHþøøø
76QLKHFHIIHþ

6DDRQBMKKJIHJþ689:øø7D0DBBQRJIH•–Iø
ø876D20027øRBBQõHJLPPþ
øøøø
õQR		
PPPþHøø¦ø

9<õB	
Pþ
H¦:9<HB	àPPþ–I¦IH		PPþ•	PPþLPPPPþøPPÿþXSUW	
þþWQBQTWX	


þXRBBQQTWY		


þBBBQSWV				


þQRUWW				
	
þWVY		
	

Y	þY		


Y		þ	

Y	Yþ


	Yþ
	Y	þXWY

þUWY

	þWY	


	þUVWWXY	
		øþ@WVVWWWW	
	Y†
øþ
5X@WWVUSUWY
	X



Pþ748	CFWVSV
	
YXIøø†
PþSSU6:GCWW–J

	JJ•L
PPþTUJBFHKI
LJH•L††
PPþUHJHB
øI–•HL†ø
Pþ
•

¨¦§†
àPPþø§g¨PPþø«¦gø
PPþ«§¥§øPPþ§øPÿþ

		þþ	Y	

þ
X


þ		X


þ	
W		
þ

W	
Y	þW	Y		þ
X	Y	Yþ
Y

	Yþ
	Y	þXWY

þUWY

	þWY	


	þWWWWXY

		øþYWXVWWWW	
	Yø
øþ
8CYXWVUSUWY
	X

PþXY5F	XWVSV	

	
YXIH–Iøøø
PþY
	5EH	XXTW

	
IH–Iø
PPþ58CI
XXV	IKø–øPPþEH
	YV
JHIJøøø
Pþ
IøI•–I
àPPþ
øIH•
PPþHIIHIP
PPþHJPPþøPPÿþþþþþþ
þþþþþ
þþþþÿþõôóóþõôóóóóñEþõôóóóóñEEEEEþõôóóóóñEEEDDDDDDþõôóóóóñEEEEEDDDDDDDDþ
õôóóóóñEEEEEEEEDDDCCCCDDþõôóóóóñEEEEEEEEEDDDCCBBBCCDDþöõôóðñEEEEEEEEEEEDDCCBBBBBCCCDDþööõôðóðñEEEEEEDDDEEDDCCCCCCDD÷øþø÷ööõôðóðñEEEEEEEEEEEDDCCDD÷øùùþøø÷ööõôðóðñEEEEEEEEEEDDD÷øùùøúþøø÷ööõôðóðñEEEEEEEEE÷øùùúúXWþøø÷ööõôðóðñEEEEE÷øùùúúXWXWþøø÷ööõôðóðõö÷øùùúúXWXWXWþøø÷ööõôð÷øùùøúXWXWXWXWþøø÷ööõùùøúXWXWXWXWXWþøø÷öøøXWXWXWXWXWXWþøøWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWþWXWXWXWXWþ
WXWXWXWþWXWXWþWXWþWþÿþõôôõþõôóóóóôõþõôóóóóóóóóôõþõôóóóóñDðóóóóóôõþõôóóóóñDDDDDðóóóóóôõþ
õôóóóóñDDDCCBBEEðóóóóóôõþõôóóóóñEEEDDDDDCDEEEðóóóóóôõþõôóóóóñEEEEEEEEDDDDDEEEEðóóóóóôõööóóñEEEEDDDDEEDDDDDDDDEEEðóóó÷øööööEEEEDDDCDDDDDDDDCBCDDEEE÷øùùøøööööEDDDDCCCCDDDDCBBCCDD÷øùùùùþøøööööEEEDDDCCCCDDCCDD÷øùùùùþøøööööEEEEBBBCDDDD÷øùùùùþUVøøööööDDBCBCCC÷øùùûûXWþUVUVøøööööDDBD÷øùûûûXWXWþUVUVUVøøöööö÷øùûûûXWXWXWþUVUVUVUVøøööùûûûXWXWXWXWþUVUVUVUVUVøøûûXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþ
UVUVUVUVUVXWXWXWXWXWþUVUVUVUVXWXWXWXWþUVUVUVXWXWXWþUVUVXWXWþUVXWÿþDCDDþCBBCCDCCþDDDCBAACCCCCþDDDDCCBBCCDCDDCDþEEDDDDDDDDDCCDDDDDEEþñEEEEECCCDDEEEEDDEEDEEEEEEþðóðñEEEECBCDDDDDDDDEEEEEEEóóóþõôðóðñEEEDCACCDDDEDDDEEEóóóðñõöþööõôðóðñEEDDDBACCDEEEEóóóðñõö÷øþø÷ööõôðóðñEEDDDDDDEEóóóðñõö÷øùùþøø÷ööõôðóðñEEEEEEóóóðñõö÷øùùþøø÷ööõôðóðñEEóóóðñõö÷øùùþøø÷ööõôðóóóóðñõö÷øùùþøø÷ööõôððñõö÷øùùþøø÷ööõõö÷øùùþøø÷÷÷øùùþøøùùþþþþþþþþ
þþþþÿþóóôõþóóóóóóôõþEEEEðóóóóóôõþCCCCECCCðóóóóóôõþCCBBBCCCCEEEðóóóóóôõþ
CCBAABBAABEEDDEEðóóóóóôõþDDDDBBBBABADEEDCDEDEðóóóóóôõþDDDDDBDCCCCDDDDCDCDDEDDEðóóóóôõöööDDDDDDDDDDDDDDDDDEDEEóóóðñõö÷øööööDDDDDDEDCDDDDDDDEóóóðñõö÷øùùøøööööDDDDECDDDDDEEóóóðñõö÷øùùþUVøøööööDDEECCCDDóóóðñõö÷øùùþUVUVøøööööEEECCóóóðñõö÷øùùþUVUVUVøøööööEóóóðñõö÷øùùþUVUVUVUVøøööööðñõö÷øùùþUVUVUVUVUVøøöööö÷øùùþUVUVUVUVUVUøøööùùþUVUVUVUVUVUøøþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUþUVUVUVUþ
UVUVUþUVUþUþþÿþõôóóþõôóóóóñDþõôóóóóñDDDDDþõôóóóóñDDDCCCCCCþõôóóóóñDDDDDCCCCCCCCþ
õôóóóóñDDDDDDDDCCCBBBBCCþõôóóóóñDDDDDDDDDCCCBBAAABBCCþöõôóðñDDDDDDDDDDDCCBBAAAAABBBCCþööõôðóðñDDDDDDCCCDDCCBBBBBBCC÷øþø÷ööõôðóðñDDDDDDDDDDDCCBBCC÷øùùþøø÷ööõôðóðñDDDDDDDDDDCCC÷øùùøúþøø÷ööõôðóðñDDDDDDDDD÷øùùúúXWþøø÷ööõôðóðñDDDDD÷øùùúúXWXWþøø÷ööõôðóðõö÷øùùúúXWXWXWþøø÷ööõôð÷øùùøúXWXWXWXWþøø÷ööõùùøúXWXWXWXWXWþøø÷öøøXWXWXWXWXWXWþøøWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWXWþWXWXWXWXWXWþWXWXWXWXWþ
WXWXWXWþWXWXWþWXWþWþÿþõôôõþõôóóóóôõþõôóóóóóóóóôõþõôóóóóñCðóóóóóôõþõôóóóóñCCCCCðóóóóóôõþ
õôóóóóñCCCBBAADDðóóóóóôõþõôóóóóñDDDCCCCCBCDDDðóóóóóôõþõôóóóóñDDDDDDDDCCCCCDDDDðóóóóóôõööóóñDDDDCCCCDDCCCCCCCCDDDðóóó÷øööööDDDDCCCBCCCCCCCCBABCCDDD÷øùùøøööööDCCCCBBBBCCCCBAABBCC÷øùùùùþøøööööDDDCCCBBBBCCBBCC÷øùùùùþøøööööDDDDAAABCCCC÷øùùùùþUVøøööööCCABABBB÷øùùûûXWþUVUVøøööööCCAC÷øùûûûXWXWþUVUVUVøøöööö÷øùûûûXWXWXWþUVUVUVUVøøööùûûûXWXWXWXWþUVUVUVUVUVøøûûXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþUVUVUVUVUVUVXWXWXWXWXWXWþ
UVUVUVUVUVXWXWXWXWXWþUVUVUVUVXWXWXWXWþUVUVUVXWXWXWþUVUVXWXWþUVXWÿþCBCCþBAABBCBBþCCCBA@@BBBBBþCCCCBBAABBCBCCBCþDDCCCCCCCCCBBCCCCCDDþñDDDDDBBBCCDDDDCCDDCDDDDDDþðóðñDDDDBABCCCCCCCCDDDDDDDóóóþõôðóðñDDDCB@BBCCCDCCCDDDóóóðñõöþööõôðóðñDDCCCA@BBCDDDDóóóðñõö÷øþø÷ööõôðóðñDDCCCCCCDDóóóðñõö÷øùùþøø÷ööõôðóðñDDDDDDóóóðñõö÷øùùþøø÷ööõôðóðñDDóóóðñõö÷øùùþøø÷ööõôðóóóóðñõö÷øùùþøø÷ööõôððñõö÷øùùþøø÷ööõõö÷øùùþøø÷÷÷øùùþøøùùþþþþþþþþ
þþþþÿþóóôõþóóóóóóôõþDDDDðóóóóóôõþCCBBDBBBðóóóóóôõþBBAAABBBBDDDðóóóóóôõþ
BBA@@AA@@ADDCCDDðóóóóóôõþCCCCAAAA@A@CDDCBCDCDðóóóóóôõþCCCCCACBBBBCCCCBCBCCDCCDðóóóóôõöööCCCCCCCCCCCCCCCCCDCDDóóóðñõö÷øööööCCCCCCDCBCCCCCCCDóóóðñõö÷øùùøøööööCCCCDBCCCCCDDóóóðñõö÷øùùþUVøøööööDDDDBBBCCóóóðñõö÷øùùþUVUVøøööööDDDBCóóóðñõö÷øùùþUVUVUVøøööööDóóóðñõö÷øùùþUVUVUVUVøøööööðñõö÷øùùþUVUVUVUVUVøøöööö÷øùùþUVUVUVUVUVUøøööùùþUVUVUVUVUVUøøþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUVUþUVUVUVUVUþUVUVUVUþ
UVUVUþUVUþUþþÿþ

þþ	þ
þþ	þ	þ

þþ	þ
þþ	þ	þ

þþ	þ
þþþþþþ		þ

þ		þ
þþ
þ	þþ	þ
þþ
þ	þþ	þ
þþ
þ	þþ	þ

þþ

þ
þ


þ
þ
þþ
þ

þþÿþ
õþõõþ
õõþ	õþþRFþRQQBþRQQQQQQQ@þ
RQQQQQQQRR5þRRQQQõõ	4RRRRõ	H5þRRRR	õ	•þRRRR		õõþ
RRRR			õõþRRR				þ			þ	õþÿ
þNMMMNNþMOOOOOOOþMOOOOOOOOþMOOOOOOOOþMLOOOOOOOOþMMOOOOOOOOþKNOOOOOOOOþMNOOOOOOOOþMMOOOOOOOOþKMOOOOOOOOþKLOOOOOOOOOþLLMOOOOOOOONþ
õIKMOOOOþõõJJMOþ
õõIJLNþ	õHJKI­­þõILJ
­
þ
RKKLK­þõõRQHKLK
þõ

õQQQQQQHJKõõ	þQQQQRQQRõþõRRQQQõõ	õõRRõõõõ		þRR			õ	þõRR	
	
	õõþ
RRR

õ	

õõþRRR	
	þ		þ	þÿþ
õþKþõõþK
þõþ	

þ	


þ	
Rþ	

RQQþ	

RQQQQQQQþ		
RQQQQQQQRR5õ
RRQQQõõ	4
	
			õ	
RRRõ	H5


			õ
	
RR	õ	•6
	
			

		R		õõ		79
		
			õ


					õõõ		86
							



				õõ			5L
			
	


			õ			–7:
	JH
	õõõõõ	õõ–7L	J–JMõõõ89M		L:75H<L:9•H9<:IH•I8589þõ••••J	õõþõõõþ
þþþUþÿþ
þRKþ
RQHKþ

QQQQQQHJþ		
QQQQRQQRþõ
RRQQQõõ	þõ	õ	
Rõõõõ			
	õ		õ
	
NM			õ					
		

N	
	
	õõ									õ
	N

õ	

õõõ												

		
	õõ			
				
	

		õ							JI

	õõõõ	õõõõ		
	J–JMõõõ	89M		L:75H<L:9õõ––HI<:IH•I8589þ–•–õõ–•••J	õõþõõõõõþ
õþþþUþÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLJMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKJIJKLMþ
õIIFBDEMJLMLKEDHMMKJKKKþõõJMGBIDKMKLMLHDJMOOMJIK
þõILGDJDGICLHFCAMOLOOOK	

þHKFDHBJIHEDAAEAJLMOOM	

þGHEBF@EDBBAABDEGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLJMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKJIJKLMþ
õIIFBDEMJLMLKEDHMMKJKKKþõõJMGBIDKMKLMLHDJMOOMJIK
þõILGDJDGICLHFCAMOLOOOK	

þHKFDHBJIHEDAAEAJLMOOM	

þGHEBF@EDBBAABDEGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKJLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLJKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKJIJKLMþ
õIIFBDEMJLMLKEDHMMKJKKKþõõJMGBIDKMDLMLHDJMLOMJIK
þõILGDJDGILLHFCABOOOOOK	

þHKFDHBJIHEDAAEJJLMOOM	

þGHEBF@EDBBAABDEGIJLMM	
þ
DBE@A@@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KJLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKJIJKLMþ
õIIFBDEMJLMLKEDHMLKJKKKþõõJMGBIDKMDLMLHDCMOOMJIK
þõILGDJDGILLHFCAMOOOOOK	

þHKFDHBJIHEDAAEJJLJOOM	

þGHEBF@EABBAABDEGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKJIJKLMþ
õIIFBDEMJEMLKEDHDMKJKKKþõõJMGBIDKMKLMLHDJMOOMJIK
þõILGDJDGILLHFCAMOOJOOK	

þHKFDHBJBHEDAAEJJLMOOM	

þGHEBF@EDBBAABDEGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIJJIDCFKEIJKLMþ
õIIFBDEMJEMLKEDHMMJJKKKþõõJMGBIDKMKLMLHDJMOJMJIK
þõILGDJDGCLLHFCAMOOOOOK	

þHKFDHBJIHEDAAEJJLMOOM	

þGHEBF@ED@BAABDEGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLLMMMþMMHEKKLK

KLJKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHIILMMMþKHFBFEGHEBABFGJFLLMMMþLKEBEFKIFJIDCFKJIJKLMþ
õIIFBDEMJLMLKEDHMMJJKKKþõõJMGBIDKDKLMLHDJMOOMJIK
þõILGDJDGILLHFCAMOOOOOK	

þHKFDHBJIHEDAAEJJLMOOM	

þGHEBF@EDABAABDAGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
KJRõõ	
LKþMLKKIõ
LKKLMþMMJHLKKJIHHHHIJKKLLMMþMMJGMMLLKKJJKKLMLLMMMþMMIFMMMMMLKKKLMMLLMMMþMMIFMMMMK

øKMLJMMMþMMHEKKLK

KLLKMMþMMHEMLJõøLKMMMþMMHDMLH
KKMMMþMMGDKKIF
Fõ
KLLMMþMMGCEIJ
õEE
øLLKMMþMLGCIDHJGHõõFEKKJLMMþMKGBIGECFGFDBFHGILMMMþKHFBFEGHEBABFGJLLLMMMþLKEBEFKIFJIDCFKJIJKLMþ
õIIFBDEMELMLKEDHMMKJKKKþõõJMGBIDKMKLMLHDJMOOMJIK
þõILGDJDGILLHFCAMOOOOOK	

þHKFDHBJIBEDAAEJJLMOOM	

þGHEBF@EDBBAABDAGIJLMM	
þ
DBE@AA@@@@AAABDFJL	
þB@@@@@AA@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMMMMMMMMNMOMOþNHDLLMMMMMMMMMMMMMMMOþMGDKKMMMMMMMMMMMMMMMNþMGCKKMMMMMMMMMMMMMMMMþMGCKIMMMMMMMMJMMMMMMMþMGBIHMMMKMLMMMMMMMMMMþMFBHFMMMMLLLMMMMMLMMMþLEBHELMMMMLMMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMMMMMKþõõJGBJDIMMMMMMMMMMMMLJIK
þõIGDGBGMMLLLLLMMMMMMML	

þHFDE@EJIHFDFHIJJLMMMM	

þGEBC@EEDBAAABDEGIJLMM	
þ
BC@BAA@@@@@@ABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMMMMMMMMNMOMOþNHDLLMMMMMMMMMMMMMMMOþMGDKKMMMMMMMMMMMMMMMNþMGCKKMMMMMMMMLMMMMMMMþMGCKIMMMKMMML<LMMMMMMþMGBIHMMMMLL<MLMMMLMMMþMFBHFMMMLMMMLMMMMMMMMþLEBHELMMM<LLMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMMMMMKþõõJGBJDIMMMMMMMMMMMMLJIK
þõIGDGBGMMLLHLLMMMMMMML	

þHFDE@EJIHFFFHIJJLMMMM	

þGEBC@EEDBAAABAEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMMMMMMMMNMOMOþNHDLLMMMMMMMMMMMMMMMOþMGDKKMMMMMMMMMMMMMMMNþMGCKKMMMKMMMLL<MMMMMMþMGCKIMMMMMMLMMMLMLMMMþMGBIHMMMMMML<LLMMMMMMþMFBHFMMLMMMMMLMMMMMMMþLEBHELMM<LMMMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMMMMMKþõõJGBJDIMMMMMMMMMMMMLJIK
þõIGDGBGMMLLHLLMMMMMMML	

þHFDE@EJIHFFFHBJJLMMMM	

þGEBC@EED@AAABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMMMMMMMMNMOMOþNHDLLMMMMMMMMMMMMMMMOþMGDKKMMMLMMMMMMMMMMMNþMGCKKMMMMMMMMMLLMLMMMþMGCKIMMMMMLMMMMMLMMMMþMGBIHMMMMMMLLMMMMMMMMþMFBHFMMMMMMMMMMMMMMMMþLEBHELMMMMMMMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMMMMMKþõõJGBJDIMMMMJMMMMMMMLJIK
þõIGDGBGMMLLLLLCMMMMMML	

þHFDE@EJIEFFFHIJJLMMMM	

þGEBC@EEDBAAABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMLMMMMMMMNMOMOþNHDLLMMLLLMMMMMMMMMMOþMGDKKMMMLMMMMMMMMLMMNþMGCKKMMMMMMMMMMMMMMMMþMGCKIMMMMLMMMMMMMLMMMþMGBIHMMMMMMMMMMMMMMMMþMFBHFMMMMMMMMMMMMMMMMþLEBHELMMMMMMMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMMMMMKþõõJGBJDIMMMMJMMDMMMMLJIK
þõIGDGBGMMGLLLLMMMMMMML	

þHFDE@EJIHFFFHIJJLLMMM	

þGEBC@EEDBAAABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMLL<MMMMMMNMOMOþNHDLLMLMMMLMMMMMMMMMOþMGDKKMM<LLMMMMMMLMLMNþMGCKKMMMMMMMMMMMMMMMMþMGCKIMMMMMMMMMMMMMMMMþMGBIHMMMMMMMMMMMMMMMMþMFBHFMMMMMMMMMMMMMMMMþLEBHELMMMMMMMMMMMMMMMþ
õIFBIDKMMMMKMMEMMMMMMMKþõõJGBJDIMMIMMMMMMMMMLJIK
þõIGDGBGMMLLLLLMMMMLMML	

þHFDE@EJIHFFFHIJJLMMMM	

þGEBC@EEDBAAABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMLLMMMMMNMOMOþNHDLLLMMMMMLMMMMMMMMOþMGDKKMLLMMMMMMMLMMMMNþMGCKKMMMMMMMMMMMMMMMMþMGCKIMMMMMMMMMMMMMMMMþMGBIHMMMMMMMMMMMMMMMMþMFBHFMMMMMMMMMMMMMMMMþLEBHELMMMMMMMFMMMMMMMþ
õIFBIDKMMKMKMMMMMMMMMMKþõõJGBJDIMMMMMMMMMMMLLJIK
þõIGDGBGMMLLLLLMMMMMMML	

þHFDE@EJIHFFFHIJJLMMMM	

þGEBC@EEDBA@ABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ

õõõõþ
					õ	þ
				
õõþ
		

				õõþ

	

		
		
	þ	
õõ		

	þ		
		þ			


þ		
		
þ	MRR
			
Mþ
LKRõõ	
LMþMKKJIõ
LKLMOþMJHMLKKJIHHHIJKLLMOMOþOJGMLMMLLLLLLLMONMOMOþOIFMMNOOOOOOOOOONMOMOþOIFMLNOOOOOOOOOONMOMOþOHEMKNONMMMMMNOONMOMOþOHEMLMMMMMMMMMMMNMOMOþNHDLLMMMMMMMLMMMMMMMOþMGDKKMMMMMMMMMMMMMMMNþMGCKKMMMMMMMMMMMMMMMMþMGCKIMMMMMMMMMMMMMMMMþMGBIHMMMMMMMMMMMMMMMMþMFBHFMMMMMMMMGMMMMMMMþLEBHELMMKMLMMMMMMMMMMþ
õIFBIDKMMMMMMMMMMMLMMMKþõõJGBJDIMMMMMMMMMMMMLJIK
þõIGDGBGMMLLLLLMMMMMMML	

þHFDE@EJIHFFFHIJJLMMMM	

þGEBC@EEDBA@ABDEGIJLMM	
þ
BC@BAA@@@@@AABDFJL	
þ@A@@@@@@@@@ABDþA@@@@@@@ABþR5õþ4
	ÿþ
NMMMNNþMOOOOOOOOþMOOOOOOOOOOþLMMþMOOOOOOOOOOþLMNNMþMLOOOOOOOOOOMNNOONMþMMOOOOOOOOONONNOOMMþKNOOOOOOOOOOONNONLMþMNOOOOOOOOONONNNMMMþMMOOOOOOOOONONNMLMMþKMOOOOOOOOOMONMMMMMþKLOOOOOOOOOOMONLMMMMþLLMOOOOOOOONOMOMKMMMMþ
õIKMOOOOONJLMMMMMþõõJJMOMKMMMMML
þõIJLNMKMMMMMML

þHJKI­­LMMMMMMML

þõILJ
­
MLMMMMML	
þ
KLK­MKMMMMLM
þLK

KMMMJLLþKõõ		õþõõþõõõÿþ	KþK
þþ	

þþ	


þ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þ¨¨þ	

þþ	


¨¨þ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þþ	


ªþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþþþ
þ

þ
	
þ


þ		
	þ
õ
	

þõ	õ	
		
þ	
	õ		õ
	
NMN

		
õþ	
		

NLMKLMM
þ			õ
	N<MI		þ
			

	L
	
	þ


þJI

<þ–JML
þ:9<	ÿþ	KþK
þþ	

þILþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þJEJþ	

þLE@ELþ	


JEJþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þJþ	

þJHJþ	


Jþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þKLþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þILþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þKLþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þILþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ	KþK
þþ	

þKLþ	


Lþ	


þ	

	
þ		

	


þ		
		

þõ
	
		
þ
	
			õ	
		

	þ


			õ
	
		


õþ	
			

		

	

þ
			õ


		



þ
			





þ



þJH
<þ–JML
þ:9<	ÿþ

þ
				
þ	Y							
þ

	Y							
þ
M	Y							þM<9	Y			
þ96	Yþ	Xþ
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	HLLMMMþõ	§¨¨¨W	LLLLLKMMMM
þ	£¥§§§§§W	JHKLLLLJHM	þ©
][><©W	ILLIJLLLLLY
þ¦	¨Y>:WWIAILLLKHLLY	þ£¥¦¦¦¦YXWYLLLLLLLYXþYYXWYLLLLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
	Y							þM<	Y			
þ<96	Yþ	Xþ6
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	LHLMMMþõ	§¨¨¨W	LLLLLLMMMM
þ	£¥§§§§§W	JHKLLLLKJM	þ©
][><©W	LILIJLLLLLY
þ¦	¨Y>:WWLJ@ILLKHLLY	þ£¥¦¦¦¦YXWYLLLLLLLYXþYYXWYLLLLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
	Y							þM	Y			
þM<9	Yþ	Xþ96
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	LJHMMMþõ	§¨¨¨W	LLLLLLMMMM
þ	£¥§§§§§W	JHKLLLLLKM	þ©
][><©W	LLJIJLLLLLY
þ¦	¨Y>:WWLJHFJLKHLLY	þ£¥¦¦¦¦YXWYLJLLLLLYXþYYXWYLLLLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
	Y							þ	Y			
þM<	Yþ	Xþ<9
þX
þY


þXþ
W	MLH

þõ	¦©¨©§©W	LKJMMMþõ	§¨¨¨W	LLLLLLMMMM
þ	£¥§§§§§W	KJKLLLLLLM	þ©
][><©W	LLLJKLLLLLY
þ¦	¨Y>:WWLJHKLLKILLY	þ£¥¦¦¦¦YXWYG@GLLLLYXþYYXWYJLLLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
6	Y							þ	Y			
þM	Yþ	XþM<
þX
þY


þXþ
W	MMJ

þõ	¦©¨©§©W	LKJKMMþõ	§¨¨¨W	LLLHLLMMMM
þ	£¥§§§§§W	LKLLLLLLLM	þ©
][><©W	LLLKLLLLLLY
þ¦	¨Y>:WWLJHKLLLKLLY	þ£¥¦¦¦¦YXWYLIFLLLLYXþYYXWYLLLLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
96	Y							þ6	Y			
þ	Yþ	XþM
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	LLKMMMþõ	§¨¨¨W	LLLJHLMMMM
þ	£¥§§§§§W	LLLLLLLLLM	þ©
][><©W	LLLLLLLLLLY
þ¦	¨Y>:WWLJHKLLLLLLY	þ£¥¦¦¦¦YXWYLIJJLLLYXþYYXWYJDJLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
<9	Y							þ96	Y			
þ	Yþ	Xþ
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	LLKMMMþõ	§¨¨¨W	LLLLJHMMMM
þ	£¥§§§§§W	LLLLLLLLLM	þ©
][><©W	JHKLLLLLLLY
þ¦	¨Y>:WWJ@CIJLLLLLY	þ£¥¦¦¦¦YXWYJDGKHLLYXþYYXWYJIGJYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ

þ
				
þ	Y							
þ

	Y							
þ
M<	Y							þ<96	Y			
þ6	Yþ	Xþ
þX
þY


þXþ
W	MMM

þõ	¦©¨©§©W	LLLMMMþõ	§¨¨¨W	LLLLKJMMMM
þ	£¥§§§§§W	JHKLLLKHLM	þ©
][><©W	LLLIJLLLLLY
þ¦	¨Y>:WWLFFKLLKHLLY	þ£¥¦¦¦¦YXWYLHILLLLYXþYYXWYLJJLYW
	þ	YYYXWYLYW
	
þ

ø

	YYYXWW

¥þø
Y

	YYYXøþ
	Y

	YYø
þ
	Y

	þ
	Y

þ	
	



þ







þ





K



þ	õ





þ





þ





þ



þ	þþÿþ	Y	Yþ	YYY		WTþ	XY				WUUþWY			YXWUUUUþYV		YXWWWWWUUUþYYW	YWWWWVXWWUUþWYXWWXVWWWWWþYWYX
WWYVWWõ



þ
WYYUVYXõUWõø

þUUY	
õVU
ø


þWW
õWUV
õWUWõ

þUVW
WUUX

Xõ
UUWYõþõõõWWXUWYXõ
õþ

WWø
WõþWVWõþþþÿþ
þþþþþþþþþþþ	þKþJþ§Iþg¥Iþ¦g§þ¦¥þøHgþ
Jg¨þIøg¨þ–¥§þ–§¦þJI¦þHK§¨þ	
	IH«§¦þ



II¨¨¨¥þ




	

–I«§¨§gøþ





ø–HJ§¦gIøõþ

	
øJ––HIø
þ


øø
	õþ

øøø

	õþ	

ø


	þ
õõþþþþÿþ	YWXþ	WWþXXWþ	XWþ
XXþ	Xþ

YþYþ		

þþþIþ
•þ
Iøþ
øH–þ–––J–IþõJH–I	þ––I	øþõ

þ

þ
þ

þøþ
þÿþWVUUVWþVUUUUUUUUVþVUUUUUUUUUUVþSUUUUUUUUUUVþVRSUUUUUUUVXþWURRSTTUWYþWXXXXXþøþøøþøøøþ
õøõøþ		

		ø
þõ
øøø

þõ

õõþõøø

øøõþ
õõõõøþþõÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMELLH	WYþN<LMMMLM
NþUMELLHLL	WXþ
N9MMMM:9NUMLLLLHJGL	WWþNMMMMMMMNVMLLLLLHLLLLWþMMMMMMNVMLLLLLJHJGLWþ	






WMLLLLLLHLLLWþVMLLLLLLKHKJWþ




WMLLLLLLLHLLWþWMLLLLLLLHKJWþ

WLLLLLLLHLLLWþWLLLLLLLHKGLXþWMLLLLLHLLLLWþ‘WMLLLLHKLLLLXþ‘‘‘OOOOOOWLLLLJJLLLLLXþWLLLJHLLLLLLXþWLLLLHLLCLMLXþWLKKKHLLLLLLXþWGEEFILLILCLXþXWWVWIFDFIILLLXþWUUWWWVWIGDFILLXþ

XUUUUUWWWVWIHFHKXþXUUUUUUUUWWWVVIGHXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMGELL	WYþN<LMMMMM
NþUMGELLLH	WXþ
N:9MMML:NUMLLLLLJHJ	WWþNMMMMMMMNVMLLLLLLHLLLWþMMMMMMNVMLLLLLLKHKJWþ	






WMLLLLLLLHLLWþVMLLLLLLLHKJWþ




WMLLLLLLHLLLWþWMLLLLLLHKGLWþ

WLLLLLLHLLLLWþWLLLLLHKLLLLXþWMLLLJJLLLLLWþ‘WMLLJHLLLLLLXþ‘‘‘OOOOOOWLLLLHLLLLLLXþWLLIKJLLLLJLXþWLLLHLLLIJCJXþWLLLHLLLLLJLXþWIGGHKLLMLILXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþML9MMM
þUMJGLL	WYþN<<LMMMM
NþUMJGELLL	WXþ
NL:MMMMMNUMLLELLLLH	WWþNMMMMMMMNVMLLLLLLLHKJWþMMMMMMNVMLLLLLLHLLLWþ	






WMLLLLLLHKGLWþVMLLLLLHLLLLWþ




WMLLLLHKLLLLWþWMLLLJJLLLLLWþ

WLLLJHLLLLLLWþWLLLLHLLLLLLXþWMLIKJLLLLLLWþ‘WMLLHLLLLLLLXþ‘‘‘OOOOOOWLHJHLLLLLLLXþWLLLHLLLLLKLXþWLLHKHLLCKIKXþWLLLLHHLLLKLXþWIGGHKLLMLCLXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþMMLMMM
þUMLJLL	WYþN<L<MMMM
NþUMLJGELL	WXþ
NLM:MMMMNUMLLGELLHL	WWþNMM9MMMMNVMLLLLLLHKGLWþMMMMMMNVMLLLLLHLLLLWþ	






WMLLLLHKLLLLWþVMLLLJJLLLLLWþ




WMLLJHLLLLLLWþWMLLLHLLLLLLWþ

WLLIKJLLLLLLWþWLLLHLLLLLLLXþWMHJHLLLLLLLWþ‘WMLLHLLLLLLLXþ‘‘‘OOOOOOWLLHKHLLLLLLXþWLLLLHHLLLLLXþWLLLLHLLILCLXþWLLLLLHLLLLLXþWJHHILLLMLILXþXWWVWLIGILLLLLXþWUUWWWVWLJGILLLXþ

XUUUUUWWWVWLKIKLXþXUUUUUUUUWWWVVLJKXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþMMLMMM
þUMLLLL	WYþN<LLMMMM
NþUMLLJGJH	WXþ
NLM<9MMMNUMLLJGEKLL	WWþNMM:LMMMNVMLLLJELLLLLWþMMMMMMNVMLLJHLLLLLLWþ	






WMLLLHLLLLLLWþVMLIKJLLLLLLWþ




WMLLHLLLLLLLWþWMHJHLLLLLLLWþ

WLLLHLLLLLLLWþWLLHKHLLLLLLXþWMLLLHHLLLLLWþ‘WMLLLHLLLLLLXþ‘‘‘OOOOOOWLLLLLHJGLLLXþWLLLLLLLLLLLXþWLLLLLLLMLILXþWLLLLLLLLLLLXþWIGGHKLLCLFLXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMLLLL	WYþN<LMMMMM
NþUMLLLJJL	WXþ
NLMM:9MMNUMLLJHGELL	WWþNMMLMMMMNVMLLLHGELLLLWþMMMMMMNVMLIKJLLLLLLWþ	






WMLLHLLLLLLLWþVMHJHLLLLLLLWþ




WMLLHLLLLLLLWþWMLHKHLLLLLLWþ

WLLLLHHLLLLLWþWLLLLHLLLLLLXþWMLLLLHJGLLLWþ‘WMLLLLLHLLLLXþ‘‘‘OOOOOOWLLLLLLJHJGLXþWLLLLLLLLLLLXþWLLLLLLLCLMLXþWLLLLLLLLLLLXþWHFFGJLLMLJLXþXWWVWJGEGJJLLLXþWUUWWWVWJHEGJLLXþ

XUUUUUWWWVWJIGILXþXUUUUUUUUWWWVVJHIXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMLLLH	WYþN<LMM<9M
NþUMLIKJLL	WXþ
NLMML:<MNUMLLHLLHLL	WWþNMMMMMMMNVMHJHLLHLLLLWþMMMMMMNVMLLHLLLLLLLWþ	






WMLHKHLLLLLLWþVMLLLHHLLLLLWþ




WMLLLHLLLLLLWþWMLLLLHJGLLLWþ

WLLLLLLHLLLLWþWLLLLLLJHJGLXþWMLLLLLLHLLLWþ‘WMLLLLLLKHKJXþ‘‘‘OOOOOOWLLLLLLLLHLLXþWLLLLLLLLLLLXþWLLLLLLLILJLXþWLLLLLLLLLLLXþWGEEFILLLLCLXþXWWVWIFDFIILLLXþWUUWWWVWIGDFILLXþ

XUUUUUWWWVWIHFHKXþXUUUUUUUUWWWVVIGHXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþWWYþUM	XYþY		

þUMLI	XYþMMMMMM
þUMLLHL	WYþN<LMM<:M
NþUMHJHLLL	WXþ
NLMMMM9MNUMLLHLLLLL	WWþNMMMMMMMNVMLHKHLLLLLLWþMMMMMMNVMLLLHHLLLLLWþ	






WMLLLHLLLLLLWþVMLLLLHJGLLLWþ




WMLLLLLHLLLLWþWMLLLLLJHJGLWþ

WLLLLLLLHLLLWþWLLLLLLLKHKJXþWMLLLLLLLHLLWþ‘WMLLLLLLLHKJXþ‘‘‘OOOOOOWLLLLLLLHLLLXþWLLLLLLJLLLLXþWLLLLLJLMLILXþWKKKLLHLLLLLXþWFDDEHKLCLILXþXWWVWHECEHHLLLXþWUUWWWVWHFCEHKKXþ

XUUUUUWWWVWHGEGJXþXUUUUUUUUWWWVVHFGXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþ
WWTWYY	õþWY	õþõþþÿþ		þõ	þ		þ		
þ	

			þþ


					
õþ	
							õõõþWVWUUW			
	Hõõõõõþ
VVXUUUWW		I•HõõõõõþVUWWX			•õþõUWVX•UUY		õõþ–VUYYXVUWõþ•Wõõõþ

VWþþþõþÿþþþþþþ
þþþþþ
þþþþÿþþþþþþ
þþþþþ
þþþþÿþþþþ	þ	þ

			þ	

		þ
	

			
	þ

		þ
		

þ
		

þ

þþþÿþþþTSSTþTSRQRRSTþTSRQRRRRRRSTþ
TSRQWPWPWPWSRRSTþTSRQRQWQWQWQWSRRRRSTþSWRTSRQRRRQWRWRWRWSRRRRRRSTUURRRRTSRRRQWSWSWSWSRRRRSTUUUUSWRTSRQTSTSTSTSRRSTUUUUUURRRRTSRRRRRRRRSTUUXXUUUUSWRTSRRRRSTUUS]SSUUUURRRRTSSTþUUXXSTSSUUUUSWRþUUXXSTTTSSUUUURRRRþUUXXSTTTTTSSUUUUWWþUUS]STTTTTTTSSUUWWþUUXXSTTTTTTTTSPYR[þUUXXSTTTTTTTTSVUXWþUUXXSTTTTTTTTSUUWWþUUS]STTTTTTTTSUUWWþUUXXSTTTTTTTTSPYR[þUUXXSTTTTTTTTSVUXWþUUXXSTTTTTTTTSUUWWþUUS]STTTTTTTTSUUWWþUUXXSTTTTTTTTSPYR[þUUXXSTTTTTTTTSVUXWþUUXXSTTTTTTTTSUUWWþUUS]STTTTTTTTSUUWWþUUXXSSTTTTTTTSPYR[þUUTTVXSSTTTTTSVUXWþUUUUTTVXSSTTTSUUWWþUUUUTTVXSSTSUUWWþUUUUTTVXSSPYR[þ
UUUUTTVXVUXWþUUUUTTUUWWþUUUUUUWWþUUPYR[þVUXWÿþ]\þ\

]þ[


[[^þZ	


Z¦¥¦\_þ\[


	Z¥¦—™¥
	Yö]_þ
[		
			Z—§¨—\

	


]þ[

		

¤¤¤˜¥—[[






]]þ\[


Z
Z¥¦˜—[

	




\]]þ\

[¤—¤¤—¤¤¤¦[
	

Y
]]]þ]



ö[¦¦—§—˜¥ôZ—			X		^^]þ^	
	¥¥—¥¤¦¦[



			^^^þ^
\\
		ôô
[



[]]]\^þ___
				
			

[^]^^^þ^__
			X		
\^^]]^^ôþ^_			
\^]^^^ôþ_[ö^]^^^^þ__^]]^^^ôþ^__^^]^^^ôþ
^_^ú\]\^^^ôþ^__^^]\^ôþ^__^^^^^ôþ^^_^^^ôþ^^^ôÿ