þòòôòþòôôðòòòòþòôôðòòòòòòòôþòôRRòòòòôô™§¨þòôöðñòôô™§¨¨§™§þ
TTTTTTññð™§¨¨§™§
PþTTTTTUVWñ™§¨¨§™§
ðPPþXXXXXXWWXXWXW™§¨¨§™§
PðPPþWWWXWWWWW™§¨¨§™§
ðPþ
WWWWW™§¨¨§™§
áðPPþW™§¨¨§™§
ðPPþ¨§™§
PðPPþ
PPPþôðPPÿþTTTþTTTTTTTþXXXXXXXXXñþòòòòòòòòòòòôþòòòòòòòòòòòôô˜™¨þòòòòòòòòòòòôô˜™¨¨™˜§þ
òòòòòòòòòòòôô™™§¨§™§
Pþòòòòòòòòòòòôô™§¨¨§™§
ðPPþòòòòòòòòòòòôô™§¨¨§™§
PðPPþòòòòòòòôô™§¨¨§™§
ðPþ
òòòôô™§¨¨§™§
áðPPþô™§¨¨§™§
ðPPþ¨§™§
PðPPþ
PPPþôðPPÿþ™þ˜™fþ˜f™˜þf™˜þþff˜þf˜¨þô¨§¨þòòð¨˜§þð§˜þô§˜ðþôò§˜ðððþððò™fðððòôþòòôôð™òðòô¨˜fþððòòòòôfðòô¨˜§¨§§˜™þòñðòòfòô¨˜¨¨¨§˜™
Pþððò5335ñð™¨™™¨¨§˜™
ðPPþTTT3ÐÐ3ññ™§¨¨¨§˜™
PðPPþT5335ñ¨f™f§™™
ðPþ
ññññf˜™§
áðPPþôf˜§¨§™§
ðPPþ¨™˜™
PðPPþ
PPPþôðPPÿþþôòþøøô	òþöòôôòþöôôòô	òþöôôô	òôô	þöôôôôôôòô	òþöôôôôôôô	òô	òþôôôô	ôôôôôòôôòþôôôôôôôôô	òôôòþôôôô	ôôôôôò	ôòþôôôôôôôôô	òôôôþôôôô	ôôô	ôò	ôòþùöôôôôô	ôôô	òôôòþöôôôô	ôôô			ôòþøöôôôôô	ô			òôôòþöôôôô	ôôô			ôôþôôôôô	ô			ô	òþô	ôô	ô					ôòþôôôôô	ô			ô	òþô	ô		ô		ô		ôòþôôô	ô	ô					òþô	ô		ô	ô				òþ	ô				ô					òþ		ô										þ	ô							ñ	þ								ñþùö						ñþö				ñþøö		ñþöñþÿþþöôôþøöôôôôþøøôôôôôôþöô
	ôôôôôþòôôô
ôôôôôôþðôòô	ô	ôôôôôþðPòôòôôô
ô	ôôôôþôòòòôöðô	ô	ôôôôôþôòPòòôðôôô
ô	ôôôôþòPPðòðô	ô
	ôôôôôþPPðPðòôô
		ôôôôþòPðPðò	ô
	ô	ôôôþôôðòð	ôô
		ôôô	þôòPPò	ô			ô	ôþðPðPPòôô		ô	ô	þPðPòðô	ô
						þðPòòðð			
						þòòòðPðò	ô
						þòòòPðòô	
						þòðPðPððô		
						þðPðPòðòò			
						þðPòòòôò			
						þòòðôôôð			
				ñþôòòôôôò		
		ñþôòPòôöò		
ñþòPòPðôöò			þðPðPðôöð		þðPòPòôöðþòPôôôþôôôþôôÿþööþööôòþööööôòþöööö	ôôòþöööö
	ôôòþöööö
			ôôôþöööö
			ô	ôôòþöööö
	ôô	ô	ôôôòþ
		ôôôôôô	òôôòþôôôôôôôôô	òôôòþùöôôôôôôôô		ôôòþöôôôôôôô		ôôôòþøöôôôôôôôò	ôôôôòþöôôôôôôô	ôôôôòþôôôôôôô	ôôôôòþôôôôôôôòôôôôôòþôôôôôôôò	ôôôôòþôôôôôôô	ôôôôòþôôôôôôôôôôôôòþôôôôôôôò	ôôôôòþôôôôôôôòôôôôôòþôôôôôôôò	ôôôôôþôôôôôôô	òôôôôôþôôôôôôôô	ôôô	þùöôôôôôôôô	ôôôôôòþöôôôôôôôôôò	ôôòþøöôôôôôôôôô	òôþöôôôôôôôôô	þôôôôôôôôþôôôôôôþôôôôþôôÿþööööþöööö
	þöööö
		ôþööö
		ôôôþööööô		ôôôôþööôòôôô
	ôôôôôþööôòòòòôô
	ôôôôôþööòòðPðòôô
	ôôôôôþðòPðòôô
ôôôôôôþðPðPPðôô
	ôôôôôþPáPðôô
ô	ôôôôþPðòáPðôôô

	ôôôþòòôPòôôôôô
ôôôþöòôòPôôôôô	
ôôôþôòòðPðôôôôôô
ôôôþòðòPðôôôôô	
ôôôþòPðáðòôôôôô
ôôôþPðPðPðòôôôô	
ôôôþPððPðòôôôô	
ôôôþðáðPðáòðôôôô	ô
ôôôþPPôòôôôôô	
ôôôþPáòôðôôôô	ô
ôôôþðáòPðPòðòôô		
	ôôôþòPðPPðòôô	ô
ôôôôþðPPPòòôô	
ôôôôôþðPPðòðòôôô
ôôôþòPðòòôðôôô
ôôþòôòôöòôôô
þôôòPòôòô	þôöòòôòþôöPðôþôôðPÿþþþòøþöþ

òþ	þ	
	öþ	þ
ñ	öøöþ		þ	ññþùö			ö

ñúþûþöô	
	ööùôþøö		
öòòøþöñööòòöùùöþôøòùÿþþþááþòPPðþòòòPáPðòòþ
ôôòòPáPðòôôþòô	òòòPPðòò	ôòþòôòôôòòðPðPðòòôôòôòòòôöðô	òòòòáòáòðòòò	ôðöôòòôòPòòôðôôòòðPðPðòòôôðôòòPòôòPPðòðô	òòòðPðPðòòò	ôðòðPPòPPðPðòôòòòðòðòòôòðPðPPòPðPðò	òòòPPðòò	òðPðPòôôðòð	ôòPPðòô	ðòðôôôòPPò	òòòðððòò	òPPòôðPðPPòôòòððòòôòPPðPðPðPòðô	òòðáPððò	ôðòPðPðPòòðð		òPPððò		ððòòPðòòòðPðò	òPðòðòò	òðPðòòòòòòPðòôòPòòôòôòðPòòòòðPðPððô	òðáòòôò	ôððPðPðòðPðPòðòò		òòòòòðò		òòðòPðPððPòòòôò		ðáðPðò		òôòòòPðòòðôôôð		PPð		ðôôôðòòôòòôôôò	PPð	òôôôòòôôòPòôöò	áPPð	òöôòPòôòPòPðôöò	áPPðð	òöôðPòPòðPðPðôöð		þ		ðöôðPðPððPòPòôöðþðöôòPòPðòPôôôþôôôPòôôôþôôôôôþôôÿþööööþööøøööþööøøøøööþööööööööööööööööþööööööôöôôöööööööþ
ööôòôôòòòôðôòöòòòôôòôööþööôòòòòôòòòPPðòòôòòòòôööþööòòðPðòôòòòPPðòòôòðPðòòööðòPðòôòòòðPðPðòòòôòðPòððPðPPðôòòòòPòPòðòòòôðPPðPðPáPðôòòòôôôðòòòôðPáPPðòáPðôòòòòáòáòòòòôðPáòðPòòôPòôòòòðPðPððòòôòPôòòöòôòPôôòòòPPðòòôôPòôòöôòòðPðôôòòòáPòòòôôðPðòòôòðòPðôôòòòðáðáððòòòôôðPòðòòPðáðòôòòòðòòðòòòôòðáðPòPðPðPðòôòòòòòPððòòôòðPðPðPPððPðòôòòòôòPððòòôòðPððPðáðPðáòðôôòòòöôðòðòòòôôðòáðPðáðPPôòôôòòòöôòòôðòòòôôòôPPPáòôðôôòòòöôòòôðòòòôôðôòáPðáòPðPòðòôòòòöòðòòòôòðòPðPòáðòPðPPðòôòòòôðPòòòôòðPPðPòðPPPòòôòòòòðPòòòôòòPPPððPPðòðòôòòòððòòòôòðòðPPðòPðòòôðôôòòðþòòòôôðôòòðPòòôòôöòôôòòþòòôôòöôòôòôôòPòôòô	þ	ôòôòPòôôôöòòôòþòôòòöôôöPðôþôðPöôôôðPþPðôôÿþþf˜þf˜f˜˜þf˜fff˜f˜˜fþf˜fffff˜fþ
f˜fffff˜˜þf˜fffff˜˜þ˜ffff˜™˜f˜f˜™¨f™˜™¨§§ff˜™˜™¨§§§§™˜˜˜™˜™¨§§§§§§™§˜˜˜˜˜™˜ff™¨§§§§§™¨§™f˜˜˜˜˜˜˜™˜f™¨™§§§§§§¨¨§™f˜˜˜˜˜˜˜˜˜™˜f˜f™¨˜™§§§§§§§§§§f™˜˜˜˜˜˜˜˜˜˜˜˜™§¨¨§§™§§§§§§§§§§§™™˜˜˜˜˜˜˜˜˜˜˜˜˜™§§§§™§§§§§§§§§§§§§™˜˜˜˜˜˜˜˜˜˜˜˜™§§§§§§§§§§§§§§¨þ˜§§™˜˜˜˜˜˜˜˜˜˜™§§§§§§§§§§§§¨¨¨þ˜™™§§™˜˜˜˜˜˜˜˜™§§§§§§§§§§¨¨¨¨¨þ˜™™™™™§§™˜˜˜˜˜˜™§§§§§§§§¨¨¨¨¨¨¨§˜™™™™™§§™˜˜˜˜™§§§§§§¨¨¨¨¨¨¨§™§f˜™™™™™§§™˜˜˜§§§§¨¨¨¨¨¨¨§˜™§§þ˜˜f˜™™™™™§§™˜§§¨¨¨¨¨¨¨§™™™§¨þ˜™™˜fff˜™™™™™§§¨¨¨¨¨¨¨§™§§§¨¨¨¨˜™™™˜ff˜™™™™§¨¨¨¨¨§™§§§¨¨¨¨§§f˜™™™˜˜ff˜™™§¨¨¨§˜§§§¨¨¨¨§™§§˜˜˜ff˜™™™˜˜˜f˜™¨§™™™§¨¨¨¨§™§§§§™˜˜˜ff˜™™™˜˜˜f™™™§¨¨¨¨§™§§§§§§¥§˜˜˜˜˜ff˜™™™˜˜§§¨¨¨¨§™§§§§§™¨§¥f˜˜˜˜˜˜˜f˜˜™™§¨¨¨§™™§§§§§§§¨¨§f˜˜˜˜˜˜˜˜˜f˜˜§§§™™§§§§§§§§§§™˜þf˜˜˜˜˜˜˜˜˜f˜™™§§§§§§§§§§™˜þf˜˜˜˜˜˜˜˜™§§§§§§§§§§™˜þ
f˜˜˜˜˜˜™§§§§§§§§™˜þff˜˜˜˜™§§§§§§™˜þff˜˜™§§§§™˜þf˜™§§™˜þff˜˜ÿþòôöþúöööþô
ð
ööööþ
ô
ö

öööööþöðð	öööô	
öööööôþòòð	öööô	
ööööôñþöòôòò	ööö	ññ	ôñðþ	ò™§ôòðò
ööññ			
ôñð	þöòò™™ôòðò
öôñð			
ø	
ôñ
þò§ôò™ôòðòöôñð			
ø	ô
þöò™™ôò˜ôòðòôñð	

ø
ööþôòò™ôòfôòðòöôñð	
ñøöþôòò˜ôòôòðòôöôñ
	

þôòòfôòôòòöô
ð	
ñ	þôòòôòfòöôöööñ
	

þôòòôòòôòðôöô
ð	
ñ	þ	ôòòfòòö[ôò
øøñ
	
þ
ôòòòòôôôôôöô
ð	
þôòòòö[ôô

ô
öööñ
þôòôôôôöòôööô
ðþôö[ôô
øööôôòôöööññþ
ôôööö	ôòôööôñþø

ööô		ôòôööôþøôö
				þööþòðöøôô	
	þöþòðPø
		
þòðPòøøø	

þòðáòôPòøøø		þòðáòööøøøøþòðPòôPôø
øþòðòöøöò



øþ
òðPPðPòôôúøúþôðPPðáðô
úûûøþôðPPðô

úûûûûþôðPô

	ûûûýýûþðô



þýýýýýþ	

	þýýýýýþ
	þýýýþ
þýÿþ
ôþ
ôööøþ	
ööööøþú
ð	öööööøþ
ôöø
ð
ööööøþöööø
ööööøþööøö	ööööøþöøö	ññ	øþøññ			øþñð			
þð			
þ	

þ
ñþ	

þð	
ñ	þñ
	

þô
ð	
ñ	þöñ
	

þ	ô
ð	
ñ	þ	
öñ
			þ
ô
ð			þ

ööññ			þñ	öôñð		þ			ø
öôñðñþ			ø
öôñðþ			öôñðñþð		
öôñð	ðþñðñöôñ–þôñð
ôðþöôñðñ

Fþööôñð	ðöþôööôñ˜ðþñôööôðþñôöö™þòôþÿþ[WVþ[WURRVWþWTRRSUWYþ
öøøRSUWYþøþ
ô
öøTW[þ[Wþ[W
ôøùYþ[WURRVþ[WTRùþ[WTRRSUWþôWRSRS
öøþ[WRSRSUWYùþô			W°UW
ô
öþYWVWY°TW[ùþôñ
W
ôøúþ[WSRTVWWYù
ôøþôöôþúú[WTRRUUWYùô	
öôþúWRSRSUWYþ
ööùôöôþ			W°UWþ
ø[Wþ	ñ
Wþø[WVWþ[Yþ[WURRVþôWR[	
úúþ[WTRRSUWþô			WYúúúøþ[WRSRSUWYùþôñ
WúúúôøùþYWVWY°TW[ùþôöôþùþ[WSRTVWWYùô	
öôþ
ööøù[WTRRUUWYùøôöôþ
øWRSRSUWYþ
ööøþ
			W°UWþø
ööþ	úñ
Wþø
ôöþúþø
þù	
úùùþ
úúöøþöþ
ööùùöùþ		

þöö
ööøöøþ
	þ	

öøø
ööøøöùþ	
øþø
ööøøöøþø
ôöööùþø
ôöööøþø
ôöùþööôôøþ	

öøþ	
øÿþ[XVþWYXVWY[˜þWXWTX[[[X§þW[[YXUfþ
öøøYXWWY˜þ[Xþ
ô
öøVWWWW[WYXVWY[þ[X
ôøùWWWW[WXWTX[[[X§þ[WTRùUXYXWWSW[[YXUfþ[WRSRS
öøXVUW°WYYXWWY˜þ[WVWY°TW
ô
öVYURXYWVWWWWYþ[WURRVWWYþ
ôø[XT°SUVWWWWWYþWTRRSUWYþ[WTRRSS°°°UXYþRSUWYþø[WRSRSTWYþøTW[þ[WVWY°TWYþXVYþùYþ[WURRVWWYYWYXVWY[˜þþ[WTRRSUWY[WXWTX[[[X§þ[WRSRSUWYùùþXWWSW[[YXUfþYWVWY°TW[ùþUW°WYYXWWY˜úþ[WSRTVWWYù
ôøùþYURXYWVWWWWY[WTRRUUWYùùþ[XT°SUVWWWWWYþRSRSUWYþ
ööù[WTRRSS°°°UXYþW°UWþ
ø[WRSRSTWYþ	Wþø[WVWY°TWYþþ[WURRVWWYþúþ[WTRRSUWYùùþøþ[WRSRSUWYùùþùþYWVWY°TW[ùöøþþ[WSRTVWWYùöùþ[WTRRUUWYùøøöøþRSRSUWYþ
ööøøöùþW°UWþø
ööøøöøþþø
ôöööùþø
ôöööøþø
ôöùþööôôøþ	

öøþ	
øÿþ			þñððððð
þ	ñ
þ		þ		ðþ		

þ		
	ööööþ
öö	ññ	þôöôññ			þööôñð			
þöôöôñð			þ	ø	öôñð	

þ		ø	ôñð	
ñ	þ			
ø
öôñ
		þ			øöô
ðþ	


öôñðñþð	
ñ	
öôñð	ðþñ
			öôñ–þô
ð
ôðþööñðñ

Fþööôñð	ðöþôööôñ˜ðþñôööôðþñôöö™þòôþÿþðòþòô
þ
ðòþòô

þ
ðòþðð	þòôñððððñ	þþðRRðññðþþRðñññþ	Rðññþ	ðððñðþ	ðñððððñ		þ	ðñññððñ	
ôöþðñððñññ	ôöööþððñôô	ññþñ		ñôôññ	þ
					òôööôñðþ		
						òðôööôñðþ
ð		

		ôòòðôööôñðþ
ñ		òôôôòôööôñþ


ôôôôôôòôööôþøöööòôôô			þöþòðöøöôôô
	þöþòðPöô
		
þòðPòøøø	

þòðáòôPòøøø		þòðáòööøøøøþòðPòôPôø
øþòðòöøöò



øþ
òðPPðPòôôúøúþôðPPðáðô
úûûøþôðPPðô

úûûûûþôðPô

	ûûûýýûþðô



þýýýýýþ	

	þýýýýýþ
	þýýýþ
þýÿþþöôôþöôôôôþöôôôôôôþöôôôôôôUXþöôôô	ôôWWWVYWþöôôôôôôWWUYWW[þöôôôôôôWWWWWW[[þôôôô	ôWWWWWWôô[ôþôôôôWWWWWWôôôòðôþôôWWWWWWôôô	ðôôòþWWWWWWôôòðôòððòþXXWW	ôôðôôòððòòþùöXXXôô	ôòððòòððòòWþöXXôô	ôôððòòôòòò[þøöXôôôñðòððòòXW[[þöôôñððòòWô	[	þôðX	ô				þôW		ô					þWWWWô				ô				þXXWW	ô		ô	ô					þXXX	ô	ô									þXXô		ô	ô								þXô				ô							ñþ		ô									ñþ	ô							ôñþ								ñþùö						ñþö				ñþøö		ñþöñÿþþþþþþþôô

þô

ô

þ
ööö
ô

öþööøö
ô

ööööþööú¤¥ùøö
ôô
ööööööþ	ö		

ùøö
ôô
öööööööþô		ö

øô
öööööööööþôôô		
ööøô
ööööööööööþôôôôôô	
öööøô
öööööööööþôôðò	ôôô	öööô
öööööööööþôôö
òò	ôô
øööøô
ööööööööþö
ôôö
òðôøô
öööööööööþö
ôôööô
ööô
öööööööööþö
ôôôøöööô
ööööööööþö
ô
ööøô
öööööööþøö

öôôôô
öööööööþö
ôò	ôôô
ööööööþô
ôôö
òðôô
ööööþ
ò	ô
ôôööôô
ö
	
þ
ò	ô
ôôôô

	
þ
ò	ô
ôô

	
þ
ò	ô
ô

	
þ
ò	ôô

	
þ
ò	
	
þ
òÿ
þ

þ
ñññ	þ
ññññññññ	þñññññññ
þñððññ
LþñððððLLLþððððððLLLLLþððððððLLLLLþððððððLLLLLLþððððððLLLLLLJþð—ððLLLJ	þ—––GðððLJ	ñY[Yþò—¤ò
	ñð	ñY[YYW[þñòò–—¤	
		ñY[YYX[XWYþ
ôòññò¤—––ñY[YYX[YYX[YYôþôôôòðñòòò[YYYW[YYW[YYô
öþôôôôôòðñòWYX[YYX[YYô
öþ	ôôöôôôôòðñWXYX[YYô
ööö
þ	ôôòöôôôôòðWWYYô
ööööþ
ôôòòôôôôôòðò
öööööö
þ
ôôöòòôôôôôôô
ööööööþö
ôôöòôôôôôôôööööööö
þö
ôôôôôôôô
ööööö
þöôòòôôôôöööö
þòòòòòòô
öö
þôôòòôôôö
þôôþÿþöþöööþöö
öööþöö
öööööööþöö
öööööööööþöö

ööööööööööööþô


ööööööööööööööööþ
ôô	
öööööööööööööööööþôôôô
ööööööööööööö
öþ
ôôôôô
öööööööööö
þôôôôôôô
ööööö
øøöþ
ôôôôôôôô
ö

öøöþ	ôôôôôôôô


øøöøöþ		ôôôôôôôô	
øøöøöþö			ôôôôôôôôøöøöþö			ôôôôôôöøøöøöþö			ôôôôôøöøþ
ö			ôôôöøøøþö			ôôøþö			öøþö		öþö	öööþööÿþøòùûþöáPáðöøùûþøPPááðùùûûþøðPPPáöôùùùùüûþøòPPáòöùùùùûûùûþøðPPPáöôùùùûûùþ
ôôðPPááòôùùûüûùùþ
òòPPáöôöùùùûûüûùþ
ôðPòòøùùûûüùûþôáòöôòùûùùûþòðáðôöøöüûþòððòöûûüûþòPPáðôöùûûûûüûþòPPáòöøùûûûüûûþøòPPáòôùûûûüûùþ
ôòPPáòôùûùûûüûùùþ	ôòPPáðòôùùûüûûùøþ	ôðPòòòöùùûûùûþ
ôáòòòôöøùùùùûþòðáðôöøöûøþôöððòöûþòôööÿþþòôþò	ôøøþòôôòöþò	ôòôôöþ	ôôò	ôôôöþò	ôòôôôôôôöþò	ôò	ôôôôôôôöþòôôòôôôôô	ôôôôþòôôò	ôôôôôôôôôþòô	òôôôôô	ôôôôþôôôò	ôôôôôôôôôþòô	òô	ôôô	ôôôôþòôôò	ôôô	ôôôôôöùþòô			ôôô	ôôôôöþòôôò			ô	ôôôôôöøþôô			ôôô	ôôôôöþò	ô			ô	ôôôôôþòô					ô	ôô	ôþò	ô			ô	ôôôôôþòô		ô		ô		ô	ôþò					ô	ô	ôôôþò				ô	ô		ô	ôþò					ô				ô	þ										ô		þ	ñ							ô	þñ								þñ						öùþñ				öþñ		öøþñöþÿþþôôöþôôôôöøþôôôôôôøøþôôôôô	
ôöþôôôôôô
ôôôòþôôôôô	ô	ôòôðþôôôô	ô
ôôôòôòPðþôôôôô	ô	ôðöôòòòôþôôôô	ô
ôôôðôòòPòôþôôôôô	
ô	ôðòðPPòþôôôô		
ôôòðPðPPþôôô	ô	
ô	òðPðPòþ	ôôô		
ôô	ðòðôôþô	ô			ô	òPPòôþ	ô	ô		ôôòPPðPðþ						
ô	ôðòPðPþ						
			ððòòPðþ						
ô	òðPðòòòþ						
	ôòðPòòòþ						
		ôððPðPðòþ						
			òòðòPðPðþ						
			òôòòòPðþñ				
			ðôôôðòòþñ		
		òôôôòòôþñ
		òöôòPòôþ			òöôðPòPòþ		ðöôðPðPðþðöôòPòPðþôôôPòþôôôþôôÿþööþòôööþòôööööþòôô	ööööþòôô	
ööööþôôô			
ööööþòôô	ô			
ööööþòôôô	ô	ôô	
ööööþòôôò	ôôôôôô		
þòôôò	ôôôôôôôôôþòôô		ôôôôôôôôöùþòôôô		ôôôôôôôöþòôôôô	òôôôôôôôöøþòôôôô	ôôôôôôôöþòôôôô	ôôôôôôôþòôôôôôòôôôôôôôþòôôôô	òôôôôôôôþòôôôô	ôôôôôôôþòôôôôôôôôôôôôþòôôôô	òôôôôôôôþòôôôôôòôôôôôôôþôôôôô	òôôôôôôôþôôôôôò	ôôôôôôôþ	ôôô	ôôôôôôôôþôôôô	ôôôôôôôôöùþòôô	òôôôôôôôôôöþôò	ôôôôôôôôôöøþ	ôôôôôôôôôöþôôôôôôôôþôôôôôôþôôôôþôôÿþööööþ	
ööööþô		
ööööþôôô		
öööþôôôô		ôööööþôôôôô	
ôôôòôööþôôôôô	
ôôòòòòôööþôôôôô	
ôôòðPðòòööþôôôôôô
ôôòðPòðþôôôôô	
ôôðPPðPðþôôôô	ô
ôôðPáPþôôô	

ôôôðPáòðPþôôô
ôôôôôòPôòòþôôô
	ôôôôôPòôòöþôôô
ôôôôôôðPðòòôþôôô
	ôôôôôðPòðòþôôô
ôôôôôòðáðPòþôôô
	ôôôôòðPðPðPþôôô
	ôôôôòðPððPþôôô
ô	ôôôôðòáðPðáðþôôô
	ôôôôôòôPPþôôô
ô	ôôôôðôòáPþôôô	
		ôôòðòPðPòáðþôôôô
ô	ôôòðPPðPòþôôôôô
	ôôòòPPPðþôôô
ôôôòðòðPPðþôô
ôôôðôòòðPòþ
ôôôòöôòôòþ	ôòôòPòôôþòôòòöôþôðPöôþPðôôÿþþøòþþò
þ
öþö	
þ		þöøö	ñ
þ	þññ	þ		þûþúñ

ö			öùþôùöö	
	ôöþøòòö
		öøþöùùöòòööñöþùòøôÿþ˜ffffff˜þ™˜™§§§§¨˜§þf™§¨¨§§˜™ff§þ§¨©¨§¨§f™™˜f˜þ
™¨©¨¨¨¨§ff™§™˜f˜þ	™¨©¨¨¨§ff™f˜f§§™f™þ	f§©©¨¨™f˜™˜˜ff™§§™˜§þ	™f§©¨©¨f˜§™§™§§™˜§þ˜§§©¨§§™§™§™§™˜˜§©þf˜™™™™˜˜f§©_©þf§©©_©_©þ˜f™§¨¨¨¨_©_§þf™˜¨§§¨©©¨§þf¨§§¨¨§™¨þff˜f˜¨¨þS°R˜§¨§¨þ
S°°°V™¨¨§§¨¨þ	S°°°V[f˜™¨¨§¨þ	SS°V[f™¨¨§§¨¨þ	SSSXòf™§¨¨§¨þSSTYð˜˜§¨¨§§¨¨[þSSTYðö˜f™§¨¨¨YþSTTYðô˜˜™¨¨§¨YþSSTYòò[ff¨[XYþSTSYôYWX[YXWY[þTSTYôòYVRSSSTWWXü[þSTTY¤òð[Y[YY[[þTSTY—ôáð[WWXY[YþUTTY—¤ðPWW[X[YY[öþ	VUTYGôôY[WYY[[XWWôöþVYþ¤–òXWWVUWòþ¤ááðôþÿþ§˜˜þ¨˜™þ¨˜™™™fþ§˜˜¨þ§˜™§§™fþ¨f™¨©¨¨§f§¨¨§§™fþ§¨©©__™§¨¨¨§§™˜ff˜fþS°R©___©_©¨¨§§™˜˜˜™™þ
S°°°V___©_©¨¨§§™˜˜™§fþ	S°°°V[______¨¨¨§™˜™™fþ	SS°V[______©¨¨¨§™™f™¨þ	SSSX§§¨____©¨¨˜f™§¨þSSTY˜™§__¨˜˜§¨¨þSSTY™ff™¨˜™§¨¨¨[þSTTY§˜f˜f™¨¨§¨YþSUTY[™f˜™¨[[þSWVYYWXf˜YYXX[þTWV[YXWVUUVWX[ü[þSWV[[üY[[þTVV[[XY[YþUVW[Y[X[YY[þ
VVX[[YY[XYY[[XWWþ[þ[[YWWWWVUWÿþþöþööþöööþööööþööööþööþööööøøþöööööøþööö
úþööö
öúþööö
öú
þööö
ú
öþööö
öú
ööþöö
öö
ööþöö
ööú
öööþö
ööú
öööþ
öûù
ööþ
ù
öþöú
ööþöú
ööþ
þøú
öþúú
ööööþ
ööööþööööööþö
öööööþ
öööþö

öþöö

þþÿþþöþöööþööööþöööþöþöööøþööööþö
úúúþöö
öúúúúúþö
öúúúúúúþöö
úúúúúúúþö
öúúúúúúúþ
ööúúúúúúþ
ööúúúúúúú
þ
ööúúúúúúú
öþöûúúúúú
ööþúûúúú
ööþúúú
öööþúúúúúú
ööþúúúúúúú
ööþúúúúúúú
ööþúúúúú
þúúúúú
öþúúú
ööööþ
ööööööþöööööþö
ööööþ
ööþö

þööþÿþþöþööþöööþöþöööøþööööþö
úúúþöö
öúúúúúúþö
öúúúúúúúúþö
úúúúúúúúþ
öúúúúúúúúúúþ
ööúúúúúúúúúúúþööþúúúúúúúúúúúúþöþúúúúúúúúúúþþúúúúúúúúþþúúúúúþúúþú
þúúþ
öþúúúúþ
ööþúúúúúúþ
ööþúúúúúúúú
öööþúúúúúúúúú
öööþúúúúúúúúú
þúúúúúúú
öþúúúú
öööþú
ööööþöööþö
ööþ
þöþÿþþöþööþöþööøþööþ
úúúþ
öúúúúúþ
öúúúúúúúúúþ
úúúúúúúúúúúþöþúúúúúúúúúúúúþöþúúúúúúúúúúþþúúúúúúúúþþ
úúúúúúþúúúúþúúþ.þþúúþþúúþ	
þúúúúþ
öþúúúúúúþ
ööþúúúúúúúú
ööþúúúúúúúú
ööþúúúúúúú
ööþúúúú
ööþú
ööþöþö
þþÿþþöþöþööøþöþ
úúúþ
öúúúúúúþöþúúúúúúúúúþþúúúúúúúúúþþúúúúúúúúþþ
úúúúúúþúúúúþúúþÎþþúúþúúþ
þúúúúþ
þúúúúúþ
öþúúúúúþ
ööþúúúúú
ööþúúúú
öööþú
ööþþöþÿþþþøþöþþúúúþþúúúþþúúúþþ
úúúþúúúþúúþÿþoþþúúþúþúþþúþ
þúþ
öþú
ööþ
ööþööþöÿþþøþöþþþþþþþþþþÿþÏþ þ þ þ þ þþþ
þ
öþööÿþþ þ þ þ þ þ þ ÿþþöþööþöööþööööþööööþööþøøööööþøöööööþú
öööþúö
öööþ
úö
öööþö
ú
öööþöö
úö
öööþöö
öö
ööþööö
úöö
ööþööö
úöö
öþöö
ùûö
þö
ù
þöö
úöþöö
úöþ
þö
úøþöööö
úúþöööö
þööööööþööööö
öþööö
þö

öþ

ööþþÿþþöþöööþööööþöööþöþøöööþööööþúúú
öþúúúúúö
ööþúúúúúúö
öþúúúúúúú
ööþúúúúúúúö
öþúúúúúúöö
þ
úúúúúúúöö
þö
úúúúúúúöö
þöö
úúúúúûöþöö
úúúûúþööö
úúúþöö
úúúúúúþöö
úúúúúúúþöö
úúúúúúúþ
úúúúúþö
úúúúúþöööö
úúúþöööööö
þöööööþöööö
öþöö
þ

öþööþÿþþöþööþöööþöþøöööþööööþúúú
öþúúúúúúö
ööþúúúúúúúúö
öþúúúúúúúú
öþúúúúúúúúúúö
þúúúúúúúúúúúöö
þúúúúúúúúúúúúþööþúúúúúúúúúúþöþúúúúúúúúþþúúúúúþþ
úþúúþö
þúúþöö
þúúúúþöö
þúúúúúúþööö
úúúúúúúúþööö
úúúúúúúúúþ
úúúúúúúúúþö
úúúúúúúþööö
úúúúþöööö
úþöööþöö
öþ
þöþÿþþöþööþöþøööþööþúúú
þúúúúúö
þúúúúúúúúúö
þúúúúúúúúúúú
þúúúúúúúúúúúúþöþúúúúúúúúúúþöþúúúúúúúúþþúúúúúúþ
þúúúúþúúþNþþþúúþ
þ	úúþö
þúúúúþöö
þúúúúúúþöö
úúúúúúúúþöö
úúúúúúúúþöö
úúúúúúúþöö
úúúúþöö
úþöþ
öþþÿþþöþöþøööþöþúúú
þúúúúúúö
þúúúúúúúúúþöþúúúúúúúúúþþúúúúúúúúþþúúúúúúþ
þúúúúþúúþîþþúúþþ
úúþ
þúúúúþö
þúúúúúþöö
þúúúúúþöö
úúúúúþööö
úúúúþöö
úþþöþÿþþþøþöþúúúþþúúúþþúúúþþúúúþ
þúúúþúúþÿþþþúúþúþþúþ
þúþö
þúþöö
úþöö
þööþöÿþþøþþöþþþþþþþþþÿþðþþþþþþþ
þþö
þööÿþþþþþþþþÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYJJHXUWþ[YHFD@CBABþ	WYJJJJHHXUWXWWWEF@CCBABþUYJJJJHHHHGXWYYYECBD@BAAþUYJJJJFFGBGGV[[Y[EACDBBABþTYJJJJJJCFGGW[[YUCDBCCABþTUWJJJJJJJ@FW[[YTEDCDDABþYWUWYJJJJJJWY[ööSVDDDBABþYUXWUWYJJJW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYJJJXUWþ[YHFD@CBABþ	WYJJJJJJXUWXWWWEF@CCBABþUYJJJJJJHJHXWYYYECBD@BAAþUYJJJJFGHDHHV[[Y[EACDBBABþTYJJJJJD@FGGW[[YUCDBCCABþTUWJJJJJCBBGW[[YTEDCDDABþYWUWYJJJ@EGWY[ööSVDDDBABþYUXWUWYJDFW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYJJJXUWþ[YHFD@CBABþ	WYJJJJJJXUWXWWWEF@CCBABþUYJJJJJJHJJXWYYYECBD@BAAþUYJJJJEHHFHHV[[Y[EACDBBABþTYJJJJCFBGHHW[[YUCDBCCABþTUWJJJCEDDDHW[[YTEDCDDABþYWUWYEEGBGHWY[ööSVDDDBABþYUXWUWYGGHW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþGFþGFDEþGFCEFDþGFCEFDADþGFCEFDADþGFCEFDADþGFCEFDADþGFCEFDADþGFCEFDADþGFCEFDACþGFDEDDACþGFDDCDACþVWþ
FFDC@BABþVYWUWþEDC@@BABþ
UYJJJXUWþ[YDA@@ABABþ	WYJJJJJJXUWXWWW@ABABBABþUYJJJJJJJJJXWYYY@BBC@BAAþUYFCCDFJJGJJV[[Y[EACBBBABþTYGGFGGHDGJJW[[YUCDABCABþTUWGGGGHFGFJW[[YTEDACDABþYWUWYHHHDJJWY[ööSVDDDBABþYUXWUWYHHHW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGFGGDADþHGFGGDADþHGFGGDADþHGFGGDADþHGFGGDADþHGFGGDADþHGFGGDACþHGFGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYJJJXUWþ[YHFD@CBABþ	WYCJJJJJXUWXWWWEF@CCBABþUYFECJJJJJJXWYYYECBD@BAAþUYGGGFFJJHJJV[[Y[EACDBBABþTYGGGHHJFHJJW[[YUCDBCCABþTUWGHHHJGHGJW[[YTEDCDDABþYWUWYHJJFJJWY[ööSVDDDBABþYUXWUWYJJJW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYGEJXUWþ[YHFD@CBABþ	WYGGDJJJXUWXWWWEF@CCBABþUYHHGDJJJJJXWYYYECBD@BAAþUYJJJHFJJJJJV[[Y[EACDBBABþTYJJJJJJGJJJW[[YUCDBCCABþTUWJJJJJHHHJW[[YTEDCDDABþYWUWYJJJGJJWY[ööSVDDDBABþYUXWUWYJJJW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYHHGXUWþ[YHFD@CBABþ	WYHHGGDHXUWXWWWEF@CCBABþUYJJHGDHJJJXWYYYECBD@BAAþUYJJJJFHJJJJV[[Y[EACDBBABþTYJJJJJJJJJJW[[YUCDBCCABþTUWJJJJJJJJJW[[YTEDCDDABþYWUWYJJJHJJWY[ööSVDDDBABþYUXWUWYJJJW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþHGþHGGGþHGGGGDþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDADþHGGGGDACþHGGGGDACþHGGGGDACþVWþ
HGGGEBABþVYWUWþHGGEBBABþ
UYHHGXUWþ[YHFD@CBABþ	WYJHHGGGXUWXWWWEF@CCBABþUYJJJGGFFGGXWYYYECBD@BAAþUYJJJJFCC@CFV[[Y[EACDBBABþTYJJJJJJJJJJW[[YUCDBCCABþTUWJJJJJJJJJW[[YTEDCDDABþYWUWYJJJHJJWY[ööSVDDDBABþYUXWUWYJJJW[8[òVUVDDBACþUWXYWUVXW¨7[öðWRRTVAABþVWWWXXWU[˜6;[YYòòR°°°RSUBþWWWWWVY[68Y[[ôR°°°°SUTRþòòWWWWWV[f77[[[R°°°°RUWXWþòððV[YWWV[Xf859[S°°°°RUWW[YòðPPòV[YòðWYW™§85R°RS°°UWWW[þôððUWXWX[WY˜™R°°°°SUU™fWþôòð—WPX[Wò™–R°°°°RUWU7þ
ô–ðáðò¤–R°°°°RUWWþôR°°°°RUXþôòòòðð°°°°RUþôðR°RþôðPáÿþ
YþWþWYþUYþTYþTUW[þYWUWY[[ôþYUXWUWYYöþUWXYWUVXWôòPþVWWWXXWU[ôö[YYòòþWWWWWVY[YY[[ôR°°þ
òòWWWWWV[YX[[[[R°°°°RþòððV[YWWV[YX[[[[[S°°°°RUYXþòðPPôV[YòðWYW[[[[[R°RS°°UWWY[þôððUWXWX[W[[[[R°°°°SUU™fWþôòð—WPX[Wò[–VVUTR°UWU7þ
ô–ðáðò¤–R°SWWVTWWþôR°°°WXVTþôòòòðð°°°°WYþôðRTUþôðPáÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHþR°TUUDHLLLLLLLLLLLJCDFþ
R°STUGJLLLLLLLLLLLHDGDEGþR°°XXJJLLLLLLLLLLJHFGGGDþT°°SWLLLLLLLLLLJGEEEEEGGþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFGE@CADFAB@@@þHGGGGDADFGGFF@C@DGG@@A@@þHGGGGDADFGGF@D@DGHD@@@@AþHGGGGDADFGFBCD@FGADB@B@BþHGGGGDACFDDBDADGEDG@BA@BþHGGGGDACCDFBBDGHCGG@B@ACþHGGGGDACCFCCBGJGBGDBC@BDþHGGGEBABFDEBFHHEAGDCB@BCþHGGEBBABCDCDFGGDCFDCA@CBUWþ[YHFD@CBABDDEDFGDAFEGC@BCAHXUWXWWWEF@CCBABCAABDDAEEEJBADC@HHGXWYYYECBD@BAADEDBAAFGDHL@CCA@BGGV[[Y[EACDBBABGGEDEGGDGJJJGB@BGGW[[YUCDBCCABEBBBEFDGJHJJHHG@FW[[YTEDCDDABBDDBBDGHGJJGGHJHþ[ööSVDDDBABEGFCFGGGJJGEHJþ[òVUVDDBACEGGBEGJJHGFJþ
öðWRRTVAABFEEDEJHGEGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHþR°TUUDHLLLLLLLLLLLHCHLþ
R°STUGJLLLLLLLLLLLHGHLLLþR°°XXJJLLLLLLLLLLJHGHJLLþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFGE@CADGAGDEAþHGGGGDADFGGFF@C@DGG@BFDCþHGGGGDADFGGF@D@DGHF@DDBFþHGGGGDADFGFBCD@FGEGBDGBGþHGGGGDACFDDBDADGEGG@DFDGþHGGGGDACCDFBBDGHCGH@DDDGþHGGGGDACCFCCBGJGBHGBDBDGþHGGGEBABFDEBFHHEDHFCBBDFþHGGEBBABCDCDFGGDFHGCCADEUWþ[YHFD@CBABDDEDFGDDHGGCADDDJXUWXWWWEF@CCBABCAABDDAGGGJBCDDBHJHXWYYYECBD@BAADEDBAAFGGHL@BDDDDHHV[[Y[EACDBBABGGEDEGGGGJJ@BBADGGW[[YUCDBCCABEBBBEFDGJHHCBAE@GW[[YTEDCDDABBDDBBDGHGHJBABDDþ[ööSVDDDBABEGFCFGGGHJJ@BBþ[òVUVDDBACEGGBEGHJJHG@þ
öðWRRTVAABFEEDEHGGGGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLJJHþR°TUUDHLLLLLLLLJHFDCJLþ
R°STUGJLLLLLLJHGEDGDLLLLþR°°XXJJLLLLJHGEDGGHFJJLLþT°°SWLLLLJGGFEGGGEEEEEGJþHS°°°TWJHGFEGGHYYYYYYYYYþHGS°°°°RTWGGHHHXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFG@@@@@AACDEAþHGGGGDADFGGBA@@@@BB@BEDCþHGGGGDADFGGB@@@@BC@@CDBFþHGGGGDADFGAA@@@AB@@BDEBGþHGGGGDACF@@@@@@B@@B@CDDGþHGGGGDAC@@AA@@BC@BB@CDFHþHGGGGDAC@A@@@BDB@B@BCBGJþHGGGEBABA@@ABCC@@B@BCBGHþHGGEBBAB@@@BCBB@@A@CCDHGUWþ[YHFD@CBAB@@ABBB@@A@BCDGHFJXUWXWWWEF@CCBAB@@@B@@@@@@BBFGGBHJJXWYYYECBD@BAA@@@B@@AB@BC@GGFDFHHV[[Y[EACDBBABBBBCCBB@BCDDGFCEHHW[[YUCDBCCAB@BBBBABCCCDFFDGBHW[[YTEDCDDABBBBBCDCD@DEFCGJEþ[ööSVDDDBABBBCCDDBBEGFCGJþ[òVUVDDBACBBBBBDFEDDC@þ
öðWRRTVAABBBDDEDDBBDþR°°°RSUB@@BBCCEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHþR°TUUBDDDDDEEEDDDDDCJLþ
R°STUFEEEEEEEEEEEFGDLLLLþR°°XXGGGGGGGGGGGGGGFJJLLþT°°SWGGGGGGGGGGGGEEEEEGJþGS°°°TWHHHHHHHHYYYYYYYYYþGFS°°°°RTWJJJJJXWWWWWWWWþGFDTS°RR°°°RTVWWWWWWWWWWþGFDEFTRRSSTSSRRRSTUTUUVWþGFCEFDAUTSTTTUTTVVWWWXWXþGFCEFDADFGVTTUUTVVWWWXWXþGFCEFDADFGGFGWUTVWWWWXWXþGFCEFDADFGGFD@@@@@AAGDEAþGFCEFDADFGGBA@@@@BB@BFDCþGFCEFDADFGGB@@@@BC@@DDBFþGFCEFDADFGAA@@@AB@@BDGBGþGFCEFDACF@@@@@@B@@B@GFDGþGFDEDDAC@@AA@@BC@BB@GDFHþGFDDCDAC@A@@@BDB@B@BHBGJþFFDC@BABA@@ABCC@@B@CGBGHþEDC@@BAB@@@BCBB@@A@CFDHGUWþ[YDA@@ABABDBABBBB@A@BCDGHFJXUWXWWW@ABABBABCAABDDAB@@DBFJHBJJJXWYYY@BBC@BAADEDBAADCDHD@HHFDGJJV[[Y[EACBBBABDDEDEDEDGEFDJGCEJJW[[YUCDABCABC@BBEEDGEDDHGDHDJW[[YTEDACDAB@DDBBDFEBGHGFHJEþ[ööSVDDDBABDGFCFGDDGJGEHJþ[òVUVDDBACFEGBEFGJHGEBþ
öðWRRTVAABGDEDEHGGEGþR°°°RSUBGEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[HGGHLþVVVGJHHGGGHLþ°SUVVDHJJHHGFFHLþ°SUVVBGJJJJHHGFEGLþ°SUUVBGJJJJJJHHGDDGHþR°TUUDHJJJJJJJJHHGCCJLþ
R°STUGJJJJJJJJJJJHGDLLLLþR°°XXJJJJJJJJJJJLJHFJJLLþT°°SWLJJJJJJJJJJGEEEEEGJþHS°°°TWJJJJJJJJYYYYYYYYYþHGS°°°°RTWJJJJJXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGFGGDADFGVTTUUTVVWWWXWXþHGFGGDADFGGFGWUTVWWWWXWXþHGFGGDADFGGFG@@@@@AAGDEAþHGFGGDADFGGFF@@@@BB@BFDCþHGFGGDADFGGF@@@@BC@@DDBFþHGFGGDADFGFBC@@AB@@BDGBGþHGFGGDACFDDBD@@B@@B@GFDGþHGFGGDACCDFBB@BC@BB@GDFHþHGGGGDACCFCCBBDB@B@BHBGJþHGGGEBABFDEBFCC@@B@CGBGHþHGGEBBABCDCDFDB@@A@CFDHGUWþ[YHFD@CBABDDEDFDBAC@BCDGHFJXUWXWWWEF@CCBABCAABDBACEEDBFJHBJJJXWYYYECBD@BAADEDBAACGDFD@HHFDHJJV[[Y[EACDBBABGGEDEGFDGJHDJGCGJJW[[YUCDBCCABEBBBEEDGJGDHGDHEJW[[YTEDCDDABBDDBBDGHFGHGFHJGþ[ööSVDDDBABEGFCFGGEHJGEHJþ[òVUVDDBACEGGBEGHJHGFDþ
öðWRRTVAABFEEDEHGGEGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLHGþR°TUUDHLLLLLLLLLLLHCHLþ
R°STUGJLLLLLLLLLLLGDJLLLþR°°XXJJLLLLLLLLLLJHFJJLLþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFGE@AABBAEGEDþHGGGGDADFGGFF@B@BBA@BFDFþHGGGGDADFGGF@B@BCA@@DGEGþHGGGGDADFGFBCB@DC@BBDGEGþHGGGGDACFDDBDADDA@B@FGEGþHGGGGDACCDFBBDEC@AB@GFFHþHGGGGDACCFCCBEEC@B@BHEGJþHGGGEBABFDEBFFEB@D@CHEGHþHGGEBBABCDCDFEDACB@CGFHGUWþ[YHFD@CBABDDEDFDDBDADCGGHFJXUWXWWWEF@CCBABCAABDDBDCAEBGJHDJJJXWYYYECBD@BAADEDBAADDBDH@HHFDJJJV[[Y[EACDBBABGGEDEGDBDJHDJGCGJJW[[YUCDBCCABEBBBEFCGJGDHGDHJJW[[YTEDCDDABBDDBBDGHFGHGFHJGþ[ööSVDDDBABEGFCFGGEHJGEHJþ[òVUVDDBACEGGBEGHJHGFEþ
öðWRRTVAABFEEDEHGGEGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLLHþR°TUUDHLLLLLLLLLLLHCCGþ
R°STUGJLLLLLLLLLLLHDGHJJþR°°XXJJLLLLLLLLLLJHFJJLJþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFGE@CADFAB@@@þHGGGGDADFGGFF@C@DGG@@A@@þHGGGGDADFGGF@D@DGHD@@@@AþHGGGGDADFGFBCD@FGADB@B@BþHGGGGDACFDDBDADGEDG@BA@BþHGGGGDACCDFBBDGHCGG@B@ACþHGGGGDACCFCCBGJGBGDBC@BDþHGGGEBABFDEBFHHEAGDCB@BCþHGGEBBABCDCDFGGDCFDCA@CBUWþ[YHFD@CBABDDEDFGDAFEGC@BCAHXUWXWWWEF@CCBABCAABDDAEEEJBADHDJJJXWYYYECBD@BAADEDBAAFGDHL@CHGFJJJV[[Y[EACDBBABGGEDEGGDGJHDJGFGJJW[[YUCDBCCABEBBBEFDGJGDHGGHJJW[[YTEDCDDABBDDBBDGHFGHGFHJGþ[ööSVDDDBABEGFCFGGEHJGEHJþ[òVUVDDBACEGGBEGHJHGFGþ
öðWRRTVAABFEEDEHGGEGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþ[[[þ[LLLLLþVVVGJLLLLLLLþ°SUVVDHLLLLLLLLLþ°SUVVBGLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLLHþR°TUUDHLLLLLLLLLLLJCDDþ
R°STUGJLLLLLLLLLLLHDGFEEþR°°XXJJLLLLLLLLLLJHFGGGGþT°°SWLLLLLLLLLLJGEEEEEGGþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXWXþHGGGGDADFGGFGE@CADFAB@@@þHGGGGDADFGGFF@C@DGG@@A@@þHGGGGDADFGGF@D@DGHD@@@@AþHGGGGDADFGFBCD@FGADB@B@BþHGGGGDACFDDBDADGEDG@BA@BþHGGGGDACCDFBBDGHCGG@B@ACþHGGGGDACCFCCBGJGBGDBC@BDþHGGGEBABFDEBFHHEAGDCB@BCþHGGEBBABCDCDFGGDCFDCA@CBUWþ[YHFD@CBABDDEDFGDAFEGC@BCAGXUWXWWWEF@CCBABCAABDDAEEEEBADC@FGGXWYYYECBD@BAADEDBAAFGDHD@CCFG@CFV[[Y[EACDBBABGGEDEGGDGJGDGGGJJJW[[YUCDBCCABEBBBEFDGJGDHGGHHJW[[YTEDCDDABBDDBBDGHFGHGFHJGþ[ööSVDDDBABEGFCFGGEHJGEHJþ[òVUVDDBACEGGBEGHJHGFJþ
öðWRRTVAABFEEDEHGGEGþR°°°RSUBFEEBDEEGþ°°SUTR°TECEHþUWXWWURSþ[YXWÿþþòYXYþYXYþWXYþYYXWXYþYXX[XYþ[Y[X[[[[þ[YXY[[[[[[[þ
[XY[[[[J[YXWWWWWþ	XY[[[[JHLHJJHHJUYþ[YXY[[[[JGFJJJJJJGGHþWWXY[[[[JGFHJJHHFGHHHþYY[YYY[[JGFHJHHGGHHGGHþòðY[JX[YYYYHGHHHFGHHHHHHFþòðYYJJW[YYYYHHHGGHHGGHHGGHòöPðYT[JJW[J[[JFGHHHHHHF[[HHþôðPööSVJJUYJJHHHHGGH[Y[[[[þôðòVUVJVRXHJJJYYY[[[[[þ
öðWRRTUUUUJJJ[[[[XWþR°°STUURUWWWWWWUþ°°SWTR°S°°°°þUXXWWURSþ[YXWÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEEEGGHLJLJGJHJJGVWWWþLLLLLLLLLJJJJJJLLJLJGJHJHDUWWWVþLLLLLLLLLLLLLLLLLJLJGJHJGBUWWWVþLLLLLLLLLLJHJLLLLJLJGJHJGBUWWWVþLLLLLLLLLLJCDFHJJJLJGJHJHDUVWY[þLLLLLLLLLLHDGDEGHJJJGJHJJGVWXX[þLLLLLLLLLJHFGGGDEGHJGJHJJJYXY[[þLLLLLLLJGEEEEEGGGEFGGHHJJYWY[[LþLLLLLLLYYYYYYYYYGGGEFHHYWX[[LþTWLLLLLXWWWWWWWWHHGGYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[HJLJLLLþFGVTTUUTVVWWWXWXWXXYXGHJHGDGLLLþFGGFGWUTVWWWWXWXBD@BCCGJHDBDLLLþFGGFGE@CADFAB@@@B@ADC@@GHGDGLLLþFGGFF@C@DGG@@A@@B@BC@ACCGJLJLLLþFGGF@D@DGHD@@@@AB@BB@CDDDJLJLLLþFGFBCD@FGADB@B@BB@B@@DB@BJLJLLLþFDDBDADGEDG@BA@BB@C@AC@ABHLJLLLþCDFBBDGHCGG@B@ACA@C@BC@BDGJJLLLþCFCCBGJGBGDBC@BD@@B@CB@CCEDGLLLôþEBFHHEAGDCB@BC@AB@CA@CABFHHLþFGGDCFDCA@CB@B@AC@BB@DGHþ
DAFEGC@BCA@B@BC@CB@DþEEJBADC@@B@CB@BAþL@CCA@B@BB@BþGB@B@ACBþG@@@ÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEEEGGHLJLJGJHJJGVWWWþLLLLLLLLLJJJJJJLLJLJGJHJHDUWWWVþLLLLLLLLLLLLLLLLLJLJGJHJGBUWWWVþLLLLLLLLLLJHJLLLLJLJGJHJGBUWWWVþLLLLLLLLLLHCHLLLLJLJGJHJHDUVWY[þLLLLLLLLLLHGHLLLLJLJGJHJJGVWXX[þLLLLLLLLLJHGHJLLLJLJGJHJJJYXY[[þLLLLLLLJGEEEEEGJLJLJGJHJJYWY[[LþLLLLLLLYYYYYYYYYLJLJHJHYWX[[LþTWLLLLLXWWWWWWWWLJLJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJHGHLLLþFGGFGWUTVWWWWXWXGJDGHHHJJGFGLLLþFGGFGE@CADGAGDEAGDFJHDEJJHGHLLLþFGGFF@C@DGG@BFDCGBGHDFHHJJLJLLLþFGGF@D@DGHF@DDBFGBGGBHJJJJLJLLLþFGFBCD@FGEGBDGBGGBGEDJGEGJLJLLLþFDDBDADGEGG@DFDGGBHDFHEFGHLJLLLþCDFBBDGHCGH@DDDGFDHBGHBGJJLJLLLþCFCCBGJGBHGBDBDGEDGBHGBHHGDGLLLôþEBFHHEDHFCBBDFBFGDHFDHFBFHHLþFGGDFHGCCADEBGDFHDGGBFHJþ
DDHGGCADDDDGBGHBHGBHþGGJBCDDBEGDHGDGFþL@BDDDGEGGEGþBBAD@DHGþE@@@ÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEEEGGHLJLJGJHJJGVWWWþLLLLLLLLLJJJJJJLLJLJGJHJHDUWWWVþLLLLLLLLLLLLLLLLLJLJGJHJGBUWWWVþLLLLLLLLLJJHJLLLLJLJGJHJGBUWWWVþLLLLLLLJHFDCJLLLLJLJGJHJHDUVWY[þLLLLLJHGEDGDLLLLLJLJGJHJJGVWXX[þLLLJHGEDGGHFJJLLLJLJGJHJJJYXY[[þLJGGFEGGGEEEEEGJLJLJGJHJJYWY[[LþHGFEGGHYYYYYYYYYLJLJHJHYWX[[LþTWGGHHHXWWWWWWWWLJLJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJJHJLLLþFGGFGWUTVWWWWXWXGJDGHHHJJHGHLLLþFGGFG@@@@@AACDEAGDFJHDEJJJHJLLLþFGGBA@@@@BB@BEDCGBGHDFHHJJLJLLLþFGGB@@@@BC@@CDBFGBGGBHJJJJLJLLLþFGAA@@@AB@@BDEBGGBGEDJGEGJLJLLLþF@@@@@@B@@B@CDDGGBHDFHEFGHLJLLLþ@@AA@@BC@BB@CDFHFDHBGHBGJJLJLLLþ@A@@@BDB@B@BCBGJEDGBHGBHHGDGLLLôþ@ABCC@@B@BCBGHBFGDHFDHFBFHHLþCBB@@A@CCDHGBGDFHDGGBFHJþ
@@A@BCDGHFDGBGHBHGBHþ@@BBFGGBEGDHGDGFþC@GGFDGEGGEGþGFCEBEHGþGB@BÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEEEGGHLJLJGJHJJGVWWWþLLLLLLLLLJJJJJJLLJLJGJHJHDUWWWVþLLLLLLLLLLLLLLLLLJLJGJHJGBUWWWVþLLLLLLLLLLJHLLLLLJLJGJHJGBUWWWVþDDDEEEDDDDDCJLLLLJLJGJHJHDUVWY[þEEEEEEEEEFGDLLLLLJLJGJHJJGVWXX[þGGGGGGGGGGGFJJLLLJLJGJHJJJYXY[[þGGGGGGGGGEEEEEGJLJLJGJHJJYWY[[LþHHHHHHHYYYYYYYYYLJLJHJHYWX[[LþTWJJJJJXWWWWWWWWLJLJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJJLJLLLþFGGFGWUTVWWWWXWXGJDGHHHJJJHJLLLþFGGFD@@@@@AAGDEAGDFJHDEJJJLJLLLþFGGBA@@@@BB@BFDCGBGHDFHHJJLJLLLþFGGB@@@@BC@@DDBFGBGGBHJJJJLJLLLþFGAA@@@AB@@BDGBGGBGEDJGEGJLJLLLþF@@@@@@B@@B@GFDGGBHDFHEFGHLJLLLþ@@AA@@BC@BB@GDFHFDHBGHBGJJLJLLLþ@A@@@BDB@B@BHBGJEDGBHGBHHGDGLLLôþ@ABCC@@B@CGBGHBFGDHFDHFBFHHLþCBB@@A@CFDHGBGDFHDGGBFHJþ
B@A@BCDGHFDGBGHBHGBHþ@@DBFJHBEGDHGDGFþD@HHFDGEGGEGþJGCEDFHGþHDADÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþGGHLLLHDB@@@@@BDHJLJGJHJXUVWVUþHGGGHLLHGGEEEGGHLJLJGJHJJGVWWWþJHHGFFHLLJJJJJJLLJLJGJHJHDUWWWVþJJJHHGFEGLLLLLLLLJLJGJHJGBUWWWVþJJJJJHHGDDGHLLLLLJLJGJHJGBUWWWVþJJJJJJJHHGCCJLLLLJLJGJHJHDUVWY[þJJJJJJJJJHGDLLLLLJLJGJHJJGVWXX[þJJJJJJJJLJHFJJLLLJLJGJHJJJYXY[[þJJJJJJJJGEEEEEGJLJLJGJHJJYWY[[LþJJJJJJJYYYYYYYYYLJLJHJHYWX[[LþTWJJJJJXWWWWWWWWLJLJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJJLJLLLþFGGFGWUTVWWWWXWXGJDGHHHJJJLJLLLþFGGFG@@@@@AAGDEAGDFJHDEJJJLJLLLþFGGFF@@@@BB@BFDCGBGHDFHHJJLJLLLþFGGF@@@@BC@@DDBFGBGGBHJJJJLJLLLþFGFBC@@AB@@BDGBGGBGEDJGEGJLJLLLþFDDBD@@B@@B@GFDGGBHDFHEFGHLJLLLþCDFBB@BC@BB@GDFHFDHBGHBGJJLJLLLþCFCCBBDB@B@BHBGJEDGBHGBHHGDGLLLôþEBFCC@@B@CGBGHBFGDHFDHFBFHHLþFDB@@A@CFDHGBGDFHDGGBFHJþ
BAC@BCDGHFDGBGHBHGBHþEEDBFJHBEGDHGDGFþD@HHFDGEGGEGþJGCGEFHGþHECEÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEDEGGHLJLJGJHJJGVWWWþLLLLLLLLLJHEHJJLLJLJGJHJHDUWWWVþLLLLLLLLLLHFHLLLLJLJGJHJGBUWWWVþLLLLLLLLLLHGHLLLLJLJGJHJGBUWWWVþLLLLLLLLLLHCHLLLLJLJGJHJHDUVWY[þLLLLLLLLLLGDJLLLLJLJGJHJJGVWXX[þLLLLLLLLLJHFJJLLLJLJGJHJJJYXY[[þLLLLLLLJGEEEEEGJLJLJGJHJJYWY[[LþLLLLLLLYYYYYYYYYLJLJHJHYWX[[LþTWLLLLLXWWWWWWWWLJLJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJJLJLLLþFGGFGWUTVWWWWXWXGJFGHHHJJJLJLLLþFGGFGE@AABBAEGEDGFGJHDEJJJLJLLLþFGGFF@B@BBA@BFDFGEGHDFHHJJLJLLLþFGGF@B@BCA@@DGEGGDGGBHJJJJLJLLLþFGFBCB@DC@BBDGEGGDGEDJGEGJLJLLLþFDDBDADDA@B@FGEGGDHDFHEFGHLJLLLþCDFBBDEC@AB@GFFHFDHBGHBGJJLJLLLþCFCCBEEC@B@BHEGJEDGBHGBHHGDGLLLôþEBFFEB@D@CHEGHDFGDHFDHFBFHHLþFEDACB@CGFHGDGDFHDGGBFHJþ
DBDADCGGHFDGBGHBHGBHþCAEBGJHDEGDHGDGFþH@HHFDGEGGEGþJGCGHFHGþHJFGÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGGGHXUVWVUþLLLLLLLHGGEEEGGHLJHGGGHHJGVWWWþLLLLLLLLLJJJJJJLHFFGHHHJHDUWWWVþLLLLLLLLLLLLLLGEFGHHHJHJGBUWWWVþLLLLLLLLLLLHGDDGHHJJHJHJGBUWWWVþLLLLLLLLLLHCCGHHJHJJHJHJHDUVWY[þLLLLLLLLLLHDGHJJJHJJHJHJJGVWXX[þLLLLLLLLLJHFJJLJJHJJHJHJJJYXY[[þLLLLLLLJGEEEEEGJJHJJHJHJJYWY[[LþLLLLLLLYYYYYYYYYJHJJHHHYWX[[LþTWLLLLLXWWWWWWWWJHJJYVWX[LLþ°°°RTVWWWWWWWWWWWWVUWY[[[LLLþSSTSSRRRSTUTUUVWWXXYXY[[[LJLLLþTSTTTUTTVVWWWXWXWXXYXY[[JJLJLLLþFGVTTUUTVVWWWXWXWXXYXJHJJJLJLLLþFGGFGWUTVWWWWXWXBD@BCCHJJJLJLLLþFGGFGE@CADFAB@@@B@ADCDEJJJLJLLLþFGGFF@C@DGG@@A@@B@BC@FHHJJLJLLLþFGGF@D@DGHD@@@@AB@BBBHJHJJLJLLLþFGFBCD@FGADB@B@BB@B@DJHGHJLJLLLþFDDBDADGEDG@BA@BB@C@FHFGHHLJLLLþCDFBBDGHCGG@B@ACA@CBGHEHJJLJLLLþCFCCBGJGBGDBC@BD@@BDHGGHHGDGLLLôþEBFHHEAGDCB@BC@AGGHFGHGDFHHLþFGGDCFDCA@CB@GHGHFHGEFHJþ
DAFEGC@BCADGFHGFHGDHþEEJBADHDEGGHGFGFþL@CHGFGGGGEGþJGFGHGHGþHJGGÿþWWWWWWWWYþWXYYYYYYYXXWVVXþ[YYWWWWWWWWW[YXWWUUWþ
[Y[YYWWWWWWWWW[[YXXWWVSWþ[Y[Y[YYDCCCCCCCD[[YXXWWWUUSVþ[LLLJGB@@@@@@@BGJLJHYWWUUVVTþLLLLLLHDB@@@@@BDHJLJGJHJXUVWVUþLLLLLLLHGGEEEGGHLJLJGJHJJGVWWWþLLLLLLLLLJJJJJJLLJLJGJHJHDUWWWVþLLLLLLLLLLLLLLLLLJLJGJHJGBUWWWVþLLLLLLLLLLLHLLLLLJLJGJHJGBUWWWVþLLLLLLLLLLJCDDDDDEEEDDDDDBUVWY[þLLLLLLLLLLHDGFEEEEEEEEEEEFVWXX[þLLLLLLLLLJHFGGGGGGGGGGGGGGYXY[[þLLLLLLLJGEEEEEGGGGGGGGGGGYWY[[JþLLLLLLLYYYYYYYYYHHHHHHHYWX[[JþTWLLLLLXWWWWWWWWJJJJYVWX[JJþ°°°RTVWWWWWWWWWWWWVUWY[[[JJJþSSTSSRRRSTUTUUVWWXXYXY[[[JHJJJþTSTTTUTTVVWWWXWXWXXYXY[[HGGGJJJþFGVTTUUTVVWWWXWXWXXYXGGJGEBEHJJþFGGFGWUTVWWWWXWXBD@BCCGHGB@BGJJþFGGFGE@CADFAB@@@B@ADC@@GGEBEHJJþFGGFF@C@DGG@@A@@B@BC@ACCFGGGJJJþFGGF@D@DGHD@@@@AB@BB@CDDDFHHJJJþFGFBCD@FGADB@B@BB@B@@DB@BDGHJJJþFDDBDADGEDG@BA@BB@C@AC@ABCFHHJJþCDFBBDGHCGG@B@ACA@C@BC@BDDDEHHJþCFCCBGJGBGDBC@BD@@B@CB@CCB@BFHHôþEBFHHEAGDCB@BC@AB@CA@CA@ACCFþFGGDCFDCA@CB@B@AC@BB@ACDþ
DAFEGC@BCA@BBBC@CB@CþEEEBADC@CFGGFCBAþD@CCFGJGHJHGþGGGJHGJGþHHGGÿþ[YWWXWWUUWWþYWYWXVUUUUVUWþòYXY[YWVTUUUUWYVþ
YXY[YWVTUUUU[YYþWXY[[Yôðþ[[[XþYYXWXY[[[WöðPþ[[[[XX[XY[[[YWWWVWòð[[[[[[X[[[[[[YWWVUTTW[[[[XY[[[[[[[[YXVWVUTSW[[[[[þ[[[[J[YXWWWWWWVSVVUTTVYY[[þ[JHLHJJHHJUYXSSUSWWUWYYYþ
FJJJJJJGGHHGVSSSWYYþJHHFGHHHHH[SSWYYþGHHGGHHGGHHGþHHHFGHHHþGHHGÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHJLLLþR°TUUDHLLLLLLLLLLLJCDFHJþR°STUGJLLLLLLLLLLLHDGDEGþR°°XXJJLLLLLLLLLLJHFGGGDþT°°SWLLLLLLLLLLJGEEEEEGGþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFGE@CADFAþHGGGGDADFGGFF@C@DGþHGGGGDADFGGF@D@DþGGGDADFGFBCDþGDACFDDBþACCDÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHJLLLþR°TUUDHLLLLLLLLLLLHCHLLLþR°STUGJLLLLLLLLLLLHGHLLLþR°°XXJJLLLLLLLLLLJHGHJLLþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFGE@CADGAþHGGGGDADFGGFF@C@DGþHGGGGDADFGGF@D@DþGGGDADFGFBCDþGDACFDDBþACCDÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLJJHJLLLþR°TUUDHLLLLLLLLJHFDCJLLLþR°STUGJLLLLLLJHGEDGDLLLLþR°°XXJJLLLLJHGEDGGHFJJLLþT°°SWLLLLJGGFEGGGEEEEEGJþHS°°°TWJHGFEGGHYYYYYYYYYþHGS°°°°RTWGGHHHXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFG@@@@@AAþHGGGGDADFGGBA@@@@BþHGGGGDADFGGB@@@@þGGGDADFGAA@@þGDACF@@@þAC@@ÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLJHLLLLþR°TUUBDDDDDEEEDDDDDCJLLLþR°STUFEEEEEEEEEEEFGDLLLLþR°°XXGGGGGGGGGGGGGGFJJLLþT°°SWGGGGGGGGGGGGEEEEEGJþGS°°°TWHHHHHHHHYYYYYþYYYþGFS°°°°RTWJJJJJXWWWWWWWWþGFDTS°RR°°°RTVWWWWWWWWWWþGFDEFTRRSSTSSRRRSTUTUUVWþGFCEFDAUTSTTTUTTVVWWWXWXþGFCEFDADFGVTTUUTVVWWWXWXþGFCEFDADFGGFGWUTVWWWWXþ
GFCEFDADFGGFD@@@@@AAþGFCEFDADFGGBA@@@@BþGFCEFDADFGGB@@@@þCEFDADFGAA@@þFDACF@@@þAC@@ÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[HGGHLLLHDB@@@@@BDþXSVVVGJHHGGGHLLHGGEEEGGHþ°SUVVDHJJHHGFFHLLJJJJJJLþ°SUVVBGJJJJHHGFEGLLLLLLLþ°SUUVBGJJJJJJHHGDDGHLLLLþR°TUUDHJJJJJJJJHHGCCJLLLþR°STUGJJJJJJJJJJJHGDLLLLþR°°XXJJJJJJJJJJJLJHFJJLLþT°°SWLJJJJJJJJJJGEEEEEGJþHS°°°TWJJJJJJJJYYYYYYYYYþHGS°°°°RTWJJJJJXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGFGGDADFGVTTUUTVVWWWXWXþHGFGGDADFGGFGWUTVWWWWXþ
HGFGGDADFGGFG@@@@@AAþHGFGGDADFGGFF@@@@BþHGFGGDADFGGF@@@@þFGGDADFGFBC@þGDACFDDBþACCDÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEDEGGHþ°SUVVDHLLLLLLLLLLJHEHJJLþ°SUVVBGLLLLLLLLLLLHFHLLLþ°SUUVBGLLLLLLLLLLLHGHLLLþR°TUUDHLLLLLLLLLLLHCHLLLþR°STUGJLLLLLLLLLLLGDJLLLþR°°XXJJLLLLLLLLLLJHFJJLLþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFGE@AABBAþHGGGGDADFGGFF@B@BBþHGGGGDADFGGF@B@BþGGGDADFGFBCBþGDACFDDBþACCDÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLGEþ°SUUVBGLLLLLLLLLLLLHGDDGþR°TUUDHLLLLLLLLLLLHCCGHHþR°STUGJLLLLLLLLLLLHDGHJJþR°°XXJJLLLLLLLLLLJHFJJLJþT°°SWLLLLLLLLLLJGEEEEEGJþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFGE@CADFAþHGGGGDADFGGFF@C@DGþHGGGGDADFGGF@D@DþGGGDADFGFBCDþGDACFDDBþACCDÿþYWWWWWWWWWþXWWWWXYYYYYYYXþXWWXY[YYWWWWWWWWWþXWY[Y[Y[YYWWWWWWWWWþYXY[[[Y[Y[YYDCCCCCCCDþ
WX[[[LLLJGB@@@@@@@Bþ	WY[[LLLLLLLHDB@@@@@BDþXSVVVGJLLLLLLLLHGGEEEGGHþ°SUVVDHLLLLLLLLLLJJJJJJLþ°SUVVBGLLLLLLLLLLLLLLLLLþ°SUUVBGLLLLLLLLLLLLHLLLLþR°TUUDHLLLLLLLLLLLJCDDDDþR°STUGJLLLLLLLLLLLHDGFEEþR°°XXJJLLLLLLLLLLJHFGGGGþT°°SWLLLLLLLLLLJGEEEEEGGþHS°°°TWLLLLLLLLYYYYYYYYYþHGS°°°°RTWLLLLLXWWWWWWWWþHGGTS°RR°°°RTVWWWWWWWWWWþHGGGGTRRSSTSSRRRSTUTUUVWþHGGGGDAUTSTTTUTTVVWWWXWXþHGGGGDADFGVTTUUTVVWWWXWXþHGGGGDADFGGFGWUTVWWWWXþ
HGGGGDADFGGFGE@CADFAþHGGGGDADFGGFF@C@DGþHGGGGDADFGGF@D@DþGGGDADFGFBCDþGDACFDDBþACCDÿþGDþJGFJþJGGEGGþJJGGGJJGþGHGGGGJHGHþSUWXYJJJHGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþDBþBBBCþD@@ACBþHJG@BBB@þGGGGG@@@@DþSUWXYGGBCDE[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþDGFGþ@@@EGGþHGD@DJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþEGFGþB@BEGGþHGEBEJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþGGFGþDADEGGþHGGDGJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþHGFGþECEEGGþHGGEGJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþHGFGþGEGEGGþHGGEGJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþGDþHGFGþHGGEGGþHGGEGJJEþGGEEGGHEGHþSUWXYGGGGGH[þWWWVUTTTTUUVWXþYXWWT°RUVWöþö[YYWV°TX[YWY[ðþ˜öYXXWSTôôø[W[[þ
UU8ôööYXTöòðôøXY[ðYþWUWôö86799W6ò7XUVòòþXUWòôö˜ô85469ðö;6679òþUUWôòôðòôöôôôôôáôf™96533þðUWôòöôöòðòfðøðPáðö¨IööòðPáðòôôöôPáòôöf˜¨þôðPáðáðôòPòôôðPPáðþôðPPðáòðPòôáòôòðáþ
ôðPPðPðôøòáðòôòþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþ[HþYWVWþVVVXXYþUVWWWWWWþRSTUUVVWWWþSUWXYTUWY[JþWWWVUTTTVVVVWôþYXWWT°RUVWYYY[Jþö[YYWV°TX[YWYYYJJþ˜öYXXWSX[[W[[[þ
UU8ôööYXTôøööö[[YYþWUYôö86799Wöðòøöôöö[YYþVXYòôö˜ô8546ôáöøöôô—¦þX[WôòôðòôöôòPòðPáòööôðP—þðUXTTWôöòðòðôðPPáðò™™òðPáðòôôööôöööôðáPPfôþôðPáðáðôòPòôôöòðfþôðPPðáòðPf¨öôôþ
ôðPPðPðôø˜™fþôðPPðáðòô˜þôðPPðPðPPþôðPPPPþôðPPÿ