þLöþGJLôþGGGELYþ@FGDDGH[þA@BDCEGGH[þBA@BBDBFEGþB@@@B@BBEDBHYþ@@@@@C@@@EDBG[þGDGJG@@@B@CCAEGXþJGFJJGGH@BCB@@FHXY[þ
JGGEGGGHJJJJG@BFVTTUYþJJGGGJJGHJJGEEGHWSTTTT–þGHGGGGJHGHGGGGE[WYYUST–þSUWXYJJJHGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDED@DCGHEHYþ@DDD@D@@@EHDH[þDBDFG@@@D@DHDEGXþBBBCDBBC@DHGEEGHXY[þ
D@@ACBADEEGGEEGHVTTUYþHJG@BBB@DFFFEEGHWSTTTT–þGGGGG@@@@DFGGGE[WYYUST–þSUWXYGGBCDE[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDEEBECGHEHYþBCCDBEC@BEHDH[þGDGGHB@BEBEHDEGXþDGFGGFEEBEHGEEGHXY[þ
@@@EGGEGGHHGEEGHVTTUYþHGD@DJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDEGDGCGHEHYþDCCDDHDACEHDH[þGDGGHDADGDHHDEGXþEGFGGFEEDGHGEEGHXY[þ
B@BEGGEGGHHGEEGHVTTUYþHGEBEJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDEGEGCGHEHYþDCCDEHECCEHDH[þGDGGHECEGEHHDEGXþGGFGGFEEEGHGEEGHXY[þ
DADEGGEGGHHGEEGHVTTUYþHGGDGJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDEGFGCGHEHYþDCCDFHFFCEHDH[þGDGGHGEEGFHHDEGXþHGFGGFEEGGHGEEGHXY[þ
ECEEGGEGGHHGEEGHVTTUYþHGGEGJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþLöþLJLôþJHHELYþDHGEEGH[þFCGGDGJJH[þGFCGGFGJHHþGEDEGGGCGHEHYþDCCDFHFGCEHDH[þGDGGHGGEGGHHDEGXþHGFGGFEEGGHGEEGHXY[þ
GEGEGGEGGHHGEEGHVTTUYþHGGEGJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþHöþDDGôþDCC@GYþ@CB@@BC[þGGFD@BDDC[þHHFJJGJJHHþGGFFGGGEGJGHYþEDDEFHFFEGJFH[þGDGGHGGEGGHHFGGXþHGFGGFEEGGHGEEGHXY[þ
HGGEGGEGGHHGEEGHVTTUYþHGGEGJJEGHHGEEGHWSTTTT–þGGEEGGHEGHGGGGE[WYYUST–þSUWXYGGGGGH[[YYY[[YWVWVUþWWWVUTTTTUUVWXYö[XWWUSUYXWWT°RUVWööòYWXT°VUþWV°TX[YWY[ððò[YWYTUþTôôø[W[[òöôò[[YVU[þ
ðôøXY[ðYôò[öôòòòôþ7XUVòòöôòòööôôþ6679ò6358GFþ653337ööþööööÿþ[YWWXWWUUWWþYWXVUUUUVUWþYWVTUUUUWYVþWVTUUUU[YYþ[[[Xþ[[[[þ[[[[þ[þ>þYþYþ[YþGG[þHHYþGHHYYþHH[YYL[Yþ[HXW[[LJ[XXþYWVW[[Y[[[JJ[VVXþ
VVVXXYXXYY[LJJ[VTTUYþUVWWWWWWWXYLLHHJWSTTTTWXþRSTUUVVWWWYJJJJJYYUSTTTVTþSUWXYTUWY[JJJHHJJJ[YWVRTTVSþWWWVUTTTVVVVWôôòôöHHJ[XWWWRTWTYXWWT°RUVWYYY[JHHöôòöYYWWXT°YXþWV°TX[YWYYYJJöööòYðYWWYTUþX[[W[[[ööôðôòVUY[þ
ôøööö[[YYôððòöUUUþøöôöö[YYYôòôö[Wþöôô—¦IöòðòþôðP—G¦ööþ™§GÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þGJLôòòXT°°°°SWV[[[[þ
GGGELYYUR°°°RUWW[[[[þ@FGDDGH[XWT°°°°SWVY[[[þA@BDCEGGH[VVT°°°°UWVY[[þBA@BBDBFEGSUU°°°RWVW[[[þB@@@B@BBEDBHYVRTS°RUWUX[[@@@@@C@@@EDBG[XVR°SUWVUY[þG@@@B@CCAEGXYXVT°RSTVWWYYYþ@BCB@@FHXY[YWUW3VUSSRRTþ
G@BFVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDED@DCGHEHYVRTS°RUWUX[[@DDD@D@@@EHDH[XVR°SUWVUY[þG@@@D@DHDEGXYXVT°RSTVWWYYYþ@DHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDEEBECGHEHYVRTS°RUWUX[[BCCDBEC@BEHDH[XVR°SUWVUY[þHB@BEBEHDEGXYXVT°RSTVWWYYYþBEHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDEGDGCGHEHYVRTS°RUWUX[[DCCDDHDACEHDH[XVR°SUWVUY[þHDADGDHHDEGXYXVT°RSTVWWYYYþDGHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDEGEGCGHEHYVRTS°RUWUX[[DCCDEHECCEHDH[XVR°SUWVUY[þHECEGEHHDEGXYXVT°RSTVWWYYYþEGHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDEGFGCGHEHYVRTS°RUWUX[[DCCDFHFFCEHDH[XVR°SUWVUY[þHGEEGFHHDEGXYXVT°RSTVWWYYYþGGHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þLöôþXR°°°°TWY[[þLJLôòòXT°°°°SWV[[[[þ
JHHELYYUR°°°RUWW[[[[þDHGEEGH[XWT°°°°SWVY[[[þFCGGDGJJH[VVT°°°°UWVY[[þGFCGGFGJHHSUU°°°RWVW[[[þGEDEGGGCGHEHYVRTS°RUWUX[[DCCDFHFGCEHDH[XVR°SUWVUY[þHGGEGGHHDEGXYXVT°RSTVWWYYYþGGHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿþXSUW[þöþW°°°TWX[þHöôþXR°°°°TWY[[þDDGôòòXT°°°°SWV[[[[þ
DCC@GYYUR°°°RUWW[[[[þ@CB@@BC[XWT°°°°SWVY[[[þGGFD@BDDC[VVT°°°°UWVY[[þHHFJJGJJHHSUU°°°RWVW[[[þGGFFGGGEGJGHYVRTS°RUWUX[[EDDEFHFFEGJFH[XVR°SUWVUY[þHGGEGGHHFGGXYXVT°RSTVWWYYYþGGHGEEGHXY[YWUW3VUSSRRTþ
EEGHVTTUYYVUWÑ5DWUWþWSTTTT–XWVXÑ5@WþST–WWXÑ7þWVUT–W5þSUVUÿ[YWWXWWUUWWþYWXVUUUUVUWþYWVTUUUUWYVþWVTUUUU[YYVþ[[[XWþ[[[[Yþ[[[[[þ[þ[[þþ[Y[þþXþYáþ[[Xþ
YôòPþ[W[þ[YôòðáW[þGG[PòôðW[þHHYô[áðXþGHHYYWYôXHH[YYL[YXWY[þ[[LJ[XXVU[YWWWYYYþ[[JJ[VVXWRWWSRRTþ
LJJ[VTTUYXVRWX[VWWþWSTTTTWXYXVTV7[WþSTTTVTYWUWX5þTTVSTXWXþWTX[ÿþòô˜þPPPááðþðððòøþòðôôöööôôôôføþòðáòööôòòô™¨þ
òðPòôPôöôòPôö˜þòðòöøöòáòöðáòôöööòþòðPPðPòôôööôPòôPöòðPPþôðPPðáðôòPòôòPðPPþôðPPðáòðPòôáôòðPþ
ôðPPðPðôøòáðPPþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþ[YþUW[XþXXUWWTþUUWXYUWTþôôööööôòððþòðððò–þ–¤G¦öôôö—öþòôö¤—–—öôRþòáðòôööööôôôò	þôòððFôô§ôòðñ8;þ
§øôòðð8Ff§ö98;Fþ™øöòôôöööô55–—G§GFfþòðòòöööòòô959F–ff
þòðPòôPôöôòPðò;778;KðPPþòðòöøöòáòöðáòôöòPôðòðPPðPòôôööôPòôPöòðPPþôðPPðáðôòPòôòPðPPþôðPPðáòðPòôáôòðPþ
ôðPPðPðôøòáðPPþôðPPðáðòðPPþôðPPðPðPPþôðPPPPþôðPPÿþ°RTTþUWU°TTTTþXUWWURTTTTUþFGJWUWXURTTTUUòþ99GG9WUðUTURRôòþ
öööô75679òðRàööþòðòòð536ñàQQàQRQ©¨§þòððòô;ññQRRQ¨§§ôòðþôòøöôòòðððQððñðôôòðþöôòòððòôRð		ôòþ
öôôôôòòòôö§	ô	ôððþø©©©§™˜ôôðþ§™f˜ðððþ¨ööòñòþôðÿþ[[þþ[Y[þXþ[[Xþ[W[þW[þW[þXþþ>XWþUWYþWY[þWWWWXYþYWXVWWWW[þ7BYXWVUSUWYþXY3D[XWVSV[[þY[4DF[XXTWþ[Y[[47BGXXV[GJþUW[XTTYDF[YVIFGIþ
XXUWWTTTWYWCGöôööööG–—þUUWXYUWTTW—WVVDEöðòôöGFþôôööööôòðð—–QààKJFDFGöGFþòðððò–	RàQLJJIGFIþ–¤G¦öôôö—öàQRIGF–—Gôðòôö¤—–—öôRààQFIKðPPþðòôööööôôôò	QRð

òPðPPþðFôô§ôòðñ8;ñ
òðPþ
Ff§ö98;Ffð
áðPPþ—G§GFf

ðPPþ–ff
ð	ðPPþKðPPPPþôðPPÿþXSUW[þöþW°°°TWX[þXR°°°°TWY[[þ°°°°SWV[[[[þ°RUWW[[[[[þWVY[[[Y[þY[[Y[[þ[Y[Yþ[Yþ[Y[þXWYþUWY[þWY[[øþUVWWXY[[[ôöþ@WVVWWWW[[Yöòôþ
4X@WWVUSUWY[XöòòòPþ637[BDWVSVöø[YXGöôôöòPþSSU59EBWW—Iø[II–KöðöòðPPþTUöGBDFöJGKIF–KòððPPþUFIFBòðôöG—–FKôòðPþ
–òðòø©§¨øòáðPPþððôø¨˜©öðPPþðôø_§˜ôòPPþ_¨™¨ôPPþ¨ôðPÿþ[[þþ[Y[þXþ[[Xþ[W[[þW[Y[þW[Y[[þX[Y[YþY[Yþ[Y[þXWYþUWY[þWY[[øþWWWWXY[[ôöþYWXVWWWW[[Yôòôþ
7BYXWVUSUWY[XööòPþXY3D[XWVSV[[YXGF—GôôôòPþY[4DF[XXTW[öGF—GôòðPPþ47BGXXV[GJöøöôöö—ôPPþDF[YVIFGIöôôöôòðPþ
GöôööööG–—GøòáðPPþöðòôöGF–òðPPþFGöGFGPòPPþFIPPþôðPPÿþððñþððððððñþðððððððððð		þððððððððððððññ		þððððððððððððððññññðöþ
ððððððððððððððððñðññðôôþððððððððððððððððððñððððððôôþðððððððððððððððððððððððððððððôôþððððððððððððððððððñðððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþð	þðñþðððáðññññþðððððððññðñññþððððððððððññðððñññþ
ðððððððððððññðððñðððñþððððððððððððððñððððððððððñþðððððððððððððððñððððððððððððñþðððððððððððððððððððððððððððþððððððððððððñððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððôøôðþðôøøöøðððþððôøöòôøðððþððöùùööøûôøöòððþ
ððôøùùûûùùûûøùôøøöòððþððòôùùùûûûýûûøùùùùöòððþðððòöûûýýýýýýûýûùùùùùùøôðððþðððôöùýýýýýýýýýûûûûøùùðððþðððòùýýýýýýýýýýýûùùôðþ
ðððýýýýýýýýýûûùùòðþððöùùûýýýýýûùöôþððôùùùùùôððþððôöôòððþððððÿþ	þ	ññþññññþ
ññðððþðñðððþððRDþðððRQàQBþððððñRQQQQQQQ@þ
ððððððñRQQQQQQQRR4þððððððððñRRQQQð
3ñðððððððððñRRRRñ	
F4þððððððððRRRR	
ðñ	
–þððððRRRR	

	ññ	þ
ñðRRRR	


	ñþñðRRR	



		þñðð	


		þñðð	
		þñððñÿ
þ_LLL__þL???????þL????????þK????????þLJ????????þLK????????þH_????????þK_????????þLK????????þHL????????þHJ?????????þJJL????????_þ	GHL????ûûûûûþ	ññGGL?ûûûûûûûûþññññGGJ_ûûûûûûûûþ
ññðððFGHG_úûûûú_ûþðñðððGJGúú_ûúþ
ððRHHJH	_úþ	ññRQàFHJH	þññ	ñQQQQQQFGH
þððððð		QQQQRQQRððþðððððññRRQQQð
	ñðððððððððñRR	ñ	

	ðþððððððððRRñ
ñ	

ðñ		
þðððRR
ñ

	ññ	þ
ñðRRR
	ñþñðRRR
	
ñ	þñððñ

þñðð	
		þñððÿþ	þHðþññþHðþñññþ
ññðððþ
ðþ
Rþ
RQàQþ		
RQQQQQQQþðð
[RQQQQQQQRR4		RRQQQð
3



[RRRñ	
F4


[RR	
ðñ	
–5



	ñ[[R	

	ññ	

68




	[[	


	ñ	

75






			



			


4K



				


			ñðð


—69				
	ñ	IF
		
	ð—6K	ðððððð
I—IK	ðñððððððññññ	78K

	K964F;K98ñðððððððððððððññ–F8;9GF–G7478		þððððððððððððððñ––––I
			þðððððððððððððññññðñþ
ñðððððððððððððððñþñðððððððððððñþñððððððñþñðUðñþñððñÿñðþðþRHþRQàFHþQQQQQQFGþ
[QQQQRQQRþ	RRQQQð
	þ		
[R	ñ	

	ðñ



[_Kñ
ñ	

ðñ		



	
	

	ñûû_
ñ

	ññ		
	





	

	[_
	ñ	
	










		[
	
ñ				


	




			ñ

ññðð			





			
	ñ	IG
		
	ð

		ðððððð
I—IK	ððððññð		
	78K

	K964F;K98ñððððððð		——FG;9GF–G7478		þðððððððððð—–—ñ—–––I
			þðððððñðð	ñññðñþ
ñððñ	ðððñðððñþñðððððððððððñþñððððððñþñðUðñþñððñÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJGLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHGGGHJLþ	GGDBCDLGJLJHDCFLLHGHHHðþññGLEBGCHLHJLJFCGL??LGGHðþñññGJECGCEGBJFDBAL?J???H
ñþððFHDCFBGGFDCAADAGJL??L
þEFDBD@DCBBAABCDEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJGLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHGGGHJLþ	GGDBCDLGJLJHDCFLLHGHHHðþññGLEBGCHLHJLJFCGL??LGGHðþñññGJECGCEGBJFDBAL?J???H
ñþððFHDCFBGGFDCAADAGJL??L
þEFDBD@DCBBAABCDEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHGJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJGHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHGGGHJLþ	GGDBCDLGJLJHDCFLLHGHHHðþññGLEBGCHLCJLJFCGLJ?LGGHðþñññGJECGCEGJJFDBAB?????H
ñþððFHDCFBGGFDCAADGGJL??L
þEFDBD@DCBBAABCDEGGJLL
þ
CBD@A@@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHGJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHGGGHJLþ	GGDBCDLGJLJHDCFLJHGHHHðþññGLEBGCHLCJLJFCBL??LGGHðþñññGJECGCEGJJFDBAL?????H
ñþððFHDCFBGGFDCAADGGJG??L
þEFDBD@DABBAABCDEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHGGGHJLþ	GGDBCDLGDLJHDCFCLHGHHHðþññGLEBGCHLHJLJFCGL??LGGHðþñññGJECGCEGJJFDBAL??G??H
ñþððFHDCFBGBFDCAADGGJL??L
þEFDBD@DCBBAABCDEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGGGGCBDHDGGHJLþ	GGDBCDLGDLJHDCFLLGGHHHðþññGLEBGCHLHJLJFCGL?GLGGHðþñññGJECGCEBJJFDBAL?????H
ñþððFHDCFBGGFDCAADGGJL??L
þEFDBD@DC@BAABCDEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJJLLLþLLFDHHJHòððñòHJGHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFGGJLLLþHFDBDDEFDBABDEGDJJLLLþJHDBDDHGDGGCBDHGGGHJLþ	GGDBCDLGJLJHDCFLLGGHHHðþññGLEBGCHCHJLJFCGL??LGGHðþñññGJECGCEGJJFDBAL?????H
ñþððFHDCFBGGFDCAADGGJL??L
þEFDBD@DCABAABCAEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
HGRðññ		
JHþLJHHGðññ	JHHJLþLLGFJHHGGFFFFGGHHJJLLþLLGELLJJHHGGHHJLJJLLLþLLGDLLLLLJHHHJLLJJLLLþLLGDLLLLHòñðòôHLJGLLLþLLFDHHJHòððñòHJJHLLþLLFDLJGððððñôJHLLLþLLFCLJFððððñòHHLLLþLLECHHGDðñòñðDòHJJLLþLLEBDGG	òðDDòðôJJHLLþLJEBGCFGEFDD	HHGJLLþLHEBGEDBDEDCBDFEGJLLLþHFDBDDEFDBABDEGJJJLLLþJHDBDDHGDGGCBDHGGGHJLþ	GGDBCDLDJLJHDCFLLHGHHHðþññGLEBGCHLHJLJFCGL??LGGHðþñññGJECGCEGJJFDBAL?????H
ñþððFHDCFBGGBDCAADGGJL??L
þEFDBD@DCBBAABCAEGGJLL
þ
CBD@AA@@@@AAABCDGJ
þB@@@@@AA@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKKKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKKKKKKGKKKKKKKþLEBGFKKKHKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKJKLLþJDBFDJKKKKKKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLKKKLHðþññGEBGCGLLLLLLLLLLLLJGGHðþñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DGGFDCDFGGGJLLLL
þEDBB@DDCBAAABCDEGGJLL
þ
BB@BAA@@@@@@ABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKKKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKHKKKK;KKKKKKKþLEBGFKKKKKK;KKKKKJKKLþLDBFDKKKKLKLKKKKKKKLLþJDBFDJKKK;KKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLKKKLHðþññGEBGCGLLLLLLLLLLLLJGGHðþñññGECEBELLJJFJJLLLLLLLJ
ñþððFDCD@DGGFDDDFGGGJLLLL
þEDBB@DDCBAAABADEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKKKKKKKKKKKKL_þKEBHHKKKHKKKKK;KKKKKLþKEBHGKKKKKKKLKLKKJKKKþLEBGFKKKKKKK;KKKKKKKLþLDBFDKKKLKKKLKKKKKKLLþJDBFDJKK;KKKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLKKKLHðþññGEBGCGLLLLLLLLLLLLJGGHðþñññGECEBELLJJFJJLLLLLLLJ
ñþððFDCD@DGGFDDDFBGGJLLLL
þEDBB@DDC@AAABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKJKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKJKKLþKEBHGKKKKKKLKKKLKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLKKKLHðþññGEBGCGLLLLGLLLLLLLJGGHðþñññGECEBELLJJJJJBLLLLLLJ
ñþððFDCD@DGGDDDDFGGGJLLLL
þEDBB@DDCBAAABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKKKKKKKKKKJKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKKKLKKKKKLKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLKKKLHðþññGEBGCGLLLLGLLCLLLLJGGHðþñññGECEBELLEJJJJLLLLLLLJ
ñþððFDCD@DGGFDDDFGGGJJLLL
þEDBB@DDCBAAABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKK;KKKKKK_L?L?þ_FCJJKKLKLKKKKKKKKLL?þLECHHKK;KKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	GDBGCHLKKKHKKDLLLKKKLHðþññGEBGCGLLGLLLLLLLLLJGGHðþñññGECEBELLJJJJJLLLLJLLJ
ñþððFDCD@DGGFDDDFGGGJLLLL
þEDBB@DDCBAAABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKLKKKLKKKKKKKLL?þLECHHKKKKKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKDKKKLLLLþ	GDBGCHLKHKHKKKLLLKKKLHðþññGEBGCGLLLLLLLLLLLJJGGHðþñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DGGFDDDFGGGJLLLL
þEDBB@DDCBA@ABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
			ñþ




	ñ	ððñ
þ



ø	ñ	ðþ

øø
	
			

ðþ

øø
			


ø	ñ
þ	ðøñ	

ø	
þ	
øøøññññøø

þ	ñ
øø
			ñ	øøøþ	ñ				
øøøø

þ	LRRøø
		

Lþ
JHRðññ		
JLþLHHGGðññ	JHJL?þLGFLJHHGGFFFGGHJJL?L?þ?GELJLLJJJJJJJL?_L?K?þ?GDLL_??????????_K?K?þ?GDLJ_??????????_K?K?þ?FDLH_?_LLLLL_??_L?K?þ?FDLJKKKKKKKKKKK_L?L?þ_FCJJKKKKKKKKKKKKKLL?þLECHHKKKKKKKKKKKKKKL_þKEBHHKKKKKKKKKKKKKKKLþKEBHGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKEKKKKKLLþJDBFDJKKHKJKKKKKKLLLLþ	GDBGCHLKKKKKKKLLLJKKLHðþññGEBGCGLLLLLLLLLLLLJGGHðþñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DGGFDDDFGGGJLLLL
þEDBB@DDCBA@ABCDEGGJLL
þ
BB@BAA@@@@@AABCDGJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4þ3
ÿþ
_LLL__þL????????þL??????????þJKLþK??????????þJL__LþLJ??????????K__??_KþLK?????????_?__??KLþH_???????????__?_JLþK_?????????_?___LKLþLK?????????_?__LJLLþHL?????????L?_LKLLLþHJ??????????L?_JLLLLþJJL????????_?L?LHLLLLþ	GHL????ûûûûûû?_GJLLLLLðþññGGL?ûûûûûûûûûûLHLLLLLJðþñññGGJ_ûûûûûûûûûLHKLLLLLJñþððFGHG_úûûûú_ûûJKLLLLLLJþGJGúú_ûúLJLLLLLJ
þ
HJH	_úúLHLLLLJLþJH	HKLLGJJþH
	
ññ	þððñðþÿþ	HðþHðþþ
ñþþ
þ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþ›þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþ›þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþ›þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþ›þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþœœþ
ñþþ
œœþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþ›þ
ñþ››þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþ›þ
ªþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþþúþþùùúþ[úþùúþ
[[úùú	þ
	[úù	ðþ		
[[[	ððþñ



[_K_

	ñþ
	

	ñûû_KLJKLL	ðñþ
	

	[_;LG[
ðñþ



		[K[
ñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþGDGþ
ñþKD@DKþ
GDGþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþIþ
ñþIFIþ
Iþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþHJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþHJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþ	HðþHðþþ
ñþHJþ
Jþ
þ
[þ			
[þðð
[[[þ		[[[þ



[[[[þ


[[[	ñþ



	ñ[[[	ðñþ


	[[	ðñþ



			ðñþ				ðñþñ	IF;	ðñþ—IK	K	ñþ98;
ÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þK[Y[[[[[[[þK;8[Y[[[þ85[Yþ	Xþþ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[FJJLLLþù	
§ø\\ø\ùùW[JJJJJHLLLLþ	
¤¥§§§§§ùW[GFHJJJJGFL[þø^][<;^W[GJJGGJJJJJYþø¦[]Z<‰WWGAGJJJHFJJY[þöø¤¥¦¦¦¦YXWYJJJJJJJYXþøøøøøøYYXWYJJJJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøùððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ[Y[[[[[[[þK;[Y[[[þ;85[Yþ	Xþ5þ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[JFJLLLþù	
§ø\\ø\ùùW[JJJJJJLLLLþ	
¤¥§§§§§ùW[GFHJJJJHGL[þø^][<;^W[JGJGGJJJJJYþø¦[]Z<‰WWJG@GJJHFJJY[þöø¤¥¦¦¦¦YXWYJJJJJJJYXþøøøøøøYYXWYJJJJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøùððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ[Y[[[[[[[þK[Y[[[þK;8[Yþ	Xþ85þ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[JGFLLLþù	
§ø\\ø\ùùW[JJJJJJLLLLþ	
¤¥§§§§§ùW[GFHJJJJJHL[þø^][<;^W[JJGGGJJJJJYþø¦[]Z<‰WWJGFDGJHFJJY[þöø¤¥¦¦¦¦YXWYJGJJJJJYXþøøøøøøYYXWYJJJJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøùððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ[Y[[[þK;[Yþ	Xþ;8þ	XþYþðXöñþ
W[LJFþðñ
¦^\^§^W[JHGLLLþù	
§ø\\ø\ùùW[JJJJJJLLLLþ	
¤¥§§§§§ùW[HGHJJJJJJL[þø^][<;^W[JJJGHJJJJJYþø¦[]Z<‰WWJGFHJJHGJJY[þöø¤¥¦¦¦¦YXWYE@EJJJJYXþøøøøøøYYXWYGJJJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøù›ððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ5[Y[[[[[[[þ[Y[[[þK[Yþ	XþK;þ	XþYþðXöñþ
W[LLGþðñ
¦^\^§^W[JHGHLLþù	
§ø\\ø\ùùW[JJJFJJLLLLþ	
¤¥§§§§§ùW[JHJJJJJJJL[þø^][<;^W[JJJHJJJJJJYþø¦[]Z<‰WWJGFHJJJHJJY[þöø¤¥¦¦¦¦YXWYJGDJJJJYXþøøøøøøYYXWYJJJJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøù›ððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ85[Y[[[[[[[þ5[Y[[[þ[Yþ	XþKþ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[JJHLLLþù	
§ø\\ø\ùùW[JJJGFJLLLLþ	
¤¥§§§§§ùW[JJJJJJJJJL[þø^][<;^W[JJJJJJJJJJYþø¦[]Z<‰WWJGFHJJJJJJY[þöø¤¥¦¦¦¦YXWYJGGGJJJYXþøøøøøøYYXWYGCGJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøù›ððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þ;8[Y[[[[[[[þ85[Y[[[þ[Yþ	Xþþ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[JJHLLLþù	
§ø\\ø\ùùW[JJJJGFLLLLþ	
¤¥§§§§§ùW[JJJJJJJJJL[þø^][<;^W[GFHJJJJJJJYþø¦[]Z<‰WWG@BGGJJJJJY[þöø¤¥¦¦¦¦YXWYGCEHFJJYXþøøøøøøYYXWYGGEGYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøù›ððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[Y[[[[[[[þ[Y[[[[[[[þK;[Y[[[[[[[þ;85[Y[[[þ5[Yþ	Xþþ	XþYþðXöñþ
W[LLLþðñ
¦^\^§^W[JJJLLLþù	
§ø\\ø\ùùW[JJJJHGLLLLþ	
¤¥§§§§§ùW[GFHJJJHFJL[þø^][<;^W[JJJGGJJJJJYþø¦[]Z<‰WWJDDHJJHFJJY[þöø¤¥¦¦¦¦YXWYJFGJJJJYXþøøøøøøYYXWYJGGJYW[þøöøøøøøøøøø[YYYXWYJYW[þòòôööööööö[YYYXWW™þùôöööööööööY[YYYXôööþûûûûû[Y[YYôòþøûùùû[Y[öþøûùûù[Yþøûøû
ù[þððøùùøøùþððððøùùøùùøøù›ððððððøùùùùHøùùþððððöù
ññññññññøùùþððññðððððððððððøúþ
ññðððñððñññððøþððððððððððððþðððððððððð
þððððððððþððððÿþ[Y[Yþ[YYY[[WTþ[XY[[[[WUUþWY[[[YXWUUUUþYV[[YXWWWWWUUUþYYW[YWWWWVXWWUUðþWYXWWXVWWWWðWðððþYWYXòWWYVWWñððòòòòðþ
WYYðUVYXUWðôòðòððþððUUY[òVUððòôòððððòòþððWWñòñWUVððòWUWòòðþðððUVWñðòWUUXòððòXòUUWYñððþðððñññWWXñUWYXòððððþ
ðððñòðWWñðñððôòWðþððððWVWññððððððþððððððððððððþððððððððþððððÿþþþþþþþþþþþþ[þJþIþ¨Gþ˜™Gþö§˜¨þð§™þôðF˜ùþòI˜©ùþGô˜©úúþ—ö™¨úúúþ—ö¨§úúúúþIGú§úúúúþúFJû¨©úúúþ

úúúGF_¨úúú§þøúúúöGG©©úú©™þ

øúúúö—G_¨©ú¨˜ôþñ	øøúúôú—FI¨§˜Gôþððñññ	ø
øúúôøùI——FGôò	þðððññññññ	úöôöøøôò
ððþðñððñññññ	úøôôöööôòò
ðþððððñññññ	
		òòöôòòò
	ðþ
ððððññññññññ						þðððñðññðððððððððþðððñððððððððþððððððððþððððÿþ[YWXþ[WWþXXWþ[XWþXXþ[XþYþYþ[[þùùþþGøþò–öþðòGôöøþððòôF—ùûþðð———I—GùþðððIF—G
þðððððñ——G
ôøûûþððððñññòòûþððððððòòûùþðððððòøûøþðððòöòþððôñññþòðððþððÿþWVUUVWþVUUUUUUUUVþVUUUUUUUUUUVþSUUUUUUUUUUVþVRSUUUUUUUVXþWURRSTTUWYþWXXXXXþôöþððöôôöþôöøôøôþò		ô		øôþð

ðö

ôòþðòôôööôòò	þ	òððò	þöôôòòôôðþòð		ôþ	þÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULDJJF[WYþ_;KKKKKK_þULDJJFJJ[WXþ
_8KKKK98_ULJJJJFGEJ[WWþ_KKKKKKK_VKJJJJJFJJJJWþKKKKKK_VKJJJJJGFGEJWþ[WKJJJJJJFJJJWþVLJJJJJJHFHGWþøøøWKJJJJJJJFJJWþùùûWKJJJJJJJFHGWþWKJJJJJJFJJJWþöWKJJJJJJFHEJXþöööööûWKJJJJJFJJJJWþøøøøøüWKJJJJFHJJJJXþûüüüýýýýýýûWKJJJGGJJJJJXþûûûûûûûûûûùWJJJGFJJJJJJXþùWJJJJFJJBJKJXþùûûùûûùûûùùWJHHHFJJJJJJXþøûøûùûûùùWEDDDGJJGJBJXþöûùûùûXWWVWGDCDGGJJJXþöûøûøøûWUUWWWVWGECDGJJXþöòùöòXUUUUUWWWVWGFDFHXþññññññXUUUUUUUUWWWVVGEFXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULEDJJ[WYþ_;KKKKKK_þULEDJJJF[WXþ
_98KKKK9_ULJJJJJGFG[WWþ_KKKKKKK_VKJJJJJJFJJJWþKKKKKK_VKJJJJJJHFHGWþ[WKJJJJJJJFJJWþVLJJJJJJJFHGWþøøøWKJJJJJJFJJJWþùùûWKJJJJJJFHEJWþWKJJJJJFJJJJWþöWKJJJJFHJJJJXþöööööûWKJJJGGJJJJJWþøøøøøüWKJJGFJJJJJJXþûüüüýýýýýýûWKJJJFJJJJJJXþûûûûûûûûûûùWJJGHGJJJJGJXþùWJJJFJJJGGBGXþùûûùûûùûûùùWJJJFJJJJJGJXþøûøûùûûùùWGEEFHJJKJGJXþöûùûùûXWWVWHFDFHHJJJXþöûøûøøûWUUWWWVWHGDFHJJXþöòùöòXUUUUUWWWVWHGFGJXþññññññXUUUUUUUUWWWVVHGGXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKK8KKKþULGEJJ[WYþ_;;KKKKK_þULGEDJJJ[WXþ
_K9KKKKK_ULJJDJJJJF[WWþ_KKKKKKK_VKJJJJJJJFHGWþKKKKKK_VKJJJJJJFJJJWþ[WKJJJJJJFHEJWþVLJJJJJFJJJJWþøøøWKJJJJFHJJJJWþùùûWKJJJGGJJJJJWþWKJJGFJJJJJJWþöWKJJJFJJJJJJXþöööööûWKJGHGJJJJJJWþøøøøøüWKJJFJJJJJJJXþûüüüýýýýýýûWKFGFJJJJJJJXþûûûûûûûûûûùWJJJFJJJJJHJXþùWJJFHFJJBHGHXþùûûùûûùûûùùWJJJJFFJJJHJXþøûøûùûûùùWGEEFHJJKJBJXþöûùûùûXWWVWHFDFHHJJJXþöûøûøøûWUUWWWVWHGDFHJJXþöòùöòXUUUUUWWWVWHGFGJXþññññññXUUUUUUUUWWWVVHGGXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULJGJJ[WYþ_;K;KKKK_þULJGEDJJ[WXþ
_KK9KKKK_ULJJEDJJFJ[WWþ_KK8KKKK_VKJJJJJJFHEJWþKKKKKK_VKJJJJJFJJJJWþ[WKJJJJFHJJJJWþVLJJJGGJJJJJWþøøøWKJJGFJJJJJJWþùùûWKJJJFJJJJJJWþWKJGHGJJJJJJWþöWKJJFJJJJJJJXþöööööûWKFGFJJJJJJJWþøøøøøüWKJJFJJJJJJJXþûüüüýýýýýýûWKJFHFJJJJJJXþûûûûûûûûûûùWJJJJFFJJJJJXþùWJJJJFJJGJBJXþùûûùûûùûûùùWJJJJJFJJJJJXþøûøûùûûùùWGFFGJJJKJGJXþöûùûùûXWWVWJGEGJJJJJXþöûøûøøûWUUWWWVWJGEGJJJXþöòùöòXUUUUUWWWVWJHGHJXþññññññXUUUUUUUUWWWVVJGHXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULJJJJ[WYþ_;KKKKKK_þULJJGEGF[WXþ
_KK;8KKK_ULJJGEDHJJ[WWþ_KK9KKKK_VKJJJGDJJJJJWþKKKKKK_VKJJGFJJJJJJWþ[WKJJJFJJJJJJWþVLJGHGJJJJJJWþøøøWKJJFJJJJJJJWþùùûWKFGFJJJJJJJWþWKJJFJJJJJJJWþöWKJFHFJJJJJJXþöööööûWKJJJFFJJJJJWþøøøøøüWKJJJFJJJJJJXþûüüüýýýýýýûWKJJJJFGEJJJXþûûûûûûûûûûùWJJJJJJJJJJJXþùWJJJJJJJKJGJXþùûûùûûùûûùùWJJJJJJJJJJJXþøûøûùûûùùWGEEFHJJBJDJXþöûùûùûXWWVWHFDFHHJJJXþöûøûøøûWUUWWWVWHGDFHJJXþöòùöòXUUUUUWWWVWHGFGJXþññññññXUUUUUUUUWWWVVHGGXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULJJJJ[WYþ_;KKKKKK_þULJJJGGJ[WXþ
_KKK98KK_ULJJGFEDJJ[WWþ_KKKKKKK_VKJJJFEDJJJJWþKKKKKK_VKJGHGJJJJJJWþ[WKJJFJJJJJJJWþVLFGFJJJJJJJWþøøøWKJJFJJJJJJJWþùùûWKJFHFJJJJJJWþWKJJJFFJJJJJWþöWKJJJFJJJJJJXþöööööûWKJJJJFGEJJJWþøøøøøüWKJJJJJFJJJJXþûüüüýýýýýýûWKJJJJJGFGEJXþûûûûûûûûûûùWJJJJJJJJJJJXþùWJJJJJJJBJKJXþùûûùûûùûûùùWJJJJJJJJJJJXþøûøûùûûùùWFDDEGJJKJGJXþöûùûùûXWWVWGEDEGGJJJXþöûøûøøûWUUWWWVWGFDEGJJXþöòùöòXUUUUUWWWVWGGEGJXþññññññXUUUUUUUUWWWVVGFGXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJJ[XYþKKKKKKþULJJJF[WYþ_;KKK;8K_þULJGHGJJ[WXþ
_KKKK9;K_ULJJFJJFJJ[WWþ_KKKKKKK_VKFGFJJFJJJJWþKKKKKK_VKJJFJJJJJJJWþ[WKJFHFJJJJJJWþVLJJJFFJJJJJWþøøøWKJJJFJJJJJJWþùùûWKJJJJFGEJJJWþWKJJJJJFJJJJWþöWKJJJJJGFGEJXþöööööûWKJJJJJJFJJJWþøøøøøüWKJJJJJJHFHGXþûüüüýýýýýýûWKJJJJJJJFJJXþûûûûûûûûûûùWJJJJJJJJJJJXþùWJJJJJJJGJGJXþùûûùûûùûûùùWJJJJJJJJJJJXþøûøûùûûùùWEDDDGJJJJBJXþöûùûùûXWWVWGDCDGGJJJXþöûøûøøûWUUWWWVWGECDGJJXþöòùöòXUUUUUWWWVWGFDFHXþññññññXUUUUUUUUWWWVVGEFXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþWWYþUL[XYþY[[þULJG[XYþKKKKKKþULJJFJ[WYþ_;KKK;9K_þULFGFJJJ[WXþ
_KKKKK8K_ULJJFJJJJJ[WWþ_KKKKKKK_VKJFHFJJJJJJWþKKKKKK_VKJJJFFJJJJJWþ[WKJJJFJJJJJJWþVLJJJJFGEJJJWþøøøWKJJJJJFJJJJWþùùûWKJJJJJGFGEJWþWKJJJJJJFJJJWþöWKJJJJJJHFHGXþöööööûWKJJJJJJJFJJWþøøøøøüWKJJJJJJJFHGXþûüüüýýýýýýûWKJJJJJJFJJJXþûûûûûûûûûûùWJJJJJJGJJJJXþùWJJJJJGJKJGJXþùûûùûûùûûùùWHHHJJFJJJJJXþøûøûùûûùùWDCCDFHJBJGJXþöûùûùûXWWVWFDBDFFJJJXþöûøûøøûWUUWWWVWFDBDFHHXþöòùöòXUUUUUWWWVWFEDEGXþññññññXUUUUUUUUWWWVVFDEXYñþñðñññðWUUUUUUUUVTWWWVVWXXW[ñþñððññðññWUUUUUVSUVTWWWWXXYY[ñðþððððððññññWUUWSUVSUVTWXYYYYY[ððþððððñðððññWWTWSUVSUWYYYY[ñðþðððððððððñWWTWSUWYYY[ñðþ
ðððððððñðñWWTWYY[ñðþððððððñðññWY[ñðþðððððñððññðþððððððñðþððððÿþ

þ			
þñ	
				
þð

				þñ	


	
ñþññþñ	




ñðñþñðñ







ðñþðWVñWUUW


	
Fþ
ðððVVXUUUWW	

G–	FðþðððññðððVUWWX
		

–ññðððþððððñññUWññVX–UUY

ð	ððððþðððððððð—VUYYXVUWñ	ñððððððþððððð–Wñññññðññððððþ
ððððððòðVWññððñññðððþðððñðððððñðððñðþðððððððññðððþððððððþððððÿþ444þ444677þ55Ó4Ó67ˆˆþ555Ó4Ô77ˆ777þ55554577ˆˆ77ˆˆþ5555Ó4Ô777ˆ7ˆˆ555þ555555456667ˆˆˆ65555þ555555ÓÓÔ656ˆˆˆ65Ó554ÓÓþ5555Ô55456557ˆˆ754Ó5Ó4ÓÓ44þ44Ô5ÔÔÔÔÓ4ÔÔÓÔ7ˆ7Ô44554ÓÓÓ4Ó55ÓÓ54ÔÔ66ÔÔÓ5Ô5567ˆ754Ó5Ó455Ó4Ó5ô4Ó5Ô67766Ô4Ô6567ˆ76ÓÓ55455554Óôô4ÓÔ7ˆˆˆ76ÔÓ677ˆˆˆ7Ô55545555Óôôôôòò67ˆˆˆ76Ó577ˆˆ7ˆ766ÔÓ55ÔÔ5ôôôôôòòò77ˆˆ6Ô467ˆ777ˆˆ76ÓÓÔÔÔ5ôôôôôôþòòò7665Ó7ˆ777ˆˆ7754ÔÔÔÔôôôôôþòò6ÔÓ57ˆˆ7ˆˆ7754ÔÔ6ôôôôôþ
òò4Ô7ˆˆˆˆˆ654Ô66ôôôôþòÓ577775Ó5Ô66ôôôþò45445Ô67ôôôþò777ˆôôôþòˆôôÿþ444þ555455þ5555457ˆˆþÔÔ5554Ô7ˆ77þ55ÔÔÔÔÓÓ77ˆ7777þÓÓ55Ô6ÔÔÓ57ˆˆˆ7766þÓÓÓ56666Ô4Ô77ˆˆ7ˆ6555þ77ÔÓÓ567776Ô4677ˆˆ76555555þ7777ÔÓÔ7ˆˆˆ77ÔÓ777776555Ó5555ÓÓþ7776Ó56ˆˆˆˆˆ75577776Ô555ÓÔ555ÓÔ5ò7654Ô7ˆˆˆˆˆ75577777ÔÔ5ÓÔÔÔÔÔÔôôòòÔ54567ˆˆˆˆ75577ˆ77ÔÓ5666666ôôôòòòò45Ô6777765Ó677654Ô67ˆ77ôôôôôþòòòÓ5Ô66666545554567ˆˆˆ7ôôôôþòòò5ÔÔ6ÔÔÔ5555Ô6ˆˆˆˆôôôôþ
òò5ÔÔÔ6666677ˆˆˆˆôôôþòò455Ô6677777ôôôþòòòÓ44Ó5ôôôôþòòòòôôôôþòòôôÿþ5566þÔÔ5677þ55ÓÔÔ677766þ7755ÓÔ77ˆ77655þ777ˆ77556ˆˆˆˆˆ765566þ	ˆˆˆ777ˆ75567ˆˆˆˆˆˆ6556555þˆˆˆ7ˆˆ754Ô77777ˆˆˆ65ÓÔ557ˆ77þòˆˆˆˆ7ÔÓ5ÔÔ66667ˆˆ7Ô444Ô7ˆ777777òòˆ77Ô5455555ÔÔ67ˆ76ÔÔÔˆˆˆˆ7777ˆòòòò55444ÓÓÓÓÓ5Ô677667ˆˆˆˆˆ77ôôôòòòòòò44444Ó44455ÔÔ66777ˆ777ôôôôþòòòòòò55Ô555544Ó5ÔÔÔ6Ô6ôôôôôþòòòòòò66666ÔÔ5Ó4445ôôôôôþ
òòòòòòòÔ6ÔÔÔôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ44Ô66þˆˆ65Ó4Ô6Ô55þ667ˆˆˆ7ˆ65Ó5ÔÔÔ54ˆˆþ4ÓÔ67ˆˆˆ7754Ó555444Ôˆ44þ	4ÓÔ7ˆˆ776ÔÓ444ÓÓ5555ˆ455ÔÔþòÓÔ7777Ô5ÓÓÓÓ5555555ˆ455Ô5ÔˆˆÔþòòò555Ó44445555ÔÔÔ55Ô4Ó555ÔÔˆˆˆÔòòòòò55Ó4Ó55Ô6Ô66ÔÔ55Ó44Ó5555Ôˆˆòòòòòòòò556Ô6667666Ô55ÓÓ44Ó5ôôôôòòòòòòòòòòòÔÔÔÔ6ÔÔÔ5555ôôôôôôôôôþòòòòòòòòòòòò4444ôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔÔ555þ44Ó555ÔÔ55ÔÔÔþ666ÔÓ4Ó5555555ÔÔÔÔÔÔþ
ˆˆ766ÔÓÓÓ55Ó5555ÔÔÔÔÔ6ÔÔÔÔþˆˆ7765Ó444Ó44Ó55ÔÔÔÔ66ÔÔÔÔ6ÔÔþˆˆˆˆ6ÔÔÔÔÔÔÓ4Ó55ÔÔ6ÔÔÔ55ÔÔ6Ô555þòòˆˆˆˆˆˆ7654Ó55ÔÔÔÔ55555Ô6ÔÔ55ÓÓòòòòòˆˆˆ7Ô54455555Ó44Ó55Ô55555ôÓòòòòòòòò7766Ô555ÔÔÔÔ5Ó4Óôôôôôôôôòòòòòòòòòòòˆˆˆˆˆˆ76Ôôôôôôôôôôôôôòòòòòòòòòòòòò7ˆ776ôôôôôôôôôôôôôôþòòòòòòòòòòòòòòôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÓÓÓ55þÔÔÔ5ÓÓ5555ÔÔþ7777ÔÔ5Ó4Ó555Ô5555þ77ˆ77766ÔÔ554Ó55555ÓÓÓþ6677ˆˆˆ766676Ô544Ó5ÓÓÓÓ577þÔÔ67ˆˆˆ7667ˆˆ76Ô5Ó4Ó4Ó4Ó57ˆˆˆþ55Ô66776ÔÔ6ˆˆˆˆ6ÔÔÔÔÔÔÔÓ567ˆˆ77þ5555Ô55Ó55Ô7ˆˆˆ7777777ÔÓ567ˆ7755ò44444ÓÓ44567ˆˆˆˆˆˆˆˆ65ÓÔ777ôôôôòòòò5555545Ô677ˆˆˆˆ7ÔÓÓ5Ôôôôôôôôòòòòòòò55Ó4Ó55ÔÔÔÔÔÓ4Óôôôôôôôôôôòòòòòòòòòò55ÓÓ4444ÓÓôôôôôôôôôôôôòòòòòòòòòòòò6ÔÔÔ555ôôôôôôôôôôôôôþòòòòòòòòòòò7776ôôôôôôôôôôôôôþòòòòòòòòòòò7ôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ777þ77ˆˆ7ˆ77ˆþ77ˆ7ˆˆˆˆ777765þ777ˆˆ76667766545Ôþ6677ˆ76555Ô7ˆˆˆ777666þ
ÔÔ6776Ô4554Ô7ˆˆˆˆˆ776ÓÓþ555Ô66ÔÓ566ÔÓ56ˆˆˆˆˆˆ7ÔÓ555þÓÓ555Ô54Ô66665567ˆˆˆˆ76Ó57ˆˆˆþ44ÓÓ444Ó6555ÔÔ5ÓÔ77ˆ776546ˆˆˆ654Ó44ÓÓÓ5654445Ô5456666Ô54Ô7ˆˆ7ôô4ÓÓ55556Ô45545Ô54Ó55554ÓÔ777ôôôô4Ó55556Ô45545ÔÔ55444445Ô77ôôôôôôòòòòÓÔÔ544Ó5Ô66Ô55Ó55566ôôôôôôôôòòòòòò55Ó5Ô77766ÔÔ5ÔÔ66ôôôôôôôôôòòòòòòòò6777777766666ôôôôôôôôôôôþòòòòòòòò7ˆˆ7777776ôôôôôôôôôôþòòòòòòòˆˆ777776ôôôôôôôôôþ
òòòòòòò7776ôôôôôôôôôþòòòòòòÔ5ôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆÔÔþ66ÔÓÓÔþ7766ÔÓÔˆ77þ66765Ó67ˆ77ÔÓþ566665Ó77ˆˆˆ7Ô455þÔÔ66Ô556ˆˆˆˆ77545ÔˆþÔÔÔÔÔ55677ˆˆˆ7654ÔˆˆˆÔþ	55ÔÔ55Ó6ÔÔ77777ÔÓÓˆˆˆÔ44þÓÓ5555ÓÓÔ5Ó56Ô6Ô6Ô45ÔˆÔÓ4Ô66þ44Ó5ÓÓ4ÓÔ5Ó455555Ô54555545Ô666þ444Ó444Ó5ÔÓÔ4555Ó5554Ó5Ó4Ó5Ô66ôÓÓ444444564Ô5Ó555Ó55544Ó4Ó5ÔÔôôô5ÓÓÓÓÓÓÓ5555ÓÔ6555Ô55444Ó55Ôôôôô55ÔÔ55ÓÓÔÓ45677ÔÔÔÔ5ÓÓ4Ó55ôôôôôôòòò66Ô45ÔÔÔ7ˆˆ7766Ô5ÓÓÓ55ôôôôôôôòòòòò5Ó677ˆˆˆˆˆ776Ô55Ó55ôôôôôôôôþòòòòò77ˆˆˆˆˆˆ776Ô555ôôôôôôôôþòòòòˆˆˆˆˆˆˆ776Ô55ôôôôôôôþ
òòòòˆˆˆˆˆ776Ô5ôôôôôôþòòòˆˆˆ777Ô5ôôôôôþòòò777Ôôôôôôþòò66ôôôôþòòôôÿþ7þ55677þÓÓ444Ó556777þÓÓ5ÔÔÓ444Ó5566777þ7ÔÓ5ÔÔ5Ó444Ó55Ô6665Óþ7Ô45Ô6ÔÔ5ÓÓ4455ÔÔÔ554þòÔÓ5666ÔÔ55Ó4Ó55555Ó4Ó5þ	òò4Ô67666Ô5Ó4Ó55555Ó44Ó5þòòòò77766Ô5ÓÓ555555ÓÓÓÓ5Ó4þòòòòòˆ776Ô5455ÔÔ55ÓÓ555ÔÔÔÔ55þòòòòòòò77654Ó5Ô5Ó444Ó555Ô5ÔÔÔ555òòòòòòòò76Ô544Ó5554Ó555ÔÔÔôôôôôôòòòòòòòòòò666776545ÔÔôôôôôôôôôôôþòòòòòòòòòòòˆˆ65ôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ77þ55Ó4567þ66665Ó4567ˆþ775Ó666Ô5ÓÓ577ˆþˆˆ75ÓÔ7766ÔÓ45Ô66Ôþ777ˆ7Ô4567776Ô5Ó4ÓÓÓÓ4þ
777ˆ764567ˆ7766Ô5ÓÓ44Ó55þ777ˆ764Ô7ˆˆˆ7766ÔÔ55455Ô66þò77ˆ7556ˆˆˆˆˆ7666ÔÔÔ54Ó5ÔÔÔÔÔþòòˆˆ64Ô7ˆˆˆˆˆˆ766666ÔÔÓ455555þòòòò556ˆˆˆˆˆˆˆ7777ˆ7654Ó5ôôôôôôôòòòòòÔ77777777677ˆˆ65ÓôôôôôôôôôôòòòòòòòÔÔÔÔÔ55Ó5Ô7ˆ7ôôôôôôôôôôôôòòòòòòòòòò5Ó4Ó4ÓÔ7ôôôôôôôôôôôôôôþòòòòòòòòòòò54Óôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ55þˆˆ765þ77ˆˆ76ÔÓþÓÓÔ7ˆˆˆ76Ô4Óþ775ÓÔ7ˆˆˆˆˆ766ÔÔþ7775Ó567ˆˆˆˆˆˆ776ÔÓ4þ
ˆˆˆ77Ô5ÓÔ7ˆˆˆˆˆˆˆˆ765ÓÓ55þˆˆˆˆˆ7654Ô7ˆˆˆˆˆˆˆˆˆˆˆ76Ô5Ó44þˆˆˆˆˆˆ775567ˆˆˆˆˆˆˆˆˆˆˆˆˆ776ÔÔþˆˆˆˆˆ77Ô456777ˆˆˆ766667ˆˆˆ7ôôôôôˆ7ˆ77665ÓÔ6666666ÔÓ4456ˆˆôôôôôôôò76Ô55555555555545ÔÔ54Ôôôôôôôôôôòò5ÓÓ55ÓÓ4444445ÔÔ555Óôôôôôôôôôôòòòò4Ô5444ÓÓ4Ó56545Ôôôôôôôôôôôôôòòòòòòò4Ó4Ó4Ó565Ó5Ôôôôôôôôôôôôôôþòòòòòòòò44ÓÔ555ôôôôôôôôôôôôôþòòòòòòòòòÔ5Ôôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆˆþ777ˆþÔÔ7777ˆþÓÓ5ÔÔÔÔ6667ˆþÓÓÓ55555ÔÔÔ677ˆˆþÔÔ5Ó4555555Ô6677ˆˆˆˆˆþ
66Ô5Ó4Ó555ÔÔ66677666677ˆþ666Ô554455ÔÔÔ666Ô5Ó444Ó5Ô666þ6666ÔÔ5Ó455ÔÔ6ÔÔ545566Ô545ôôôþ6666766Ô5Ó45555Ô554Ô676766ÓôôôôÔÔ6676ÔÔÔ5Ó44ÓÓ5Ó45ÔÔ5ÓÓ55ôôôôôô5Ô66655ÔÔ55444444565ÓÔ554ôôôôôôô556Ô5556Ô55ÓÓÓ4Ó5655Ô5ÓÓôôôôôôôôòÔÔ5Ó5Ô6Ô5ÓÓÓ44ÓÔ5Ó545ôôôôôôôôôôòòò55Ô6Ô5Ó444Ó45ÔÓ456ôôôôôôôôôôôþòòòò5Ó44Ó5554ÔÔ567ôôôôôôôôôôþòòòòòÔÔÔÔÓ5667ˆôôôôôôôôôþ
òòòòòò5Ó677ôôôôôôôôôþòòòòòò77ôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þÓÓþ444Ó4þ44444ÓÓ5Óþ44444ÓÓÓ5Ó555þ444444444ÓÓ555555þÓÓ444ÓÓÓ44444Ó55Ô6666þ
ÓÓÓ44ÓÓ5Ó4Ó44ÓÓ56677777þ44Ó444ÓÓÓÓÓ444Ó5Ô677777777þ554444444444444ÓÔ667777776ôôþ66Ô5444Ó4Ó444444Ó5Ô6ÔÔ5ÔÔ5Óôôôþ666Ô54ÓÓ555ÓÓ4444Ó565ÓÓÓ5Ó4ôôôô5Ô66Ô54Ó5555Ó444445Ô5Ó4Ó554ôôôôô5ÔÔÔÔÓ4555Ó44ÓÓ5Ó45Ô5Ó577ôôôôôôôò5Ô6Ô544Ó4Ó5ÔÔÔÔ54Ô6Ô77ˆôôôôôôôôþòò6Ô555Ô6677665567ˆˆ7ôôôôôôôþòòòÔ67ˆˆˆ77Ô4Ôˆˆ7ôôôôôôôþ
òòòòˆˆˆˆ6557ˆ7ôôôôôôþòòòòˆ7Ô46ˆ7ôôôôôþòòò7557ôôôôôþòòò5ôôôôþòòôôÿþ4þÓÓþ44Óþ4444444Óþ4454ÓÓÓÓ44ÓÔþ55455ÔÔ555455ÔÔþÔÔ5ÔÔÔ6ÔÔ55Ó5Ô6777þ777Ô66666Ô554ÓÔ6777ˆˆþ	77ˆ7776666ÔÔ5Ó45Ô6777ˆˆˆˆþ4457ˆˆ7766ÔÔ55544556777ˆˆ777þ55545Ô777766Ô5555Ó4Ó5677777665Óþ55554567ˆ766ÔÔ5Ô55545Ô77766ÔÓÓôôò55ÓÓ67ˆˆ76ÔÔ6666ÔÔÓÓÔ777665ôôôôòòòòÔ776Ô555Ô67776654Ô77777ôôôôôþòòòò4Ó5Ó4ÓÔ67ˆ7765467ˆˆˆôôôôþòòòòÔ545Ô6777765Ó7ˆˆôôôôþ
òòòò45667777Ô45ˆˆôôôþòòòò677776Ô4Ôôôôþòòò67776Ôôôôþòò66ôôôôþòòôôÿþÓÓþ55ÓþÔÔ656666þ777Ô66777776þˆˆˆ77677ˆˆ776ÔÓ5þ5545ˆˆˆ77777776Ô5Ó67þ	ÔÔÔÔ5456ˆˆˆ7777766ÔÓ56ˆˆˆþ55ÔÔÔ5Ó4Ô777777776Ô54567ˆˆˆþò5555Ó45Ô66666666665Ó4577ˆˆˆˆþòòòò44Ó554444Ó5Ô6666Ô545677777þòòòòòò4Ó5ÔÔ6Ô54ÓÔ67776ÔÓÓ56676Ôþòòòòòòò77ˆˆˆ765ÓÔ67ˆ777Ô545Ô6ôôôþòòòòòòòˆˆˆ7ÔÓÓÔ6677776ÔÓ55ôôþòòòòòòˆ7Ô545ÔÔ667776Ô4ôôþ
òòòòò544555ÔÔ66666ôôþòòòòò44444455ôôôþòòòòò5ôôôôôôþòòòòôôôôþòòôôÿþ4þ445Óþ554445Ó45þÔÔ5Ó4544ÓÓ4ÓÔ6þ54Ó555Ô5Ó4ÓÓ44445Ô667þ54Ó55555Ó4ÓÓ44ÓÓ5ÔÔ666þ
ò55Ó44444444444455Ô66665þòòò55ÓÓ444ÓÓ55Ó455Ô6676Ô5þòòòòò554Ó55ÔÔÔÔ54ÓÔÔ67776Ô5þòòòòòò54ÓÔ67777Ô545ÔÔ6777ˆ777þòòòòòòò4577ˆˆˆ765ÓÓ55ÔÔ6677ˆˆˆˆþòòòòòòòòò7ˆˆˆ76ÔÓ44ÓÓ5555Ô677ôôôþòòòòòòòò77655444Ó4Ó44445ôôôôþòòòòòòòòÓÓ455Ô5Ô6Ôôôôôôôþ
òòòòòòòò455ôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ55þÔ555ÓÓÓþÔÔÔÔ5ÓÓÔ77þ6666ÔÔ545Ô7ÔÔÔþ776666Ô54566ÔÔ544þˆ7766666Ô5ÓÔ66555444þˆ76666666ÔÓ566ÔÔ5544555þ77ÔÔÔÔÔÔ777Ô467766Ô5Ó555ÓÓþÔÔÔÔÔÔ5ÔÔÔ7ˆˆ7557ˆˆˆ7655554ÓÔ54Ó5ÔÔ6ÔÔÔÔ67ˆˆˆ646ˆˆ77ˆ76Ô5ÓÓ5ôôòòò55ÔÔ66677ˆˆ7ÓÔˆ7777ˆˆ76ÓÓÔôôôòòòòò55ÔÔ6677655ˆˆ7777ˆˆ655ôôôôôþòòòòò55ÔÔ6Ô557777777ˆ755ôôôôþòòòòò555Ó57ˆ77777ˆ75ôôôôþ
òòòòòÓÓÔˆ77777ˆ75ôôôþòòòò57ˆ7777ˆ7ôôôþòòò7ˆˆˆˆôôôôþòòòòôôôôþòòôôÿþˆˆþ7ˆˆˆ766þ7ˆˆˆˆ76Ô44þ66677ˆˆˆˆ6Ô4577þ55ÔÔ667ˆˆˆˆ7Ô457ˆˆþ	55ÓÓ44Ó5ÔÔ67ˆˆˆˆ75467ˆˆˆˆþÓÓÓÓÓ44555Ô667ˆˆ76Ó57ˆˆˆˆˆˆþòòò66655Ó455ÔÔ667654Ô7ˆ7ˆˆˆ555þòòòòò765Ó4455ÔÔÔÔ5457ˆˆ7ˆˆ755ˆˆˆòòòòòòÔ5Ó444Ó555Ó457ˆˆˆˆˆ7ÔÓ7ˆˆˆòòòòòòòò444444Ó4Ó567ˆˆˆˆ7646ˆôôôþòòòòòòòÓÓ4444Ó567ˆˆˆˆ7Ô46ôôôþòòòòòòò5ÓÓÓ5Ô6ˆˆˆˆ75Óôôôþ
òòòòòò5555Ô7777Ôôôôôþòòòòòò55ÔÔôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆˆþ555ÔˆˆˆˆþÓÓ444Ó55ˆˆˆˆˆˆþ44ÓÓÓ5ÓÓÓ44455Ôˆˆˆˆˆˆþ	55Ó455Ô5Ô555Ó44Ó5ÔˆˆˆÔÓÓþòò456777776Ô5Ó44Ó555Ô5Ó444þòòòòˆ7ˆˆˆ77Ô55444ÓÓ555Ó4455þòòòòò77ˆˆ7Ô55ÓÓ44444Ó44455Ó44þòòòòòòˆˆ65Ó444Ó4Ó4444Ó5555Ó45Ô55òòòòòòòò4Ó544ÓÓÓÓÓÓÓ555Ô55ÓÓ5ÔôÓòòòòòòòòòò54Ó555555555ÔÔ5Ó4ôôôôôþòòòòòòòòò455ÔÔÔ6ÔÔÔÔÔôôôôôôôþòòòòòòòòò5555ôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÓþ55þ555555ÓÓ555þ5Ó4Ó5555555Ó55555þ65Ó455ÔÔÔÔ5555555555þ
6ÔÔÓÓ5Ô677766Ô55555Ó5Ó55þòÔ54ÓÔ777ˆˆ77Ô55ÓÓÓ5ÓÓ5555þòò54567ˆˆˆ77Ô5Ó4Ó4ÓÓÓ5Ó55555þòòòò67ˆˆˆ7754ÓÓÓ44Ó55555555Ô555þòòòòòˆˆˆˆ7ÓÔ6Ô54Ó555555555ÔÔ55Ô5òòòòòòòˆ7Ó6ˆ654Ó5ÔÔÔÔÔÔ5ÔÔôôôôôôòòòòòòòòòÔˆˆÔ4Ó55ÔÔÔ5ôôôôôôôôôôôòòòòòòòòòòò7ÔÓ4ÓÓÓôôôôôôôôôôôôôôþòòòòòòòòòòòò5Ôôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ6Ô5544þÔ6Ô55Ó44444þ55ÔÔÔÔ554444444þ555ÔÔ6Ô55Ó444444ÓÓÓþ555ÔÔ6ÔÔ55544ÓÓÓ4ÓÓ5555þÔ555555ÔÔÔÔ5Ó45ÔÔ544Ó5555555þÔÔ55ÓÓ555ÔÔ55ÓÔ66Ô54ÓÓ555555Ó555Ô5Ó444Ó5ÔÔÔ54Ôˆˆ654Ó55555ÓÓ4Ó5ôÓòò4Ó44Ó5Ô6ÔÓ57ˆ654Ó555Ó45ÔôôôôôôòòòÓ445Ô66ÔÓ5765Ó4ÓÓ4ÓÔôôôôôôôôôòòòòòÓÔÔÔÔ5ÓÔ6Ô5ÓÓÓ56ôôôôôôôôôôôòòòòòòòÔ5554Ô76ÔÔÔ6ôôôôôôôôôôôôôòòòòòòòòòò5567777ôôôôôôôôôôôôôôôþòòòòòòòòòòò77ˆôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ6544þ7654Ô777þ766545Ô777766þ77665ÓÓÔ677776Ô555þ676Ô5Ó45Ô67ˆˆ76Ô555Ô66þ666ÔÔ5Ó4ÓÔÔ7ˆˆˆ7Ô5555Ô67ÔÔþ66ÔÔ5544Ó5567ˆˆ7Ô5555Ô677Ô67þ6ÔÔ5Ó44444Ó5Ô666Ô555Ô67ˆˆÔôôôþ6ÔÔ55Ó44444ÓÓ4455555ÔÔ67ˆ7ôôôôô55Ô5544444Ó5555Ó455ÔÔÔ77ˆôôôôôôôÓ5Ô544444Ó5ÔÔÔ5Ó45Ô6677ôôôôôôôôôò55Ó4444Ó5ÔÔ555Ó5Ô6777ôôôôôôôôôôòòòÓÓ5Ó4Ó5Ô555545667ôôôôôôôôôôôôòòòòòò545Ô5Ó555ÓÔ66ôôôôôôôôôôôôôþòòòòòòò55555ÓÓÔÔôôôôôôôôôôôôþòòòòòòòòÔ54Óôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5455þ6Ô54567ˆˆþÔÔ5ÓÓÔ67ˆ7777þ5Ô55ÓÓ5Ô6777776777þ5555Ó4ÓÔÔÔ666666776ÔÔþ
5555Ó4Ó5555555ÔÔ6676Ô44þ555ÓÓ4444444Ó44Ó5ÔÔ666547ˆþ55ÓÓ4444445555554Ó5Ô6Ô54Ôôôþ5ÓÓÓ44444Ó5ÔÔÔÔ554Ó5ÔÔ5Óôôôôþ55ÓÓ44444Ó5ÔÔ555554Ó5554ôôôôôþ5555ÓÓ4444455ÔÓÓÓ5554Ó55ôôôôôôô555ÓÓ4444ÓÓ45ÔÓ44Ó55Ó4Ó5ôôôôôôôô55Ó44ÓÓ5555ÓÔ5Ó4Ó555Ó4Óôôôôôôôôôòò55Ô5Ô66Ô45ÔÔ55ÔÔÔ5Ó4ôôôôôôôôôôþòòò66765Ó7776766Ô5ôôôôôôôôôôþòòòòò4677777765ôôôôôôôôôþ
òòòòò7ˆˆ776Ôôôôôôôôôþòòòòòˆ776ôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5555þ5555Ó4ÓÓÓþ4ÓÓ5ÓÓÓ4ÓÓ5ÔÔþÓ4ÓÓÓÓÓ45555Ô555þ5Ó4444ÓÓ55Ô55555555þ55Ó4444Ó55Ô555Ó555555þ	ÔÔ5Ó4444Ó5555544Ó555555ÔÔþ6Ô5Ó44444Ó55544Ó44555555Ô6þÔÔÓ4444ÓÓ4Ó55ÓÓÓÓ4Ó555555ôôþ6654444Ó55545Ô5ÓÓ44Ó55555ôôôôþ776Ô5ÓÓÓ5Ô66ÔÓÔ666Ô555Ô55Óôôôôôˆˆ766ÔÔÔ667ˆ6ÓÔ77777766Ô55ôôôôôôòòˆˆ77777ˆˆ7Ô57ˆˆˆˆˆ776Ô5ôôôôôôôþòòò777ˆˆˆ647ˆ777ˆˆˆ7Ôôôôôôôôþòòòòˆˆ756ˆ77777ˆ76ôôôôôôþ
òòòòÔ5777777ˆˆ6ôôôôôþòòòòˆ77777ˆôôôôôþòòò777ˆôôôôôþòòòˆôôôôþòòôôÿþ7þˆˆˆþ777ˆˆ7þ777777ˆ75þˆˆ77777ˆ7556þ77ˆˆ7777ˆˆ64Ô7ˆþ777ˆ77777ˆ75567ˆˆˆþ66777ˆ777ˆ77ÓÔ7ˆˆˆˆˆþ
6666557ˆˆˆ777Ô4Ô77ˆˆˆˆ77þ66665457ˆ776665Ó66777776666ˆþÔÔ665Ó45776Ô56Ô45ÔÔ666ÔÔÔÔÔ7ˆˆˆÔÔÔ65Ó5ÓÔ76555Ô5455ÔÔÔ5555567ˆôôòÔ6Ô45Ó566Ô555Ô5455555ÓÓÓ5Ô6ôôôôòòÔÓ554Ô6Ô5Ó5Ô5Ó4555Ó444Ó5ôôôôôôòòòòÔ4566555ÔÔ54Ó4Ó44444ÓôôôôôôôòòòòòÓÔ6Ô555Ô5Ó444444444ôôôôôôôôòòòòòòò6ÔÔÔÔÔ5444444Ó4ôôôôôôôôôôþòòòòòòÔ6ÔÔ5Ó4444ÓÓÓôôôôôôôôôþòòòòòò655Ó4ÓÓÓÓ5ôôôôôôôôþ
òòòòòò5ÓÓÓÓ5ôôôôôôôôþòòòòòòò55ôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ77þ777þ77777þˆˆˆ77777þ77ˆˆ7777ˆ77þ66777ˆ77ˆ76Ô4þ6666Ô67ˆˆ755Ô5ÓÔÔþ66665ÓÔ7765ÓÓ5Ó555555þ
ÔÔ66544Ô66Ó5Ó554555ÓÓ44Ó5þ55Ô6Ô44Ó5ÔÓ55Ó5ÓÓ5ÓÓÓ44Ó555Óþ4445Ô65Ó4Ó5ÓÓÔ455455ÓÓ44Ó555ôôÓ444456ÔÓÓ4ÓÓ45Ó5545555Ó4Ó55Ôôôô4444ÓÔ65Ó44Ó4Ó4554Ó555Ó4Ó55Ôôôôôò4Ó45Ô6555554455ÓÓ555Ó4Ó55ôôôôôôòò44566ÔÔ55555ÔÓÓ555Ó4455ôôôôôôôòòòòÔ776666Ô65ÓÓ5Ô554455ôôôôôôôôþòòò7777776Ô45ÔÔ55ÓÓÓ5ôôôôôôôþòòò77775Ó5ÔÔÔ5Ó4Óôôôôôôôþ
òòò6Ô45ÔÔÔ5Ó4ÓôôôôôôþòòòòÔÔÔ54ÓÓôôôôôþòòòòò44ôôôôôþòòòòôôôôþòòôôÿþˆþ777þ77777þ6676Ô55þÔÔ665Ó4ÓÔÔþ445Ô654Ó5Ô655ÔÓþÔÓ45ÔÔ45Ô66Ô5Ô54444þˆÔÔÓ45654Ô66Ô4Ô5444ÓÓ44Ôþ77ÔÔ54565ÓÔÔÔ4554Ó555545ÔÔ5þˆˆˆ76654Ô654Ó5Ó55Ó55555ÓÓÔ65ôþˆˆˆˆˆˆ7654Ô6Ô5Ó5ÔÓ5ÔÔÔÔ554ÔÔôôôˆˆˆˆˆˆˆ77Ô4Ô666Ô545Ô66ÔÔ545ÔôôôôòÔˆˆˆˆˆˆ7Ô45Ô6Ô55Ô666ÔÔ5ÓÓÔôôôôôòòòˆˆˆˆˆ76545Ó4Ô67776ÔÔÓ45ôôôôôôþòòòÔÔˆ76Ô55Ô67ˆ776ÔÔ5ÓôôôôôôþòòòÔ77677ˆˆˆ7766ÔÔ5ôôôôôþ
òòòòˆˆˆˆˆ776666ôôôôôþòòòòòò76666ôôôôôþòòòòòò7ôôôôôþòòòòôôôôþòòôôÿþ5þ44þÔÔ545þ66Ô545ÔÔþ6666Ô545ÔÔ556þ6666666Ô45ÔÔ5Ô5455þ666666666ÔÓ555545Ô66666þ66ÔÔ66ÔÔ6677654Ó4ÓÔ677776Ô4Ôþ55ÔÔ6ÔÔÔ5ÔÔ67ˆˆ7Ô55Ô777ˆ77765577òÔÔÔ555555Ô67ˆˆ76677ˆˆˆˆˆ77Ô4Ôôôòòò5ÓÓ44445Ô7ˆˆ7ˆˆˆˆˆˆˆˆˆ765Óôôôòòòòòò5554Ó56777ˆˆˆˆˆˆˆˆˆ76ôôôôôþòòòòòòò5455Ô667777ˆˆˆˆˆ7ôôôôþòòòòòòòòÓ5ÔÔÔ6677ˆˆˆôôôôþ
òòòòòòòò5ÔÔÔ667ôôôôôþòòòòòòòòÔôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ444þÓÓ544Óþ555ÓÓ5445Ô67þ44Ó5555Ó5Ó4ÓÔ7ˆˆ6ÔÔþ44444Ó4Ó5555554456ˆˆ6ÔÔÔ67ˆþò4444Ó55555555ÓÓÔ66ÔÔ5Ô67ˆˆˆˆþòòòò555ÔÔÔ66Ô54ÓÔÔ555Ô66ˆˆˆˆˆˆþòòòòòòò66766Ô5444ÓÓ55Ô677ˆˆˆˆ76Óòòòòòòòòòò6Ô5ÓÓ444455Ô6677ˆˆˆ76ôòòòòòòòòòòòòÓ4ÓÓ444Ó5ÔÔ66777ˆôôôþòòòòòòòòòòòòÓÓ4Ó44Ó55ÔÔ6ôôôôþòòòòòòòòòòò5Ó5Ó44ôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔ5þ5555Ô5Ô55þ55Ó4Ó5555Ô555554ÓþÔÔ6ÔÔ5Ó4Ó5555555554Ó5Ô5þ	òÔ6ÔÔ554Ó555ÔÔÔ55Ó444Ó566þòòòò554ÓÓ555Ô555ÓÓÓ5Ô7777ÔÓþòòòòòòòÓ5555ÓÓ4445567777Ô545Ôþòòòòòòòòò44Ó5554ÓÔ67776Ô545ÔÔ6þòòòòòòòòòòòÔÔÔÓÓÔ777665Ó4Ó55ÔÔÔþòòòòòòòòòòòò54ÓÔÔ66Ô55Ó44ÓÓ555ôôòòòòòòòòòòòòòòÔÔˆÔÔ55Ó444ôôôôôôôþòòòòòòòòòòòòòˆÔ555ôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÓÓ555þÔÔÔ55Ó5555þ7767ÔÔ5544ÓÓ55ÓÓþ776Ô76776Ô5Ó44ÓÓ44444þ	77ÔÔ6ÔÔ6ˆˆ76Ô5Ó444444455þÔÔÓÓ55Ô6ˆˆˆ76Ô5555ÓÓ456ˆˆ7þòòò666Ó6ˆˆˆˆ7666ÔÔ5456ˆˆ7ˆˆþòòòòò6Ó7Ôˆˆˆˆˆˆ7765ÓÔ7ˆˆˆˆ77þòòòòòòò7Ôˆˆˆˆˆˆ7654Ô77ˆˆ765Ó44þòòòòòòòòòÔˆˆˆ76ÔÓ567776Ô544444Ó5òòòòòòòòòò776ÔÓÓ5Ô66Ô554Ó555ôôôôòòòòòòòòòòòò54ÓÔÔÔÔÔ54Ó5ôôôôôôôôòòòòòòòòòòòòò55ÔÔÔ5Ó4ôôôôôôôôôôôþòòòòòòòòòòòòòÔ554ôôôôôôôôôôôþòòòòòòòòòòòòÓôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ555ÔÔþÓÓÓ55ÔÔÔþÔÔ7ÓÓ45Ô6ÔÔ5þ667Ô7654Ô6776ÔÔ5þ55767ˆˆ75Ó67ˆ776ÔÔ5þ66577ˆˆˆ7556ˆˆˆ7766Ô5þ	ÓÓ667677ˆˆ7556ˆˆˆˆ776ÔÓÓÔþÓÓÓ6655Ô7777557ˆˆˆˆˆ77ÔÓÓ67þòÓ6ÔÓ45Ô6777Ó57ˆˆˆˆˆ76545ÔÔ54þòòò4Ó456677Ô4Ô677776Ô5455Ó45ÔÔ5þòòòòÓ5Ô7676545Ô666Ô5ÓÓ554ÓÔ676ôôòòòòòò77776545ÔÔÔ5Ó4Ó554567ôôôôôòòòòòòòò77Ô54555Ó4Ó555456ôôôôôôôòòòòòòòòò6ÔÓ4ÓÓ44Ó55Ó45ôôôôôôôôôòòòòòòòòòò5Ó444Ó5555ÓôôôôôôôôôôôþòòòòòòòòòòÓÓÓ5555ôôôôôôôôôôôþòòòòòòòòòò5555ôôôôôôôôôôþ
òòòòòòòòòò5ôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿ