þRSSRþRRSSQSRSþRRSSSQSSRRSRþSRQSRTSSQSRRRRRRþSSQRRSRRRSSTRSQRRQQRþ
RQSRRRQRRSRRRRRRRRSRQSSRþSSQSQSSRQRQRSSRSRRRRRSRRSSSTþTRRQSQSRRSSRRSRRSSRSSRRRSRSQSRRRþTSRQSQRSRRSRSSRRRQRRQSRQSTSSþRSSSRRQRRRRRQSRRRRRSRQQRþ
RQRRRQRRRSRSSRSRQSQQþTRSSQSSRRRQSSSQRþRRRRRRSRSSRRþSSSRQRSRþRRRRÿþRRRRþSSSRUSRRþQQQSSSSSTSRQþQQRSTSSRRRSTTWQRþQQRRSSSTUUTRRSSSSRRTþ
RRRRSSUVUUUWWTTTTTTXRRRRþRRRRSSSTWZXWWXYVUVVVVUTSRRRQþQUTRSSSSTUYZYXXX[XXWVTSSRQSQQQQQþTQSTTUVWZ\ZZZYZYXWTSSQSQSTTTþRRRRRRRRTV[Y[TSSTSRRTSQTþ
QTTTSSRRU\[URQXWQQQQþQSRRTRQVZWSSQQQQþTRRRRSUZURSRþRRRRRUTVþRRRRÿþRRRRþQUTSUVQRþQQQUSUTSQURQþQQQUTSSVTRSTQUQRþQQQRTSRRRXUURSRQQQRTþ
RRRQTSSRRQTZWWRRRRVSRRRRþRRRTUVVVSQSUX[YXTTRRRQQQRRRQþQUTRRRRRTUXZ[Z[\ZXVUWWTRSRVUQQQQþTQTTTRTQUSV[\][YWVXWWUUWSTTTþRRRRTTTSRRQU\YYYUTRQQVQTþ
QTTTSRRRRR]VSQQQQQQQþQSRRRRQUXSQSQQQQþTRSSUWSTRRSRþRSRRRRRQþRRRRÿþRRRRþRQSRTWWRþQQQTTWWYYWRQþQQQUTSTXWYXUUTQRþQQQRTSRRRSVVUSSSSRRTþ
RRRQRSSRTTVTRRRSRRRTRRRRþRRRRSSSRQSVVWXVTSTTUSRRQRRRQþQUTRRRRRRRSVWXXXTRUTUZWSQQSQQQQQþTQTTTRSQVXXVUTYYWUXWUQTQSTTTþRRRRTSTTTTTTUWYYUSTVUTQTþ
QTTTSRRRRSQSTTSQQQQQþQSRRRRQSQQQSQQQQþTRRRRSQTRRSRþRRRRRRRQþRRRRÿþRRRRþSRURURRTþQQQSSSSTUYYYYþQRQVSTUTTUVWYYWWþQQQTWUUVUTRTWXYZZWRTþ
RRRQVUVVUWTSSVYYY[ZXRRRRþRRSSTSQWUTTVSUVYYXZ[[ZTTRRRQþQUTUUWWXSUWWYSUXYYWVX[\[UTSQQQQQþTQTVVXURWYYRXZYYVYZX\ZUTSTTTþRRRTTSVYYT[[\XVXZZZUUVQTþ
QTTUSTTUZ\[XYXZZVTQQþQSRSUUUUUUUUVTTQþTRRRRSQTRRTTþRRTRTRRQþRRRRÿþTUXþSTUYVWþSTSTTUVWYYWVþSUUTSSRTWXYZZWVþSTSRRRRRSVWY[ZXXZþSTTUSRRTURTUXZ[[ZZWYþTSRUUSSVWUSVTVX[\[ZYXWþ
USRQTUWXVSTVVUZX\\\ZYXþ	WWVTRTVYVTTSVVUWYY\\[ZZSTþWVVTSVYWTRSTYYXYWY\\[[[TSRRþSXVTSWVXVRRUXUTVWWZ\XWVVTTRRQþQSUVTUWWWWRTWWUSVXWZYWWWYVSSRQQQþTVXVVXXTTUWWVSXXY[WVUW\YSTTTþXVVXYUUWXWVVYY[ZWTWZYYXTþ
ZZZUVWYWWXY[[[XUZZYUþUVXXYWXXZYZZWUXUþSSSUWYYZYUUUþURUUTTRQþRRRRÿþSTUUTUXþTUUUUWWVUTSSWVþSTQQRRSSSSQQRUWXþRRSUUTSTUSSSQTVXYþRSVVVSRQPSUVWTUWYZþTTSRUUTSRRSUXYZXZ[þTVTTVXUSUUUWYYWZX[ZþSTTVWXTUUVVXXYZXUY[[[þ	SSWVUWXUTTVVWXZZZUXZ[X[þRQQTVXXYTUVWWYY[Z[ZZ[[[[þSTTSSTRSWVWXXZWW[\ZZ\[\[þUUTTUUSTTTTTUVXY[[[[\Y[[þWVRUWVUSVWVWYYYZ\\[\\\ZYXþXWSVVUUQYWWXYZZ\\\\\\\[ZYXþTRVXUWWWVSZXXYZ[\[[\Z\[\\[[[þUVTVVXXWXU[YYZ[\\W[[[\Z[\\[[þXWUVUSSUXX\ZZ[\VVYZ[\[\Z[\\ZþXXVWVWWVVRTTUVWXXZZ[[[\[Z[YXþVWTXWXXYXWXTWWXXYXXZY[\\\XXWWUTSþTUXYYZYXYUXXYYZXYZYZXWUUSTTTþUZZ[ZYZUYYZZ[YZYZXWTTTQTþ
VZ[Z[WZY[[\Z[XYVUTUQþZSWW[Z[\ZYVVVTTQþTRTWWWVUUUSRþWZZUUTTQþRWRRÿþXWVVUTþWVTUUUUUVVþVTSRRSUVUUUVWþWTQPRSSTUUUUUUWþWVWUþ
TTQSUTRRUTTUUWWVWTWWUTTþ	UUTSUVUTRUUVWWVTUVVXWUTXþUUSUVVVWSWWWXXTTTUSWXWUXYþUTRTVWVVTVWXYSSTSUVVWXUVXþTWUSWWUVVVWXYVRSUVUUXWWWVXYþUXXSWVUVUWXYVSSSVXVTUWXXVXXþVVXVXVSVVUXYVQSVYXXTVWWXXXXZþWVXWUWTVVXXZYTRTVYYWTWXWYXXZþXXVVXVUVVWX[[VTTUVXXVTUVYXXY]þYYXXVXVXWWZ[[YXVUTUWXTUWXXYYZþZXXWXVXXX[[\YXXVUUUUSVVUYYZ[þ[YYXXXXYY[]\]WWXUSSUVXUYZZ[[þQQTVZYYXXX[][]]UXYVTTVXYYZ[[ZWVUþTWYYZXZY[[][]VYYUVWXZ[[[ZZVTþRWYZZZ\\\]]YYZVXY[[[\\VTþ
VUWWWWX[\[ZZZYZ\[[VQþVSRTUWWY[[\[[\YQþTRRSUUUYYYVRþRRVWWRRQþRRRRÿþRRRVþXWVXXXXVþWWYYWXXXWWVQþQQQWVWWXXVVVVWQRþWQVWXZZZYYWXYZYSWRWTþ
VYYWWXYZ\\ZWX]]]\XWVWWURþRRUVVWWXYZZ\]\ZZ]__\WXY\ZXUTþTXXXVVVVWV]Z\\]]^__]ZYXZ^^^\YYXVþTQVVWWWZ]]YZZ\^^]]ZY\^\^^\XTþVXVWWVWYYWVY\\\\\ZYXYYXTþ
QWYYXWXX]]ZZZZYXWWVVþWXXVXYW\\YYYXWQQþTXYYXWXXXWSWþRRWXXYWWþRWWRÿþRRRRþWVWZZZSRþUVWWYYYZZZUTþUUVXYZ]\^ZXYZXXSþWWXYZY\\]^_\WX]]YWWWþ
UUWXVVZZ\]^^^ZXY\]\]YYWVþRRRUVXVXX]^^^^^\\Z^_\YXWVWWVþQXWVWXZ^WYZ^^\^\\^^^^_\]ZXXXYXXQþTQTTYZ^^^^^^^^^^^^^^_]\ZYTTTþYZYYXZZYW\^^^^^^]ZXZ\YVRþ
XTWZZUWZ]__]]ZZXXWWSþQXY]Y\^]]ZZXWSTUþTX]^^]ZXZZZRþRZZ\ZZVVþRXZRÿþPQSþPPTVþPRTXY[[þPPTVYZ[[[þPPQUWZ[[[[þPPPQSVZ[[[[[þPPPPQQUXZ[[[[[ZþPQPPPQPRTXZ[[[ZYXVUþPQQQPPQQQTWZ[ZYXXVUSRþQQPPPPPPPQSVXYYYXWUTRRþ
QPQPPPPPPPQQSVXXYWWUTRRTþ	RPQQQPQQPPQQQRXXXWWVVþPQQQQPQQPPPQXXWXXWþQPQQQQPQQQXWWXXþPPQQQPQQQWXXþPPPQPQPXXþQQQQQXþQQQÿþRRRRRRRRRRRRþRRRQPPPPPPPPPPPQQQQþPQQRRRRSSSSRRRRRRPPQQQþPPQRSTUUUTTTSSSRRQQPQPPRQþPQRTUVVWWWWVUUTSSRRQPPPPQXWþXWVXXYYYYYYXWVUTTSRRQPPPPXXXþXWYZZZZZYYYYXWVUTTSSRQPPPWWXXþXXWX[[[ZZZZYYXVVUUTSRQPPPXXWXXþXXX[[[[ZZYYYXWVUTTSRPPXXWXWXþX[[[[[ZYXWVUTSRRRQQPWWXXþ
[[ZZYWUTSSRRQRPRQWXXþZYWUSSRRQQPRPPXXþZTQQQPPPPQXXþZPPQRPSXþPQRXÿþ
QþRQQRþPPPQRþPPPPQRSþPPPPPQRSþPPPPPPPSUTþQPPPPPRTUUSþQPPPQPQSUWWVSþPPQPPPPQTUXWXVSþQRPQQQPPQRUWWXXXVTþQPPPQXWWPRTUUWWWWWWSþ
PPQRQPXXXXXTUTSTVXVXVRþ	PPQPQRXXWXXWXVUWWTVWWVTþRRRXXWXWXWXUUUWWTWVTSþXWXXXWXXXXWWSTTWUSRþXWXXXWXWWUURUTSRþXWXWWXXUUPTSQþXXXXXURRTQþXXWXURQþXXSRÿþQPPþPPQQRþRQQQQPPPQQRQSUþ
PQRSTSSPRRPPPPQRQQRSTUþ	QPQPPQRQQQRRQQQSSSSTVWSWþPPPPPPRSSRRRPSSRUQUTVUSWWþQQPPPQQQPPQRRRRRRQUTUVSWWWþQPQPPPRQPQPPSSSRRRRRSVTSSSRþPQRQPQRSQPQPPQQTQRSRTURRUTSTSþPPPPPPPRRRSSPQQTSSSSSSUQUUUTTRþQQPQQQQPQRRQRSRTTSRUTSUUTTTTSTþQQQPQPQQRTTTSSSRTTUTSUSSRQþPPPPPPQQQPSSQQQQQQQRQÿþPPRþPPRTVþPPRTVXþPPRTVXYþPPQSUWYZþPPPQRUWYZ[þPPPQQSUWYZ[þQPPPPQRTVZZ[þPPPPPPQPRUWXZ[þPQQPPPPQQQSUVXZ[þPQQPPPPQQPRSTUXZþPQPQQQPPPQQPQSTWYþPQPQPPPQQQQQQQQSUVþQQQPPPPPQPPPPPVVVVþQPPQPPPPPPPPPVVUUVVþQQPPPPQQPQQQVUVUUVVþRQPQPQQQPQVVVVUVVþQPQQQQQQUVUUVVþQPQQQQVUUVVþQRPQVUVVþQQPVVþPÿþQQQþPPQQQQQQPþPPPPQPRRSTSSþPQPQQRSSTTUUUUþPQQRSTUVVVVVVVWþPPPRTVWWWWWXXXXXXþPPQSUWZXXYYYYYYYYYþVVTVXYYZZZZZZZYYYYYþVVVVXYZ[[[[[ZZZZZYYYþVVUVYZ[[[[[[[[ZZZZZYþVUVVVZ[[[[[[[[[[[[ZZZYþ
VUVVV[[[[[[[[[[[[[[[ZZþ	VUUUVVV[[[[[[[[[[[[ZZZYXXþVVUUVUV[[[[[[[[[[ZZZZYXZWVUþVUUVVVV[[[[[[[[ZZZZYYXWVUTSSþVVVVUUUV[[[[[[ZZZZYYXWUTSSSþVVVUVUUV[[[[ZZZYYXXWVTSRþ
VVVVVU[[[[ZZYXXXZWUTþVUVVVZ[[ZYXXXXWVþVVUU[Z[ZYXXZþVU[[YYYYþVZYXÿþPPPPPPPPPPPPPPPPPQQQQþVPPPPPPPPPPPPPPPPPPPVVþ	VVVSSSSRRRRRRQQQQPPPPVVþ	VVVVTTTTTSSSSRRRQQQVVVVþ	VVUVWWVVUUTTSSSRRRVVVVUVþVUVUVVXXWVUUTTTSSRRUUVVUVVþVVVUVVXXXWVUUTTTSSRVVVVVVVþSþVUVUUVVYXXWVUUTTTSVUUUUVUVþVVVUVYYXXWVUUTTTVVVVUVVVþ
VVVYYYXXWVUUTVUVUVVVþVVYYYXXWVUUVVVUVþZYYYXWVUVVUVþXWVUUTUVþTSVVÿþ	QPþPQQQPþPPPQQQPPþPPPQPPPRQQQPþQQPPPPPPPPPQQQPþRQQPPPPPPPPPPQQPPþRRQQPPPPPPPPPPQRQPþSSRRQQPPPPPPPPPPQSVVþTSSRRPQPPPPPPPPPPRVVþTTSSRRQPQPPPPPPPPPPVVVþ
TSSRRRRPRPPPPPPPPPPVVUþ	UTQRRQRRRQPQPPPPPPPPVVUVþSSRQQPQPPQPQPPPPPPPVUVVUVþSSSRRQPPPPPQPPPPPPPPVVVVVUVþRRRRQRRPPPPPPPPPPPQQVVUVVUVVþQQPRQPPPPPPPPPPQPVVVVVVUVUþRRRQPPQPPPPQQPQUVVVUUVVVþ
QQQQPPPQQPPPVUUVUVVVþPPPRQQPQPQUUVVVVþQQPPPPPVVVUUþPPQPUVUVþQVVVÿþRRQþPQRRþPQSTQþPQSTUSþPQRTVVTþPPQRTUXVSþPPQQSUVWXVTþPPPQSVVWWWXVTþPPQSUVWWXWWXVTþQPSUVVWXWXXWXVTþVVVRUVWWWWXXXXXTRþVUVVUWUUVWWXWWXWTSþVVVVVSTTUUVXVXWXVTSþVUVUVVVTVUVVWXVWXVVTSþVVVVVVVVWTWVTVWXWVVTSþVVUVVUVTWWTVVWVUUSRþVVVUVVWWTUWVVTTRRþUUVVVTSVWUUTRSþVVUVUUTVTRQþVVVUUTSRþVVUSRþSÿþPQQþPQRPSSþPPQQSSPVVþPPQRSTTQVVWþPQQRRRQSUVVVUUþQQQSTTRRURRUVVUUUþVUQRSTTTQUUUUVUVVUVþVVUSSUTTTUUUUTTVVVTVþUUUUUTSTRRUUUTVQTVTSSþ
VVVVTSSRSQSSUSTRTTTUUSUþ	VVVVTTTSSQSSSQTUVTUUUUTUþVTVUVRUTPQSSTUTTSTUTUUUTSþVVUVVVQRSRSSSTSVSSRUUUTTTSSþVVUVTVVSSSSSRSUSUSRUSTURSþUVTUVVVTURRRTUTTTRTSUURPþVVVUVVUVURQUUUUUTTTRRQþVVUVUVVSUUUUUTTSSRRþVVVUVVTTTTTTRSQþVUVUTSSQRQþVVVQRQþVQÿþPPPPPPPPPþPPPQQPPPPPQQQQQTþPQRRQQQQRRRRRTTTUþPQQQTRRRRRTSQQSRRUþSSRQRRQRRTRPRSSRRUTþPPQSRPQPRUSRRPRSQRRUþPRRQQQPPQQSRRQRRSRRRQþ
PPRQQPPPPPPUSRPSRRRRRRþ
RRPRRRQQPSQQRQSSRRRRSSSþQPRSRQQPQPQPPQQSTQTRSSRSþPRRRRRQSSSSQPQTSSSSSRSSTSþQSQSRRRRSSSSSPQQSQSRTTTTUUþQPRQRPRQQRSSRRTTRRRUUTTSUUUþQQPQQQRRRTTTTSSSSRRTTTTUTUSUþQQQPPPQRQRRRRRRRRRTTTTTRRTSSRþPPPPRPPQQQQQQPRRSQQQQRQSQQQQRRþQQPQPQQQQQQQSPPRPPPPPPPPÿþTVXþQQQQSUWþPPQPPRRSTVþQPQPPQPQPQRRSTþPPPPPPPQQQRPPPPPPþPQQQPPPPPQQQQPQQPPVþQQQQQPPPQQQPQQQPPPVVþQQQQQPQQQQQPPPPPPPPVUVþ
QPPQQQQQQQQPPPQRPQVUUVþ	PPQQQQPQQQQQPQQQPPPVUUVVþPPPPPQPQQQPQQPQPPPVUUUVVXþPQPRPQPQQQQQPPPPRVVVVVUVWVþQQQQQPQQPQQRQPPVVUUUVUVVWþQQQQQPPPPPPPPPVUVVUVVVþPPPPPQQQQPQVUVVVUVþQQQPQQQQQVVUVVþQQQQQPVVVVþPQPQVUþPÿþRRRQþQQRPPPRSþRRQQQPPPPRPQþUURRPQPQQRPPSQPPþWWUSRRRPQQSQSQQPPPQQþ
XXWWUTSRPPPQQQPQPQQRQQPPþWWXXWWVUTSQQQQQSQQQQQPPPQQSUþWYUVVVWUUUTSSRQQQQQQQQQQQQQQUWUUþWWXWXWWWTUSSSSRRQQQRQRRQSTQTþXWWXVVVUUUTTSSSRRQQRRSQSþ
WWXVVTVUVTTTRQQQRRQQþWWWWWVVUTTSSSQQQþXVVVVVTTTTSSþXWWWVTTUþXWWVÿþSUTUþYþT

UþR	

UþT	
	WUþRY
TUþSSU	

VWþSþU		UU		ZYZþSþSSSTSTTSSþSSS	Wþ

XSþSÿþTSSþ		
USþS		

þWUU		
	WSþTUVX		


UUTSþWXWXXY	
TS	
VUVþXWXYZ[ZYSXTUVY	
XXWY[þSSSSSSTUUXXVZYZYZ[\þSþSZUZXZZZUSSSSþZY[\\\þZ]þSSTTTþZ\]þSSÿþSUþTTSþVTþ	
	

TþT
	UþX

	
	
	UþSþ\ZX		
VþSþ
SþST\ZZXWUVWþSþST\ZXXWVUþSþSTTTþSSÿþSþSQþWþVXUþSS
SþSVXWXþ
SþWYZTRþSTTþSVZZWSUVþSþSSZYWXþSSþSÿþQQRQQQQQQQQQQQXþQQQQQQQQQQQQVVþ
QQQQRQQRQRQQQQQVUXþQQQQQQQRQQQQQQWVWXþQQQQQQQQRQQQQQRVUXVXþQQQQQQQRQQQRQQVWXVUWþQQRRQQQRQQRQRQQQQQXVUWVXVQQRQQQQQRQQQQQQQQWVWVXWVXþQQQQRQQQRQRQQQQQQWVUXUVXþQQQQQQQQQQQQQQQWVWXVWþ
QQQQQQQQQQQRQWVUWUþQQQQQQQQQVXVXþQRQQQQQQQWWUþQQQQQVUþQQWÿþQQRQQQQQQQQQQWXþQQQQQQQQQQQQUVVVþ
QQQQRQRQRQQRQQQUWWVUXþQQQQQQQQRQQQXVXVWVWXþQQQQQQQQQQQRQQUWUVWVUXVXþQQQQRQQQQRQRQQWVXWVWVWXVUWþQQRQRQQRQQRRXVUXUVWXVUWVXVQQQRQRQQQRQRRXVWXVWVWWVWVXWVXþUVTUVTUUTVTVUVVXVWUVXWVUXUVXþUVVTVTVUVUTUWUVXWVWVWXVWþ
VVTUUVVUTUXVXUVWVUWUþUVUTUTUVXWVWVXVXþVTVVUVXUVWWUþUUTUVVVUþVUXWÿþQQTSþQQQQSSSTþQQQQSQRTSSTSþQQQRQQQQRSTTUSTSþQQQSQQQQQSSSTTTSUTTþ
RQQQQQQQQQRSTTTTTTSTSTþQQQQQQQRQQQQQQSSUTSTUTTTUSTSþQQQQQQQQQQQQQQQQRSTTTTTTUTTTSSTTþUVTUVTUUTVTVUVWXWXVWXWWVWVXWþUVVTVTVUVUTUWXWWUVXWVWXUþ
VVTUUVVUTUXWVXWVWVWXþUVUTUTUVWVXUVXVWþVTVVUVXWVWVXþUUTUWUWWþVUWWÿVVUTUUSRTUTUTUUTSTþTUVUUTUUSTSTUTSUUUSUþTTTVVUTUTUUTTSSTTUTTTTþ
UTTUTUVVSUTTUUSTUUTSTTSUþTUVTTVTVVUSUTUTUUTUSUUUTTTþTVUUUTUUVTVUUUTUUTTTTUTTUUTTþUUTVTVUTUVTUVVUTTSUSTUTUSTTUUTþUVUUTUTUTUUTUTVVSTTUTTUTTUTTUTUTþTUTUUTUTUTUUVUWVWXVWVWWVWVXWþUTVUTUVTVTUUVXVWUVXWVUXUþ
TVUUTUUUVTVUVXWVWVWXþVTVUTVUTXVXUVWVUþUTUTTUVWVWVXþVUTTVUVWþTTVVÿVSVUUSTSTTTTTTUSUTþTUTUUVUTUURSUTSSUUSUþTTVTTSUUVUTRTSSTSUTTTTþ
UTTVUUSUUUUVUUTTSUTSTTSUþTUVTVTUTUVUUTSVUVUUSUUUTSTþTVUUUUTSSSSSVUUUTTVUVUTTUUSTþUUTVTVVSUSUTTSSVUSUSTVTVUVUUSTþUVUUTUTVSTUUUTTTSTUUTUTUUUTUVUTVþTUTUUTVTUUTUUUTSTTUTTVTUSSTUþUTVUTVTSUSTTUUUSTTUTSTTRþ
TVUUUTUTUUSTUUTSSSSTþVTVUUUUTUUUTTTUTþUTVTUTSTTSUTþVUTUTSSRþVSTTÿþQQQþRQQQQþQQQQRQQQþRSQQQQQRþQQQQQQQQRQQQQþQQQQQRQQQQQQQQQQQþQQQQQQRQQRQQQRQQQQþ
QQQQQRQQQQQQQQQSQQQþQQRQQRQQQRQQQQQQQQQQQQXþSRQQQQQQQQQQQQQQQQQQQVVþQQQRQQQQQRQRQRQQQQQQQVUXþQQQQQQQQQQQQQQQQQQQQQWVWXþQQQQQQQQQQQQQRQQQQQQRUUXVXþQQSQQQRQQQQRQQQQRQQQVWXVUWþQQRQRQQQRQQRRQRQQQQQXVUWVXVQQRQQRQQQQQQQQQQQQQQQQWVWVXWVXþQQQQRQQQQQRQQQQQQQQUVUXUVXþQQQQQQQQQQQQQQQQQWVWXVWþ
QQQQQQQQQQQQRQQWVUWUþQQRQQQQQQQVXVXþQRQQQQQQWWUþQRQQQQVUþRQQWÿþTUTþTUSTTTþTTUUTUTVUþTTSTTUSUSSTTþTTTUVTVUTTSSUUTþTRSTTTTTTTTUTTTTUTþTTSTTTSTRUSUTSTUUTTSTþ	SSUSTUUTTUTTTSTTSTUUUSSTþUSTUUSTSTTTTTTUSUTTSTTTTTþTTTUSTUTUURSUTSSUSSTTSTUTTþTTUTTSUUTTTRTSSTSSTSUSTTSUTþUTTUUUSUUUSTSUTTSTSTSSUTUTUTþTUVTUTUTUTUUTSSTTTSUSTUTSUTTTþTVUUUTTSSSSSTUUUTSTSTTUSTSTUTUþUUTVTVUSUSUTTSSSUTUTSUSTUUUTTSTþUVUUTUTUSTUUUTTTSTUUTUTUUUTUSUSTþTUTUUTUTUUTUUUTSTTUTTSTUSSTTþUTVUTUTSUSTTUUUSTTUTSTTSþ
TVUUTTUTUUSTUUTSSSSTþVTVTUUUTUUUTTTUTþUTUTUTSTTSUTþVTTUTSSTþUSTTÿþQRþQRRþQQQSTUþQQQSSTTþQRQQSSUUUþQQQQQRRSSTTSþQQQQRSRSTUTTþQQQQQRQRRTSUSTSþQQQQQQQQQSSSUTSTUTþQQRQQRRRSUTUSSTTþQRQQRQRQQQRSTSSTUUTUTþ	QQQQQQQQQRRRSSTSUUTUTTþQQQQRQQQQQRSSTUUTUTTUTUþQQQQQQQRRQRQRTRSTSSTUSTSTTþQQQQQQQQQQQQSRSSUUSUTUSSTUSþQQQQQQQQQQQQRQQRRSRSSTTUTTTUTTUþQQQQQQRQQQQRQSSRTTSUUUSSSUUþRQQQQQQQQQRRRSUTTTTTSUþ
QQQSQQQQQSRSTRTUUTTþRQQRQQQQRRSUUSTUþQQQRSQRRRRSTþQQQQSRSRþQQRSÿþQQQþRQQQQþQQQQRQQQþRSQQQQQRþQQQQQQQQRQQQQþQQQQQRQQQQQQQQQQQþQQQQQQRQQRQQQRQQQQþ
QQQQQRQQQQQQQQQSQQQþQQRQQRQQQRQQQQQQQQQQSQWXþSRQQQQQQQQQQQQQSQSQUVVVþQQQRQQQQQRQRQRSQTQQQUWWVUXþQQQQQQQQQQQSQSRQQQXVXVWVWXþQQQQQQQSQSQQQRQQUWUVWVUXVXþQQSQQQRSQQQRQRQQWVXWVWVWXVUWþQQSRSRQQRQQRRXVUXUVWXVUWVXVQQQRQRQQQRQRRXVWXVWVWWVWVXWVXþUVTUVTUUTVTVUVVXVWUVXWVUXUVXþUVVTVTVUVUTUWUVXWVWVWXVWþ
VVTUUVVUTUXVXUVWVUWUþUVUTUTUVXWVWVXVXþVTVVUVXUVWWUþUUTUVVVUþVUXWÿþTUTþTUSTTTþTTUUTUTVUþTTSTTUSUSSTTþTTTUVTVUTTSSUUTþTRSTTTTTTTTUTTTTUTþTTSTTTSTRUSUTSTUUTTSTþ	SSUSTUUTTUTTTSTTSTUUUSSTþVVUVUVTSTTTTTTUSUTTSTTTTTþTUVUUTUUSVRSUTSSUSSTTSTUTTþTTTVVUTUTUUVTVSTSSTSUSTTSUTþUTTUTUVVSUTTUUSVUVSTSSUTUTUTþTUVTTVTVVUSUTUTUUTUSUVUTSUTTTþTVUUUTUUVTVUUUTUUTTTTUVTUVTUTUþUUTVTVUTUVTUVVUTTSUSTUTUTTTUUVTþUVUUTUTUTUUTUTVVSTTUTTUTTUTTUTUVþTUTUUTUTUTUUVUWVWXVWVWWVWVXWþUTVUTUVTVTUUVXVWUVXWVUXUþ
TVUUTUUUVTVUVXWVWVWXþVTVUTVUTXVXUVWVUþUTUTTUVWVWVXþVUTTVUVWþTTVVÿþTUQQþTUSTQQQþTTUUTUQRQQQþTTSTTUSUQQQQQRþTTTUVTVUTTQQQRQQQQþ
TRSTTTTTTTTUQQQQQQQQQQQþTTSTTTSTRUSUTSQQRQQQRQQQQþSSUSTUUTTUTTTSTTRQQQQQQQQQSQQQUSTUUSTSTTTTTTUSRQQQQQQQQQQQQXTTTUSTUTUURSUTSSQQQQQQQQQQQQQVVTTUTTSUUTTTRTSSTQRQRQQQQQQQVUXUTTUUUSUUUSTSUTTQQQQQQQQQQWVWXTUVTUTUTUTUUTSSTQQQRQQQQQQRUUXVXTVUUUTTSSSSSTUUUQQQRQQQVWXVUWUUTVTVUSUSUTTSSSRRQRQQQQQXVUWVXVUVUUTUTUSTUUUTTTQQQQQQQWVWVXWVXþTUTUUTUTUUTUUUQQQQQQUVUXUVXþUTVUTUTSUSTTQQQQQWVWXVWþ
TVUUTTUTUUQQRQQWVUWUþVTVTUUUTQQVXVXþUTUTUTQQWWUþVTTUQQVUþUSQWÿUUUTUUSRTUTUTUUTRQQQQQQQQQQWXTUUTUTUUSTSTUTSUQQQQQQQQQUVVVTTTVUTTUTUUTTSSTQRQRQQRQQQUWWVUXUTTUTUUUSUTTUUSTQQRQQQXVXVWVWXTUVTTVTVUTSUTUTUQQRQQUWUVWVUXVXTVUUUTUUVTUTUUTURQQWVXWVWVWXVUWUUTVTVUTUVTUUUUTRRXVUXUVWXVUWVXVUVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXþTUTUUTUTUTUUVUVXVWUVXWVUXUVXþUTVUTUVTVTUUWUVXWVWVWXVWþ
TVUUTUUUVTXVXUVWVUWUþVTVUTVUTXWVWVXVXþUTUTTUXUVWWUþVUTTVVVUþTTXWÿþRSSRþRRSSQSRSþRRSSSQSSRRSRþSRQSRTSSQSRRRRRRþSSQRRSRRRSSTRSQRRQQRþ
RQSRRRQRRSRRRRRRRRSRQSSRþSSQSQSSRQRQRSSRSRRRRRSRRSSSTþTRRQSQSRRSSRRSRRSSRSSRRRSRSQSRRRUUTSRQSQRSRRSRSSRRRQRRQSRQSTSSWXTUUTRSSSRRQRRRRRQSRRRRRSRQQRUVVVTTTVUTRQRRRQRRRSRSSRSRQSQQUWWVUXUTTUTUUUTRSSQSSRRRQSSSQRXVXVWVWXTUVTTVTVUTRRRRRRSRSSRRUWUVWVUXVXTVUUUTUUVTUTSSSRQRSRWVXWVWVWXVUWUUTVTVUTUVTUUURRRRXVUXUVWXVUWVXVUVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXþTUTUUTUTUTUUVUVXVWUVXWVUXUVXþUTVUTUVTVTUUWUVXWVWVWXVWþ
TVUUTUUUVTXVXUVWVUWUþVTVUTVUTXWVWVXVXþUTUTTUXUVWWUþVUTTVVVUþTTXWÿ þRSSRþRRSSQSRSþRRSSSQSSRRSRþSRQSRTSSQSRRRRRRþSSQRRSRRRSSTRSQRRQQRþ
RQSRRRQRRSRRRRRRRRSRQSSRþSSQSQSSRQRQRSSRSRRRRRSRRSSSTþTRRQSQSRRSSRRSRRSSRSSRRRSRSQSRRRQQTSRQSQRSRRSRSSRRRQRRQSRQSTSSRQUUQQRSSSRRQRRRRRQSRRRRRSRQQRQQWXTUUTQQRQRRRQRRRSRSSRSRQSQQQRUVVVTTTVUTQQTRSSQSSRRRQSSSQRRQUWWVUXUTTUTUUUQQRRRRRRSRSSRRQQXVXVWVWXVUVTTVTVUTQQSSSRQRSRQQUWUVWVUXVXTVUUUTUUVTUTQQRRRRQQWVXWVWVWXVUWUUTVTVUTUVTUUUQQQQXVUXUVWXVUWVXVTVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXVUTUTUUTUTUTUUVUVXVWUVXWVUXUVXWXTUUTUTVUTUVTVTUUWUVXWVWVWXVWUVVVUVTVUTTVUUTUUUVTXVXUVWVUWUUWWVUXVUTUTUUUVTVUTVUTXWVWVXVXXVXVWVWXTUVTTVTVUTUTUTTUXUVWWUUWUVWVUXVXTVUUUTUUVTUTVUTTVVVUWVXWVWVWXVUWUUTVTVUTUVTUUUTTXWXVUXUVWXVUWVXVTVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXVUTUTUUTUTUTUUVUVXVWUVXWVUXUVXWXTUUTUTVUTUVTVTUUWUVXWVWVWXVWUVVVTUTVUTTVUUTUUUVTXVXUVWVUWUUWWVUXUTTUTUUUVTVUTVUTXWVWVXVXXVXVWVWXTUVTTVTVUTUTUTTUXUVWWUUWUVWVUXVXUVUUUTUUVTUTVUTTVVVUWVXWVWVWXVUWVUTVTVUTUVTUUUTTXWXVUXUVWXVUWVXVTVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXþTUTUUTUTUTUUVUVXVWUVXWVUXUVXþUTVUTUVTVTUUWUVXWVWVWXVWþ
TVUUTUUUVTXVXUVWVUWUþVTVUTVUTXWVWVXVXþUTUTTUXUVWWUþVUTTVVVUþTTXWÿ	þRSSRþRRSSQSRSþRRSSSQSSRRSRþSRQSRTSSQSRRRRRRþSSQRRSRRRSSTRSQRRQQRþ
RQSRRRQRRSRRRRRRRRSRQSSRþSSQSQSSRQRQRSSRSRRRRRSRRSSSTþTRRQSQSRRSSRRSRRSSRSSRRRSRSQSRRRUUTSRQSQRSRRSRSSRRRQRRQSRQSTSSWXTUUTRSSSRRQRRRRRQSRRRRRSRQQRUVVVTTTVUTRQRRRQRRRSRSSRSRQSQQUWWVUXUTTUTUUUTRSSQSSRRRQSSSQRXVXVWVWXTUVTTVTVUTRRRRRRSRSSRRUWUVWVUXVXTVUUUTUUVTUTSSSRQRSRWVXWVWVWXVUWUUTVTVUTUVTUUURRRRXVUXUVWXVUWVXVTVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXVUTUTUUTUTUTUUVUVXVWUVXWVUXUVXWXUUUTUTVUTUVTVTUUWUVXWVWVWXVWUVVVTUTVUTTVUUTUUUVTXVXUVWVUWUUWWVUXVTTUTUUUVTVUTVUTXWVWVXVXXVXVWVWXTUVTTVTVUTUTUTTUXUVWWUUWUVWVUXVXUVUUUTUUVTUTVUTTVVVUWVXWVWVWXVUWTUTVTVUTUVTUUUTTXWXVUXUVWXVUWVXVTVUUTUTUTUUTUTUUXVWXVWVWWVWVXWVXþTUTUUTUTUTUUVUVXVWUVXWVUXUVXþUTVUTUVTVTUUWUVXWVWVWXVWþ
TVUUTUUUVTXVXUVWVUWUþVTVUTVUTXWVWVXVXþUTUTTUXUVWWUþVUTTVVVUþTTXWÿ