þ[GVGþG¦Z:9¦GGþ¥ZGZZ¦:—G:JGþVJ¦§:[§—G¦:¦G:¥:þG§9F—Z—UFWG—[—::§¥Z9þ
HGH¥:¦GVVVVVUUTG¥H§¥¥:¥Gþ¦I¦GJ[:—VVVVUUUUUUTF¦§W¦¥GGGþ¥G¦J—::¥¦GVVUUU9GUUUUUTVG—W:VGF:þ—:G—:¦—GUUUUUUVUGGUUUFFG§:::þ¦GW—G:UUUUUUUFHGUUU¦GGZ¥þ
¦W——ZUUUUUUUVVU¥:—H:þFG¦G:—UUUUUG¥¥§Gþ[G:GG¦GJ[H¥¥þ¦GGZ:¦¦¥þ¥¥¥§ÿþ]˜˜–þ—^_^˜]^–þ—¦^___^^^^^_þ_____^_^]^^]^__^þ_^^__^^^^^]]]]^^_^^_þ
–™_^^^^^]]_]^\_^]^^__]˜˜þ˜™^___^]]]]^][]¦\]^]^^^^_™˜˜þ¦™™^___^^^]\]^]_]]™^]]]^^_™™˜™˜Gþ˜™^___^]]\[]]™^^\[\\]^™—§™™™þ–˜__^^]]\]\]]\]_][^^^^^¨þ
˜™^^^]]\—]^]\[\]]^]^þ—^^^][^^\\\\]]^]þ_^^]\¥˜˜˜˜™™þ^^¨˜™™——þ˜]™™ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦—GG¥HGFFG§;;;þ¦GX—G;]¦GG¦FHG]JG¦GG\¥þ
¦X——\—¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;§—G¦;¦G;¥;þG§9F—\XG—]—;;§¥\9þ
HGH¥;¦G\
G¥H§¥¥;¥Gþ¦I¦GJ];—Z
§F¦§X¦¥GGGþ¥G¦J—;;¥¦	


G—WG—X;WGF;þ—;G—;¦—¥HGFFG§;;;þ¦GX—G;HG]JG¦GG\¥þ
¦X——\—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦
]§—G¦;¦G;¥;þG§9F—¦FX
—;;§¥\9þ
	GH¥;
\W
¥H§¥¥;¥Gþ¦IJ]
H§F¦	X¦¥GGGþ¥G¦J—;;¥]J9G¦F—¥G——X;WGF;þ—;G—;¦—G¦G—
G—G
HGFFG§;;;þ¦GX—G;]¦¦FHJG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;	
;GH§G¥¥§Gþ]G;¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþþþ	þþ
þ
þþþþ
þþ]\\þþG¦\;]
G]þ¥\G\\¦;]GþWJ¦§;]§—G¦^^;¥;þG§9F—\—¦FXG—\;;§¥\9þ
HGH¥;¦G\G\WGX
[¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J
F—¥G—WG—X;WGF;þ—;G—;¦—G¦G
HGFFG§;;;þ¦GX—G;]G—¦FHG¦GG\¥þ
¦X——\—G¦¦GJF¥¥;—H;þFG¦G;—;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþþþ]þ]þþ^þþ^þþþþ
þ]þ^]þþ^^þþ^_þþ
þþþþþ
þþ_þ_GþG¦^¦GGþ¥\G\^—G;JGþWJ¦§;]_¦;¦G;¥;þG§9F—\—¦—;;§¥\9þ
HGH¥;¦G\G^]¥H§¥¥;¥Gþ¦I¦GJ];—GHW—_¦§X¦¥GGGþ¥G¦J—;;¥¦G
]J9G¦F¥G—X;WGF;þ—;G—;¦—¦G—¦¦;G—GGHGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ—þX—þFWGGþWþG¦WGþX—Wþ;þIX9;¦þ¦þ—þ	XþJþ¦þWGX¦—F¦þ—þFþWGXþ¦þXFþ—þ]GWG—GG—þGþG¦FþWGþ—WXXþG¦\;9¦GGHGþGþXWGXþ¦þ9G¦XWGX¥\G\\¦;—G;JGþ;WGXHþFþ—þ—FWFXWJ¦§;]§—G¦;¦G;¥;þWG¦þG¦þGþFG—G§9F—\—¦FXG—]—;;§¥\9;—¦¦H—þGFGHGH¥;¦G\G\WGXG\G¥H§¥¥;¥G——JGþF¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGG—G¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþGGWFþGW¦GþWþ	—þ¦þ¦;9XIþ;þW—XþFþ—þ¦F—¦XGWþ¦þJþXþF¦GþGþ—GG—GWG]þ—þFXþ¦þXGWþXGWXþGþGHGG¦9;\¦GþXXW—þGWþFþHXGW;þGJ;G—;¦\\G\¥XGWX¦G9þ¦þ¦Gþ¦GWþ;¥;G¦;¦G—§];§¦JWXFWF—þ—þ—H¦¦—;9\¥§;;—]—GXF¦—\—F9§G—GFþGþGJ——G¥;¥¥§H¥G\GXGW\G\G¦;¥HGHGFGþG—GGG¥¦X§¦F§¦¦G—WH¥G—G—;]JG¦I¦Fþ;FGW;X—GW—G¥—F¦G9J]¦F;G¦¥;;—J¦G¥þ;;;§GFFGH¥GG—G;¦¦—G¦G—¦;—G;—þ¥\GG¦GJ]GHF¦G¦—G¦];G—XG¦þ
;H—;¥¥FJG—;¦¦G—\——X¦þG§¥¥G§HG;——;G¦GFþ¥¥H]JG¦GG;G]þ¥¦¦;\GG¦þ§¥¥¥ÿþ¦þ—þ
¦þ¦þ—XþXþFFþ¦þ—þF¦XGWþGþ¦¦Gþ—þ¦þG¦Fþ¦—X—W¦þWþ——Fþ—¦Xþ—¦G—GX¦þ—FGFF¦þ¦¦—þ¦GG¦¦¦GW—XGW;F;GW—GG¦GG—þ——¦þ¦XG¦——¦¦FFH¦G¦GFW¦GGI—IHGþG¦—þ—G;¦FG——¦¦J—G¦H¦9—G¦¦¦XJGXGXGW¦þGGX—GGGG—¦¦G;—J—¦¦;——XF—¦;;X—W¦þ¦XGGW;GGG——¦GG—F——FG¦¦GF¦¦¦GFþ—¦—JWG—;X;WGG—;GGGGGGXF—HG———¦GþG—GX¦;FX¦W¦GGGG;F¦XGXGWFJIGGG—I¦GGGþ—;G——9—F;¦X9G—G;¦WHG¦JGG—¦J—;X;]GGIXG¦¦GGXGWH¦W¦—9XH—¦;;X—GGXGþGGXGG——HWGWGJ—¦—G;GJ¦¦F;¦GXGþJW;GGJF—¦HGG—¦G¦G¦——X——Gþ
X¦GG¦F—JXG¦—;—;—GXGWþ;G—GG¦¦;—G;G¦¦GFþXIG——GGGXG——þ;GGGG¦G;þG;;—ÿþ	¦þXþX—þ¦þFþ¦þ
—þGþWGX¦FþFHþ—þ¦þFFþWþ¦W—X—¦þHGþ¦Gþ¦þ—þG¦¦þ—¦¦þ¦FFGF—þ¦XG—G¦—þFX¦—þF——þ¦——þ—GG¦GG—WG;F;WGX—WG¦¦¦GG¦þ—¦GþGHI—IGG¦WFG¦G¦HFF¦¦——¦GX¦þ¦WGXGXGJX¦¦¦G—9¦H¦G—J¦¦——GF¦;G—þ¦W—X;;¦—FX——;¦¦—J—;G¦¦—GGGG—XGG¦—þFG¦¦¦FG¦¦GF——F—GG¦——GGG;WGGX¦—GþG¦———GH—FXGGGGGG;—GGW;X;—GWJ—GG¦I—GGGIJFWGXGX¦F;GGGG¦W¦XF;¦XGX;—J¦—GGJ¦GHW¦;G—G9X¦;F—9——G;—þGGXGG—X;;¦—HX9—¦W¦HWGXGG¦¦GXIGG];þGXG¦;F¦¦JG;G—¦—JGWGWH——GGXGGþG——X——¦G¦G¦—GGH¦—FJGG;WJþ
WGXG—;—;—¦GXJ—F¦GG¦XþFG¦¦G;G—;¦¦GG—G;þ——GXGGG——GIXþ;G¦GGGG;þ—;;Gÿþ—þX—þFWGGþWþG¦WGþX—Wþ;þIX9;¦þ¦þ—þ	XþJþ¦þWGX¦—F¦þ—þFþWGXþ¦þXFþ—þ]GWG—GG—þGþG¦FþWGþ—WXXþG¦\;9¦GGHGþGþXWGXþ¦þ9G¦XWGX¥\G\\¦;—G;JGþ;WGXHþFþ—þ—FWFXWJ¦§;]§—G¦;¦G;¥;þWG¦þG¦þGþFG—G§9F—\—¦FXG—]—;;§¥\9;—¦¦H—þGFGHGH¥;¦G\G\WGXG\G¥H§¥¥;¥G——JGþF¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGG—G¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþGGWFþGW¦GþWþ	—þ¦þ¦;9XIþ;þW—XþFþ—þ¦F—¦XGWþ¦þJþXþF¦GþGþ—GG—GWG]þ—þFXþ¦þXGWþXGWXþGþGHGG¦9;\¦GþXXW—þGWþFþHXGW;þGJ;G—;¦\\G\¥XGWX¦G9þ¦þ¦Gþ¦GWþ;¥;G¦;¦G—§];§¦JWXFWF—þ—þ—H¦¦—;9\¥§;;—]—GXF¦—\—F9§G—GFþGþGJ——G¥;¥¥§H¥G\GXGW\G\G¦;¥HGHGFGþG—GGG¥¦X§¦F§¦¦G—WH¥G—G—;]JG¦I¦Fþ;FGW;X—GW—G¥—F¦G9J]¦F;G¦¥;;—J¦G¥þ;;;§GFFGH¥GG—G;¦¦—G¦G—¦;—G;—þ¥\GG¦GJ]GHF¦G¦—G¦];G—XG¦þ
;H—;¥¥FJG—;¦¦G—\——X¦þG§¥¥G§HG;——;G¦GFþ¥¥H]JG¦GG;G]þ¥¦¦;\GG¦þ§¥¥¥ÿþ¦þ—þ
¦þ¦þ—XþXþFFþ¦þ—þF¦XGWþGþ¦¦Gþ—þ¦þG¦Fþ¦—X—W¦þWþ——Fþ—¦Xþ—¦G—GX¦þ—FGFF¦þ¦¦—þ¦GG¦¦¦GW—XGW;F;GW—GG¦GG—þ——¦þ¦XG¦——¦¦FFH¦G¦GFW¦GGI—IHGþG¦—þ—G;¦FG——¦¦J—G¦H¦9—G¦¦¦XJGXGXGW¦þGGX—GGGG—¦¦G;—J—¦¦;——XF—¦;;X—W¦þ¦XGGW;GGG——¦GG—F——FG¦¦GF¦¦¦GFþ—¦—JWG—;X;WGG—;GGGGGGXF—HG———¦GþG—GX¦;FX¦W¦GGGG;F¦XGXGWFJIGGG—I¦GGGþ—;G——9—F;¦X9G—G;¦WHG¦JGG—¦J—;X;]GGIXG¦¦GGXGWH¦W¦—9XH—¦;;X—GGXGþGGXGG——HWGWGJ—¦—G;GJ¦¦F;¦GXGþJW;GGJF—¦HGG—¦G¦G¦——X——Gþ
X¦GG¦F—JXG¦—;—;—GXGWþ;G—GG¦¦;—G;G¦¦GFþXIG——GGGXG——þ;GGGG¦G;þG;;—ÿþ	¦þXþX—þ¦þFþ¦þ
—þGþWGX¦FþFHþ—þ¦þFFþWþ¦W—X—¦þHGþ¦Gþ¦þ—þG¦¦þ—¦¦þ¦FFGF—þ¦XG—G¦—þFX¦—þF——þ¦——þ—GG¦GG—WG;F;WGX—WG¦¦¦GG¦þ—¦GþGHI—IGG¦WFG¦G¦HFF¦¦——¦GX¦þ¦WGXGXGJX¦¦¦G—9¦H¦G—J¦¦——GF¦;G—þ¦W—X;;¦—FX——;¦¦—J—;G¦¦—GGGG—XGG¦—þFG¦¦¦FG¦¦GF——F—GG¦——GGG;WGGX¦—GþG¦———GH—FXGGGGGG;—GGW;X;—GWJ—GG¦I—GGGIJFWGXGX¦F;GGGG¦W¦XF;¦XGX;—J¦—GGJ¦GHW¦;G—G9X¦;F—9——G;—þGGXGG—X;;¦—HX9—¦W¦HWGXGG¦¦GXIGG];þGXG¦;F¦¦JG;G—¦—JGWGWH——GGXGGþG——X——¦G¦G¦—GGH¦—FJGG;WJþ
WGXG—;—;—¦GXJ—F¦GG¦XþFG¦¦G;G—;¦¦GG—G;þ——GXGGG——GIXþ;G¦GGGG;þ—;;GÿþGFW–þG–H–9—G–þ–US––;——XþGQ	
UUSR––GFþX;WU		WUSRSHG——þ
FX–QS
	WYWUIGGG—þ—;G——S	
	W

TGG—–J—þ¥]GGIXG–T	
	

V;;X—GGXGþGGXGG——HWU	

	XSTV		ZF;–GXGþJW;GGJF—–HGG—T	V——X——Gþ
X–GG–F—JXG–	WGXGWþ;G—GG––;—GU
X–GFþXIG——GGGXG——þ;GGGG–G;þG;;—ÿþGFW–þG–HSUTU–þ–G;—ã—XþG——–GT

U–GFþX;WGG—R	

UHG——þ
FX–W–GGT	
	WUIGGG—þ—;G——9—F;Rã
TUJGG—–J—þ;]GGIXG––GGSSU	

VW–;;X—GGXGþGGXGG——HWGU		—G		ZYZF;–GXGþJW;GGJF—–HGG—–T–——X——Gþ
X–GG–F—JXG–	WGXGWþ;G—GG––;—G

X–GFþXIG——GGGXG——þ;GGGG–G;þG;;—ÿþTSSþ		
US–þS		

—XþãUU		
	äSGFþTUVä		


UUTS——þ
FWXWXXY	
TS	
VUVGG—þ—;GXWXYZ[ZYSãTUVY	
XXWY[—–J—þ;]GGIXG––GGXSTUUXXVZYZYZ[\X—GGXGþGGXGG——HWGäUäXZZZ;GJ––F;–GXGþJW;GGJF—–ZY[\\\–Gã]—X——Gþ
X–GG–F—JXG–—;—çé]XGWþ;G—GG––;—G;G––GFþXIG——GGGXG——þ;GGGG–G;þG;;—ÿþGFW–þG–H–9—G–þ–G;—J—––;——XþG——–GG—F——FG––GFþX;WGG—;GSGGSQG——þ
FX–W–GGGGãXVXUGG—þ—;G——9—F;–SS
SWHVXWXG—–J—þ;]GGIXG––GGXWYZTRXH—–;;X—GGXGþGGXGG——HWGWGVZZWSUVJ––F;–GXGþJW;GGJF—–HGG—ZYWX–——X——Gþ
X–GG–F—JXG–—;—;—GXGWþ;G—GG––;—G;G––GFþXIG——GGGXG——þ;GGGG–G;þG;;—ÿþ£¥þ£þ¥Fþ£þ£¥þ¥¦F£þ£¥G—þ¥¦¥þF£G¥þ¦¦9þ¥—¦þG¥9FF——¦§þ£þ£þ¦£—¥9F9GGG¦§¥þ£þ¥þ—VG££¥WW9¥¦¦¥þW¥þ¥¤F9FFH£¥¦WG\]^]§þWþWG¦GFGG¦GG8¥F—W¤\§\\\þWG—W£þ£GV—HG99V9££FGF¦¥\\§_¦þVFH¥¦¥¦8F—9—GV9¥¥G¥G§\§§^^^þ8G¦¦—F£9GWGGV—9FF9¦\]]\^^_]þ9I——FG¥G£G9£8£¥GGG¥§\]]___þWþ¦£FJFFGVFV¥£££9¥F999¥\§]^___WGV—¤GFGG£¥¦¦F¥¥¥HFGH—¥_^¦\]^__§VVF¤W¦9¦¥W—¦GFWFVG9H¦^_\\\]^^þ¦—WGV9—FGV—9G£GG9H\^^]^^]^__þ—VF¦GGVHG—9¥9¥¤¤]]]§\§]]þ
¦V¥98WHVGFF¦¥§^]]\]]þ¦G9GVH9GG¦¥_^^^^þ998G¦99¦^^^þ99—¥¥þG¥_ÿþ£þWþ£¥þ¥þ¥þ¥þ¥¥£¦EþEF£þEþEEþE¦¥—FþF8¥þFþFF£þ¦—EF¦£8¦§þ	Wþ££8WþW8U£¥þWFFG—¤¦§¥þ	GUþ¥¥WGUþGF¥E¥GG8§§\¦¦¥þ¥þ££þEEFU¤¦G8EF¦G¥¤]§]^]§þ¦þEþ¥¥þFFG7¦—F¥¦8¤§^]\\§\\\þ—þWF¥¦WEE£¦8¦8—G8U¥¥_]^]§\\§_¦þGWGUE—GFF¥—E§¦WG¥¤§]]¦§^\§§^^^þ£G¥WEFFU¦8EGF¥W¦§§\\]§§]]]\^^_]þ££WGU8G7—¦F¥¥¦¤¥]]]\^]]§\]]___þ¥¥WU8GE¥¥£¦¤¤¦¥^^^^___^\§]^___£EE¥¤¤¤£¥¤¥¥¥¥¤¥\^_^_^^_^¦\]^__¥¤¥¦¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]^^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþWþIþWGUþJGþ¢þUþKIþ£þ¢þ7¢YLGJþGþW£þEþ£F8£LMIKJþIþGþ¢GUWFþE8¥E_J?GþG?Iþ£UF¥8¢¥G£FIYýIGIýJþþ£¢þ£7EE78£££¦G¥8Y_JJIJKLIYþ¥£EE8FF8¥¥EE¥¦¢GGKJLIJL_GJY_þ¦¥FFF88F¢¦FF¥¥§¦§^¦]L_IKKGþGþ—¦888G88¥¥£¦¤¤¦¥^^^^^___I_IIIþFG¦£¤¤¤£¥¤¥¥¥¥¤¥\^_^_^^_¦]^^GJI¥¤¥¦¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]]^_^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþJþGþKþGþJJIþ?þI_þGþL?KLJþýIJþJGþIIþMýL_LLKJKIJIþYJþGþ]]MI__?LGGKJJGKþJIþIþGþ¥¥_\J_ýJII?LLILLKJþJþIIIþ¤¥¥¦^^_KJJý_JM_?LYGGþJYJþGþ£]\§¥¥_§LYKIYLJIý_IIIþLJKþGþ¤\]¥¤¥¤¦^^?YJ_JJKKJJJG_KIIIþ£¥¤¤¤¥¥§¤¤^\YJKL?GLLLGþIYJJþGþ¤¥¦¤¦¤££¤¤¥¤^^?_ýI___IþJYYLLLJIþ¥§]¥¥¤£¢¤¢¢¢¥¤]^^JG^J¦KKY__GKJþ¤¥¥£¤££¤£¢£¤¤¥¥§]^¦]\L_?_JJKIGLþ¥¥¥¥¦¤¤£¤¢¥¤¤¤¦¥^^^^^____LLLJI_þ¤£¤¤¦¢¤¥¥¤¥¥¥¥¤¥\^_^_^^_¦]^^LJýþ¤¦¥¥¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]]^_^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþHþKHIþIFFþ[þGKFJIþJ[GþIFþFþHGKJI[IXGFGþJþIGþ]]HFLJXXJHGIþF[J[þ¥¥_G?LXKKJFFþGF[IXG[þFþ
¤¥¥¥H?IKGKGGGHGLXG[IXIþFþ£]\§JKJLHFHHFJFKKFIXFJþGþ¤\]¥]HLJJGJJGFG[KGJKGLþHþGþF[þ£¥¤¤¤^?KKHKKFGX_XHLKþ?XFJHþGIXþ¤¥¦¤¦¤^LG[HHGHG¦KJ?L_JKGKJþHXFþ¥§]¥¥¤£][FXJHJF^FK^?^KKHKKþJKFþ¤¥¥£¤££¤JGKKJKG§GG¦K\KFJ¦KþKKGþ¥¥¥¥¦¤¤£§HFJKKH¥HH^K^LGK^¦FGþHFþ¤£¤¤¦¢¤¥¥^GKGLJJJJ_GH[[K¦]GI^JGþ¤¦¥¥¤¤¤¤¥¥¦?HJKLKF\IJ[XFGFHJFKH^þ§¦¥§¥§\\¥§JKJ?IGJ[KIXGHGJKGJþ§§§¦^^]¦K¥LGJHKIJXHHJHKLþ
^]]\\¤§§?HFJ§XLKJJKJþ^^¥¥¥¥§JGK¦K?KKKþ]§¥\]KHL§KI\þ]]\]J?§Kþ^^KIÿþIþ¥þGJþ¦§IFþFþWF¥FGFþFþWG¥¦[FGþGFþ¥þ\V¦WIGH^HGþ¦¦\¥F¦FHJ§JHþFFV¦G—FJKGKJKþ¥þ¥¥G¥F—FGKJXKKKIþFþW¥V¦9¦GFGH[LIJFIJþGþ—¦F¦FF9GIJI?JIGXLþHþ¦¥FG—GGFHFKXJLJHG?þJFþ
¥—¦G9F¥9G¥GJKK?LJIKFKGþ	—¦FF9¦G¦G9¦9LK?]?KJLGGHþ[þ¥þFFGGH¥IF9WFW?HL¥JKK]HHJ[IXþ¦¥GGI9F\9GWGWGX[?]KLLFJJK\XþFþ—þF¦H9¥¥G¥¥9GV9V[IX[?H]IKK]FKþFþFþGF¥G¤¥9¦¥¦98W8JX[IXJ]J?K§GKþGFGþ9G¦H¥¦¥¥¦F¦9G9KKG[^F^L^KFH¥HHGH¥¥9¥¥WF¥¦F¦F¥VFLK[IXG[?IHGJ^JJH§¥¦¥¤WGV\¥G—G¦8GF^JX^HIXJJHKFKKJþF¦¥¦V¦¥¦9F9¥99G§IK]JX¥LKJFG¥þ¥¥8F¦FG¥¥¦¦¥HFJKIKKF?^KGþ
9G¥GV¦§F—¥JGLKJIFGFFþ¥98F¥GF¦KH?[LJGHþ9GV9GWGJ[IXKþ¥FWGHK§XþVVJJÿþ—þ¥þ¥FþWþG¦þ§\GWG¥9þ9F—\¦I§V¦GWGþ¥WGF——¤¥8F¥G9G¦þ¦G9GFFV¦9G¦V¦9—WGþF—¦HWG—F\9F¥¥¥F8VFþ¥þGFFW¥I¥¥¥9G¦W¦G—8G¤9¦þ	¦¥9GG¥¦9¦¥¦H9¦GFIF99V¤¤þ¥þ—þF¦¥H¥§F¥F¦F¤W—¥GWWGV¦¦¥þ¦þFþWGF¦F¦§G¦GFG¥¦¥¦9¦HV9¦§¥þFFGWGVGFGF¥9F9G9¦F¦FW—88¥¦¦¥þGGHG—§9WIG¥FG¤9G¦GFGGV99]^]§þ99—WFVWGV9¥G9§¥V—¦G9VGW\§\\\þ¦GF¥G—¤V¥W¤9¦¤¦8F—9I8H¥\\§_¦þFWG¦H¥¤8WGV¥W¦F9GFFI9§\§§^^^þ¥WGHF9¦¥9FV¥WG—G¥—GGF\]]\^^_]þG¦¥¥IG¥F¤9G8¦¦VF9¥FI9G§\]]___þ9F¦¦¥¥¦G§¦H9¦F8GH¥G¤G¥\§]^___þ¥¥GFF¦¦F9¥—\¦¥G9H¥¥H¦¥_^¦\]^__I¥¦9—G¥FG¥¤F¤F¥9¦¦W¦H¦^_\\\]^^þFV—9¦G¥¦¦G§W¦G¥FGF\^^]^^]^__þF9F9¦F—I¥G—H¦G¥G]]]§\§]]þ
GWF—F¦¦VF—F9¦§^]]\]]þVFG—F8GFG¦¥_^^^^þI¥G9IG9¦^^^þ99¥H¥þ¦¥_ÿþGHþGþLLIJHHJ[þLG[?IKJJ[IXþK??HKXJ?KK[XþFþG^JJJKLKG[IXþHþG§H[LKFK?LIKXKþHJ§H§JI?GGKJFJIK§þ[IþXþFJK[J\FX§FHIKGKJKF]þXþ\]GK[IKIGK\GJJJHLLIX]FþKþ¥¦H]IX¥JHK^HKLKJG?XH]G\Kþ¥¥¦¦JX¥LJG[JJ?FKHLKJ]HIJJþ¤¥¥¥LKF?K[FKKGGJJ?KKFJJKLþKþFþ£]\§?GG[[IGGLHHLKHF§GKLI?þKþGþ¤\]¥]HH]XXHIKFJ?IJG]HF?J¥FGIHJþ£¥¤¤¤^J]KKJX¥GKIJKH¥JGKKFGHJJLþ¤¥¦¤¦¤^¦KKKIFHLXLXJ[KH§LGHJLK?þG¥§]¥¥¤£]§¥KJGJFK?KK]GJ]\HJK[JIXH¤¥¥£¤££¤]]KLHKGKKK\]IK]\JK[IXXGJ¥¥¥¥¦¤¤£§§??J\H§LK]FJ\^]KGGXLKHK¤£¤¤¦¢¤¥¥^\¥F\JIKF¥GK][[[FHKFKJJ¤¦¥¥¤¤¤¤¥¥¦^GFKJLG\HL[IXIGJKGKKLþ§¦¥§¥§\\¥§HG¥LIHFI]FXGXHK?HIþ§§§¦^^]¦JH]FJJGJIFKFKJKFþ
^]]\\¤§JFGG[HLJGKFKKþ^^¥¥¥¥GH[IJILH[Gþ]§¥\]§JXKJ?Jþ]]\]KKXLþ^^LKÿþ¦þ—þ
¦þ¦þ—XþXþFFþ¦þ—þF¦XGWþGþ¦¦Gþ—þ¦þG¦þ¦—X—W¦þWþ——Fþ—¦Xþ—¦G—þX¦þ—FGFF¦þ¦¦—þ¦GG¦¦¦GW—XGW;F;GW—GG¦GG—þ——¦þ¦XG¦——¦¦FFH¦G¦GFW¦GGI—IHGþG¦—þ—G;¦FG——¦¦J—G¦H¦9—G¦¦¦XJGXGXGW¦þGGX—GGGG—¦¦G;—J—¦¦;——XF—¦;;X—W¦þ¦XGGW;GGG——¦GG—F——FG¦¦GF¦¦¦GFþ—¦—JWG—;X;WGG—;GGGGGGXF—HG———¦GþG—GX¦;FX¦W¦GGGG;F¦XGXGWFJIGGG—I¦GGG]—;G——9—F;¦X9G—G;¦WHG¦JGG—¦J—;X;]GGIXG¦¦GGXGWH¦W¦—9XH—¦;;X—GGXG¥¤GGXGG——HWGWGJ—¦—G;GJ¦¦F;¦GXG¦¥¥¥¦¥JW;GGJF—¦HGG—¦G¦G¦——X——G§\§¥¤¥¥¦¤¥X¦GG¦F—JXG¦—;—;—GXGW]¥\¦¦¥£]\§¥¥¤¤;G—GG¦¦;—G;G¦¦GF__]§]^]§¤\]¥¤¥¤¦¥¥XIG——GGGXG——_]^]\\§\\\£¥¤¤¤¥¥§¤¤¥¦;GGGG¦G;§\_]^]§\\§_¦¤¥¦¤¦¤££¤¤¥¤£¤G;;—\§§]]¦§^\§§^^^¥§]¥¥¤£¢¤¢¢¢¥¤¤¥¥]§\\]§§]]]\^^_]¤¥¥£¤££¤£¢£¤¤¥¥§¥]]]\^]]§\]]___¥¥¥¥¦¤¤£¤¢¥¤¤¤¦¥^^^^___^\§]^___¤£¤¤¦¢¤¥¥¤¥¥¥¥¤¥\^_^_^^_^¦\]^__¤¦¥¥¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]^^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþ—þ¥þ¥FþWþG¦þ§\GWG¥9þ9F—\¦I§V¦GWGþ¥WGF——¤¥8F¥G9G¦þ¦G9GFFV¦9G¦V¦£—WGþF—¦HWG—F\9F¥£¥F¥VF¥þ¥þGFF¥¥I¥¥¥9G¦¥¥£¦EGEF£þ	¦¥9GGE¦9¦¥EE9¦E¦¥—F9F8¥þ¥þ—þF¦¥H¥FF¥F¦FF£—¦—EF¦£8¦§þ¦þFþWWF¦££8W¦W8U£¥¥WFFG—¤¦§¥þFFGWGGUF¥¥WGU9GF¥E¥GG8§§\¦¦¥þ¥GHG—££WEEFU¤¦G8EF¦G¥¤]§]^]§þ¦þE9—WF¥¥GFFG7¦—F¥¦8¤§^]\\§\\\þ—þWF¥¦WEE£¦8¦8—G8U¥¥_]^]§\\§_¦þGWGUE—GFF¥—E§¦WG¥¤§]]¦§^\§§^^^þ£G¥WEFFU¦8EGF¥W¦§§\\]§§]]]\^^_]¥££WGU8G7—¦F¥¥¦¤¥]]]\^]]§\]]___¦¥¥WU8GE¥¥£¦¤¤¦¥^^^^___^\§]^___£EE¥¤¤¤£¥¤¥¥¥¥¤¥\^_^_^^_^¦\]^__¥¤¥¦¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]^^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþGHþGþLLIJHHJ[þLG[?IKJJ[IXþK??HKXJ?KK[XþJþG^JJJKLKG[IXþGþK§H[GKFK?LIKXKþJJI§?§JII_GGJFJIK§þ[IþL?KLJ[ýIJXJGHIIGKJKF]þXþMýL_LLKJKIJIJYJHLLIXGFþKþ]]MI__?LGGKJJGKJJIXHIGGþ¥¥_\J_ýJII?LLILLKJKJJHIIIþ¤¥¥¦^^_KJJý_JM_?LYGGJJYJþKGFþ£]\§¥¥_§LYKIYLJIý_IIIKLJKþKGGþ¤\]¥¤¥¤¦^^?YJ_JJKKJJJG_KIIIHJþ£¥¤¤¤¥¥§¤¤^\YJKL?GLLLGKIYJJJLGþ¤¥¦¤¦¤££¤¤¥¤^^?_ýI___I§JYYLLLJIG¥§]¥¥¤£¢¤¢¢¢¥¤]^^JG^J¦KKY__GKJH¤¥¥£¤££¤£¢£¤¤¥¥§]^¦]\L_?_JJKIGLJ¥¥¥¥¦¤¤£¤¢¥¤¤¤¦¥^^^^^____LLLJI_K¤£¤¤¦¢¤¥¥¤¥¥¥¥¤¥\^_^_^^_¦]^^LJýJ¤¦¥¥¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]]^_^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþGHþ—þLLIJ¥FþWþLG[?IK\GWG¥9þK??HKXJ?¦I§V¦GWGþFþG^JJJKLK—¤¥8F¥G9G¦þ
HþG§H[LKFK?LFV¦9G¦V¦9—WGþHJ§H§JI?GGKJFG—F\9F¥¥¥F8VFþXþFJK[J\FX§FHIKGI¥¥¥9G¦W¦G—8G¤9¦\]GK[IKIGK\GJJJH9¦¥¦H9¦GFIF99V¤¤¥¦H]IX¥JHK^HKLKJ¥F¦F¤W—¥GWWGV¦¦¥¥¥¦¦JX¥LJG[JJ?FK¦GFG¥¦¥¦9¦HV9¦§¥¤¥¥¥LKF?K[FKKGGJF9G9¦F¦FW—88¥¦¦¥£]\§?GG[[IGGLHHLG¤9G¦GFGGV99]^]§¤\]¥]HH]XXHIKFJ?9§¥V—¦G9VGW\§\\\£¥¤¤¤^J]KKJX¥GKI¦¤¦8F—9I8H¥\\§_¦¤¥¦¤¦¤^¦KKKIFHLXW¦F9GFFI9§\§§^^^¥§]¥¥¤£]§¥KJGJFKG—G¥—GGF\]]\^^_]¤¥¥£¤££¤]]KLHKGKVF9¥FI9G§\]]___¥¥¥¥¦¤¤£§§??J\H§8GH¥G¤G¥\§]^___¤£¤¤¦¢¤¥¥^\¥F\JI9H¥¥H¦¥_^¦\]^__¤¦¥¥¤¤¤¤¥¥¦^GFKJ¦¦W¦H¦^_\\\]^^þ§¦¥§¥§\\¥§HG¥L¥FGF\^^]^^]^__þ§§§¦^^]¦JH]F¦G¥G]]]§\§]]þ
^]]\\¤§JFGF9¦§^]]\]]þ^^¥¥¥¥GHG¦¥_^^^^þ]§¥\]§9¦^^^þ]]\]¥þ^^_ÿþJþGþKþGþ£þWþJJIþ?þI_þGþ	£¥þ¥þ¥þL?KLJþýIJþJGþIIþ¥¥£¦EþEF£MýL_LLKJKIJIþYJþEEþE¦¥—FþF8¥]]MI__?LGGKJJGKþFF£þ¦—EF¦£8¦§¥¥_\J_ýJII?LLILLþW8U£¥þWFFG—¤¦§¥¤¥¥¦^^_KJJý_JM_UþGF¥E¥GG8§§\¦¦¥£]\§¥¥_§LYKIYLJI¤¦G8EF¦G¥¤]§]^]§¤\]¥¤¥¤¦^^?YJ_JJ¦—F¥¦8¤§^]\\§\\\£¥¤¤¤¥¥§¤¤^\YJKL—G8U¥¥_]^]§\\§_¦¤¥¦¤¦¤££¤¤¥¤^^?_WG¥¤§]]¦§^\§§^^^¥§]¥¥¤£¢¤¢¢¢¥¤]^¦§§\\]§§]]]\^^_]¤¥¥£¤££¤£¢£¤¤¥¥§¥]]]\^]]§\]]___¥¥¥¥¦¤¤£¤¢¥¤¤¤¦¥^^^^___^\§]^___¤£¤¤¦¢¤¥¥¤¥¥¥¥¤¥\^_^_^^_^¦\]^__¤¦¥¥¤¤¤¤¥¥¥¥§¥§¥^^^^_^_\\\]^^þ§¦¥§¥§\\¥§¦¥¤¥]_^]^^]^^]^__þ§§§¦^^]¦§]¥¦]^]]]§\§]]þ
^]]\\¤¦§¦¥]_^]]\]]þ^^¥¥¥\¥¦]___^^^^þ]§¥\¥¥^_^^^þ]]\§^þ^^_ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\©¨§§¨G\G¥H§¥¥;¥Gþ¦I¦GJ];—G¨ª©¨¨©G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G¨ª«ª©©ª¦F§¥G—WG—X;WGF;þ—;G—;¦§¨ªª¨¨¦;G—¨¨¥HGFFG§;;;þ¦GX—G;]¦G—¨G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦©¨GJF¥¥;—H;þFG¦G;——;©§§G¥¥§Gþ]G;GG¦G§]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;©ª©¨§WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];««¬©¨HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦©Jª©©ª¨¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦¬«««ªªªGFFG§;;;þ¦GX—G;]¦G—¬¬¬¬¬«¬ª¨¨©G\¥þ
¦X——§¨©ª«;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;§¨§¥;þG§9F—\—¦F§G¨¨©©¨©¥\9þ
HGH¥;¦G\G§©ª¨G\G¥H§¥¥;¥Gþ¦I¦GJ];—G§ªª«ª¨G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦§©¬¬©§9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥H¨FFG§;;;þ¦GX—G;]¦G—¦G¦FH¨ª«§¦GG\¥þ
¦X——\—G¦¨©©©©©ª§;—H;þFG¦G©©©©GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G§§—¦¦§¨§GG¥HGFFG§;;;þ¦GX—G;]§G§§¨¨FHG]JG¦§G\¥þ
¦X——\—G¦¦;—GJF¥¥§¨¨;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦§§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦§§9G¦F¨¨G—WG—X;WGF;þ—;G—;¦—G§ªªª§;G—G§©¨§FFG§;;;þ¦GX¨¨©««ª©¨§¦F¨©¨ª©«ª©\¥þ
¦X——\§©©¨©ª««««¨§—H;þFG¦G;§§¨¨§§§§¥§Gþ]G;GG§§J]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J§¨¨F—¥G—W§—X;WGF;þ—;G—;¦—G¦§§¦§¨©ª§G¥HG¨¨©ª;;;þ¦GX—G;¨©ª¨©ªªFH§¨JG¦GG\¥þ
¦X——\—Gª««—G¨©©§;—H;þFG¦G;——;©©ª«¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—§¨HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G§¨¨©©9G¦F—¥G—WG—X;WGF;þ—;§§¨¦¨ªªª¨§§;G—G©¨¨¨§§¨§;;;þ¦GX—G;¨¨¨§¦G¦FHG]JG¦GG\¥þ
¦X——\—§§¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦§¨]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥©G\\§;—G;JGþWJ§¨;]§¨G¦;¦G;¥;þG§§¨¨¨—§¨¨G—]—;;§¥\9þ
HGH¥;§¨\G¨¨GXG\¨¥¨¨§¥;¥Gþ¦I¦©§§¨©G—G¥HW—¨§©¨¨§§¨¦¥GGGþ¥G¦J—;ªª§G;F¨]J9G©©—¨G—WG—X;WGF;þ—;G—;¦—§¦G¨§¦;§—GG¥HG¨FG§;;;þ¦GX—G;¨¨¨¨§G§¨¨G]§¨©GG\¥þ
¦X—¨©©G§¨;©¨§F¨¨§—H;þ¨¨©G;¨—;G©¨§¥¥§Gþ]G;G¨§¨J]H¥¥þ¦GG¨§¨¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;§§JF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];§G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G§J—;;¥¦G;F¦]¨¨G¦F—¥G—WG—X;WGF;þ—;§§;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦©X—G;]¦G—¦GªFHG]JG¦GG\¥þ
ªX——\—G¦¦;ª§JF¥¥;—H;þFG¦G¨——§ª¨§G¥¥§Gþ]G¨¨¨©ªJ]H¥¥þ©ª©\;¦¦¥þ¥¥¥§ÿþ]GW§þG¦\;§¦GGþ¥\G\\¦©—G;JGþWJ¦§;]§—G¨;¦G;¥;þG§§F¨\—¦FXG¨§—;§¨¥ª9þ
HGH¥§§©\¨§WGXª\G¥H§¨«;¨Gþ¦I¦GJ]§§ª—©¨HW¨¬§¨¨F§©¬§©¨ªªþ¥G¦J—;;¥¦G;¨ª©J§©¬§©¨¨¨«¬©ª§WGF;þ—;G—;¦—G¦G—¦§¨©ª¨ª«©©FFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¨¨;9¦GGþ¥\G¨©§;—G;JGþWJ¦§;]©©G¦;§©;¥;þG§9F—\—¦FXG©§¨ª;§¥\9þ
HG¨¥;¦G\G©WGXG©©¥H§¥¥;©Gþ¦I¦G©¨§—G—G©©W—G¦¦§F¦§X§¨GGGþ¥G¦J—;;¨¨¨;F¦ª©¨G¦F—¥G—W¨©©;WGF;þ—;G—;¦¨¨¦G©¦ª¨¨—GG¥H§©©©§;;;þ¦GX—G;]§¨—¦G¦FHG]JG¦GG\¥þ
¦X——§¨©¦©¨—GJF¥¥;—H;þF¨¨©;—¨©§¨¨G¥¥§Gþ]G;GG¦¨§]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;§©ªG;F¦]J©¨§¨§ªG—WG—X;WGF;þ—;G—;¦«G¦G§§¨ª©¨©¨©H¨¨§§§§;;þ¦GX—«§§¦¨¨©«ª©ª©¨J©©¨¨§¨þ
¦X«¨¨§ª¨©;—GJF¥¨ªªª©þªª©¨;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—©—¦FXG—]—;;§§\9þ
HGH¥;¦G\©ªWGX§\G§H©¨¥;¥Gþ¦I¦GJ];§G—G¥©¨§¨§¦©¨¦§X¦¥GGGþ¥G¦J—;;¥¦G;¬«ª©¨¨©ª©¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;©ªGG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦§HG]JG¦GG\¥þ
¦X——\—G¦¦;—G§F¥¥;—H;þFG¦G;——;GH§§¥¥§Gþ]G;GG¦GJ]H§¥þ¦GG\;¦¦¨þ¥¥¥§ÿþ]GWGþG§¨;9¦GGþ¨©§¨ª¦;—G;JGþWJ¦§¨©ª§G§;¦G;¥;þG§9F—\—¦F¨§¨]—;;§¥\9þ
HGH¥;¦G\G\WG¨©\§§H§¥¥;¥Gþ¦I¦G¨§§§G—G¥HW—G¦¦¨§¦§X¦¥GGGþ¥G¦©¨©§¥¦G§F¦]J9§§F—¥G—WG—X;WGF;þ©©G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ©GX—G;]¦G—¦G¦FHG]J§¦GG\¥þ
¦X——\—G¦¦¨ª«¨¨¥¥;—H;þ§G¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]G©©þG¦¨¨ª«ª«þ¥\ª¨©¦;—G;J©þW¨©©ª]§—G¦;¦G;§¨þG§¨ª—\—¦FXG—]—;;§¥\9þ
©¨H¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦Iª©§];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G;]¦G—©G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦©—GJF¥¥;—H;þFG¦G;——§GH§G¥¥§Gþ]G;GG©GJ]H¥¥þ¦GG\©¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;¨§—G¦;¦G;¥;þG§9F—\—¦©XG—]—;;§¥\9þ
HGH¥;¦G\G\¨«XG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥©«ªG¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦§ª«ª¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦«¬«—GG¥HGFFG§;;;þ¦GX—G;]¦G§¬¬¬FHG]JG¦GG\¥þ
¦X——\—G©­­­GJF¥¥;—H;þFG¦G§ª­®®§§G¥¥§Gþ§¨§¯®¯®©]H¥¥þ©¯¯¯®ª¦¥þ¯¯¯«ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥©©¨©þ¦I¦GJ];—G—G¥HW§¨©¦§F¨©«ª©ª¬¯þ¥G¦J—;;¥¦G;F¦]J9G¦F©§¨ª¬­«««¬©¯¯þ—;G—;¦—G¦G—¦¦;G—GG©ª«­­¬¬¬­¬þ¦GX—G;]¦G—¦G¦FHG]JG¦G­­­þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¯¬¨J—¨§¥¦G;F¦]J9G¦F—¥G—WG—X;WGF;þª¨§¨¨¦¨G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—G§]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ®¯®­þ®®¯¯¯­«¨þ¥\G®¯¯¯­­;JGþWJ¦§;]§¯¯­;¦G;¥;þG§9F—©ª«¬¯¯§]—;;§¥\9þ
HGH¥¨¨©ª«¬«­XG\G¥H§¥¥;¥Gþ¦I¦GJ§§—G—G¥H­—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9«¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;G«GG¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦F¨G]JG¦GG\¥þ
¦X——\—G¦¦;—GJ©¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥§¨—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9§¦F—¥G—WG—X;WGF;þ—;G—;¦—G¦G—¦¦;¨©§G¥HGFFG§;;;þ¦GX—G;]¦G—¦G¦F§G]JG¦GG\¥þ
¦X——\—G¦¦;—G§F¥¥;—H;þFG¦G;——;G¨ªG¥¥§Gþ]G;GG¦§©«¨§¥þ¦GG\©ª¬ªþ¥©ª«ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
HGH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥¦G;F¦]J9G¦F—¥G—WG—X;WG©«þ—;G—;¦—G¦G—¦¦;G—GG¥HGFFG§;;©þ¦GX—G;]¦G—¦G¦FHG]JG¦GG\¥þ
¦X——\—G¦¦;—GJ§¨¥;—H;þFG¦G;——;GH§G«©§Gþ]G;GG¦GJ]H¥«þ¦GG\;¦¦¥þ¥¥¥§ÿþ]GWGþG¦\;9¦GGþ¥\G\\¦;—G;JGþWJ¦§;]§—G¦;¦G;¥;þG§9F—\—¦FXG—]—;;§¥\9þ
¨GH¥;¦G\G\WGXG\G¥H§¥¥;¥Gþ­«©GJ];—G—G¥HW—G¦¦§F¦§X¦¥GGGþ¬¬®¬ª§;¥¦G;F¦]J«©§F—¥G—WG—X;WGF;þ¯®«¨§§—G§¨ª«¬­¨—GG¥HGFFG§;;;þ¬ª§¨G¨©©«—¦G¦FHG]JG¦GG\¥þ
¨X——\—G¦¦;—GJF¥¥;—H;þFG¦G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿþ«¬­­þG¬¬­­®¯¯þ¥\«­¬®®¯¯¯®ªþWJ¦«¬®­¯¯¯¯¯G;¥;þ¬«ª¬¬¬®¯FXG—]—;;§¥\9þ
HGH¥;­­®G\WGXG\G¥H§¥¥;¥Gþ¦I¦GJ];®®—G¥HW—G¦¦§F¦§X¦¥GGGþ¥G¦J—;;¥©­;F¦]J9G¦F—¥G—WG—X;WGF;þ—;G—;¦¨G¦G—¦¦;G—GG¥HGFFG§;;;þ¦GX—©ª]¦G—¦G¦FHG]JG¦GG\¥þ
¦X—©©—G¦¦;—GJF¥¥;—H;þFG¨G;——;GH§G¥¥§Gþ]G;GG¦GJ]H¥¥þ¦GG\;¦¦¥þ¥¥¥§ÿ&þLKKKLþ–––GÿþFþ EþFGþE“FK–¦þEþF–K–¦GHþE“–K–¦þH¦HÿþFþ£Eþ–MGFþHHGLMF£EþHLM–FþEþ–þEÿþF–GHþK–G––HE–þFF¦–HG–GHE£¡þ¦K¦E¦––FG¡–G£££¡þ––¦¦–FHH––FE£HE££¡¡ þ
¦G––E¦H¦GHH–FEE¡ D¡¡ ¡¡¡þ¦¦HF¦FH¦H¦EEG–FEE“¡ ¡ ¡¡¡¡  þH¦H¦¦G¦¦FGH£FFFFE¡¡ ¡¡¡ ¡“““ ¡ þGFFEHHF£EGFG GF¡ ¡¡¡¡  ¡““¡“þFD¡FG£GF¡G EF¡¡¡ ¡ ¡¡¡¡þ
£F£G¡ G G¡¡F¡ ¡¡¡¡¡¡þF    ¡¡“ ¡¡¡ ¡¡ þ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþF–GHþK–G––HE–þFF¦–HG–GHE£ þ¦K¦E¦––FGL–G£¡  þ––¦¦–FHH–GF¡£HE¡ ¡¡ þ
¦G––E¦H¦GHH–ME££¡D¡¡¡¡¡¡þ¦¦HF¦FH¦H¦EEG–F E¡  ¡ ¡¡¡¡  þH¦H¦¦G¦¦GFGHGFFF£E¡ ¡¡¡¡ ¡“““ ¡ þGFFEHHKLEGMGMGF ¡“ ¡¡¡ ¡““¡“þKFDF¡ GFG“ E ¡¡¡ ¡ ¡¡¡¡þ
DF¡G£¡G“G“ F¡ ¡¡¡¡¡¡þF£¡   ¡¡““¡¡¡ ¡¡ þ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþHG–Fþ–EH––G–Kþ““EHG–GH–¦FFþ¡¡““G–GGF––¦E¦K¦þ ¡ ¡¡EHEF––HHF–¦¦––þ
    ¡ D¡“EEF–HHG¦H¦E––G¦þ    ¡¡¡   ¡EEF–GEE¦H¦HF¦FH¦¦þ   ¡¡¡      ¡¡EFFFF–HGFG¦¦G¦¦H¦Hþ ¡ ¡¡¡   ¡¡¡“FGKGFGELFHHEFFGþ¡¡¡¡ ¡ ¡  FE“G“FG“GF“DFKþ
 ¡¡¡¡   F  G“G¡¡G F þ    ¡ ¡“¡¡¡¡  ¡Fþ    ¡   ¡   þ ¡ ¡¡¡¡ þ¡   ÿþ¡¡¡ þ¡ ¡ ¡¡¡¡þ   ¡¡¡¡““¡  þ  ¡““¡ ¡¡¡¡   ¡“þ ¡ ¡¡¡¡ ¡¡¡¡   ¡¡¡¡ þ
    ¡““¡““¡   ¡¡¡¡¡¡ ¡¡¡þ    ¡¡¡¡    ¡¡ ¡““¡ ¡ ¡¡¡¡  þ   ¡¡¡¡“¡    ¡“  ¡¡¡ ¡¡¡ ¡“““ ¡ þ¡““¡ ¡¡  ¡¡¡¡¡ ¡ ¡¡¡¡  ¡““¡“þ¡¡¡¡ “ ¡“¡  ¡¡¡¡¡ ¡ ¡¡¡¡þ
¡““““    ¡¡ ¡ ¡¡¡¡¡¡þ     ¡¡“ ¡¡¡ ¡¡ þ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþHG–Fþ–EH––G–Kþ““EHG–GH–¦FFþFþ  ¡“G–“GF––¦E¦K¦Dþ ¡ ¡“EH FF––HHF–¦¦––þEEþ    ¡“D¡¡EEE–HHG¦H¦E––G¦FFþ    ¡¡¡¡  ¡EEF–GEE¦H¦HF¦FH¦¦þ   ¡¡¡¡“¡    ¡EFFFFHGFH¦¦G¦¦H¦Hþ¡““¡ ¡¡   ¡EEFGGGEGE¦HHHEFFGþ¡¡¡¡ HD “EEE–HHFGH¦F–DF¦þ
¡““¡¡EH“FF–GHGF–G¦F–þ ¡  G–“GF––¦E¦K¦þ““EHG–GH–¦FFþ–EH––G–KþHG–Fÿþ¡¡¡¡þ ¡““¡ ¡¡þ  G¦¦G“     þ¡  GHHHHG¡¡ ¡¡ ¡þ ¡ ¡G¦H¦HGGG    ¡¡¡ þ
    ¡ GG¦HH¦GGG¡¡ ¡ ¡   þ    ¡¡¡ GGGGH¦GGH“   ¡ ¡¡¡¡ þ   ¡¡¡ “““G–GG¦¦GGH¦G“¡ ¡   “ ¡ þ ¡ ¡¡¡¡¡¡“G¦H¦HGGGKH ¡     ¡þ¡¡¡¡ ¡ ¡“–––KGH–L¦¡ ¡¡¡¡þ
 ¡¡¡¡  ““KMK–MM ¡¡  þ  H ¡ ¡“¡¡¡¡ ¡  þ    ¡       þ ¡ ¡¡¡¡ þ¡   ÿþ¡¡  þ ¡¡¡¡ “ þFþ    ¡““¡¡““¡þD¡    ¡¡“ ¡¡¡ ¡¡ þEEþE££G¡ G G¡¡F¡ ¡¡¡¡¡¡þFFFE¡F££GF¡  E¡¡¡¡ ¡ ¡¡¡¡þGFFFHH££EGGG GF¡ ¡¡¡¡  ¡““¡“þH¦H¦¦G¦¦FGH£FFF¡E¡¡ ¡¡¡ ¡“““ ¡ þ¦¦HF¦FH¦H¦EEG–F E“¡ ¡ ¡¡¡¡  þ¦G––E¦H¦GHH–£E£¡ D¡¡ ¡¡¡þ
––¦¦–FHH–¡F££HE££¡¡ þ¦K¦E¦––FG¡–G£££¡þFF¦–HG–GHE£¡þK–G––HE–þF–GHÿþ¡¡  þ ¡¡¡¡ “ þ    ¡““¡¡““¡þFþ     ¡¡“ ¡¡¡ ¡¡ Dþ¡““““   F¡¡G¡G¡ G““EþEEþ¡¡¡¡ “ ¡“¡ E¡¡GFG  F“EF–FFþ¡““¡ ¡¡  ¡¡¡¡FG¡G“GEHHFFFGþ   ¡¡¡¡“¡    ¡E¡FFFGHGF¦¦¦G¦¦H¦Hþ    ¡¡¡¡   E¡F–GEE¦H¦HF¦FH¦¦þ    ¡“D ¡“E“–HHG¦H¦E––G¦þ
 ¡  ¡EH“F¦–HHF–¦¦––þ¡¡““G––GF––¦E¦K¦þ““EHG–GH–¦FFþ–EH––G–KþHG–FÿþHG–Fþ–EH––G–Kþ““EHG–GH–¦FFþ¡¡““G––GF––¦E¦K¦þ ¡  ¡EH“EF––HHF–¦¦––þ
    ¡“D ¡EEF–HHG¦H¦E––G¦þ    ¡¡¡¡   EEF–GEE¦H¦HF¦FH¦¦þ   ¡¡¡¡“¡    ¡EFFFF“HGF¦¦¦G¦¦H¦Hþ¡““¡ ¡¡  ¡¡¡¡FG¡GFGEFHHEFFGþ¡¡¡¡ “ ¡“¡FE¡G¡FG GF“DF–þ
¡““““   F¡¡G¡G¡ G“F“þ     ¡¡“ ¡¡¡ ¡¡Fþ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþ    þ ¡¡¡¡ ¡¡þ  ¡   ¡¡¡   þ  ¡¡¡¡¡ ¡ ¡¡¡ ¡¡þ ¡¡ ¡ ¡¡ ¡¡¡   ¡¡¡¡ þ
     ¡¡¡¡¡¡   ¡““¡“¡¡ ¡ þ    ¡““¡    ¡“ ¡¡¡¡ ¡  ¡¡¡  þ   ¡““¡¡¡    ¡¡¡     ¡“¡ ¡“““ ¡ þ¡¡¡¡ “   ¡““¡ ¡¡¡¡ ¡¡  ¡¡¡ “þ¡¡ ¡¡¡ ¡¡¡ ¡      ¡¡ ¡ ¡þ
¡““““    ¡ ¡¡¡¡ ¡ ¡¡þ     ¡¡“¡    “¡ þ    ¡¡¡ ¡¡¡¡þ¡ ¡ ¡¡¡ þ¡¡  ÿþ¡¡¡ þ¡ ¡ ¡¡¡¡þ   ¡¡GGG“¡  þ  ¡“G¦¦HH¦¦¦G ¡“þ ¡ ¡G¦HHHHHHH¦¦G¡¡¡ þ
    G¦GHHHHHH¦GGHHHG ¡¡¡þ    ¡¡GG¦HHHHHGGGG¦GH¦G¡¡¡  þ   ¡¡¡¡“HGG¦¦¦¦¦¦GGGHGG–¦H“““ ¡ þ¡““¡ “–GGGGGGGGGGGGK–LK–““¡“þ¡¡¡¡“HH¦GG–G¦¦–¦–MK–“¡¡þ
¡““––KG¦KG¦–¦–KML¡¡þ £  HKH¦––KL¡¡ þ   ““““““““¡þ ¡¡¡¡ “ þ¡¡  ÿþ¡¡¡ þ¡ ¡ ¡¡¡¡þ   ¡¡¡¡““¡  þ  ¡““¡ ¡¡¡¡   ¡“þ ¡ ¡¡¡¡ ¡¡¡¡   ¡¡¡¡ þ
    ¡““¡““¡   ¡¡¡¡¡¡ ¡¡¡þ    ¡¡¡¡    ¡¡ ¡““¡ ¡ ¡¡¡¡  þ   ¡¡¡¡“¡    ¡“  ¡¡¡ ¡¡¡ ¡“““ ¡ þ¡““¡ ¡¡  ¡¡¡¡¡ ¡ ¡¡¡¡  ¡““¡“þ¡¡¡¡ “ ¡“¡  ¡¡¡¡¡ ¡ ¡¡¡¡þ
¡““““    ¡¡ ¡ ¡¡¡¡¡¡þ     ¡¡“ ¡¡¡ ¡¡ þ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþHG–Fþ–EH––G–KþFFEHG–GH–¦FFþ¦K¦EG––GF––¦E¦K¦þ––¦¦–EHH–FF–HHF–¦¦––þ
¦G––E¦D¦GHE––HHG¦H¦E––G¦þ¦¦HF¦FH¦H¦EEGF–GEE¦H¦HF¦FH¦¦þH¦H¦¦G¦¦KFGHGFEFFFFWHGF¦¦G¦¦H¦HþGFFEHH¡EG¡G¡FG£GFGE¡FHHEFFGþMFD¡F££GFGFEEG¡FG GF“DFMþ
DF£G¡¡G F¡¡G¡G¡¡G¡F¡þF     ¡¡“ ¡¡¡ ¡¡Fþ    ¡““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþF–GHþK–G––HE–þFþFF¦–HG–GHE£¡þD¦K¦E¦––FG£–G“¡¡“þEEþ––¦¦–FHH––FF£HE¡¡¡¡ þFF¦G––E¦H¦GHH–EEE““D¡¡ ¡¡¡þ¦¦HF¦FH¦H¦EEG–FEE ¡ ¡ ¡¡¡¡  þH¦H¦¦G¦¦HFGHKFFFFE¡¡¡¡¡¡ ¡“““ ¡ þGFFEHHH¦EGEGGGF¡E¡¡¡¡  ¡““¡“þ¦FD–F¦HGFHH–EE¡¡ D¡ ¡¡¡¡þ
–F¦G–FGHG£FF£HE¡¡¡¡¡þ¦K¦E¦––FG¡–G ¡¡ þFF¦–HG–GHE“¡þK–G––HE–þF–GHÿþ¡¡¡ þ¡ ¡ ¡¡¡¡þFþ   ¡¡¡¡““¡  þFþFþD  ¡““¡ ¡¡¡¡   ¡FDþ
EEþE¡ G¡¡G G¡¡F G ¡G¡DEþEEþFF£FE¡F““GF“FEEG¡FG¡GF EFFFþEGFFFHH£¡EGGG£GF¡GFGE¡FHHFFFGþH¦H¦¦G¦¦£FGH FFFFEF£HGF ¦¦G¦¦H¦Hþ¦¦HF¦FH¦H¦EEG–FGEE¦H¦HF¦FH¦¦þ¦G––E¦H¦GHH––EHG¦D¦E––G¦þ
––¦¦–FHH–FF–HHE–¦¦––þ¦K¦E¦––FG––GE¦K¦þFF¦–HG–GHEFFþK–G––HE–þF–GHÿþ¡¡¡ þ¡ ¡ ¡¡¡¡þ   ¡¡¡¡““¡  þ  ¡““¡ ““¡¦–H ¡“þ ¡ ¡GGG¦¡¡¡HGG¦L¡¡¡ þ
    ¡G–––¦– “K¦L““¡¡ ¡¡¡þ    ¡¡¡H–GH¦K¡ ¡““¡ ¡ ¡G¡¡  þ   ¡¡¡¡“HGGH–K  ¡¡¡ ¡¡¡ £¡““ ¡ þ¡““¡“““HHM““H¡““ HHH¡  ¡““¡“þ¡¡¡¡ “ ¡“¡  ¡H¦GGH¦ ¡¡¡¡þ
¡““““ –G–¡GG¦–KL¡¡¡¡þ    –––G“L––“““¡þ  “““““¡¡““¡þ ¡¡¡¡ “ þ¡¡  ÿþHH¦HþH¦H¦EEG–þGEGFGHEFFFGEþ““FEGEEGEG GFE£ þ ¡¡–¡FF¡ GFD£G¡FE ¡ þ
     E¡G¡G¡¡G¡G““GG¡¡ ¡ þ    ¡““G G G¡G ¡F¡¡¡HE ¡¡¡  þ   ¡““¡¡¡  £ ¡¡GH    ¡“¡ ¡“““ ¡ þ¡¡¡¡ “   ¡““¡££¡¡¡ ¡¡  ¡¡¡ “þ¡¡ ¡¡¡ ¡¡¡ ¡      ¡¡ ¡ ¡þ
¡““““    ¡ ¡¡¡¡ ¡ ¡¡þ     ¡¡“¡    “¡ þ    ¡¡¡ ¡¡¡¡þ¡ ¡ ¡¡¡ þ¡¡  ÿþ    þ ¡¡¡¡ ¡¡þ  ¡   ¡¡¡   þ  ¡¡¡¡¡ ¡ ¡¡¡ ¡¡þ ¡¡ ¡ ¡¡ ¡¡¡   ¡¡¡¡ þ
     ¡¡¡¡¡¡   ¡““¡“¡¡ ¡ þ    ¡““¡    ¡“ ¡¡¡¡ ¡  ¡¡¡  þ   ¡““¡¡¡    ¡¡¡     ¡“¡ ¡“““ ¡ þ¡¡¡¡ “   ¡““¡ ¡¡¡¡ ¡¡  ¡¡¡ “þ¡¡ ¡¡¡ ¡¡¡ ¡      ¡¡ ¡ ¡þ
¡““““    ¡ ¡¡¡¡ ¡ ¡¡þ     ¡¡“¡    “¡ þ    ¡¡¡ ¡¡¡¡þ¡ ¡ ¡¡¡ þ¡¡  ÿ